# Introduction

Our lectures are going to teach you basic concepts of probability and 
their applications in computational finance. Our approach is based on 
intuition and on understanding concepts by building them with your own hands.

But how can we build abstract concepts such as probability, random phenomena and chance? 
While probability is a mathematical theory, it gains practical value and an intuitive meaning in
connection with real or conceptual experiments such as, tossing a coin, rolling two dice, playing
roulette, observing the change in the index value of stocks, bonds or in exchange rates, selecting
a random sample of financial transactions in a payment system and observing 
the number of transactions with a value below a certain amount.

Many of these experiments we can nowadays do not only physically -- by actually 
rolling a pair of dice, for example -- but we can use the computer to build a 
virtual dice and roll it on the computer. We
can build and simulate a huge variety of random phenomena. We can - for instance - 
implement models of random fluctuations of asset prices. We can model financial risks
and contemplate possible future scenarios through simulation.

We can approach our understanding of abstract concepts
by building them with our own hands on the computer. This is the approach to teaching you
probability in this course.

There are many ways to build virtual objects and to run simulations to manipulate 
them. For this we will need a programming language. The language we choose for this
course is R and the integrated development environment RStudio. This is one of the main
languages used in data analysis, statistics, data science and is widely used in industry and 
academia. This introductory chapter will introduce you to this tool in a straightforward and
minimalist way to get us started. As the course develops we will gradually introduce more
and more concepts of R in parallel to our main thread, the introduction to probability.

