# Empirical background and some terminology

If you chose to study Finance it should be natural for you to study probability. 
After all, Finance studies the allocation and pricing of money across time. You can
safe money to use it later for purchasing goods and services you can borrow money to
invest today and repay in the future from the revenues of your project. But the 
future is uncertain and we do not know today how it will look like. In Finance we unavoidably
have to deal with risk and uncertainty. The most fundamental concept we have available
to deal with risk and uncertainty and to think about and analyze it is probability. Therefore
every serious student of Finance has to study probability early on.

Probability is a mathematical theory. This theory gets practical value and intuitive meaning
in connection with real or conceptual experiments such as rolling a dice, tossing a coin or
selecting a random sample of stocks and observing their most extreme price drop over a
given period of time or observing the frequency of car accidents etc. All of these
descriptions are, however, rather vague. We have to be more precise what we mean by an
experiment or observation.

When we use the term (random) *experiment* we mean a process leading to an uncertain 
outcome. To make this notion precise and useful we need to agree what we mean by
uncertain outcomes.

Take the simple example of tossing a coin. In a practical situations the outcome 
of a coin toss can be that the coin lands on head or tail. But it could in principle
also fall on an edge, stand and roll away. Still when we think about the
experiment of tossing a coin in the theory of probability we agree *on the outset* that
heads and tail are the only possible outcomes of this experiment. By such an
agreement we have pinned down the possible outcomes. 

The collection of all possible outcomes of an experiment is calles the *sample space*.
While the sample space of the experiment of tossing a coin is an idealization it is
exactly this idealization which simplifies the theory without affecting its applicability.

Idealizations of this kind are standard in probability and are widely used also in Finance. It
is - for example - impossible to measure how high the price of a stock might become. Is there
a maximal price beyond which the price can not possibly be higher? Many of us would
hesitate to claim that the price might rise without bound. Yet many models in applied
Finance are based on such an assumption. The models allow arbitrary price hikes but with arbitrary
small probability as the price gets higher and higher. Practically it does not make sense
to believe that a security price can become arbitratily high. The use of arbitrarily small
probabilities in a financial model might seem absurd but it does no practical harm and makes
the model simple and convenient to use. Moreover, if we seriously introduced an upper bound 
on a security price at $x$ it would be also awkward to assume that it is impossible that it
could be just a cent higher, an assumption equally unappealing as assuming it can get in
principle arbitrarily high.

When we talk of a *basic outcome* we mean the possible outcome of a random experiment. An *event* is 
a subset of basic outcomes. Any event which consists of a single outcome in  the sample space
is called a *simple event*.

Probability is a measure of how likely an event of an experiment is. Thus when we 
talk about probability in a precise and meaningful sense we can only so in relation to
a given sample space or to a certain conceptual experiment. Thus before we can begin to seriously 
talk about probability we need to develop a good understanding of experiments, sample
spaces, basic outcomes and events. In the spirit of this course we will develop this
understanding by building these concepts using R. This will at the same time
get us started with using the R language as a tool which will allow us to "touch"
probability concepts. As we proceed through our course we will develop a broader and deeper
understanding of this language together with the probability concepts.

# Building experiments, sample spaces and events using R




