--- 
title: "An Introduction to Probability"  
subtitle: "With Applications to Computational Finance using R"
author: "Martin Summer"
date: "`r Sys.Date()`"
output: pdf_document
documentclass: book
bibliography:
- book.bib
- packages.bib
biblio-style: apalike
link-citations: yes
new_session: yes
description: Lecture Notes. The output format for this example is bookdown::gitbook.
site: bookdown::bookdown_site
---

# Preface {-}

> "What I hear, I forget; What I see, I remember; What I do, I understand"
>
> `r tufte::quote_footer('--- Confucius, 551-479 BC')`

## What are these lecture notes about {-}

These lecture notes support the course **An Introduction to Probability with Applications to Computational Finance using R**. 
Our lectures are going to teach you basic concepts of probability every finance 
practitioner needs to know and be familiar with. Because you will need
probability as a tool for thinking about and solving finance problems with
computational methods, we will use computational finance as the context within
which we develop the concepts and ideas of probability. But we will also
make much use of the computer in this course: Our approach to teaching you 
basic concepts of probability is based on understanding concepts by building 
them with your own hands.

But how can we build abstract concepts such as probability, random phenomena and chance by 
our own hands? 
While probability is a mathematical theory, it gains practical value and an intuitive meaning in
connection with real or conceptual experiments such as, the future change in a stock price
index, the future value of a portfolio of securities, the chance that a creditor is not going
to be able to pay back your loan.

Many of these experiments we can nowadays simulate on the computer. We
can can construct, build and simulate a huge variety of random phenomena. We can - for instance - 
implement models of random fluctuations of asset prices. We can model financial risks
and contemplate possible future scenarios through simulation.

The arrival of the computer has been indeed a sea change for the mathematics of probability 
because it allows both reflecting about probability through theorems and proofs as well as
by making use of computer simulation. 
We can approach our understanding of abstract concepts
by building them with our own hands on the computer. This is the approach to teaching you
probability in this course.

It is, however important to always keep in mind that the
real world is different from the simulated world. The real world is both richer 
and more complex than the simulation. It may contain features which need to be be 
taken into account for the 
explanation of phenomena which are absent in the simulation. We will try our best to develop
your feeling for the difference, between theoretical concepts, application and the relations
of simulations to both theory and applications.

There are many ways to build virtual objects and to run simulations to manipulate 
them. For this we will need a programming language. The language we choose for this
course is R and the integrated development environment RStudio. This is one of the main
languages used in data analysis, statistics and data science and is widely used in industry and 
academia. It will be our tool to do probability in this course.

## Downloading and installing R {-}

So lets start by downloading and installing R first. R is an open source project maintained
by an international team of developers. The software is made available through a website called
the comprehensive R archive network (http://cran.r-project.org).

At the top of this website, in a box named "Download and install R" you will find three
links for downloading R. Choose the link that describes your operating system, Windows, Mac or 
Linux. These links will lead you to the necessary information you need to install a current
version of R. The easiest install option is to install R from precompiled binaries. There is also
the option to built R from source on all operating systems if you have the tools and the
expertise to do so. R also comes both in a 32-bit and a 64-bit version. It does not make
a substantial difference which version you use. 64-bit versions 
can handle larger files and data sets with fewer memory management problems.

## Downloading and installing RStudio {-}

RStudio is an application that helps you write and develop R code. It makes using
R much easier for you than using it in isolation. The interface of RStudio looks the
same across all operating systems.

You can download RStudio for free from https://www.rstudio.com/products/rstudio/. 
Select the box RStudio Desktop and follow the download instructions. RStudio Desktop is free.
Note that you need to have a version of R installed to use RStudio.

If you have successfully installed R and RStudio, we are ready to start.

## Prerequisites {-}

This course is built as an intuitive and elementary introduction to the field. No knowledge
of probability or R is assumed and all concepts are built from scratch. Many of you will
have heard or studied probability at some stage in college or at university. I hope the
course will appeal to the newcomers as well as to the experienced. While it should allow the first
group to quickly learn some of the most important concepts and raise your curiosity and
excitement about a field of knowledge which is both beautiful and immensely practical, I hope it
will open a new perspective for the more experienced among you and thus help deepening
your understanding of concepts you might already have heard elsewhere.


## Structure of the Notes {-}


## Acknowledgements {-}

## References {-}



