<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; First probability ideas and first steps in R – An Introduction to Probability</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-lecture1_updated.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">First probability ideas and first steps in R</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">An Introduction to Probability</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-lecture1_updated.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">First probability ideas and first steps in R</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#rolling-a-die" id="toc-rolling-a-die" class="nav-link active" data-scroll-target="#rolling-a-die"><span class="header-section-number">1.1</span> Rolling a die: First Probability ideas.</a>
  <ul class="collapse">
  <li><a href="#random-experiments-sample-space-events" id="toc-random-experiments-sample-space-events" class="nav-link" data-scroll-target="#random-experiments-sample-space-events"><span class="header-section-number">1.1.1</span> Random experiments, sample space, events</a></li>
  <li><a href="#the-role-and-nature-of-idealizations-in-applications" id="toc-the-role-and-nature-of-idealizations-in-applications" class="nav-link" data-scroll-target="#the-role-and-nature-of-idealizations-in-applications"><span class="header-section-number">1.1.2</span> The role and nature of idealizations in applications</a></li>
  <li><a href="#classical-probability" id="toc-classical-probability" class="nav-link" data-scroll-target="#classical-probability"><span class="header-section-number">1.1.3</span> Classical Probability: Measuring uncertainty</a></li>
  </ul></li>
  <li><a href="#rolling-die-on-computer" id="toc-rolling-die-on-computer" class="nav-link" data-scroll-target="#rolling-die-on-computer"><span class="header-section-number">1.2</span> Rolling a die on the computer: First steps in R</a>
  <ul class="collapse">
  <li><a href="#r-interface" id="toc-r-interface" class="nav-link" data-scroll-target="#r-interface"><span class="header-section-number">1.2.1</span> The R User Interface</a></li>
  <li><a href="#objects" id="toc-objects" class="nav-link" data-scroll-target="#objects"><span class="header-section-number">1.2.2</span> Objects</a></li>
  <li><a href="#functions" id="toc-functions" class="nav-link" data-scroll-target="#functions"><span class="header-section-number">1.2.3</span> Functions</a></li>
  <li><a href="#writing_your_own_functions" id="toc-writing_your_own_functions" class="nav-link" data-scroll-target="#writing_your_own_functions"><span class="header-section-number">1.2.4</span> Writing your own functions</a></li>
  <li><a href="#arguments" id="toc-arguments" class="nav-link" data-scroll-target="#arguments"><span class="header-section-number">1.2.5</span> Arguments</a></li>
  <li><a href="#scripts" id="toc-scripts" class="nav-link" data-scroll-target="#scripts"><span class="header-section-number">1.2.6</span> Scripts</a></li>
  <li><a href="#packages_help" id="toc-packages_help" class="nav-link" data-scroll-target="#packages_help"><span class="header-section-number">1.2.7</span> Using packages and finding Help</a></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages"><span class="header-section-number">1.2.8</span> Packages</a></li>
  <li><a href="#getting_help" id="toc-getting_help" class="nav-link" data-scroll-target="#getting_help"><span class="header-section-number">1.2.9</span> Getting Help</a></li>
  </ul></li>
  <li><a href="#coincidences" id="toc-coincidences" class="nav-link" data-scroll-target="#coincidences"><span class="header-section-number">1.3</span> Application: Coincidences and the Blockchain</a>
  <ul class="collapse">
  <li><a href="#birthday_problem" id="toc-birthday_problem" class="nav-link" data-scroll-target="#birthday_problem"><span class="header-section-number">1.3.1</span> The birthday problem</a></li>
  <li><a href="#an-r-function-to-compute-birthday-probabilities" id="toc-an-r-function-to-compute-birthday-probabilities" class="nav-link" data-scroll-target="#an-r-function-to-compute-birthday-probabilities"><span class="header-section-number">1.3.2</span> An R function to compute birthday probabilities</a></li>
  <li><a href="#determining-birthday-collisions-by-simulation" id="toc-determining-birthday-collisions-by-simulation" class="nav-link" data-scroll-target="#determining-birthday-collisions-by-simulation"><span class="header-section-number">1.3.3</span> Determining birthday collisions by simulation</a></li>
  <li><a href="#hashfunctions" id="toc-hashfunctions" class="nav-link" data-scroll-target="#hashfunctions"><span class="header-section-number">1.3.4</span> Hash-functions and the blockchain</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">1.4</span> Summary</a></li>
  <li><a href="#project-1-craps-a-casion-dice-game." id="toc-project-1-craps-a-casion-dice-game." class="nav-link" data-scroll-target="#project-1-craps-a-casion-dice-game."><span class="header-section-number">1.5</span> Project 1: Craps: A casion dice game.</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="first-steps" class="quarto-section-identifier"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">First probability ideas and first steps in R</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Studying Finance naturally leads to studying probability. Finance focuses on allocating and pricing money over time, which inherently involves dealing with uncertainty and risk.</p>
<p>You can safe money to use it later for purchasing goods and services. Borrowing money allows you to invest today, with the expectation of repaying it from future project revenues. However, the future is uncertain, and we cannot predict tomorrow.</p>
<p>In Finance we therefore unavoidably have to deal with risk and uncertainty. The most fundamental concept we have available to deal with risk and uncertainty and to think about and analyze it is probability. Probability theory provides tools to quantify risk and manage uncertainty, both of which are fundamental to financial decision-making. Therefore every serious student of Finance has to study the theory of probability early on.</p>
<p>But of course probability is first of all a mathematical theory. It gets practical value and intuitive meaning in connection with real or conceptual experiments. Indeed these fascinating interconnections are already visible in the very beginning of probability, which emerged in the 16th and 17th century in Europe in the context of practical as well as scholarly discussions about gambling. These discussions engaged the greatest minds of their times, with names like Gerolamo Cardano (1501-1576), Galileo Galilei (1564 - 1642), Blaise Pascal (1623-1662), Pierre Fermat (1601 - 1665), Christiaan Huyghens (1629 - 1695), Jacob Bernoulli (1654 - 1705), Abraham de Moivre (1667 - 1754), Thomas Bayes (1701 - 1761) and Pierre Simon de Laplace (1749 - 1825).</p>
<p>While people were aware of chance at all times, liked to gamble or even had a godess of chance like the Greeks it seems only later it occurred to them that something as elusive as uncertainty or chance could perhaps be measured. This is the starting point for classical probability. It is also a very good starting point to familiarize ourselves with some basic concepts and knowledge of R by building a simple chance game people apparently had enjoyed playing at all times: Rolling a die. We will learn how to roll a die using the computer.</p>
<p>What has a die to do with Finance, some of you might ask. To those of you, who think so I would say: Perhaps more than you think. But clearly this is still an example quite removed from an actual Finance context, I agree. But be patient and bear with me. The building of a die, which can be rolled on the computer is a simple but extremely rich example which can lead us straight both into probability and into R at the same time and get us started for actual probability applications in Finance.</p>
<section id="rolling-a-die" class="level2 page-columns page-full" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="rolling-a-die"><span class="header-section-number">1.1</span> Rolling a die: First Probability ideas.</h2>
<p>Lets start with a classic and old example of a probability model, which occupied the attention of Pascal and Fermat as well as their gambling friend the Chevalier de Méré: Rolling a six sided die.</p>
<p>When you role a die or several dice like shown in the following picture @ref(fig:dice), it is uncertain on which face it will finally end up after the throw.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/dice.jpg" class="img-fluid figure-img" style="width:25.0%"></p>
<figcaption>Rolling dice: An old game of chance</figcaption>
</figure>
</div>
</div>
</div>
<p>What seems clear though is, that it will turn out that it is either one of the six possible faces of the die.</p>
<section id="random-experiments-sample-space-events" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="random-experiments-sample-space-events"><span class="header-section-number">1.1.1</span> Random experiments, sample space, events</h3>
<p>In the theory of probability a process leading to an uncertain outcome is called a <strong>random experiment</strong>. The example of throwing a die helps us to give a precise meaning to the notion of an uncertain outcome. While we can imagine in principle that the die lands on one of its corners and this is one outcome, we agree <em>on the outset</em> that we are going to consider the (practically relevant cases) that it will land on one of the faces.</p>
<p>The collection of all possible outcomes of a practical or conceptual random experiment is called in probability theory a <strong>sample space</strong>. While the sample space of throwing a die is an idealization it is exactly this idealization which simplifies the theory without affecting its applicability. The <strong>basic outcomes</strong> in the random experiment of throwing a die are that the die lands such that the upward showing face shows a 1 a 2, 3, 4, 5 or a 6. In the theory the collection of basic outcomes is denoted as a set. Thus the sample space of throwing a die is given as the set <span class="math inline">\({\cal S} = \{1,2,3,4,5,6\}\)</span>.</p>
<p>The sample space <span class="math inline">\({\cal S}\)</span> is the set of all basic outcomes. The <em>subsets</em> of the sample space are often called <strong>events</strong> in probability theory. An event could be - for example - an outcome where the die shows an upward looking face with an even number <span class="math inline">\(A = \{2,4,6\}\)</span>.</p>
</section>
<section id="the-role-and-nature-of-idealizations-in-applications" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="the-role-and-nature-of-idealizations-in-applications"><span class="header-section-number">1.1.2</span> The role and nature of idealizations in applications</h3>
<p>Idealizations of the kind we discussed for the throw of a die are standard in probability and we will encounter them again and again. For example the movement of a stock price is often though of as a conceptual random experiment. When we try to agree on what is the appropriate sample space of this experiment, we can say that the price can not fall below 0 but it is hard to agree on what will be the highest possible price. In the probabilistic treatment of stock prices, which we will discuss later in our course, it is for instance common to assume that the sample space of this random experiment is the entire interval of non-negative real numbers <span class="math inline">\({\cal S} = [0, \infty)\)</span>.</p>
<p>Many of us would hesitate to claim that the price might rise without bound. Yet many models in applied Finance are based on such an assumption. The models allow arbitrary price hikes but with arbitrary small probability as the price gets higher and higher. Practically it does not make sense to believe that a security price can become arbitrarily high. The use of arbitrarily small probabilities in a financial model might seem absurd but it does no practical harm and makes the model simple and convenient to use. Moreover, if we seriously introduced an upper bound on a security price at <span class="math inline">\(x\)</span> it would be also awkward to assume that it is impossible that it could be just a cent higher, an assumption equally unappealing than assuming it can get in principle arbitrarily high.</p>
</section>
<section id="classical-probability" class="level3 page-columns page-full" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="classical-probability"><span class="header-section-number">1.1.3</span> Classical Probability: Measuring uncertainty</h3>
<p><strong>Probability</strong> is a measure of how likely an event of an experiment is. But how could we measure chance? Here is the first big idea of probability theory and how the originators thought about it.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> How do you measure anything? If you think of length, for example, you take an arbitrary standard you agree on and then count. The originators of probability theory pursued the same idea with chance: To measure probability you choose equally probable cases and then count.</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;In this discussion I use chapter 1 in <span class="citation" data-cites="DiaconisSkyrms2019">Diaconis and Skyrms (<a href="#ref-DiaconisSkyrms2019" role="doc-biblioref">2019</a>)</span></p></div></div><p>The probability of an event <span class="math inline">\(A\)</span> according to the originators of the theory of probability is then <span class="math display">\[\begin{equation}
P(A) = \frac{\text{Number of cases where $A$ occurs}}{\text{Total number of cases}}
\end{equation}\]</span></p>
<p>Thus, if we want to know the probability of the die ending up on a face such that an even number is shown (2,4,6) we have to compute according to this notion <span class="math inline">\(3/6\)</span> (since the total number of cases are six basic outcomes) which is a chance of <span class="math inline">\(50 \%\)</span>.</p>
<p>Note that this classical notion of probability has a few interesting consequences, which we will discuss in more detail later but which already now naturally flow from this basic idea of measuring chance.</p>
<ol type="1">
<li>Probability is never negative.</li>
<li>If an event <span class="math inline">\(A\)</span> occurs in all cases <span class="math inline">\(P(A)=1\)</span>.</li>
<li>If <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> never occur in the same case, then <span class="math inline">\(P(A \,\text{or}\, B) = P(A) + P(B)\)</span>.</li>
</ol>
<p>In particular then the probability that an event does <em>not</em> occur is 1 less the probability that it occurs: <span class="math inline">\(P(\text{not}\, A) = 1 - P(A)\)</span>.</p>
<p>Let us interrupt here our discussion of probability for a moment and ask how we can make good on our promise to make these ideas tangible, so we can play with them.</p>
<p>For this we will need the computer. Since we will talk to the computer in R, it is now the right time to look at the die rolling example from the perspective of R and dive into some of its basic concepts.</p>
</section>
</section>
<section id="rolling-die-on-computer" class="level2 page-columns page-full" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="rolling-die-on-computer"><span class="header-section-number">1.2</span> Rolling a die on the computer: First steps in R</h2>
<section id="r-interface" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="r-interface"><span class="header-section-number">1.2.1</span> The R User Interface</h3>
<p>Before we can ask our tool to do anything for us, we need to know how to talk to it. In our case RStudio allows us to talk to our computer. It works like any other application. When you launch RStudio on your computer, in figure @ref(fig:rstudio-start-screen) you see a screen looking like this:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/Screenshot_RStudio.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>The RStudio startup screen</figcaption>
</figure>
</div>
</div>
</div>
<p>In this picture you see a screenshot of my RStudio screen. Interacting with the app is easy. You type commands via your keyboard at the <strong>prompt</strong>, which is the <code>&gt;</code> symbol. You find this symbol in the RStudio pane called <strong>Console</strong>. You can see it in the left pane in the screenshot. You send the command to the computer by pressing enter. After you have pressed enter, RStudio sends the command to R and displays the result of your command with a new prompt to enter new commands, like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">+</span><span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>Let me pause to explain what you see here in this code example. First you see a light-gray box containing the command <code>1+1</code>. This is an instance of a so called <strong>code chunk</strong>. Moving the cursor to the right upper corner of the chunk, will display a copy icon and you can click this icon to copy the code to the computer’s clipboard and then paste it at the prompt of your console (or for that matter anywhere else) and run it in R studio, if you wish. In the code-chunk the R-prompt <code>&gt;</code> is not displayed. This symbol of the prompt is only shown in the Console itself.</p>
<p>When the code is executed, you see the result in the second light-gray box, just below the first one. It starts with a double hash <code>##</code>, indicating that it shows an output of running the above code chunk and then displays the output as it would appear in the command window <code>[1] 2</code>.</p>
<p>The <code>[1]</code> means that the line begins with the first value of your result. For example, if you enter the command <code>20:60</code> at the prompt of your console which means in the R language, “list all the integers from 20 to 60” and press enter you get:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="dv">20</span><span class="sc">:</span><span class="dv">60</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
[26] 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60</code></pre>
</div>
</div>
<p>meaning that 20 is the first value displayed in your result. Then there is a line break because not all values can be displayed on the same line and R tells you that <code>45</code> is the 26-th value of the result.</p>
<p>The colon operator <code>:</code> is a very useful function in R which we will need often. It allows us to create sequences of every integer between two given integers.</p>
<p>R needs a complete command to be able to execute it, when the return key is pressed. Lets see what happens, if a command is incomplete, like for instance <code>&gt; 5*</code>.</p>
<p>In this case R will show the expression followed by a <code>+</code> instead of showing a new prompt. This means that the expression is incomplete. It expects more input. If we complete the expression, say like</p>
<pre><code>&gt; 5*
+ 4</code></pre>
<p>the expression can be evaluated and a new prompt is shown in the console.</p>
<p>If you type a command that R does not understand, you will be returned an error message. Don’t worry if you see an error message. It just is a way the computer tells you that he does not understand what you want him to do.</p>
<p>For instance, if you type <code>5%3</code> you will get an error message like this</p>
<pre><code>&gt; 5%3
Error: unexpected input in "5%3"
&gt;</code></pre>
<p>Sometimes it is obvious why a mistake occurred. In this case, that R just does not know what to do with the symbol <code>%</code>. It has no meaning in this context. Sometimes it is not so obvious what the error message actually means and what you might do about it.</p>
<p>A useful strategy in this case is to type the error message into a search engine and see what you can find. The chance is very high that others encountered the same problem before you and got helpful advice how to fix it from other users on the internet. One site, we find particularly helpful for all kinds of questions related to R and R programming is https://stackoverflow.com/. Try it at the next opportunity.</p>
<p>Now with this basic knowledge, we can already make the first step to create a die on the computer using R. If you think of a physical die, the essential thing that matters are the points on its six sides. If you throw the die it will usually land on one of these sides and the upward showing side of the die shows the number of points. The colon operator <code>:</code> gives us a way to create a group of numbers from 1 to 6. R gives us the result as a one dimensional set of numbers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">:</span><span class="dv">6</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 2 3 4 5 6</code></pre>
</div>
</div>
<p>Lets use these first steps in R to recap the probability concepts we have learned using this example of the six sided die: A <em>basic outcome</em> of rolling a six-sided die is for example <code>6</code> if the upper side after rolling the die happens to be the side with 6 points. The <em>sample space</em> of the experiment of rolling a six-sided die is the set <span class="math inline">\({\cal S} = \{1,2,3,4,5,6\}\)</span>. In probability theory we often use the symbol <span class="math inline">\({\cal S}\)</span> or <span class="math inline">\(S\)</span> for sample space. In many probability texts the sample space is also often denoted by the symbol <span class="math inline">\(\Omega\)</span> the Greek letter for (big) Omega. A <em>random experiment</em> in this example is the rolling of the die. The outcome is uncertain but once the die is rolled the outcome can be determined precisely. The event that the outcome is a display of 10 points is the empty set <span class="math inline">\(A = \emptyset\)</span>. The symbol <span class="math inline">\(\emptyset\)</span> comes from set theory and means the set containing no elements. This event can contain no elements because we can not get a score of 10 by rolling a six sided die.</p>
</section>
<section id="objects" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="objects"><span class="header-section-number">1.2.2</span> Objects</h3>
<p>You can save data in R by storing them in <strong>objects</strong>. An object is a name, you can choose yourself to store data. For example, if you choose to store the value <code>6</code> in an object called <code>point_six</code>, you would type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>point_six <span class="ot">&lt;-</span> <span class="dv">6</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>at the prompt. R will the store the value 6 in the object called <code>point_six</code>, which you can use to refer to the value. If you type the name of your object at the prompt, R will display the value you have assigned. A useful key combination for typing the assignment operator <code>&lt;-</code> is to use the key combination <code>ALT _</code>. At the R prompt R will automatically print an assignment operator.</p>
<p>Now if you type the name of the object and press enter, R will display the value or values stored in it, like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>point_six</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<p>Now you can use the name of the object to refer to its value. For instance, you could divide <code>point_six</code>by <code>2</code>and get a meaningful result</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>point_six<span class="sc">/</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>Now to make our <code>die</code> more tangible and useful, let us store it in an R object by typing the following command at the prompt. This command creates an object with name <code>die</code> and assigns the vector <code>1,2,3,4,5, 6</code> to it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>die <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/screenwithobject.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>The RStudio Environment pane keeps track of the objects you have created</figcaption>
</figure>
</div>
</div>
</div>
<p>You can now see in the right upper Environment pane in figure @ref(fig:rstudio-screen-with-command) that R shows you that there is an object with the name <code>die</code> that it consists of integers <code>1,2,3,4,5</code>. As you create more objects they will be stored in the Environment pane and are ready for your reference, unless you delete them. You can remove or delete an object by typing <code>rm(object)</code> or by assigning the value <code>die &lt;- NULL</code> which would also remove the object from your environment or workspace.</p>
<p>You can name your objects almost anything with a few exceptions. An object name must not start with a number. There are some special symbols which can also not be used in object names, like <code>^, !, $, @, +, -, /, *</code>. Note that R is case sensitive and distinguishes small and big letters. If you assign a new value for an object you have already created, R will overwrite the object without warning.</p>
<p>You can see which objects are currently created and available for you in the Environment pane of your session of by typing <code>ls()</code>. The UNIX users among you will recognize this command from the unix shell, where it displays the files in a directory.</p>
<p>Before we learn how we can actually roll our die and perform a random experiment with it, let us briefly use the opportunity to explain a few things about how R does computations. We have already explained that we can use the object name to refer to the value. So for instance if we type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>die<span class="sc">*</span>die</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1  4  9 16 25 36</code></pre>
</div>
</div>
<p>This might irritate some of you because we have called the object a vector. In linear algebra multiplication of vectors is only allowed if there is an inner product. What happens here, if we use <code>*</code> the multiplication operator is that R does an element-wise multiplication of the six numbers of our die. Of course R allows to take an inner product as well, but this needs a different operator. To compute an inner product, we would type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>die <span class="sc">%*%</span> die</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]
[1,]   91</code></pre>
</div>
</div>
<p>Now R displays the result as a vectors with one row and one column, which is denoted in the output by <code>[ , 1]</code> for the column and <code>[1, ]</code> for the row. We will learn later more about the use and the meaning of this notation in R.</p>
<p>The element wise execution R usually uses also means that when you, for example type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>die <span class="sc">-</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0 1 2 3 4 5</code></pre>
</div>
</div>
<p>R would subtract <code>1</code> from every component in the vector <code>die</code>.</p>
<p>Another specific behavior of R, you need to know about is called <strong>recycling</strong>. If you give R two vectors of different length in an operation, R will repeat the shorter vector as long as it is of equal length with the longer one. For example, if you have: ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>die <span class="sc">+</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2 4 4 6 6 8</code></pre>
</div>
<p>:::</p>
<p>you see that R adds 1 to 1 and 2 to 2 and then starts over again by adding 1 to 3 and 2 to 4 and then starts over once again by adding 1 to 5 and 2 to 6. If the longer vectors is not a multiple of the shorter one, R recycles but the cuts off. It will give you a warning though. ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>die <span class="sc">+</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in die + 1:4: longer object length is not a multiple of shorter object
length</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2 4 6 8 6 8</code></pre>
</div>
<p>:::</p>
<p>While this might seem awkward to some of you, we will see that for data manipulation element-wise execution is often extremely useful. It allows to manipulate groups of values in a systematic yet easy way.</p>
</section>
<section id="functions" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="functions"><span class="header-section-number">1.2.3</span> Functions</h3>
<p>R contains many <strong>functions</strong> which we can use to manipulate data and compute things. The syntax for using a function is very simple: You type the function name and put the value of the function <strong>argument</strong> in parentheses. Here we use for illustrations the function of the square root <code>sqrt()</code>: ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<p>::: or rounding a number: ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fl">3.1415</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<p>::: The data you write in the parentheses are called the <strong>function arguments</strong>. Arguments can be all sorts of things: raw data, R objects, results from other functions.</p>
<p>If functions are nested, R evaluates the innermost function first and then goes on to the outer functions. To see examples of all these instances you can take ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(die)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(die))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<p>::: for example.</p>
<p>For simulating random experiments, R has the very useful function <code>sample()</code>. With this function we can roll our die on the computer and conduct actual random experiments.</p>
<p>The function takes as arguments a vector names <code>x</code> and a number named <code>size</code>. <code>sample</code> will return <code>size</code> elements randomly chosen from the vector <code>x</code>. Lets say: ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">size =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3 1</code></pre>
</div>
<p>:::</p>
<p>In this case <code>sample</code> has chosen <code>4,1</code> from the vector <code>x = (1,2,3,4)</code> at random.</p>
<p>If we want to roll the die in our computer we can thus pass the die as an argument to <code>sample</code> and use the number <code>1</code> for the <code>size</code> argument. Lets do a few rolls with our die ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="at">x =</span> die, <span class="at">size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="at">x =</span> die, <span class="at">size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="at">x =</span> die, <span class="at">size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(<span class="at">x =</span> die, <span class="at">size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<p>::: These are the random outcomes of our consecutive rolls. It is as if we had thrown an actual die but in this case we have done the same thing on the computer. Isn’t it cool that this is possible at all? The <code>sample()</code> function will remain our good friend throughout this course.</p>
<p>R functions can have many arguments, but they need to be separated by a comma.</p>
<p>Every argument in every function has a name. We specify which data are assigned to the arguments by setting a mathematical equal sign <code>=</code> between the name and the data. Names help us to avoid passing the wrong data and thereby mixing up things or committing errors. But using names is not necessary. If we just wrote ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(die,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<p>::: R would also know what to do. It is not always clear which names to use for a function. If you are not sure, you can use the function <code>args()</code> to look it up. Here we take the function <code>round</code>as one example. ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">args</span>(round)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>function (x, digits = 0, ...) 
NULL</code></pre>
</div>
<p>::: Note that the <code>digits</code> argument in the <code>round</code> function is already set to <code>0</code>. Frequently R functions come with optional arguments. These arguments are optional because the come with a default value, which is <code>0</code> in case of the round function.</p>
<p>We recommend that you write out argument names as a rule. It gives clearer code and avoids errors. If you don’t write argument names, R matches your values to the arguments of the function by order.</p>
</section>
<section id="writing_your_own_functions" class="level3" data-number="1.2.4">
<h3 data-number="1.2.4" class="anchored" data-anchor-id="writing_your_own_functions"><span class="header-section-number">1.2.4</span> Writing your own functions</h3>
<p>Now we are ready to write our own function to roll the die in our computer. Each function in R has the same elements: A <strong>name</strong>, a <strong>function body</strong> of code and a set of <strong>arguments</strong>. To write your own function, you have to write up all of these parts and save them in an R object. The syntax is:</p>
<pre><code>my_function &lt;- function() {}
</code></pre>
<p>The name here is <code>my_function</code>, next comes the expression <code>function()</code> which needs to be assigned. The names of the function arguments have to be written between the parentheses. Then we have to write the actual code within the braces <code>{}</code>.</p>
<p>To do this for the die, lets write a function named <code>roll_die</code>. ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>roll_die <span class="ot">&lt;-</span> <span class="cf">function</span>(){die <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">sample</span>(die, <span class="at">size =</span> <span class="dv">1</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<p>Now we can roll our die for a few times to show how the function works ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<p>::: Note that in our function <code>roll_die()</code> has no arguments, just the function body. This is perfectly legitimate in R. It is important that when we call the function we have to call it with the parenthesis like <code>roll_die()</code>. If we only call the name <code>roll_die</code>, R will display the code in the function body.</p>
<p>A final remark in the <code>sample</code> function is in place here. If we look at the arguments of sample using the <code>args</code> function we see ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">args</span>(sample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>function (x, size, replace = FALSE, prob = NULL) 
NULL</code></pre>
</div>
<p>::: Lets do not discuss all the details of this output but concentrate for a moment on the <code>replace</code> argument. What does this mean?</p>
<p>As we saw previously we can use the sample function to model the rolling of our die. If we set the <code>size</code> argument to <code>1</code> we get the roll of one die. If we set the <code>size</code> argument to <code>n</code>, we would simulate the rolling of <code>n</code> dies. But now the <code>replace</code> argument becomes crucial. As we can see in the output of the <code>args</code> function <code>replace</code> has a default value <code>FALSE</code>. This is a logical argument. It tells R, for example, that if we set <code>size = 2</code>, meaning that two dice are rolled, if the first dice shows, say a value of 3, the second die cannot show 3 as well.</p>
<p>This is clearly not what we have in mind when we model the rolling of 2 dice. It should be possible that both dies show the same value. To enable this behavior of the sample function, we have to change the default value of the <code>replace</code> argument to <code>TRUE</code>. Then R chooses a random draw from all of the six possible values for all dice rolled.</p>
<p>Congratulations ! You have written your first R function for conducting a simple random experiment. Let me remind you once again: Think of the parentheses as a trigger that tells R to run the function. If you omit the trigger R just prints the body of the function. When you run a function, all the code in the function body is executed and R returns the result of the last line of code. If the last line of code does not return a value neither will R.</p>
</section>
<section id="arguments" class="level3" data-number="1.2.5">
<h3 data-number="1.2.5" class="anchored" data-anchor-id="arguments"><span class="header-section-number">1.2.5</span> Arguments</h3>
<p>Imagine we remove the first line of code in our function body and changed the name die in the sample function to “ball”. ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>roll_die2 <span class="ot">&lt;-</span> <span class="cf">function</span>(){<span class="fu">sample</span>(ball, <span class="at">size =</span> <span class="dv">1</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: If we call the function now, we will get an error. The function call <code>roll_die2()</code> will result in the error message <code>Error in sample(ball, size = 1) : object 'ball' not found</code> (try it!)</p>
<p>We could supply ball when we call <code>roll_die2</code> if we make ball an argument of the function. Lets do this: ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>roll_die2 <span class="ot">&lt;-</span> <span class="cf">function</span>(ball){<span class="fu">sample</span>(ball, <span class="at">size =</span> <span class="dv">1</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: Now the function will work as long as we supply <code>ball</code> when we call the function. ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die2</span>(<span class="at">ball =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<p>::: Note that we still get an error, if we forget to supply ball argument. This could be avoided if we give the function a default argument ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>roll_die2 <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">ball=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>){<span class="fu">sample</span>(ball, <span class="at">size =</span> <span class="dv">1</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: Now if we type: ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">roll_die2</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
<p>::: everything works, just as intended.</p>
</section>
<section id="scripts" class="level3" data-number="1.2.6">
<h3 data-number="1.2.6" class="anchored" data-anchor-id="scripts"><span class="header-section-number">1.2.6</span> Scripts</h3>
<p>So far we have worked by interacting with the console. But what if you want to edit your functions? It would be much easier, if you could use a draft of your code and work form there. This can be done by using a <strong>script</strong>.</p>
<p>You create a script by going to <code>File &gt; New File &gt; R script</code> in the menu bar of RStudio. Using scripts is the standard way to write code in R. It not only helps you to keep track of your code, save it and edit it later. It also makes your work <em>reproducible</em>. You can edit and proofread your code and share it with others. To save your script go to <code>File &gt; Save As</code> in the menu bar.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/scriptscreen.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>The RStudio Script</figcaption>
</figure>
</div>
</div>
</div>
<p>RStudio has many useful features to help you work with scripts. You can for instance automatically execute a line in a code by using the run button. You can also execute sections of code or the entire script. The entire script is executed by running the Source button. For all these commands there are key short cuts which you will learn as you work more with RStudio and R.</p>
<p>From now on you should write all your R-code for this course in scripts. Make a new folder for the scripts you write and store your R-code there from now on.</p>
</section>
<section id="packages_help" class="level3" data-number="1.2.7">
<h3 data-number="1.2.7" class="anchored" data-anchor-id="packages_help"><span class="header-section-number">1.2.7</span> Using packages and finding Help</h3>
<p>We have now a function which we can use to simulate the rolling of a die, <code>roll_die()</code>. If the die is <em>fair</em> it should be the case that if we roll the die often, all numbers should occur about equally often. The die should not be weighted in favor of a particular value.</p>
<p>One way to learn whether our die is fair are <em>repetition</em> and <em>visualization</em>. These are tools we will need all the time, when working with data and when doing probability. While R has many useful functions, one of the great powers is that R is constantly extended by a huge community of users by providing packages.</p>
<p>Packages are add on functions, which will not be available when you install R. They need to be installed and loaded before you can use them. Since packages are such a powerful tool in R we need to introduce what they are and how to use them in the beginning.</p>
</section>
<section id="packages" class="level3 page-columns page-full" data-number="1.2.8">
<h3 data-number="1.2.8" class="anchored" data-anchor-id="packages"><span class="header-section-number">1.2.8</span> Packages</h3>
<p>There are many visualization tools in R that come with the basic installation. Since the point we want to make here is about packages, we will use a visualization function which is part of the add on package <strong>ggplot2</strong>, a very popular package for making all kinds of graphs. ggplot2 is not part of the base-R distribution. It has to be therefore loaded before we can use it.</p>
<p>There are many additional functions provided with this package. Indeed you could run a whole course on just that <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> For the point we want to make here we will use just one of them, called <code>qplot()</code>, a shorthand for for quick plot.</p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;A very good starting point is for instance <span class="citation" data-cites="Healy2018">Healy (<a href="#ref-Healy2018" role="doc-biblioref">2019</a>)</span>, in case you are interested. Also a good source is the first chapter in <span class="citation" data-cites="WickhamGrolemund2017">Wickham and Grolemund (<a href="#ref-WickhamGrolemund2017" role="doc-biblioref">2017</a>)</span>.</p></div></div><p>Since <code>qplot()</code> is a function in the package <em>ggplot2</em>, we first need to install this package. To install a package you need to be connected to the internet. If you have internet connection go to the command line and run at the command line: <code>install.packages("ggplot2")</code>.</p>
<p>R displays what is happening while executing the command. Don’t worry if you don not know what all of these messages exactly mean and don’t panic that they are displayed in red. All packages can be installed like this. You have just to enter the correct name in the function <code>install.packages()</code>. The lower right pane in the RStudio software alternatively provides a tab called <strong>Packages</strong>. Using this tab, you can also install R packages interactively by clicking the install button on the upper left corner of the Packages tab.</p>
<p>After installation the package is on our hard-drive but it can not yet be used. To use the package it has to be loaded. This is done with the command <code>library</code>. To load the <em>ggplot2</em> package we type ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: and hit the return key. Many things could be said about the R package system and you will learn it in more detail as we go along in our course. For the moment the most important thing to remember is that a package needs to be newly loaded whenever you want to use it in a new R session.</p>
<p>To check whether our dies is fair, we need to roll it many times. R provides a function, that does this for us. This function is called <code>replicate()</code> and provides an easy way to repeat a command many times. The number of times we want to repeat something is given as an argument to the <code>replicate</code> function.</p>
<p>Now lets roll our die 100 times and save the result in an object we call <code>rolls</code>: ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>rolls <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100</span>, <span class="fu">roll_die</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: We now use the <code>qplot()</code>function from the <em>ggplot2</em> library to make a quick visualization, by typing the command <code>qplot(rolls)</code>. I include the resulting picture in the following figure ::: {.cell layout-align=“center”} ::: {.cell-output-display} <img src="figures/100_rolls.png" class="img-fluid quarto-figure quarto-figure-center" style="width:90.0%" alt="Frequencies of 1, 2, 3, 4, 5, 6 after rolling our virtual die 100 times"> ::: ::: If you try this and your picture looks a bit different from mine, don’t worry. This is as things should be. I have stored the picture after one particular run of the replicate function and saved it in my figures folder to these lecture notes. Each time you run the replicate function anew a new random outcome is stored which will look not exactly the same as any other or course. This is what randomness does to the outcome of rolling a die.</p>
<p>It looks like every value occurred roughly 16 times but there is still quite some variation. For instance, the value 3 seems to occur more than 20 times whereas the value 2 occurs less than 15 times.</p>
<p>Maybe we have to give it another trial with more replications. With the computer we can do this with a fingertip. Let us roll our die 10000 times and plot the result.</p>
<pre><code>&gt; rolls2 &lt;- replicate(10000, roll_die())
&gt; qplot(rolls2m bindwidth = 1)</code></pre>
<p>Now the picture looks better.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/10000_rolls.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Frequencies of 1, 2, 3, 4, 5, 6 after rolling our virtual die 10000 times</figcaption>
</figure>
</div>
</div>
</div>
<p>We will learn in our course why the picture get better as we increase the number of rolls of the die. For the moment, let us just state that at least for this case it seems that there is no significant visual evidence that our virtual die is loaded.</p>
</section>
<section id="getting_help" class="level3" data-number="1.2.9">
<h3 data-number="1.2.9" class="anchored" data-anchor-id="getting_help"><span class="header-section-number">1.2.9</span> Getting Help</h3>
<p>We have now learned a tiny number of R functions and we have written one function ourselves. We have learned how to make use of functions provided by packages.</p>
<p>It would be overwhelming to memorize and learn them all. In R, fortunately, every function comes with a detailed documentation and with its own help page. You need to learn how to use this source right from the beginning.</p>
<p>To access the help page of a function you type the function name preceded by a question mark at the prompt, like this ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>?sample</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<p>Then, after you have pressed the return key, a help page is opened in the right lower pane under the help tab as shown in @ref(fig:helpinr) ::: {.cell layout-align=“center”} ::: {.cell-output-display} <img src="figures/rhelp.png" class="img-fluid quarto-figure quarto-figure-center" style="width:90.0%" alt="The Help-pane in RStudio"> ::: :::</p>
<p>This help page has a particular structure that you will find for every other R function no matter whether it is provided by the base installation or by a package. In the upper left corner you see the name of the function (<code>sample</code>) and in curly brackets next to it the term <code>base</code>, which means that this is a function in the R base installation. Then you see a headline about what the function does.</p>
<p>From the top of the page, you then first see the field <strong>Description</strong>. This is a short description what the function does. Here it says</p>
<pre><code>Description
sample takes a sample of the specified size from the elements of x using either with or without replacement.</code></pre>
<p>The next field is <strong>Usage</strong>. It gives you the function description with the arguments. Here for example</p>
<pre><code>Usage
sample(x, size, replace = FALSE, prob = NULL)

sample.int(n, size = n, replace = FALSE, prob = NULL,
           useHash = (!replace &amp;&amp; is.null(prob) &amp;&amp; size &lt;= n/2 &amp;&amp; n &gt; 1e7))
           </code></pre>
<p>The first line in Usage should by now be familiar. Don’t worry about the second line. The function can obviously do more than we know so far.</p>
<p>Next comes a list of arguments the function takes and what type of information R expects you to provide, as well as what R will do with this information. Here it says for example</p>
<pre><code>Arguments
x   
either a vector of one or more elements from which to choose, or a positive integer. See ‘Details.’

n   
a positive number, the number of items to choose from. See ‘Details.’

size    
a non-negative integer giving the number of items to choose.

replace 
should sampling be with replacement?

prob    
a vector of probability weights for obtaining the elements of the vector being sampled.

...
</code></pre>
<p>We omit some information here.</p>
<p>Then comes a field called <strong>Details</strong> which gives a more in-depth description of the function. The next field is called <strong>Value</strong>. It describes what the function returns when you run it. Then we have a reference to related R functions under the field <strong>See</strong>. Finally there is a field called <strong>Examples</strong>. This field contains example code that is guaranteed to work. It shows a couple of different cases how you can use the function in practice.</p>
</section>
</section>
<section id="coincidences" class="level2 page-columns page-full" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="coincidences"><span class="header-section-number">1.3</span> Application: Coincidences and the Blockchain</h2>
<section id="birthday_problem" class="level3 page-columns page-full" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="birthday_problem"><span class="header-section-number">1.3.1</span> The birthday problem</h3>
<p>We learned now some basic notions of probability and of R with the example of the rolling of a fair die. It is really surprising what already can be done by just applying the simple ideas we have just learned. The application we want to show you now is known to probability theorists as the <strong>birthday problem</strong>. It originates in a piece of recreational maths and math-puzzles but it reaches out until cryptography, computer security and blockchain architecture. It also gives us an opportunity to apply some of our newly acquired R-knowledge.</p>
<p>The starting question in the birthday puzzle is: What is the probability that at least two people in a room share the same birthday, when we neglect things like leap years, and when we assume that birthdays on any day of the year are equiprobable and the birthdays of the people in the room are independent. We have no twins for example. Perhaps some of you have already seen this problem before. If not, the result may surprise you. Even if you saw the birthday problem before, perhaps not many of you have seen the connection to the cryptography and the blockchain.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp;We follow here the discussion in <span class="citation" data-cites="DiaconisSkyrms2019">Diaconis and Skyrms (<a href="#ref-DiaconisSkyrms2019" role="doc-biblioref">2019</a>)</span></p></div></div><p>First, observe that we took our assumptions such that we are in the frame of classical probability like the originators of the field thought about it.</p>
<p>Now for the sake of familiarizing ourselves with the new concepts, let us try to map the birthday problem into the probability notions we learned so far.</p>
<p>The <em>sample space</em> is the set of possible outcomes of the experiment. Assume we have <span class="math inline">\(n\)</span> people in the room. Since each person can have a birthday at any of the 365 days in the year (note that we assumed we exclude leap years) and we have <span class="math inline">\(n\)</span> people in the room, the possible basic outcomes are <span class="math inline">\(365 \times 365 \times 365 \cdots 365\)</span> taken <span class="math inline">\(n\)</span> times. This will produce a set with <span class="math inline">\(365^{n}\)</span> ordered <span class="math inline">\(n-tuples\)</span> or sequences of birthdays. This is the sample space of this experiment, written as <span class="math inline">\({\cal S} = \{x | x \in 365^n\}\)</span> in set theoretic notation. It means the sample space is the set of all ordered <span class="math inline">\(n-tuples\)</span> from the Cartesian product <span class="math inline">\(365^n\)</span>.</p>
<p>Remember that in mathematics, a Cartesian product is a mathematical operation that returns a set (or product set or simply product) from multiple sets (in this case the sample space, <span class="math inline">\({\cal S}\)</span>. That is, for sets <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, the Cartesian product <span class="math inline">\(A \times B\)</span> is the set of all ordered pairs <span class="math inline">\((a, b)\)</span> where <span class="math inline">\(a \in A\)</span> and <span class="math inline">\(b \in B\)</span>.</p>
<p>Now given this sample space we can assign a probability to the event that two people chosen at random will have the same birthday. The denominator will this be <span class="math inline">\(365^n\)</span>. The nominator for this probability will be much more straightforward to figure out, if we compute the complement. We discussed before that the probability of the complement of an event is 1 minus the probability of the event. Translated to the birthday problem, this means we look for the 1 minus the probability that that all birthdays are different. The probability that the second person has a different birthday from the first is <span class="math inline">\(\frac{364}{365}\)</span>. If they are different the probability that the third person has a different birthday from them is <span class="math inline">\(\frac{363}{365}\)</span> and so on for all <span class="math inline">\(n\)</span> in the room. Thus the probability of a shared birthday in the room is: <span class="math display">\[\begin{equation*}
P(\text{at least two people share birthday}) =
1 - \frac{365 \times 364 \times 363 \cdots \times 365 - n +1}{365^n}
\end{equation*}\]</span> Now there is an additional thing we did not yet introduce and which we will learn about in the next lecture. This refers to our assumption that the individual birthdays are independent. For the moment you need to take the following fact on faith: The probability of independent events is the product of the probability these events.</p>
<p>Now comes the surprise for those of you who did not already see the birthday problem. Assume the group size of people is 23. Let us compute the birthday coincidence probability. For this computation we make use of the R function <code>prod()</code> which takes a vector of numbers as input and computes their product. For <span class="math inline">\(n=23\)</span> we need the list of numbers from 365 to 343. Now we can use the <code>:</code> operator and take advantage from one of its cool properties. If we formulate the command as <code>365:343</code> then the colon operator will give us a descending list of integers starting at 365 and ending at 343. Then the probability can be computed as ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">prod</span>(<span class="dv">365</span><span class="sc">:</span><span class="dv">343</span>)<span class="sc">/</span><span class="dv">365</span><span class="sc">^</span><span class="dv">23</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5072972</code></pre>
</div>
<p>::: We have used the operator <code>^</code> which is needed to compute powers. Now we see from our computation that with 23 people the probability is already larger than 50 %. Quite stunning. You can now verify yourself that with 50 people this probability is already at 97 %.</p>
</section>
<section id="an-r-function-to-compute-birthday-probabilities" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="an-r-function-to-compute-birthday-probabilities"><span class="header-section-number">1.3.2</span> An R function to compute birthday probabilities</h3>
<p>Now let us use our knowledge about how to write R functions to write a function to compute birthday probabilities. The function argument is the number <span class="math inline">\(n\)</span> of people in class. The coincidence probability is given by the formula we have derived. Now here is how we could go about writing this function: ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>birthday_collisions <span class="ot">&lt;-</span> <span class="cf">function</span>(n){</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span> <span class="sc">-</span> <span class="fu">prod</span>(<span class="dv">365</span><span class="sc">:</span>(<span class="dv">365</span><span class="sc">-</span>n<span class="sc">+</span><span class="dv">1</span>))<span class="sc">/</span><span class="dv">365</span><span class="sc">^</span>n</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: Now lets verify what I have claimed before about the group size 50. ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">birthday_collisions</span>(<span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9703736</code></pre>
</div>
<p>::: Voila, indeed with 50 people in the group the collision probability is already at 97 %.</p>
</section>
<section id="determining-birthday-collisions-by-simulation" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="determining-birthday-collisions-by-simulation"><span class="header-section-number">1.3.3</span> Determining birthday collisions by simulation</h3>
<p>Now this was an argument derived analytically and then we just packed the derived result into a function to compute the exact birthday-collision probabilities. Here is how we could figure out these probabilities by simulation, even with the minimal tools we have learned so far.</p>
<p>Let us simulate first birthdays for 23 people in a room using the sample function. We stick to the assumption that our year has 365 days (no leap years), and that all birthdays are equally likely, so we can sample from the list of days from 1 to 365 with the sample function which we have already encountered.</p>
<p>We need to take care to set the <code>replace</code> argument in the sample function to the value <code>TRUE</code>. This is because we always draw for every person in the room from the same list of values. If one birthday is drawn it is possible in principle that later in the process the same birthday is drawn again. Before, when we worked with only one die we did not need to care whether sample drew with replacement or not. ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>b_23 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">365</span>, <span class="dv">23</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: This little piece of code is to be read in the same way as before when we built the process of rolling a die on the computer. We sample 23 values from the vector <span class="math inline">\(1,2,3,\cdots,365\)</span> <strong>without</strong> replacement. Think about a situation where I use uniform random numbers to call 23 people in your group and write the birthdays I get in this way into the object <code>b_23</code>.</p>
<p>Here is how I can find the number of matches in <code>b_23</code>. R has a built in function, which is called <code>unique()</code>. So if there were two people with the same birthday in <code>b_23</code>, applying <code>unique()</code> to <code>b_23</code> would only keep one value. Now clearly if we subtract the length of the resulting object from 23 we get the number of collisions in <code>b_23</code>. Fortunately we can use the R function <code>length()</code> to achieve this task. <code>length()</code> computes the length of any object we give it as an argument. ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>m_23 <span class="ot">&lt;-</span> <span class="dv">23</span> <span class="sc">-</span> <span class="fu">length</span>(<span class="fu">unique</span>(b_23))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: So for instance if <code>sample()</code> drew 23 different birthdays <code>m_23</code> would be 0.</p>
<p>Let’s pack this process into a function: ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>sim_23 <span class="ot">&lt;-</span> <span class="cf">function</span>(){</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>  b_23 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">365</span>, <span class="dv">23</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">23</span> <span class="sc">-</span> <span class="fu">length</span>(<span class="fu">unique</span>(b_23)))</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: Now we can repeat this process many times - say 10000 times - using the replicate function. ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>simprobs_23 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, <span class="fu">sim_23</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<p>Now how do we get from here to probabilities? Here we anticipate and introduce a new probability concept which we will discuss in more detail in the next lecture but which you perhaps already came across a few times.</p>
<p>This concept could be called the <strong>relative frequency probability</strong> . In this concept the probability of an event <span class="math inline">\(A\)</span> is defined as <span class="math display">\[\begin{equation*}
P(A) = \frac{\text{Number of times $A$ occurs in repeated identical trials}}{\text{Total number of trials in a random experiment}}
\end{equation*}\]</span> Applying this concept to our data generated by the replicate function and stored in <code>b_23</code> would require two things. First we would have to count the number of times we saw a 1,2 or more matches, which in our case means 1,2 or more birthday collisions, add up the count and divide by the number of replications. Clearly it is also easier here to work the other way round. We count the number of no collisions and use the complement rule, by computing 1 minus the relative frequency of no collisions. Let us do that.</p>
<p>Now this is clearly too tedious to do by hand. We will discuss systematically in the next lecture how to refer to individual values in an R object and select and operate on ranges of values etc.</p>
<p>For the moment, look at the next step just as a piece of magic and don’t worry if you do not exactly understand the syntax at the moment.</p>
<p>In the numerator I ask R to count the number of 0s (no birthday collisions) in the object <code>simprobs_23</code> and then I divide it by 10000, just as in the definition of relative frequency probability. Then I compute 1 minus this relative frequency ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">length</span>((simprobs_23[simprobs_23 <span class="sc">==</span> <span class="dv">0</span>]))<span class="sc">/</span><span class="dv">10000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5067</code></pre>
</div>
<p>::: Voila, this is pretty good, isn’t it? Remember that the analytical solution we just got a bit earlier was <code>0.5072972</code></p>
<p>Isn’t this cool? Instead of using formal reasoning we built a random experiment on the computer and came up with a pretty good approximation of the collision probability.</p>
<p>Let’s check the result with 50 for the sake of completeness and for the sake of practice, with an experiment with 10000 trials. I now stitch all steps together. ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>sim_50 <span class="ot">&lt;-</span> <span class="cf">function</span>(){</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  b_50 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">365</span>, <span class="dv">50</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  (<span class="dv">50</span> <span class="sc">-</span> <span class="fu">length</span>(<span class="fu">unique</span>(b_50)))}</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>simprobs_50 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100000</span>, <span class="fu">sim_50</span>())</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">length</span>((simprobs_50[simprobs_50 <span class="sc">==</span> <span class="dv">0</span>]))<span class="sc">/</span><span class="dv">100000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.97027</code></pre>
</div>
<p>::: Pretty amazing! Before we got the exact value as <code>0.9703736</code>.</p>
<p>But now let us stay still with the birthday problem but now get away from this playful application to something really serious: Cryptography.</p>
</section>
<section id="hashfunctions" class="level3 page-columns page-full" data-number="1.3.4">
<h3 data-number="1.3.4" class="anchored" data-anchor-id="hashfunctions"><span class="header-section-number">1.3.4</span> Hash-functions and the blockchain</h3>
<p>The birthday problem is the canonical model for the probabilistic study of coincidences of all kinds. A particular important application of this idea is in cryptography, and its concept of so called <strong>hash-functions</strong>.</p>
<p>A hash-function maps a string of arbitrary but finite length to a fixed length string of output.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> A very frequently used hash-function in practice is the function SHA-256, which maps its input to a string of 256 bits<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>. So, you could for instance give the text of these lecture notes as an input to SHA-256 and it would map this into a 256-bit string, which functions like a finger print of this text. This function is an instance of a special from of mappings called a <em>one-way-function</em> meaning that it is easy to evaluate or compute but it is practically impossible to learn from the value the initial argument by computing the inverse.</p>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;We have taken this discussion from https://brilliant.org/wiki/birthday-paradox/</p></div><div id="fn5"><p><sup>5</sup>&nbsp;A bit, short for binary digit, is defined as the most basic unit of data in telecommunications and computing. Each bit is represented by either a 1 or a 0</p></div></div><p>Hash-Functions are key pillars of modern cryptography, where they play a major role in message authentication. This is because it is impossible to modify the input without significantly changing the output. So in our previous example, if you only deleted or added a comma to these notes and hash-them again they would hash into a completely different value than the previous version which still was without this minor change. Comparing the hash-values would reveal immediately that something has changed.</p>
<p>The collision problem for hash-functions is formally equivalent to the birthday problem. The event we are interested in is that <em>at least two input strings hash-to the same value</em>. Again it is easier to think about the complementary event that <em>all inputs hash to a different value</em>.</p>
<p>If the range of the hash-function is <span class="math inline">\(M\)</span> and the hash-function maps into a 256 bit string then there are <span class="math inline">\(2^{256}\)</span> basic outcomes. Since the hash-function maps a large string onto a smaller string it is possible that there are two different strings <span class="math inline">\(x \neq y\)</span> mapping to the same value <span class="math inline">\(\text{hash}(x)=\text{hash}(y)\)</span>. This would be a problem for message authentication because it would give the same “fingerprint” for two different strings.</p>
<p>For a cryptographically secure hash function it is therefore required that the probability of such a collision should be small enough to exclude a collision in all practically relevant circumstances.</p>
<p>Note that this is a problem formally similar to the birthday problem. In the cryptography context we ask, how many values does a potential attacker have to hash through SHA-256 before the probability of a collision is larger than a certain threshold?</p>
<p>The probability of no-collision (<span class="math inline">\(nc\)</span>) with <span class="math inline">\(n\)</span> hashed-messages through a SHA-256 hash function is <span class="math display">\[\begin{equation*}
P_{nc}(n) = 1 \times \left(1 - \frac{1}{2^{256}}\right)\times
\left(1 - \frac{2}{2^{256}}\right) \times \cdots \times \left(1 - \frac{(n-1)}{2^{256}}\right)
\end{equation*}\]</span></p>
<p>Now to do the estimation of the threshold we use an approximation, which works with a simple property of the logarithm: <span class="math inline">\(\log(1-x)\approx -x\)</span> when <span class="math inline">\(x\)</span> is small. Thus for <span class="math inline">\(n\)</span> much smaller than <span class="math inline">\(M\)</span>, or <span class="math inline">\(n \ll M\)</span>, we can write the no-collision probability approximately as <span class="math display">\[\begin{align*}
P_{nc}(n) &amp;\approx 1 \times \exp\left(-\frac{1}{2^{256}}\right) \times \exp\left(-\frac{2}{2^{256}}\right) \times \cdots
\times \exp\left(-\frac{(n-1)}{2^{256}}\right) \\
&amp;\approx 1 \times \exp\left(-\frac{(1+2+3+...+(n-1))}{2^{256}} \right) \\
&amp;\approx \exp\left(-\frac{n \times (n-1)}{2 \times 2^{256}}\right)
\end{align*}\]</span> Now if <span class="math inline">\(n \ll 2^{256}\)</span> we can again use the approximation <span class="math inline">\(\exp(x) \approx 1 + x\)</span> to get the probability of a hash-collision as <span class="math display">\[\begin{align*}
P_{nc}(n) &amp;\approx 1 - \frac{n \times (n-1)}{2\times 2^{256}}\\
       &amp; \approx 1 - \frac{n^2}{2\times 2^{256}}
\end{align*}\]</span> Thus the probability of a hash-collision as a function of <span class="math inline">\(n\)</span> is then approximately <span class="math display">\[\begin{equation*}
P_{c}(n) = \frac{n^2}{2 \times 2^{256}}
\end{equation*}\]</span> Thus to have a collision probability with <span class="math inline">\(99.8%\)</span> you need ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">2</span><span class="sc">*</span><span class="dv">2</span><span class="sc">^</span><span class="dv">256</span><span class="sc">*</span><span class="fl">0.998</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.807505e+38</code></pre>
</div>
<p>::: which is about <span class="math inline">\(5*10^{38}\)</span> hashes. To have a collision probability of <span class="math inline">\(50 \%\)</span> you need ::: {.cell}</p>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">2</span><span class="sc">^</span><span class="dv">256</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.402824e+38</code></pre>
</div>
<p>::: which amounts to <span class="math inline">\(2^{128}\)</span> hashes. This is, of course a <strong>really</strong> big number.</p>
<p>Let’s put this into perspective: If a computer computes <span class="math inline">\(10000\)</span> hashes per second, it would take more than <span class="math inline">\(10^{27}\)</span> years to compute <span class="math inline">\(2^{128}\)</span> hashes. <span class="citation" data-cites="Narayananetal2016">Narayanan et al. (<a href="#ref-Narayananetal2016" role="doc-biblioref">2016</a>)</span> formulate it like this: “<em>…if every computer ever made by humanity had been computing since the beginning of the universe, the odds that they would have found a collision by now are still infinitesimally small. So small that it it’s far less than the odds that a meteor will land on your house.</em>”.</p>
</section>
</section>
<section id="summary" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="summary"><span class="header-section-number">1.4</span> Summary</h2>
<p>In this lecture we have taken a first step towards some very basic probability notions and some basic steps in R. Isn’t it amazing how much territory we could cover with so few concepts? You have learned about how to think probabilistically about collision probabilities and how to solve for them analytically, by simulation and for large numbers by approximation.</p>
<p>We have convinced ourselves using this knowledge only and taking on faith that the probability of independent events is the product of their individual probabilities, that the cryptographic Hash-function SHA-256, while it can produce collisions in theory, practically the number of hashes to make such a collision occur would be so large that we can be confident that hashing bit strings with SHA-256 gives us a unique fingerprint practically with certainty.</p>
<p>These are the basic <strong>probability concepts</strong> we have covered in this lecture:</p>
<ol type="1">
<li>A <strong>random experiment</strong>: A process leading to an uncertain outcome.</li>
<li><strong>Sample space</strong>: The collection of all possible outcomes of a random experiment.</li>
<li><strong>Basic outcome</strong>: A possible outcome of a random experiment.</li>
<li><strong>Event</strong>: An event is a subset of basic outcomes. Any event which contains a single outcome is called a simple event.</li>
<li><strong>Classical probability</strong> find or make equally probably cases and the count them. The probability of an event <span class="math inline">\(A\)</span> is the number of cases when <span class="math inline">\(A\)</span> occurs divided by the total number of cases.</li>
<li><strong>Relative frequency probability</strong> defined as the number of times an event <span class="math inline">\(A\)</span> occurs in a repeated number of trials divided by the total number of trials in a random experiment.</li>
</ol>
<p>These are the <strong>R concepts</strong> we have covered in this lecture:</p>
<ol type="1">
<li><strong>objects</strong> arbitrary names that can store different values and data types.</li>
<li><strong>functions</strong> ab R object that can accept other R objects as arguments, operate on them and return a new object.</li>
<li><strong>scripts</strong> files that store sequences of R commands and can be saved, repopened and allow the execution of commands.</li>
<li><strong>using packages</strong></li>
<li><strong>finding help</strong></li>
<li><strong>the functions sample and replicate</strong></li>
</ol>
<p>These are the <strong>Applications</strong> we have covered in the lecture:</p>
<ol type="1">
<li><strong>Constructing a die on the computer and roll it an arbitrary number of times</strong></li>
<li><strong>The birthday problem and how to solve it analytically as well as through simulation</strong></li>
<li><strong>Extrapolating the birthday problem to analyze cryptographic collision resistance of hash-functions by using ideas from probability</strong></li>
</ol>
</section>
<section id="project-1-craps-a-casion-dice-game." class="level2 page-columns page-full" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="project-1-craps-a-casion-dice-game."><span class="header-section-number">1.5</span> Project 1: Craps: A casion dice game.</h2>
<p>The first project is about one of the very few dice games offered at a Casino: Craps.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn6"><p><sup>6</sup>&nbsp; This will be the only project in this course where we do not go into a direct financial application. Before we can do so, we need to build still a bit more knowledge of probability and skills in R.</p></div></div><p>In Craps people throw a pair of dice and bet on outcomes of these throws. In this project we practice our new knowledge by implementing the dice throws of craps and the automatic summation of points on the computer. We try to find out the probability of the possible outcomes and check the fairness of the dice.</p>
<ol type="1">
<li><p>Your first task in this project will be to write a function which allows you to virtually throw a pair of dice and sum up the points shown after the throw.</p></li>
<li><p>Simulate and plot the result of your simulation using <code>qplot()</code> with the <code>binwidth</code> argument set to 1.</p></li>
<li><p>Are these dice fair? Why?</p></li>
<li><p>Assume the dice were unfair in the following sense: Numbers 1,2,3,4 and 5 have a probability of <span class="math inline">\(1/8\)</span> while the 6 has a probability of <span class="math inline">\(3/8\)</span>. Study the help page of the <code>sample</code>function and find out how you could give these new probability weights to the function. If you redo your simulation analysis with the loaded dice, how does the picture change?</p></li>
<li><p>Write a script for this random experiment.</p></li>
<li><p>Now look at the random experiment of throwing two dice with the concepts from probability theory: What is the sample space of this experiment. What are the probabilities of the basic outcomes? What is the probability of getting sum 7, what is the probability of getting sum 2 for the case of the fair dice, for the case of the unfair dice?</p></li>
<li><p>Imagine now that you are at the casino which uses fair dice and you can spend 150 Euro for chips. Since you have figured out that 7 is the most likely outcome you would like to buy bets on 7. The casino offers you a bet for 15 cent. When you win you get 1 Euro for the bet, when you loose you get nothing. Every bet costs 15 cents, so you can make 1000 bets in total on 7 from your budget of 150. Is this a good or a bad deal for you? Try to think about this problem in terms of a simulation.</p></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-DiaconisSkyrms2019" class="csl-entry" role="listitem">
Diaconis, Persi, and Brian Skyrms. 2019. <em>10 Great Ideas about Chance</em>. Princeton University Press.
</div>
<div id="ref-Healy2018" class="csl-entry" role="listitem">
Healy, Kirean. 2019. <em>Data Visualization: A Practical Introduction</em>. Princeton University Press.
</div>
<div id="ref-Narayananetal2016" class="csl-entry" role="listitem">
Narayanan, Arvind, Joseph Bonneau, Edward Felten, Andrew Miller, and Steven Goldfeder. 2016. <em>Bitcoin and Cryptocurrency Technologies: A Comprehensive Introduction</em>. Princeton University Press.
</div>
<div id="ref-WickhamGrolemund2017" class="csl-entry" role="listitem">
Wickham, Hadley, and Garrett Grolemund. 2017. <em>R for Data Science</em>. O’Reilly. <a href="https://r4ds.had.co.nz/">https://r4ds.had.co.nz/</a>.
</div>
</div>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Preface">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>