---
title: 'Information for the course: An Introduction to Probability - With Applications
  to Computational Finance using R'
author: "Martin Summer"
date: "10.1.2022"
output:
  pdf_document: default
  html_notebook: default
---

# General Information

Welcome to the course **An Introduction to Probability - With Applications to 
Computational Finance using R** which is going to start this week. In this sheet I would like 
to give you some basic information on the course in terms of contents and procedures.

My name is Martin Summer. I am currently the head of the economic studies division at the 
Oesterreichische Nationalbank in Vienna. My division is OeNB's research division. As a researcher
specialized in financial economics and the analysis of financial risks, I have been using
probability as well as R for many years and I am happy to leverage this background for
teaching this course.

This course is built as an intuitive and elementary introduction to the field. No knowledge
of probability or R is assumed and all concepts are built from scratch. 
You should be able to study for this course by relying on the slides
and the lecture notes only without having to consult a textbook
or further literature.

Many of you will
have heard or studied probability at some stage in college or at university. I hope the
course will appeal to the newcomers as well as to the experienced. While it should allow the first
group to quickly learn some of the most important concepts and raise your curiosity and
excitement about a field of knowledge which is both beautiful and immensely practical, I hope it
will open a new perspective for the more experienced among you and thus help deepening
your understanding of concepts you might already have heard elsewhere.

The lectures develop probability concepts and R concepts in
parallel within the context of computational Finance. 
The idea underlying this course is to develop
your knowledge of probability concepts by building them on the
computer yourself with R and then play with them on some Finance
applications. In this way we hope to build
your probability as well as your R skills more thoroughly because they appear in a natural 
context. 

# Study material

## Lecture Notes

My lectures will be based on lecture notes, which you can access on the internet under the address:

https://martin-summer-1090.github.io/Probability_Introduction/

They are self contained and should provide a reference to which you can come back during and after
the course. The notes are themselves written in R using R's bookdown package. This package provides
the layout, you can click through the contents, search in the manuscript and read it using
a web browser. What is - I hope - also convenient is that the layout is such that you have
examples of R code in the document appearing with a special font in a light gray box, like this
```{r example}
1+1
```
Navigating into the gray box with your mouse in the lecture notes 
will automatically show a copy paste sign in the
right upper corner of your box and you can click this icon to copy the code to your clipboard and
paste it to your R console to execute it. If you are not sure what this means exactly, don't worry. I will explain as we proceed through the course.

## Slides

While the lecture notes are the basis of the course in terms of contents, I will  use slides to
teach from these notes. The slides will also be distributed to you after 
each unit via the infrastructure of your program.

## Data

There is one example dataset on stock prices which you will also receive together with the study 
material. I distribute only one data set because we will soon learn right at the beginning how
to get data ourselves using the internet capbabilities of the R language.

# Procedure: Lectures and Projects

The lectures will be delivered online via zoom. I will present and explain material written down 
in the notes, I stand ready for questions and discussions as we go along and I will do some
demonstrations and many examples as we go through the material. 

Each unit has three hours in total and I would like to cover each of the five topics roughly 
in one of these double units. 

1. First probability ideas and first steps in R
2. Probability: Basic Definitions and Rules
3. Conditional Probability
4. Random variables
5. Continuous random variables

I plan to split each session of the course in two units with a break of about 10 minutes in between.

Each unit ends with a **Project**. A project is an exercise where you can apply the 
concepts and knowledge covered in the lecture to work on an application problem. The projects
will get more complex as we proceed with the lectures but they are constructed such that they
can be done between the units. I want to use the end of each unit - about 15 minutes - to discuss 
the project with you and what you are expected to do. In general you should finish a project before
the next unit starts. This should give you roughly a week between projects. After the project phase
I will distribute a worked example with a suggestion how to solve the project, which will
hopefully be useful for you. So at the end of the course, in terms of practice you should have
completed all five projects and you will have a worked solution for each project against which you
can compare your solutions.

# Learning Goals

At the end of this course, I hope you will feel comfortable to use R for basic simulations and as
a tool to solve basic probability problems. I hope you will be able to recognize the basic concepts
covered in the course when  they come across your path in a different context. I also hope the 
course will help you to get a feeling of what the concepts mean and how to apply them 
critically and thoughtfully in a real world context. Of course most people can not aquire
a very deep knowledge of probability and R in just a few weeks, because it requires time to
develop a certain mastery of these fields. This course should, however equip you with some
basic skills allowing you to delve deeper yourself and be able to analyze some practical examples
independently. If, however, the course has raised your excitement for the subject and made you
want to know more, this would be a great outcome of this course.

# R and RStudio

We will use R and RStudio as tools to study probability concepts throughout the course. I expect
you to have a working installation or R and RStudio up and running when we start the course. 

## Downloading and installing R

R is an open source project maintained
by an international team of developers. The software is made available through a website called
the comprehensive R archive network (http://cran.r-project.org).

At the top of this website, in a box named "Download and install R" you will find three
links for downloading R. Choose the link that describes your operating system, Windows, Mac or 
Linux. These links will lead you to the necessary information you need to install a current
version of R. The easiest install option is to install R from precompiled binaries. There is also
the option to built R from source on all operating systems if you have the tools and the
expertise to do so. R also comes both in a 32-bit and a 64-bit version. It does not make
a substantial difference which version you use. 64-bit versions 
can handle larger files and data sets with fewer memory management problems.

## Downloading and installing RStudio

RStudio is an application that helps you write and develop R code. It makes using
R much easier for you than using it in isolation. The interface of RStudio looks the
same across all operating systems.

You can download RStudio for free from https://www.rstudio.com/products/rstudio/. 
Select the box RStudio Desktop and follow the download instructions. RStudio Desktop is free.
Note that you need to have a version of R installed to use RStudio.

## Questions, Feedback and Troubleshooting during the course

If you have questions, or issues you would like to raise during the course but could not address
them in class please do not hesitate to contact me by mail: You can contact me at

E-mail: martin.summer@chello.at

I will do my best to reply to your mail during the course.

# Readings

The course is self contained and the lecture notes and the slides should be sufficient as reading
material. For those of you who have interest and time to read further I refer to the reading 
advice in the lecture notes.

I am looking forward very much to teaching this course and to interact with you. Probability 
is an exciting and fascinating topic which is intellectually fun and at the same time
immensely practical. I hope I will be able to convey some of this excitement during this course. Looking forward to seeing you soon.

Martin Summer, Vienna 10.1.2022
