<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Conditional Probability – An Introduction to Probability</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./02-lecture2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-lecture3.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Conditional Probability</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">An Introduction to Probability</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-lecture1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">First probability ideas and first steps in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-lecture2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability: Basic Definitions and Rules</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-lecture3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Conditional Probability</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#why-neglecting-conditional-probability-may-be-expensive-a-case-study." id="toc-why-neglecting-conditional-probability-may-be-expensive-a-case-study." class="nav-link active" data-scroll-target="#why-neglecting-conditional-probability-may-be-expensive-a-case-study."><span class="header-section-number">3.1</span> Why neglecting conditional probability may be expensive: A case study.</a>
  <ul class="collapse">
  <li><a href="#bonds-and-credit-risk" id="toc-bonds-and-credit-risk" class="nav-link" data-scroll-target="#bonds-and-credit-risk"><span class="header-section-number">3.1.1</span> Bonds and Credit Risk</a></li>
  <li><a href="#pooling-and-tranching-the-innovation" id="toc-pooling-and-tranching-the-innovation" class="nav-link" data-scroll-target="#pooling-and-tranching-the-innovation"><span class="header-section-number">3.1.2</span> Pooling and Tranching: The Innovation</a></li>
  <li><a href="#a-simple-event-tree-for-one-bond" id="toc-a-simple-event-tree-for-one-bond" class="nav-link" data-scroll-target="#a-simple-event-tree-for-one-bond"><span class="header-section-number">3.1.3</span> A Simple Event Tree for One Bond</a></li>
  <li><a href="#combining-two-bonds-with-independence-assumption" id="toc-combining-two-bonds-with-independence-assumption" class="nav-link" data-scroll-target="#combining-two-bonds-with-independence-assumption"><span class="header-section-number">3.1.4</span> Combining Two Bonds with Independence Assumption</a></li>
  <li><a href="#pooling-and-tranching" id="toc-pooling-and-tranching" class="nav-link" data-scroll-target="#pooling-and-tranching"><span class="header-section-number">3.1.5</span> Pooling and Tranching</a></li>
  <li><a href="#pooling-and-tranching-without-independent-risks" id="toc-pooling-and-tranching-without-independent-risks" class="nav-link" data-scroll-target="#pooling-and-tranching-without-independent-risks"><span class="header-section-number">3.1.6</span> Pooling and Tranching without Independent Risks</a></li>
  </ul></li>
  <li><a href="#conditional-probability" id="toc-conditional-probability" class="nav-link" data-scroll-target="#conditional-probability"><span class="header-section-number">3.2</span> Conditional Probability</a>
  <ul class="collapse">
  <li><a href="#an-illustration-using-old-and-new-r-concepts" id="toc-an-illustration-using-old-and-new-r-concepts" class="nav-link" data-scroll-target="#an-illustration-using-old-and-new-r-concepts"><span class="header-section-number">3.2.1</span> An illustration using old and new R concepts</a></li>
  </ul></li>
  <li><a href="#advanced-r-concepts-environments-scoping-rules-and-closures" id="toc-advanced-r-concepts-environments-scoping-rules-and-closures" class="nav-link" data-scroll-target="#advanced-r-concepts-environments-scoping-rules-and-closures"><span class="header-section-number">3.3</span> Advanced R Concepts: Environments, Scoping Rules, and Closures</a>
  <ul class="collapse">
  <li><a href="#introduction-to-environments" id="toc-introduction-to-environments" class="nav-link" data-scroll-target="#introduction-to-environments"><span class="header-section-number">3.3.1</span> Introduction to Environments</a></li>
  <li><a href="#scoping-rules" id="toc-scoping-rules" class="nav-link" data-scroll-target="#scoping-rules"><span class="header-section-number">3.3.2</span> Scoping Rules</a></li>
  <li><a href="#closures" id="toc-closures" class="nav-link" data-scroll-target="#closures"><span class="header-section-number">3.3.3</span> Closures</a></li>
  </ul></li>
  <li><a href="#bayes-rule-one-of-the-great-ideas-in-probability" id="toc-bayes-rule-one-of-the-great-ideas-in-probability" class="nav-link" data-scroll-target="#bayes-rule-one-of-the-great-ideas-in-probability"><span class="header-section-number">3.4</span> Bayes’ Rule: One of the Great Ideas in Probability</a>
  <ul class="collapse">
  <li><a href="#a-simple-example-revising-beliefs-about-market-valuation" id="toc-a-simple-example-revising-beliefs-about-market-valuation" class="nav-link" data-scroll-target="#a-simple-example-revising-beliefs-about-market-valuation"><span class="header-section-number">3.4.1</span> A simple example: Revising beliefs about market valuation</a></li>
  <li><a href="#bayes-rule-intuitive-understanding-with-a-speck-of-sand" id="toc-bayes-rule-intuitive-understanding-with-a-speck-of-sand" class="nav-link" data-scroll-target="#bayes-rule-intuitive-understanding-with-a-speck-of-sand"><span class="header-section-number">3.4.2</span> Bayes’ Rule: Intuitive Understanding with a Speck of Sand</a></li>
  </ul></li>
  <li><a href="#using-an-llm-to-explore-conditional-probability" id="toc-using-an-llm-to-explore-conditional-probability" class="nav-link" data-scroll-target="#using-an-llm-to-explore-conditional-probability"><span class="header-section-number">3.5</span> Using an LLM to Explore Conditional Probability</a>
  <ul class="collapse">
  <li><a href="#example-dialogue" id="toc-example-dialogue" class="nav-link" data-scroll-target="#example-dialogue"><span class="header-section-number">3.5.1</span> Example Dialogue</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">3.6</span> Summary</a>
  <ul class="collapse">
  <li><a href="#probability-concepts" id="toc-probability-concepts" class="nav-link" data-scroll-target="#probability-concepts"><span class="header-section-number">3.6.1</span> Probability Concepts</a></li>
  <li><a href="#r-concepts" id="toc-r-concepts" class="nav-link" data-scroll-target="#r-concepts"><span class="header-section-number">3.6.2</span> R Concepts</a></li>
  </ul></li>
  <li><a href="#project-evaluating-credit-risk-using-conditional-probabilities" id="toc-project-evaluating-credit-risk-using-conditional-probabilities" class="nav-link" data-scroll-target="#project-evaluating-credit-risk-using-conditional-probabilities"><span class="header-section-number">3.7</span> Project: Evaluating Credit Risk Using Conditional Probabilities</a>
  <ul class="collapse">
  <li><a href="#problem-description" id="toc-problem-description" class="nav-link" data-scroll-target="#problem-description"><span class="header-section-number">3.7.1</span> Problem Description</a></li>
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions"><span class="header-section-number">3.7.2</span> Questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Conditional Probability</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this lecture we are going to discuss the concept of <strong>conditional probability</strong>. The notion of conditional probability is a basic tool of probability theory which has particular relevance in Finance. The ideas of conditional probability are very simple but often obscured by a clumsy terminology.</p>
<p>To intuitively appreciate the significance of conditional probability first, let us start with a simple but striking scenario from the world of finance. Imagine you are an investor trying to evaluate the safety of a bond portfolio. On paper, the bonds are rated highly by reputable agencies, and the portfolio looks diversified—a dream investment. However, during a global recession, a few defaults occur, and to your surprise, the entire portfolio begins to unravel, causing significant losses. How could this happen?</p>
<p>This seemingly safe portfolio turned risky because it underestimated the connections between events—a core idea tied to conditional probability. Conditional probability helps us analyze how the risk of one event changes given another has occurred. It enables us to model dependencies, a critical factor in real-world scenarios, particularly during financial crises.</p>
<p>Understanding these relationships isn’t just an intellectual exercise—it’s crucial for preventing catastrophic losses. Whether you’re pricing complex financial instruments, assessing credit risk, or making investment decisions, mastering conditional probability allows you to account for interconnected risks and avoid misleading conclusions based on oversimplified assumptions.</p>
<section id="why-neglecting-conditional-probability-may-be-expensive-a-case-study." class="level2 page-columns page-full" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="why-neglecting-conditional-probability-may-be-expensive-a-case-study."><span class="header-section-number">3.1</span> Why neglecting conditional probability may be expensive: A case study.</h2>
<p>With this motivation in mind let us turn to a historical example that demonstrates the importance of understanding conditional probability: the financial crisis of 2007-2008. This crisis revealed how wrong assumptions about independence and neglect of dependence in events and conditional probabilities can lead to systemic failures in structured finance.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp; See <span class="citation" data-cites="Tooze2018">Tooze (<a href="#ref-Tooze2018" role="doc-biblioref">2018</a>)</span>: For an engaging and comprehensive exploration of the great financial crisis of 2007 - 2008 and its causes and aftermath. It is highly recommended for deeper study.</p></div></div><p>To understand the real world aspects of this example it is necessarry to understand some basic ideas of structured finance and the engineering of specific risk profiles from a portfolio of risky securities in the first place. I will explain the finance context with a simple and stylized example and then discuss how understanding conditional probability may help us to make better financial decisions.</p>
<section id="bonds-and-credit-risk" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="bonds-and-credit-risk"><span class="header-section-number">3.1.1</span> Bonds and Credit Risk</h3>
<p>A <strong>bond</strong> is a financial instrument where the issuer agrees to pay the holder a specific amount, the <strong>face value</strong> or <strong>par value</strong>, at maturity. Bonds are widely used as fixed-income securities but carry the risk of default if the issuer faces financial difficulties.</p>
<p>To quantify this risk, bonds are rated by agencies such as Moody’s and Standard &amp; Poor’s. Investment-grade bonds are considered low-risk, while speculative or “junk” bonds are riskier and more likely to default. Here is a summary of their rating schemes and what the ratings mean in words:</p>
<table class="table">
<thead>
<tr class="header">
<th>Rating Category</th>
<th>Moody’s</th>
<th>Standard &amp; Poor’s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>High grade</td>
<td>Aaa</td>
<td>AAA</td>
</tr>
<tr class="even">
<td></td>
<td>Aa</td>
<td>AA</td>
</tr>
<tr class="odd">
<td>Medium grade</td>
<td>A</td>
<td>A</td>
</tr>
<tr class="even">
<td></td>
<td>Baa</td>
<td>BBB</td>
</tr>
<tr class="odd">
<td>Speculative grade</td>
<td>Ba</td>
<td>BB</td>
</tr>
<tr class="even">
<td></td>
<td>B</td>
<td>B</td>
</tr>
<tr class="odd">
<td>Default danger</td>
<td>Caa</td>
<td>CCC</td>
</tr>
<tr class="even">
<td></td>
<td>Ca</td>
<td>CC</td>
</tr>
<tr class="odd">
<td></td>
<td>C</td>
<td>C</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>D</td>
</tr>
</tbody>
</table>
</section>
<section id="pooling-and-tranching-the-innovation" class="level3 page-columns page-full" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="pooling-and-tranching-the-innovation"><span class="header-section-number">3.1.2</span> Pooling and Tranching: The Innovation</h3>
<p>Structured finance emerged in the early 2000s as a way to manage risk through <strong>pooling</strong> and <strong>tranching</strong>. By pooling risky assets and dividing cash flows into “tranches” with distinct risk profiles, financial engineers created new bonds, including investment-grade securities, from portfolios of bonds which individually would be rated as speculative grade or junk bonds. A major product of this innovation was the <strong>mortgage-backed security (MBS)</strong>. Many other products were then invented using similar financial engineering ideas.</p>
<p>Let us develop an intuitive understanding of structured finance and its relation to probability through a simplified example, which I learned from Karl Schmedder’s course.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;See https://www.coursera.org/learn/introductiontoprobability</p></div></div></section>
<section id="a-simple-event-tree-for-one-bond" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="a-simple-event-tree-for-one-bond"><span class="header-section-number">3.1.3</span> A Simple Event Tree for One Bond</h3>
<p>Consider a single bond you can own today that pays €1 at maturity at some point in the future. Time is often abbreviated as <span class="math inline">\(t\)</span> and the points in time are symbolized by letting <span class="math inline">\(t\)</span> take different values like <span class="math inline">\(t=0\)</span> for today and <span class="math inline">\(t=1\)</span> for a future point in time, say a year from today.</p>
<p>This bond has a 10% chance of default, meaning there is a 90% chance it will not default. With a default probability of 10%, this bond would likely receive a speculative grade rating, such as ‘B’ or ‘B-’ in the rating tables presented earlier. This poor rating reflects the significant risk of non-payment associated with such a bond, which could deter risk-averse investors and highlight its ‘junk’ bond status. The payoff is structured as follows:</p>
<ul>
<li>If the bond does not default (<span class="math inline">\(N\)</span>), the payoff is €1.</li>
<li>If the bond defaults (<span class="math inline">\(D\)</span>), the payoff is €0.</li>
</ul>
<p>This situation can be graphically represented as a simple probability tree of <a href="#fig-single_bond_event_tree" class="quarto-xref">Figure&nbsp;<span>3.1</span></a></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-single_bond_event_tree" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-single_bond_event_tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/single_bond_event_tree.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-single_bond_event_tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1: Event tree for one bond
</figcaption>
</figure>
</div>
</div>
</div>
<p>The graph above visualizes the outcomes of a single bond. Each node represents a possible state of the bond at different times:</p>
<ul>
<li><span class="math inline">\(t=0\)</span> is the starting point.</li>
<li><span class="math inline">\(t=1\)</span> No Default <span class="math inline">\(N\)</span> occurs with a probability of <span class="math inline">\(P(N) = 0.9\)</span>.</li>
<li><span class="math inline">\(t=1\)</span> Default <span class="math inline">\(D\)</span> occurs with a probability of <span class="math inline">\(P(D) = 0.1\)</span>.</li>
</ul>
<p>You could see this in analogy to the toss of a coin with the difference that both sides of the coin show with different probability. With this analogy - using the concepts of the last two lectures - you can understand the bond in probabilistic terms as a random experiment with a sample space consisting of two basic outcomes, <span class="math inline">\(N\)</span> and <span class="math inline">\(D\)</span> with given probabilities <span class="math inline">\(P(N)\)</span> and <span class="math inline">\(P(D)\)</span>.</p>
</section>
<section id="combining-two-bonds-with-independence-assumption" class="level3 page-columns page-full" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="combining-two-bonds-with-independence-assumption"><span class="header-section-number">3.1.4</span> Combining Two Bonds with Independence Assumption</h3>
<p>We now combine two such bonds into a portfolio. The assumption of <strong>independence</strong> implies that the defaults of these bonds occur independently of each other. This means that the default of one bond has no influence on the probability of the other bond defaulting. Under the assumption of independence you would treat the default probability of one bond as unconnected with the default probability of the other.</p>
<p>While this assumption simplifies calculations, it was historically used by financial engineers to justify creating tranches from risky portfolios. The reasoning was that diversification reduces the likelihood of joint defaults, making some tranches appear safer.</p>
<p>At the time, financial engineers relied on historical data and market conditions to argue for this independence. Defaults were often uncorrelated under normal economic conditions, and diversification was seen as a proven strategy for mitigating risk. For example, if bond defaults were driven by isolated events (such as company-specific issues), the assumption of independence seemed reasonable. Moreover, the packaging of diverse assets from different industries into portfolios strengthened the appearance of safety, as individual economic shocks were less likely to affect the entire portfolio simultaneously.</p>
<p>However, this reasoning neglected systemic risks. During economic downturns or financial crises, defaults often become highly correlated due to shared macroeconomic pressures, such as declining housing markets or credit tightening. For instance, in the lead-up to the 2008 financial crisis, rising mortgage defaults were driven by broader economic factors that impacted many bonds simultaneously. With this in mind it would be not plausible to assume that bonds can be stacked together in a portfolio without the default risks of one being not pushed up by the default risk of others.</p>
<p>Even without the formal use of probability theory, financial engineers could have questioned whether diversification truly guaranteed independence in the context of systemic risks.</p>
<p>The idea that junk plus junk could be transformed into investment-grade bonds through pooling should have raised skepticism. Careful critical thinking—considering broader economic dependencies—would have revealed that this transformation was too good to be true. By ignoring these dependencies, financial engineers failed to see how small cracks in the system could cascade into systemic failures.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp; A famous voice at the time warning about the flawed reasoning was Raghuram Rajan, former chief economist of the International Monetary Fund. He warned that rather than reducing risk through diversification, CDOs and other derivatives spread risk and uncertainty about the value of the underlying assets more widely. </p></div></div><p>But let us not jump ahead and try to see how the tree for two bonds looks like when we <strong>assume</strong> independence in <a href="#fig-two_bond_event_tree" class="quarto-xref">Figure&nbsp;<span>3.2</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-two_bond_event_tree" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two_bond_event_tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/two_bonds_event_tree.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two_bond_event_tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.2: Event tree for two bonds with independent default risk
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The outcome of combining two bonds can be represented as a double event tree, showing all possible combinations of defaults and no defaults at <span class="math inline">\(t=1\)</span>. Let me unpack this more complex tree for you.</p></li>
<li><p>Since we have a portfolio of two bonds, instead of one as before, we have now two event trees combined. Since we have to take into account all of the possible combinations of basic outcomes this means that we have to attach a new bond event tree to each outcome of the initial tree.</p></li>
<li><p>Note the time index. In the example the realizations of basic outcomes for the portfolio happen simultaneously. So the walk from the origin to the end of the tree along a path is taking place in one time step and only the outcomes at <span class="math inline">\(t=1\)</span> are observed.</p></li>
<li><p>At the edges we write the probability of the outcomes. For example <span class="math inline">\(P(N)\)</span> is the probability of the first bond (represented by the upper tree) is not defaulting whereas <span class="math inline">\(P(D)\)</span> denotes the probability of the bond not defaulting. The assumption of independence is hidden in this tree by modelling the probabilities of <span class="math inline">\(N\)</span> and <span class="math inline">\(D\)</span> for the second bond in <em>exactly</em> the same way no matter whether the first bond defaults or not. It is modelled in anaology to the toss of two fair coins. The probability of the second coin showing Heads is <span class="math inline">\(1/2\)</span> no matter whether the first coin shows Heads or Tails.</p></li>
<li><p>At the end of the tree we have written the outcome of each path in the notation <span class="math display">\[\begin{equation*}
B_{\text{state of bond 1 at} \, t = 1 \, \text{state of bond 2 at} \, t=1} = \binom{\text{payoff of bond 1 at } \, t= 1}{\text{payoff of bond 2 at } \, t = 1}
\end{equation*}\]</span> So, for example, <span class="math inline">\(B_{NN} = \begin{pmatrix} 1 \\ 1 \end{pmatrix}\)</span> means that bond 1 does not default and bond two does not default (<span class="math inline">\(B_{NN}\)</span>). Bond 1 has in this case a payoff of 1 and bond 2 also has a payoff of 1.</p></li>
</ul>
</section>
<section id="pooling-and-tranching" class="level3" data-number="3.1.5">
<h3 data-number="3.1.5" class="anchored" data-anchor-id="pooling-and-tranching"><span class="header-section-number">3.1.5</span> Pooling and Tranching</h3>
<p>When you look at this portfolio <strong>under the independence assumption</strong> there seems to be room for re-engineering the risk profile of this portfolio. In all outcomes but in the one where both bonds default you can guarantee a payoff of 1. There remains an adverse outcome, where both bonds default in which case you can’t pay out anything. But <strong>under the assumption of independence</strong> this risk is small. The probability of this event - remember our treatment of independent events in the first lecture - would be: <span class="math inline">\(P(D) \times P(D) = 0.1 \times 0.1 = 0.01\)</span>. Pretty low, actually. For example assume that the probability of default refer to the probability of the bond defaulting over a year, the usual time frame taken in ratings, this would be a one in a hundred years event. In <span class="math inline">\(99%\)</span> we would get a sure payoff of 1. So under this restructuring the first restructured bond would qualify as an investment grade bond.</p>
<p>So this is the idea. We <strong>pool</strong> the payoffs of both securities and define two new securities by changing their payoff profile. The first one pays always 1 except when both bonds default in which case this bond pays 0. The other one will always pay 0 except in the case where both bonds do not default. This is under independence an event with probability <span class="math inline">\(P(N) \times P(N) = 0.81\)</span>. Rember the complementarity rule? This says that the second restructured bond will thus have a default probability of <span class="math inline">\(19\)</span> % instead of <span class="math inline">\(10%\)</span> it would be speculative grade or close to toxic junk now.</p>
<p>Here is picture how you can visualize this piece fo financial magic. This picture can be read in exactly the same way as the previous picture. There is only one additional element. We have written the payoff of the original bonds by <span class="math inline">\(B\)</span>. Underneath these original bonds we draw a black horizontal like, think of it as the financial engineering lab that does the restructuring and below we get new bonds, with different payout promises, which we denote by <span class="math inline">\(R\)</span> (for <em>restructured</em>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pooling-and-tranching" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pooling-and-tranching-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/pooling_and_tranching.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pooling-and-tranching-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.3: Event tree for two bonds with independent default risk with pooling and tranching
</figcaption>
</figure>
</div>
</div>
</div>
<p>What is done here is that the aggregate payoffs of both bonds are collected in a pool and new securities - called R - in this picture are issued against the pool. One, the upper one is now an investment grade asset paying 1 in every state except one and the other is a toxic junk bond paying always 0 except in one state. Note that the investment grade status could be engineered under the assumption that the risks are independent.</p>
</section>
<section id="pooling-and-tranching-without-independent-risks" class="level3" data-number="3.1.6">
<h3 data-number="3.1.6" class="anchored" data-anchor-id="pooling-and-tranching-without-independent-risks"><span class="header-section-number">3.1.6</span> Pooling and Tranching without Independent Risks</h3>
<p>Now, let us consider a hypothetical question: <strong>How would the event tree change if the independence assumption does not hold?</strong> Dependence would alter the probabilities in a way that reflects the increased likelihood of joint defaults during systemic events.</p>
<p>Suppose we now assume that the probability of Bond 2 defaulting changes rather than staying unchanged under the condition that Bond 1 has defaulted:</p>
<ul>
<li>If Bond 1 does <strong>not</strong> default, Bond 2 defaults with probability 0.1 (as before).</li>
<li>If Bond 1 <strong>does</strong> default, Bond 2 defaults with a higher probability of 0.6 due to systemic dependence.</li>
</ul>
<p>To express this formally we need a piece of new notation. The convention in probability theory is that the notation is - for example - <span class="math inline">\(P(N | D)\)</span>. This would read as * bond 2 does not default given bond 1 has defaulted *. The event we are interested in is written first separated by a <span class="math inline">\(|\)</span> from the conditioning event, which is in our case the outcome that bond 1 defaults.</p>
<p>This dependence reflects a scenario where defaults are more likely to occur together, such as during an economic downturn. The resulting event tree can be visualized as follows:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pooling-and-tranching-dependent" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pooling-and-tranching-dependent-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/two_bonds_event_tree_dependent_events.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pooling-and-tranching-dependent-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.4: Event tree for two bonds with independent default risk with pooling and tranching with dependent default risk
</figcaption>
</figure>
</div>
</div>
</div>
<p>On the first sight this looks almost identical to the picture before. Only the numbers on the edges of the second tree have changed. These changed numbers reflect the idea that the event that one bond has defaulted changes the probability of the second bond defaulting as well. How could such a dependence occur?</p>
<p>Here’s a real-world example to illustrate how dependence can occur: In the context of bonds, dependence in default probabilities can arise from shared exposure to systemic risks or interconnected factors. For instance, consider two companies that issue bonds and operate in the same industry, such as the energy sector. If oil prices plummet due to an economic downturn or geopolitical instability, both companies might experience financial stress, making it more likely that one default is followed by another.</p>
<p>Another example is during a financial crisis, such as the 2008 global financial meltdown. A bank’s default on its obligations can lead to cascading defaults in other institutions due to counterparty risks or a general loss of confidence in the financial system. In such cases, the probability of a second default is no longer independent of the first because the events are tied to the same underlying macroeconomic factors.</p>
<p>These examples highlight that the assumption of independence between bond defaults might hold under normal market conditions but breaks down during systemic crises. Such dependencies must be carefully modeled to avoid underestimating risk, as was the case in structured finance products leading up to the 2008 crisis.</p>
<p>A prudent risk manager must keep such a scenario in mind when he analyzes a portfolio. Think about it in the context of the toy example. In the first case the default risk of the first asset created by pooling and tranching was <span class="math inline">\(P(D) \times P(D) = 0.1 \times 0.1 = 0.01\)</span>. Under a scenario with dependent risks this changes to <span class="math inline">\(P(D) \times P(D | D) = 0.1 \times 0.6 = 0.06\)</span>, a risk larger by a factor of 6! While in the first case the first restructured bond would be rated as investment grade, in the second case the same restructured bond would be rated as speculative grade and the magic from pooling and tranching suddenly disappears. Junk plus junk remains junk after all.</p>
<p>For pooling and tranching to reduce overall risk and create safe tranches:</p>
<ol type="1">
<li><strong>Diversification:</strong> Assets must come from independent sectors with minimal systemic risk.</li>
<li><strong>Stable Macroeconomic Conditions:</strong> Systemic risks must be low to maintain independence assumptions.</li>
<li><strong>Transparent Modeling:</strong> Dependence structures must be explicitly modeled and accounted for in risk assessments.</li>
</ol>
<p>The neglect of these conditions led to a flawed sense of security in structured finance, which contributed to the 2008 financial crisis.</p>
</section>
</section>
<section id="conditional-probability" class="level2 page-columns page-full" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="conditional-probability"><span class="header-section-number">3.2</span> Conditional Probability</h2>
<p>Conditional probability provides us with a concept to formalize how the probability of one event changes when another event is known to occur, providing a framework for understanding dependencies quantitatively.</p>
<p>Here is the mathematical definition:</p>
<div id="conditional-probability" class="callout callout-style-default callout-tip callout-titled" title="Definition: Conditional probability">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Conditional probability
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(B\)</span> be an event with positive probability. For an arbitrary event <span class="math inline">\(A\)</span> we define the <strong>conditional probability</strong> of <span class="math inline">\(A\)</span> given <span class="math inline">\(B\)</span> as <span class="math display">\[\begin{equation*}
P(A\,|\,B) = \frac{P(A \cap B)}{P(B)}\,\,\, \text{provided}\,\,\, P(B) \neq 0
\end{equation*}\]</span></p>
</div>
</div>
<p>Note that conditional probabilities remain undefined when the conditioning event <span class="math inline">\(B\)</span> has probability 0.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;As pointed out in <span class="citation" data-cites="Feller1968">Feller (<a href="#ref-Feller1968" role="doc-biblioref">1968</a>)</span> p 115, this has no consequences in the case of discrete sample spaces but is important in the general theory.</p></div></div><p>Let us clarify a few things about this concept. As in the example of the financial crisis, which we discussed before we really did not much more than introducing one piece of new notation to indicate that the probabilities now have changed.</p>
<section id="an-illustration-using-old-and-new-r-concepts" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="an-illustration-using-old-and-new-r-concepts"><span class="header-section-number">3.2.1</span> An illustration using old and new R concepts</h3>
<p>This is an excellent moment in this lecture to make use of R to illustrate the concept and play with it. On the way we introduce some not yet covered R concepts.</p>
<p>Let us stay with the example of defaultable bonds and use the freedom and the opprotunity of simulating probabilistic examples on the computer.</p>
<p>Let us make use of the <code>sample()</code> function first to create a portfolio of bonds. The relevant data for this portfolio should be recorded in a dataframe.</p>
<p>To make the data reproducible we need to specify a random seed. Just like in Python, the set.seed() function in R ensures reproducibility of random numbers. When generating random data (like our simulated bond portfolio), R uses a pseudo-random number generator. By setting a “seed” value, you tell R to start its random number generator from a specific point. This guarantees that every time you run the code, you’ll get the same random results, which is crucial for debugging, sharing code, or teaching concepts.</p>
<p>The <code>set.seed()</code>functions requires and argument. We can for instance use a sequence of numbers, which can be arbitrary like <code>123</code>or <code>42</code>or <code>2025</code>. What is important is that using the same seed will always give you the same numbers and thus make your example reproducible.</p>
<p>Here is an example for illustration. Let’s go back to our old coin tossing example and let us toss our coin 10 times one time using the <code>set.seed()</code>function and one time not.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tossing a fair coin 10 times, two different runs without set.seed()</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>example_without_1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"H"</span>,<span class="st">"T"</span>), <span class="at">size =</span><span class="dv">10</span>, <span class="at">replace =</span> T)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>example_without_2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"H"</span>,<span class="st">"T"</span>), <span class="at">size =</span><span class="dv">10</span>, <span class="at">replace =</span> T)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Without set.seed():</span><span class="sc">\n</span><span class="st"> "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Without set.seed():
 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(example_without_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "H" "T" "T" "H" "H" "T" "H" "H" "H" "T"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(example_without_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "T" "T" "H" "T" "H" "H" "T" "H" "T" "T"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tossing a fair coin 5 times, two different rund with set.seed()</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>example_with_1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"H"</span>,<span class="st">"T"</span>), <span class="at">size =</span><span class="dv">10</span>, <span class="at">replace =</span> T)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>example_with_2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"H"</span>,<span class="st">"T"</span>), <span class="at">size =</span><span class="dv">10</span>, <span class="at">replace =</span> T)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"With set.seed():</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>With set.seed():</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(example_with_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "H" "H" "H" "T" "H" "T" "T" "T" "H" "H"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(example_with_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "H" "H" "H" "T" "H" "T" "T" "T" "H" "H"</code></pre>
</div>
</div>
<p>Now let us go to our bind portfolio simulation. Let us simulate our data first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set a random seed for reproduceability</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of bonds</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">5000</span> </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate portfolio data</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>portfolio <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">BondID =</span> <span class="dv">1</span><span class="sc">:</span>N,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">CreditRating =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"AAA"</span>, <span class="st">"BBB"</span>, <span class="st">"Junk"</span>), N, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.3</span>, <span class="fl">0.2</span>)),</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sector =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Finance"</span>, <span class="st">"Energy"</span>, <span class="st">"Real Estate"</span>), N, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">Defaulted =</span> <span class="cn">NA</span>  <span class="co"># Initialize with NA for later assignment</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let me unpack this a bit:</p>
<p>First we create a dataframe using the <code>data.frame()</code>function of R.<br>
It is used to create a structured dataset in R, similar to a table in Excel or a DataFrame in Python’s pandas library. Here, we are simulating a dataset called portfolio, which represents a collection of financial bonds. Each row corresponds to a bond, and each column represents an attribute (or variable) of that bond.</p>
<p>In the first column of our dataframe we store unique bond IDs by just assigning them a sequence of integers starting at 1 and counting to <span class="math inline">\(N\)</span>, the total number of bonds in the portfolio. Remember the colon operator <code>:</code> we have already used before to create such sequences.</p>
<p>In the next column of our dataframe we assign a credit rating randomly using a probability of 0.5 that the rating will be “AAA”, 0.3 that it will be “BBB” and 0.2 that it will be “Junk”. You know already how to do this using the sample function. Note that we have set <code>replace = TRUE</code>: This allows sampling with replacement, so the same credit rating can appear multiple times</p>
<p>Finally we imagine that the bonds are issued by different sectors, Finance, Energy and Real Estate in the economy which we also assign randomly with equal probability for each sector using the sample function.</p>
<p>The final column creates a vector of unknown values, because we would like to assign these values in a separate step to be consistent with actual rating probabilities.</p>
<p>The way we do this is to assign the value <code>NA</code> to the variable <code>Defaulted</code>for the moment. What does this variable mean in R?</p>
<p>The NA character is a special symbol in R. It stands for “not available” and can be used as a placeholder for missing information. R will treat NA exactly as you should want missing information treated. For example, what result would you expect if you add 1 to a piece of missing information?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">+</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
</div>
<p>R will return a second piece of missing information. It would not be correct to say that <code>1 + NA = 1</code> because there is a good chance that the missing quantity is not zero. You do not have enough information to determine the result.</p>
<p>There are two functions which are very useful to know about, when working with data that contain <code>NA</code> which will be the case in almost all practical circumstances.</p>
<p>While <code>NA</code> is useful for indicating missing information it can be annoying in practical data work. Assume you had a vector of 100 numbers and only one value, say at the beginning is <code>NA</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="cn">NA</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  NA   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
 [19]  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
 [37]  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
 [55]  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
 [73]  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
 [91]  90  91  92  93  94  95  96  97  98  99 100</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
</div>
<p>This is clearly annoying and we would like to enforce a different behavior. Most R functions, such as <code>mean()</code> and others come with the option <code>na.rm</code> that controls R’s behavior when data contain missing information. Here is how it works in the case of mean:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50.5</code></pre>
</div>
</div>
<p>A second useful function when working with missing data is <code>is.na()</code>. This is the case because the identity operator <code>==</code> used in logical subsetting does not work with <code>NA</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="cn">NA</span>) <span class="sc">==</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA NA NA NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.na</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="cn">NA</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE FALSE FALSE  TRUE</code></pre>
</div>
</div>
<p>So while the first approach will just yield <code>NA</code>, the second will identify which value in our vector is missing.</p>
<p>Now putting it all together this will give us a dataframe where the data.frame() function combines these columns into a structured dataset, where: - BondID is an integer sequence labeling each bond. - CreditRating is a randomly assigned credit rating, weighted by the specified probabilities. - Sector is a randomly assigned economic sector. - Defaulted a vector with missing values yet to be determined.</p>
<p>You can inspect the first rows of this dataframe by</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(portfolio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  BondID CreditRating      Sector Defaulted
1      1          AAA Real Estate        NA
2      2          BBB      Energy        NA
3      3          AAA      Energy        NA
4      4         Junk      Energy        NA
5      5         Junk     Finance        NA
6      6          AAA Real Estate        NA</code></pre>
</div>
</div>
<p>Now we assign different default probabilities for the different credit ratings such that the simulated data show similar values than with actual ratings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>default_probabilities <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">CreditRating =</span> <span class="fu">c</span>(<span class="st">"AAA"</span>, <span class="st">"BBB"</span>, <span class="st">"Junk"</span>),</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">DefaultProb =</span> <span class="fu">c</span>(<span class="fl">0.0001</span>, <span class="fl">0.002</span>, <span class="fl">0.05</span>)  <span class="co"># Default probabilities</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>default_probabilities <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">CreditRating =</span> <span class="fu">c</span>(<span class="st">"AAA"</span>, <span class="st">"BBB"</span>, <span class="st">"Junk"</span>),</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">DefaultProb =</span> <span class="fu">c</span>(<span class="fl">0.0001</span>, <span class="fl">0.002</span>, <span class="fl">0.05</span>)  <span class="co"># Default probabilities</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We do this in a separate rating dataframe, organizing compactly our rating information. To see what is happening here observe that a <code>data.frame</code> is created to store default probabilities for each credit rating. <code>CreditRating</code> is a character column containing the categories: <code>"AAA"</code>, <code>"BBB"</code>, and <code>"Junk"</code>. <code>DefaultProb</code> is a numeric column with the corresponding default probabilities: AAA: <span class="math inline">\(0.01\%\)</span>, BBB: <span class="math inline">\(0.2\%\)</span>, Junk: <span class="math inline">\(5\%\)</span> This dataframe organizes the default probabilities in a clear and structured way, making the probabilities easy to reference if needed later.</p>
<p>Now we can use the power of R’s subsetting rules to fill the last column in our portfolio dataframe such that we get realistic values. Let me show you the code and then unpack the elements step by step:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>portfolio<span class="sc">$</span>Defaulted[portfolio<span class="sc">$</span>CreditRating <span class="sc">==</span> <span class="st">"AAA"</span>] <span class="ot">&lt;-</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample</span>(<span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>), <span class="fu">sum</span>(portfolio<span class="sc">$</span>CreditRating <span class="sc">==</span> <span class="st">"AAA"</span>), <span class="at">replace =</span> <span class="cn">TRUE</span>, </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.0001</span>, <span class="fl">0.9999</span>))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>portfolio<span class="sc">$</span>Defaulted[portfolio<span class="sc">$</span>CreditRating <span class="sc">==</span> <span class="st">"BBB"</span>] <span class="ot">&lt;-</span> </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample</span>(<span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>), <span class="fu">sum</span>(portfolio<span class="sc">$</span>CreditRating <span class="sc">==</span> <span class="st">"BBB"</span>), <span class="at">replace =</span> <span class="cn">TRUE</span>, </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.002</span>, <span class="fl">0.998</span>))</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>portfolio<span class="sc">$</span>Defaulted[portfolio<span class="sc">$</span>CreditRating <span class="sc">==</span> <span class="st">"Junk"</span>] <span class="ot">&lt;-</span> </span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample</span>(<span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>), <span class="fu">sum</span>(portfolio<span class="sc">$</span>CreditRating <span class="sc">==</span> <span class="st">"Junk"</span>), <span class="at">replace =</span> <span class="cn">TRUE</span>, </span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here’s a step-by-step explanation of the code, unpacking the logic and reinforcing R subsetting rules: Let’s look at the AAA bonds first.</p>
<p>Here we see the code line <code>portfolio$CreditRating == "AAA"</code>. This line checks each row in the <code>CreditRating</code> column to see if the value is <code>"AAA"</code>. It returns a <strong>logical vector</strong> (e.g., <code>TRUE</code> for <code>"AAA"</code> rows, <code>FALSE</code> otherwise). Here you see two important R concepts at work. To check whether two expressions are equal the appropriate symbol is <code>==</code>. It returns a logical <code>TRUE</code> when the equality holds and <code>FALSE</code>otherwise.</p>
<p>We use this logical vector created by the assignment to assign a probability to the <code>Defaulted</code>column whenever the rating is <code>AAA</code>. So the operation selects the <code>Defaulted</code> column for rows where <code>CreditRating</code> is <code>"AAA"</code> and default status to these rows based on a random sample.</p>
<p>Now for the random sample we use the <code>sample()</code> function we encountered before. It generates random values <code>TRUE</code>for default and <code>FALSE</code>for non-default, the two possible outcomes. It samples with replacement as many times as we have an <code>AAA</code>rating. This count is achieved by <code>sum(portfolio$CreditRating == "AAA")</code> using R’s coercion rules. It returns the count because each <code>TRUE</code> is forced to 1 and contributes one count to the total whereas <code>FALSE</code>is forced to 0 and contributes nothing to the count. Finally <code>prob = c(0.0001, 0.9999)</code> specifies the probabilities for for this class. Note that here we could also have used the complement rule by writing <code>prob = c(0.0001, 1 - 0.0001)</code></p>
<p>Now we do the same thing for <code>BBB</code> bonds and the <code>Junk</code>bonds, which have each different probabilities from the <code>AAA</code>binds and from each other.</p>
<p>Here you have in one example the <strong>General Rules for R Subsetting</strong> reviewed</p>
<ol type="1">
<li><strong>Logical Conditions</strong>:
<ul>
<li>Use conditions like <code>==</code> to create logical vectors.</li>
<li>Example: <code>portfolio$CreditRating == "AAA"</code> checks for equality and returns a logical vector.</li>
</ul></li>
<li><strong>Row Selection</strong>:
<ul>
<li>Logical vectors are used to select rows in a data frame.</li>
<li>Example: <code>portfolio$Defaulted[...]</code> updates only the rows where the condition is <code>TRUE</code>.</li>
</ul></li>
<li><strong>Column Access</strong>:
<ul>
<li>Use <code>$</code> to access specific columns in a data frame.</li>
<li>Example: <code>portfolio$Defaulted</code>.</li>
</ul></li>
<li><strong>Combining Logical Subsetting and Assignment</strong>:
<ul>
<li>Subset rows using logical conditions, then assign values to those rows.</li>
<li>Example: <code>portfolio$Defaulted[portfolio$CreditRating == "AAA"] &lt;- sample(...)</code></li>
</ul></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Now you try
</div>
</div>
<div class="callout-body-container callout-body">
<p>Here are some more assignment exercises for you to try:</p>
<ol type="1">
<li><p><strong>Explore Subsetting</strong>:</p>
<ul>
<li><p>Print all AAA bonds using:</p>
<p><code>portfolio[portfolio$CreditRating == "AAA", ]</code></p></li>
<li><p>Verify the number of rows using:</p>
<p><code>sum(portfolio$CreditRating == "AAA")</code></p></li>
</ul></li>
<li><p><strong>Check Assigned Values</strong>:</p>
<p>Confirm that <code>Defaulted</code> is only updated for the relevant rows:</p>
<p><code>table(portfolio$Defaulted[portfolio$CreditRating == "AAA"])</code></p></li>
</ol>
</div>
</div>
<p>Let’s check how our <code>portfolio</code>dataframe looks now after the assignment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(portfolio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  BondID CreditRating      Sector Defaulted
1      1          AAA Real Estate     FALSE
2      2          BBB      Energy     FALSE
3      3          AAA      Energy     FALSE
4      4         Junk      Energy     FALSE
5      5         Junk     Finance     FALSE
6      6          AAA Real Estate     FALSE</code></pre>
</div>
</div>
<p>Now let us go on to the illustration of the conditional probability concept. If we choose a bond at random from this portfolio we should get a probability of</p>
<p><span class="math inline">\(P(D) = \frac{\text{number of defaultet bonds}}{\text{total number of bonds}}\)</span> and <span class="math inline">\(P(N) = \frac{\text{number of non-defaultet bonds}}{\text{total number of bonds}}\)</span></p>
<p>Let’s check these numbers in our sample, using the R subsetting rules and a new operator, the <code>$</code> sign, which plays an important role in R data manipulation. Let me do the calculation and then explain:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>PD <span class="ot">&lt;-</span> <span class="fu">mean</span>(portfolio<span class="sc">$</span>Defaulted <span class="sc">==</span> <span class="cn">TRUE</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>PN <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> PD</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>PD</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0108</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>PN</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9892</code></pre>
</div>
</div>
<p>Let me explain this bit of code. The name of our dataframe is <code>portfolio</code>. We may refer to this as an R-object in the R language. An operator that is frequently used in R to select a column from a dataframe is the colon operator <code>$</code>. If we tell R <code>portfolio$Defaulted</code>, R will select the column <code>Defaulted</code>from the dataframe portfolio. The same operator is used to select elements in an R list. This is no coincidence, since a dataframe is formally a list in the R language. You can see this by</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(portfolio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "list"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(portfolio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
<p>If you look at the type of a data frame, you will see that it is a list. In fact, each data frame is a list with class data.frame. You can see what types of objects are grouped together by a list (or data frame) with the <code>str()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(portfolio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   5000 obs. of  4 variables:
 $ BondID      : int  1 2 3 4 5 6 7 8 9 10 ...
 $ CreditRating: chr  "AAA" "BBB" "AAA" "Junk" ...
 $ Sector      : chr  "Real Estate" "Energy" "Energy" "Energy" ...
 $ Defaulted   : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...</code></pre>
</div>
</div>
<p>Now the numbers of the unconditional probabilities of a bind defaulting or not defaulting (note that we applied the complement rule here to compute this probability) is as it should be given the parametrisation of our example.</p>
<p>We now want to restrict our attention to the subset of our portfolio consisting of junk bonds. What is the probability that a bond chosen from this sub-population is in default?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate conditional probability: P(Default | CreditRating = "Junk")</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>junk_bonds <span class="ot">&lt;-</span> portfolio[portfolio<span class="sc">$</span>CreditRating <span class="sc">==</span> <span class="st">"Junk"</span>, ]</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>P_Default_given_Junk <span class="ot">&lt;-</span> <span class="fu">mean</span>(junk_bonds<span class="sc">$</span>Defaulted)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(Default | CreditRating = 'Junk'):"</span>, P_Default_given_Junk, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(Default | CreditRating = 'Junk'): 0.05353535 </code></pre>
</div>
</div>
<p>Now you see perhaps with your own hands how conditional probability works in terms of R’s subsetting rules. <strong>Among</strong> the subset of bonds which are classified as junk, how many are also defaulted and what is their relative frequency among the junk bonds? This would be in set notation: <span class="math display">\[\begin{equation*}
\frac{P(\text{set of all defaulted bonds} \cap \text{set of all junk bonds})}{P(\text{set of all junk bonds})}
\end{equation*}\]</span> To provide an appropriate notation for this we have used: <span class="math inline">\(P(\text{defaulted} \, | \,\text{junk})\)</span> This is read as the probability of event <span class="math inline">\(A\)</span> (the bond is defaulted) assuming the event <span class="math inline">\(B\)</span> (the bond is a junk bond).</p>
<p>Thus taking a conditional probability of various events with respect to a particular event <span class="math inline">\(B\)</span> amounts to choosing <span class="math inline">\(B\)</span> as a new sample sapce with the probabilities proportional to the original ones. The proportionality factor <span class="math inline">\(P(B)\)</span> is necessary in order to make the probabilities in the new sample space sum up to 1. All general theorems on probabilities are valid also for conditional probabilities with respect to any particular event <span class="math inline">\(B\)</span>.</p>
<p>Note that for conditional probabilities we have for two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, that <span class="math inline">\(P(A|B) \neq P(B|A)\)</span>. To see this assume that <span class="math inline">\(P(A) \neq P(B)\)</span> and <span class="math inline">\(P(A) \neq 0\)</span> and <span class="math inline">\(P(B)\neq 0\)</span>.</p>
<p>We then get: <span class="math display">\[\begin{equation*}
P(A|B) = \frac{P(A\cap B)}{P(B)} = \frac{P(B \cap A)}{P(B)}
\end{equation*}\]</span> since <span class="math inline">\(P(A \cap B) = P(B \cap A)\)</span>. It follows that <span class="math display">\[\begin{equation*}
\frac{P(B \cap A)}{P(B)} \neq \frac{P(B \cap A)}{P(A)} = P(B|A)
\end{equation*}\]</span> since we have assumed that <span class="math inline">\(P(A) \neq P(B)\)</span>. Therefore <span class="math inline">\(P(A|B) \neq P(B|A)\)</span>.</p>
<p>Let’s illustrate this remark with the example of our bond portfolio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate conditional probability: P(CreditRating = "Junk" | Default)</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>defaulted_bonds <span class="ot">&lt;-</span> portfolio[portfolio<span class="sc">$</span>Defaulted <span class="sc">==</span> <span class="cn">TRUE</span>, ]</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>P_Junk_given_Default <span class="ot">&lt;-</span> <span class="fu">mean</span>(defaulted_bonds<span class="sc">$</span>CreditRating <span class="sc">==</span> <span class="st">"Junk"</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(Junk | Default):"</span>, P_Junk_given_Default, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(Junk | Default): 0.9814815 </code></pre>
</div>
</div>
<p>Now you can see clearly that <span class="math inline">\(P(\text{Default} \, |\, \text{Junk} ) =\)</span> 0.0535354 which is clearly different from <span class="math inline">\(P(\text{Junk} \, |\, \text{Default} ) =\)</span> 0.9814815.</p>
<p>The formula for conditional probability which we wrote down in the definition of <a href="#conditional-probability">Conditional Probability</a> is often used in the form of the <strong>multiplication rule</strong>:</p>
<div id="multiplication-rule" class="callout callout-style-default callout-tip callout-titled" title="Definition: Multiplication rule">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Multiplication rule
</div>
</div>
<div class="callout-body-container callout-body">
<p>Given events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, it holds that: <span class="math inline">\(P(A \cap B) = P(A \mid B)\times P(B)\)</span></p>
</div>
</div>
<p>which is just an equivalent way to write the formula for conditional probability. The multiplication rule can be thought of the AND rule of probability theory.</p>
<p>With the multiplication rule we can gain a deeper insight into the meaning of independence. Remember that two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if <span class="math display">\[\begin{equation*}
P(A \cap B) = P(B \cap A) = P(A) \times P(B).
\end{equation*}\]</span></p>
<p>If we combine this rule with the concept of conditional probability, we see that if two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent, then <span class="math display">\[\begin{equation*}
P(A|B) = \frac{P(A \cap B)}{P(B)} = \frac{P(A) \times P(B)}{P(B)} = P(A)
\end{equation*}\]</span> and <span class="math display">\[\begin{equation*}
P(B|A) = \frac{P(B \cap A)}{P(A)} = \frac{P(A) \times P(B)}{P(A)} = P(B)
\end{equation*}\]</span></p>
<p>This formula says that if two events are independent the probability of <span class="math inline">\(A\)</span> is not influenced by the event <span class="math inline">\(B\)</span> occurring and the probability of event <span class="math inline">\(B\)</span> is not influenced by the event <span class="math inline">\(A\)</span> occurring.</p>
<p>Here’s a proposal for a draft subsection devoted to introducing advanced R concepts (Environments, Scoping Rules, Closures) while reinforcing conditional probability ideas. The examples are tied to a financial and conditional probability context, ensuring continuity with your lecture themes.</p>
<hr>
</section>
</section>
<section id="advanced-r-concepts-environments-scoping-rules-and-closures" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="advanced-r-concepts-environments-scoping-rules-and-closures"><span class="header-section-number">3.3</span> Advanced R Concepts: Environments, Scoping Rules, and Closures</h2>
<p>In this section, we will explore some advanced R programming concepts that are essential for understanding how R evaluates and stores variables, as well as how you can create reusable and dynamic functions. We will demonstrate these concepts through examples related to conditional probability and financial modeling.</p>
<section id="introduction-to-environments" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="introduction-to-environments"><span class="header-section-number">3.3.1</span> Introduction to Environments</h3>
<p>An <strong>environment</strong> in R is where objects (variables, functions, etc.) are stored and looked up. R uses environments to determine where a variable exists and what its value is. The most common environment is the <strong>global environment</strong>, where user-created variables and functions are stored.</p>
<p><strong>Example: Setting Global and Local Variables</strong></p>
<p>Suppose we are modeling interest rates in a financial portfolio. Globally, we set the baseline interest rate. Locally, we may override this rate for specific calculations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Global interest rate</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>interest_rate <span class="ot">&lt;-</span> <span class="fl">0.05</span>  <span class="co"># 5%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to calculate interest payments</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>calculate_interest <span class="ot">&lt;-</span> <span class="cf">function</span>(principal, <span class="at">rate =</span> interest_rate) {</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  interest <span class="ot">&lt;-</span> principal <span class="sc">*</span> rate  <span class="co"># Uses the rate passed to the function</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(interest)</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Global calculation</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>global_interest <span class="ot">&lt;-</span> <span class="fu">calculate_interest</span>(<span class="dv">1000</span>)  <span class="co"># Uses global interest_rate</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Global Interest:"</span>, global_interest, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Global Interest: 50 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Local override</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>local_interest <span class="ot">&lt;-</span> <span class="fu">calculate_interest</span>(<span class="dv">1000</span>, <span class="at">rate =</span> <span class="fl">0.07</span>)  <span class="co"># Overrides global interest_rate</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Local Interest:"</span>, local_interest, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Local Interest: 70 </code></pre>
</div>
</div>
<p><strong>Global variables</strong> are available everywhere, but <strong>local variables</strong> (like <code>rate</code>) take precedence within a function. Understanding this behavior is crucial for writing clear and predictable code.</p>
</section>
<section id="scoping-rules" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="scoping-rules"><span class="header-section-number">3.3.2</span> Scoping Rules</h3>
<p>R follows specific <strong>scoping rules</strong> to determine where and how to find variables. These rules become important when working with nested functions.</p>
<p><strong>Example: Variable Lookup in Nested Functions</strong></p>
<p>Let’s calculate conditional probabilities using nested functions. We simulate a financial scenario where we compute probabilities of default for different credit ratings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define global default rates for credit ratings</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>default_rates <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">AAA =</span> <span class="fl">0.01</span>,  <span class="co"># Global default rate for AAA bonds</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">BBB =</span> <span class="fl">0.02</span>,  <span class="co"># Global default rate for BBB bonds</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Junk =</span> <span class="fl">0.05</span>  <span class="co"># Global default rate for Junk bonds</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to calculate conditional default probability</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>conditional_default <span class="ot">&lt;-</span> <span class="cf">function</span>(rating) {</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Lookup table for default rates</span></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>  local_default_rates <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">AAA =</span> default_rates[<span class="st">"AAA"</span>],  <span class="co"># Local default for AAA</span></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">BBB =</span> default_rates[<span class="st">"BBB"</span>],  <span class="co"># Local default for BBB</span></span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">Junk =</span> default_rates[<span class="st">"Junk"</span>] <span class="co"># Local default for Junk</span></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Return the default rate using vectorized subsetting</span></span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(local_default_rates[rating])</span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-24"><a href="#cb51-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Test the function</span></span>
<span id="cb51-25"><a href="#cb51-25" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Default rate for Junk bonds:"</span>, <span class="fu">conditional_default</span>(<span class="st">"Junk"</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Default rate for Junk bonds: NA </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Default rate for BBB bonds:"</span>, <span class="fu">conditional_default</span>(<span class="st">"BBB"</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Default rate for BBB bonds: NA </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Default rate for AAA bonds:"</span>, <span class="fu">conditional_default</span>(<span class="st">"AAA"</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Default rate for AAA bonds: NA </code></pre>
</div>
</div>
<p>Her you see how R is using <strong>Lexical scoping</strong>. This ensures that R looks for variables in the closest environment first, then moves outward (from local to global). Nested functions can use both local and global variables.</p>
<p>This example uses a concept you might find useful in many other contexts: The <strong>lookup table</strong>. The concept of a lookup table is a simple yet powerful way to map input values to corresponding outputs. In R, we can create a lookup table using a named vector, where each element has a name (the input) and a value (the corresponding output). This allows us to retrieve the correct value by directly referencing the name.</p>
<p>In the example, we used a named vector local_default_rates to store the default probabilities for different credit ratings: “AAA”, “BBB”, and “Junk”. Each credit rating serves as a key, and the corresponding default probability serves as the value. When we pass the rating (e.g., “Junk”) to the function, R uses it to subset the vector and directly return the associated probability. This approach is efficient and avoids the need for verbose or complex conditional statements.</p>
<p>By using a lookup table, we also demonstrate an important principle of programming: separation of data and logic. The mapping of ratings to probabilities is encapsulated in a single data structure (local_default_rates), making the function simpler and easier to modify. For instance, if the default probabilities change, you only need to update the values in the vector—no changes to the function logic are required. This approach is especially useful in financial modeling, where mappings like these are common and can evolve over time.</p>
</section>
<section id="closures" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="closures"><span class="header-section-number">3.3.3</span> Closures</h3>
<p>A <strong>closure</strong> is a function that remembers the environment in which it was created. Closures are powerful for creating dynamic, reusable functions, such as calculators for different conditional probabilities.</p>
<p><strong>Example: Probability Calculator Factory</strong></p>
<p>This code demonstrates a powerful concept in R: <strong>closures</strong>. A closure is a function that “remembers” the environment in which it was created, allowing you to dynamically generate new functions with specific behaviors. Let’s create a function factory that generates specific probability calculators based on a given event.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function factory for conditional probability calculators</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>probability_calculator_factory <span class="ot">&lt;-</span> <span class="cf">function</span>(event_probability) {</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(conditional_probability) {</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>    joint_probability <span class="ot">&lt;-</span> event_probability <span class="sc">*</span> conditional_probability</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(joint_probability)</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create calculators for different events</span></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>junk_calculator <span class="ot">&lt;-</span> <span class="fu">probability_calculator_factory</span>(<span class="fl">0.05</span>)  <span class="co"># Junk bonds</span></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>bbb_calculator <span class="ot">&lt;-</span> <span class="fu">probability_calculator_factory</span>(<span class="fl">0.02</span>)   <span class="co"># BBB bonds</span></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate joint probabilities</span></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>junk_joint <span class="ot">&lt;-</span> <span class="fu">junk_calculator</span>(<span class="fl">0.1</span>)  <span class="co"># P(Default | Junk) * P(Junk)</span></span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>bbb_joint <span class="ot">&lt;-</span> <span class="fu">bbb_calculator</span>(<span class="fl">0.2</span>)    <span class="co"># P(Default | BBB) * P(BBB)</span></span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Joint probability for Junk bonds:"</span>, junk_joint, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Joint probability for Junk bonds: 0.005 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Joint probability for BBB bonds:"</span>, bbb_joint, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Joint probability for BBB bonds: 0.004 </code></pre>
</div>
</div>
<p>Let’s unpack the code step by step:</p>
<p>The <code>probability_calculator_factory</code> is a <strong>function factory</strong>. It takes one argument, <code>event_probability</code>, and returns a new function that calculates the <strong>joint probability</strong> for a given conditional probability:</p>
<ul>
<li><strong>Input</strong>:
<ul>
<li><code>event_probability</code>: The probability of the event (e.g., the probability of a bond being “Junk”).</li>
<li>The returned function takes <code>conditional_probability</code> as its argument (e.g., the probability of default given the bond is “Junk”).</li>
</ul></li>
<li><strong>Output</strong>:
<ul>
<li>The joint probability, <span class="math inline">\(P(A \cap B) = P(A | B) \times P(B)\)</span>.</li>
</ul></li>
</ul>
<p>This structure encapsulates the logic for joint probability into a reusable framework.</p>
<p>The <code>junk_calculator</code> and <code>bbb_calculator</code> are functions created by the factory. Each calculator “remembers” the <code>event_probability</code> it was initialized with: - <code>junk_calculator</code>: <span class="math inline">\(P(Junk) = 0.05\)</span>. - <code>bbb_calculator</code>: <span class="math inline">\(P(BBB) = 0.02\)</span>.</p>
<p>These calculators are then used to compute joint probabilities by providing the corresponding conditional probabilities: - <code>junk_joint &lt;- junk_calculator(0.1)</code>: - <span class="math inline">\(P(\text{Default} \cap \text{Junk}) = P(\text{Default | Junk}) \times P(\text{Junk})\)</span>. - <span class="math inline">\(0.1 \times 0.05 = 0.005\)</span> (0.5%). - <code>bbb_joint &lt;- bbb_calculator(0.2)</code>: - <span class="math inline">\(P(\text{Default} \cap \text{BBB}) = P(\text{Default | BBB}) \times P(\text{BBB})\)</span>. - <span class="math inline">\(0.2 \times 0.02 = 0.004\)</span> (0.4%).</p>
<p>The <code>cat()</code> function displays the results:</p>
<p>A closure allows you to “lock in” parameters (like <code>event_probability</code>) when the function is created, while still allowing flexibility for additional inputs.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Now you try">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Now you try
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Modify the <code>calculate_interest</code> function to add a penalty rate for overdue payments using local variables.</li>
<li>Extend the <code>conditional_default</code> function to include an additional credit rating (e.g., “CC”).</li>
<li>Use the <code>probability_calculator_factory</code> to compute joint probabilities for a new event, such as “Real Estate Sector Default.”</li>
</ol>
</div>
</div>
</section>
</section>
<section id="bayes-rule-one-of-the-great-ideas-in-probability" class="level2 page-columns page-full" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="bayes-rule-one-of-the-great-ideas-in-probability"><span class="header-section-number">3.4</span> Bayes’ Rule: One of the Great Ideas in Probability</h2>
<p>Bayes’ Rule stands among the ten great ideas in probability. Its power lies in solving a fundamental problem: how to infer underlying chances from observed frequencies. This insight filled a critical gap left by Bernoulli’s weak law of large numbers, which explained how observed frequencies converge to probabilities but left unanswered the question of how to reason from those frequencies back to the chances that generated them.</p>
<p>At its core, Bayes’ Rule provides a framework for updating our beliefs in light of new information. But what does it mean to assign a probability to a belief? This idea rests on another deep insight in probability theory: judgments about uncertainty can be measured, and when those judgments are coherent, they follow the rules of probability. <a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn5"><p><sup>5</sup>&nbsp;This idea goes back to the work of Frank Ramsey (1903–1930). He was a British mathematician, philosopher, and economist whose profound contributions spanned multiple fields despite his tragically short life. In probability, he established the foundation for subjective probability theory, showing that coherent judgments about uncertainty adhere to the axioms of probability. Ramsey also made groundbreaking advances in decision theory, logic, and economics, including the famous Ramsey pricing in public economics and his foundational work in mathematical logic. For more, on Ramsey’s ideas of connecting judegment to probability see chapter 2 in <span class="citation" data-cites="DiaconisSkyrms2019">Diaconis and Skyrms (<a href="#ref-DiaconisSkyrms2019" role="doc-biblioref">2019</a>)</span></p></div></div><p>The key breakthrough of Bayes’ Rule is that it ties these coherent judgments—our initial beliefs, or priors—to evidence, using conditional probability. This process transforms subjective judgments into a systematic method for reasoning under uncertainty, with profound applications across science, finance, and everyday decision-making.</p>
<section id="a-simple-example-revising-beliefs-about-market-valuation" class="level3 page-columns page-full" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="a-simple-example-revising-beliefs-about-market-valuation"><span class="header-section-number">3.4.1</span> A simple example: Revising beliefs about market valuation</h3>
<p>We discussed the big financial crisis of 2007-2008 earlier in this lecture. Imagine now you are an investor in the year 2011, just a bit later. The market is gripped by fear of another financial crisis, this time triggered by tensions in the Eurozone.</p>
<p>Let’s imagine how you could have asessed the market situation by looking at financial data. This is also an excellent opportunity to introdcue you to one of many great opportunities to load real world data directly into R using add on packages. The package we are going to use here is called <code>tidyquant</code>. To be able to use it you must first install it using the <code>install.packages()</code>function of base R or the package installer pane in RStudio. Let us do that - assuming that this package has been installed. You might remember how to load a package from before.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyquant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now tidyquant has many functions allowing you to retrieve and transform real world financial data. We do not go into any detail here. This is something you can do yourself using the excellent documentation of this package, the many examples on the web or by interrogating your LLM.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>. One of the core workhorse functions in tidyquant is the function <code>tq_get()</code> which allows you to retrieve data.</p>
<div class="no-row-height column-margin column-container"><div id="fn6"><p><sup>6</sup>&nbsp;Check out https://cran.r-project.org/web/packages/tidyquant/index.html</p></div></div><p>One thing an anlyst might be interested in is how the stock market as measured by a broad index does at the moment compared to its historical values. Let’s say you are looking back 11 years from 2011 into the past and see how the S&amp;P500 does now compared to this history. This is how you would use <code>tidyquant</code> to do this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fetch S&amp;P 500 data from 2000 to 2011</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>sp500_data <span class="ot">&lt;-</span> <span class="fu">tq_get</span>(<span class="st">"SPY"</span>, <span class="at">from =</span> <span class="st">"2000-01-01"</span>, <span class="at">to =</span> <span class="st">"2011-12-31"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In order to do load data you need the string of the name of the series you are interested in, which you can learn from the documentation. In our case this is “SPY” for the SP500. You can also specify a time range or just the beginning of the series. In the latter case it will give you all the data from the beginning up to the current or most recent trading day. We have written the data into an R object called <code>sp500_data</code> and now you might inspect it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sp500_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  symbol date        open  high   low close   volume adjusted
  &lt;chr&gt;  &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 SPY    2000-01-03  148.  148.  144.  145.  8164300     92.7
2 SPY    2000-01-04  144.  144.  140.  140.  8089800     89.1
3 SPY    2000-01-05  140.  142.  137.  140  12177900     89.2
4 SPY    2000-01-06  140.  142.  138.  138.  6227200     87.8
5 SPY    2000-01-07  140.  146.  140.  146.  8066500     92.9
6 SPY    2000-01-10  146.  147.  145.  146.  5741700     93.2</code></pre>
</div>
</div>
<p>The otput says that the data object is a <code>tibble()</code>. Don’t worry about this detail at the moment and think of a <code>tibble()</code>as something equivalent to a dataframe.</p>
<p>Now let us visualize the data using base R’s <code>plot()</code> function. Use the help facilities or your LLM to find out abut the syntax details.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Base R plot</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  sp500_data<span class="sc">$</span>date, sp500_data<span class="sc">$</span>adjusted,</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"l"</span>,                <span class="co"># Line plot</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"blue"</span>,              <span class="co"># Line color</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span>,                   <span class="co"># Line width</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Date"</span>,             <span class="co"># X-axis label</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Adjusted Price"</span>,   <span class="co"># Y-axis label</span></span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"S&amp;P 500 Price Trends (2000–2011)"</span> <span class="co"># Title</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Add grid lines for better readability</span></span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>(<span class="at">nx =</span> <span class="cn">NULL</span>, <span class="at">ny =</span> <span class="cn">NULL</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-lecture3_files/figure-html/visualize-sp500-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that the index is about the same level as it was 10 years ago. The index alone does not tell you very much. How about relating this to some relevant market fundamentals?</p>
<p>One powerful feature of <code>tidyquant()</code> is that it can fetch data from various data sources. Here I get, for the sake of this example, data on corporate profits from the FRED database of the Fed St.&nbsp;Louis<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn7"><p><sup>7</sup>&nbsp;See https://fred.stlouisfed.org/</p></div></div><div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get corporate profits data from FRED</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>corporate_profits <span class="ot">&lt;-</span> <span class="fu">tq_get</span>(<span class="st">"CP"</span>, <span class="at">from =</span> <span class="st">"2000-01-01"</span>, <span class="at">to =</span> <span class="st">"2011-12-31"</span>, <span class="at">get =</span> <span class="st">"economic.data"</span>)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize corporate profits</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  corporate_profits<span class="sc">$</span>date, corporate_profits<span class="sc">$</span>price,</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"l"</span>,</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Year"</span>,</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Corporate Profits (Index)"</span>,</span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Corporate Profits (2000–2011)"</span></span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>(<span class="at">nx =</span> <span class="cn">NULL</span>, <span class="at">ny =</span> <span class="cn">NULL</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-lecture3_files/figure-html/retrieveing spfundamentals-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Profits have roughly tripled over the same period. The market does seem to be undervalued. Let’s put this into perspective by looking at Price-Earning data or P/E ratios.</p>
<p>Now we run into a problem which you will often encounter when working with data. It is rare that a tool covers all cases. P/E rations seem to be difficult to retrieve with <code>tidyquant</code>. These data do however exist on the web, for example at the website Macrotrends.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<div class="no-row-height column-margin column-container"><div id="fn8"><p><sup>8</sup>&nbsp;The P/E ratio for the SP500 can be found for instance here: https://www.macrotrends.net/2577/sp-500-pe-ratio-price-to-earnings-chart</p></div></div><p>To retrieve data from this site, I had to download the data locally first before I could get them into R. Let’s look at them a bit closer now using again R’s visualization tools.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the path to the downloaded CSV file</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="st">"data/sp-500-pe-ratio-price-to-earnings-chart.csv"</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the CSV file into R</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>pe_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(file_path, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>, <span class="at">skip =</span> <span class="dv">16</span>,</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Date"</span>, <span class="st">"PE_ratio"</span>))</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the date column to Date class</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>pe_data<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(pe_data<span class="sc">$</span>Date, <span class="at">format =</span> <span class="st">"%Y-%m-%d"</span>)</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter data for the desired date range</span></span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>pe_data_filtered <span class="ot">&lt;-</span> <span class="fu">subset</span>(pe_data, Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2000-01-01"</span>) <span class="sc">&amp;</span> </span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>                             Date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2011-12-31"</span>))</span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the average P/E ratio over the specified period</span></span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a>average_pe <span class="ot">&lt;-</span> <span class="fu">mean</span>(pe_data_filtered<span class="sc">$</span>PE_ratio, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-18"><a href="#cb67-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the P/E ratio for the y-axis</span></span>
<span id="cb67-19"><a href="#cb67-19" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb67-20"><a href="#cb67-20" aria-hidden="true" tabindex="-1"></a>  pe_data_filtered<span class="sc">$</span>Date, pe_data_filtered<span class="sc">$</span>PE_ratio,</span>
<span id="cb67-21"><a href="#cb67-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"l"</span>,                   <span class="co"># Line plot</span></span>
<span id="cb67-22"><a href="#cb67-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"blue"</span>,                 <span class="co"># Line color</span></span>
<span id="cb67-23"><a href="#cb67-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span>,                      <span class="co"># Line width</span></span>
<span id="cb67-24"><a href="#cb67-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Year"</span>,                <span class="co"># X-axis label</span></span>
<span id="cb67-25"><a href="#cb67-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"P/E Ratio"</span>, <span class="co"># Y-axis label</span></span>
<span id="cb67-26"><a href="#cb67-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"S&amp;P 500 P/E Ratio (2000–2011)"</span>, <span class="co"># Plot title</span></span>
<span id="cb67-27"><a href="#cb67-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb67-28"><a href="#cb67-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-29"><a href="#cb67-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a horizontal line for the average P/E ratio</span></span>
<span id="cb67-30"><a href="#cb67-30" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> average_pe, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb67-31"><a href="#cb67-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-32"><a href="#cb67-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a legend to the plot</span></span>
<span id="cb67-33"><a href="#cb67-33" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(</span>
<span id="cb67-34"><a href="#cb67-34" aria-hidden="true" tabindex="-1"></a>  <span class="st">"topright"</span>,                   <span class="co"># Legend position</span></span>
<span id="cb67-35"><a href="#cb67-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"P/E Ratio"</span>, <span class="st">"Average P/E Ratio"</span>), <span class="co"># Labels</span></span>
<span id="cb67-36"><a href="#cb67-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>),       <span class="co"># Line colors</span></span>
<span id="cb67-37"><a href="#cb67-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>),                <span class="co"># Line types</span></span>
<span id="cb67-38"><a href="#cb67-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)                 <span class="co"># Line widths</span></span>
<span id="cb67-39"><a href="#cb67-39" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-lecture3_files/figure-html/pe-sp500-macrotrends-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>At first glance, the market seems undervalued, with a trailing price-to-earnings (P/E) ratio of 14, well below the historical average of 29.</p>
<p>As a cautious investor, you form the hypothesis that these low valuations are deceptive. You believe that corporate profits, which are at record highs of 1672 compared to the historical average of 1119, will revert to the mean. When this happens, earnings will drop, pushing the P/E ratio from a seemingly cheap to expensive.</p>
<p>With this belief in mind, you decide to hold off on investing, waiting for valuations to normalize. However, as the years pass—2012, 2013, 2014, and beyond— corporate profits remain elevated, and the market continues to rally. Each year, your cautious stance leaves you with underwhelming returns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get corporate profits data from FRED</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>corporate_profits <span class="ot">&lt;-</span> <span class="fu">tq_get</span>(<span class="st">"CP"</span>, <span class="at">from =</span> <span class="st">"2000-01-01"</span>, <span class="at">to =</span> <span class="st">"2019-12-31"</span>, <span class="at">get =</span> <span class="st">"economic.data"</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize corporate profits with a vertical line at 2011</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>  corporate_profits<span class="sc">$</span>date, corporate_profits<span class="sc">$</span>price,</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"l"</span>,</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Year"</span>,</span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Corporate Profits (Index)"</span>,</span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Corporate Profits (2000–2019)"</span></span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb68-14"><a href="#cb68-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-15"><a href="#cb68-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a vertical line at 2011</span></span>
<span id="cb68-16"><a href="#cb68-16" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">as.Date</span>(<span class="st">"2011-01-01"</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb68-17"><a href="#cb68-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-18"><a href="#cb68-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Add grid lines for readability</span></span>
<span id="cb68-19"><a href="#cb68-19" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>(<span class="at">nx =</span> <span class="cn">NULL</span>, <span class="at">ny =</span> <span class="cn">NULL</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"gray"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-lecture3_files/figure-html/corporate profits extended-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>By 2019, you’re forced to confront the possibility that your belief about corporate profit mean-reversion might be wrong.</p>
<section id="the-need-for-updating-probability-asessments" class="level4" data-number="3.4.1.1">
<h4 data-number="3.4.1.1" class="anchored" data-anchor-id="the-need-for-updating-probability-asessments"><span class="header-section-number">3.4.1.1</span> The Need for Updating Probability Asessments</h4>
<p>This scenario highlights the importance of updating beliefs in the face of new evidence. Initially, your hypothesis about profit margins reverting to the mean was reasonable, based on historical data. But as year after year passed without mean-reversion, the accumulating evidence should have prompted you to revise your prior beliefs.</p>
<p>Bayes’ Rule offers a principled way to do this. It allows you to combine your initial belief (the prior probability) with new evidence (e.g., sustained elevated profit margins) to calculate an updated belief (the posterior probability). This process ensures that your decisions adapt as reality unfolds, helping you avoid the dangers of clinging to outdated assumptions.</p>
</section>
</section>
<section id="bayes-rule-intuitive-understanding-with-a-speck-of-sand" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="bayes-rule-intuitive-understanding-with-a-speck-of-sand"><span class="header-section-number">3.4.2</span> Bayes’ Rule: Intuitive Understanding with a Speck of Sand</h3>
<p>Bayes’ rule, one of the cornerstone ideas of probability, provides a systematic method for updating probabilities based on new evidence. It is formalized as: <span class="math display">\[\begin{equation*}
P(B|A) = \frac{P(A|B) P(B)}{P(A)}
\end{equation*}\]</span></p>
<p>Here</p>
<p>Here:</p>
<ul>
<li><span class="math inline">\(A\)</span>: Represents the new evidence or data that has been observed.</li>
<li><span class="math inline">\(B\)</span>: Represents the hypothesis or prior belief about an event.</li>
</ul>
<p>This formula arises naturally from the multiplication rule and the symmetry of <span class="math inline">\((A \cap B)\)</span>. Here’s a quick derivation:</p>
<ol type="1">
<li>By the multiplication rule: <span class="math inline">\(P(B|A)P(A) = P(A \cap B)\)</span></li>
<li>Similarly: <span class="math inline">\(P(A|B)P(B) = P(A \cap B)\)</span></li>
<li>Equating the two expressions for <span class="math inline">\(P(A \cap B)\)</span> and dividing by <span class="math inline">\(P(A)\)</span>: <span class="math inline">\(P(B|A) = \frac{P(A|B)P(B)}{P(A)}\)</span></li>
</ol>
<p>Bayes’ rule is often challenging to grasp intuitively. To build understanding, let’s explore a simple and vivid example involving a speck of sand.</p>
<section id="the-speck-of-sand-an-intuitive-illustration" class="level4" data-number="3.4.2.1">
<h4 data-number="3.4.2.1" class="anchored" data-anchor-id="the-speck-of-sand-an-intuitive-illustration"><span class="header-section-number">3.4.2.1</span> The Speck of Sand: An Intuitive Illustration</h4>
<p>Imagine a square of area 1, representing our entire sample space. Within this square, there is a circle <span class="math inline">\(B\)</span>, with area equal to <span class="math inline">\(P(B)\)</span>. You have a tiny speck of sand on your finger, which accidentally falls somewhere within the square. The location of the speck is entirely random.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/where_speck.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Where is the speck of sand?</figcaption>
</figure>
</div>
</div>
</div>
<p>The probability that the speck lands in <span class="math inline">\(B\)</span> is simply the area of <span class="math inline">\(B\)</span>, <span class="math inline">\(P(B)\)</span>, since the speck could have landed anywhere within the square with equal likelihood.</p>
</section>
<section id="updating-beliefs-with-new-information" class="level4" data-number="3.4.2.2">
<h4 data-number="3.4.2.2" class="anchored" data-anchor-id="updating-beliefs-with-new-information"><span class="header-section-number">3.4.2.2</span> Updating Beliefs with New Information</h4>
<p>Now, suppose you are told that the speck landed within another circle <span class="math inline">\(A\)</span> that also lies inside the square:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/speck_in_D.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>In fact we learn that the speck is inside circle <span class="math inline">\(A\)</span></figcaption>
</figure>
</div>
</div>
</div>
<p>How does this new information affect the probability that the speck is in <span class="math inline">\(B\)</span> ? Mathematically, we now want to compute <span class="math inline">\(P(B|A)\)</span>, the probability that the speck is in <span class="math inline">\(B\)</span>, given that it is inside <span class="math inline">\(A\)</span>.</p>
</section>
<section id="overlap-between-a-and-b" class="level4" data-number="3.4.2.3">
<h4 data-number="3.4.2.3" class="anchored" data-anchor-id="overlap-between-a-and-b"><span class="header-section-number">3.4.2.3</span> Overlap Between <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span></h4>
<p>Intuitively, the updated probability <span class="math inline">\(P(B|A)\)</span> depends on the overlap of <span class="math inline">\(B\)</span> and <span class="math inline">\(A\)</span>. Specifically, it is the fraction of <span class="math inline">\(A\)</span> that lies within <span class="math inline">\(B\)</span>, expressed as: <span class="math display">\[\begin{equation*}
P(B|A) = \frac{\text{Area of } A \cap B}{\text{Area of } A} = \frac{P(A \cap B)}{P(A)}
\end{equation*}\]</span></p>
<ul>
<li>If <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> overlap only slightly, <span class="math inline">\(P(B|A)\)</span> will be small:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/small_overlap.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Small overlap between <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span></figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>If the overlap is large, <span class="math inline">\(P(B|A)\)</span> will be large:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/big_overlap.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Large overlap between <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span></figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="bayesian-interpretation" class="level4" data-number="3.4.2.4">
<h4 data-number="3.4.2.4" class="anchored" data-anchor-id="bayesian-interpretation"><span class="header-section-number">3.4.2.4</span> Bayesian Interpretation</h4>
<p>In Bayesian reasoning:</p>
<ul>
<li><span class="math inline">\(P(B)\)</span> is the <strong>prior probability</strong>, representing our belief in the hypothesis <span class="math inline">\(B\)</span> before observing the data.</li>
<li><span class="math inline">\(P(A|B)\)</span> is the <strong>likelihood</strong>, describing how consistent the observed data <span class="math inline">\(A\)</span> is with the hypothesis <span class="math inline">\(B\)</span>.</li>
<li><span class="math inline">\(P(A)\)</span> normalizes the result, ensuring all probabilities sum to 1.</li>
</ul>
<p>The speck-of-sand example illustrates how Bayesian updating works:</p>
<ol type="1">
<li>Start with a <strong>prior</strong> <span class="math inline">\(P(B)\)</span>.</li>
<li>Receive new <strong>evidence</strong> <span class="math inline">\(P(A|B)\)</span>.</li>
<li>Update the probability of the hypothesis given the evidence <span class="math inline">\((P(B|A)\)</span>.</li>
</ol>
<p>Bayes’ theorem quantifies this intuitive process of revising beliefs based on data.</p>
</section>
</section>
</section>
<section id="using-an-llm-to-explore-conditional-probability" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="using-an-llm-to-explore-conditional-probability"><span class="header-section-number">3.5</span> Using an LLM to Explore Conditional Probability</h2>
<p>In each lecture I try to involve a use case showing you how you could leverage the power of LLMs to deepen your learning experience. Conditional probability is an excellent topic to explore with the LLM. Understanding conditional probability can be challenging because our intuitions about likelihoods often conflict with the precise rules of probability theory. Unlike geometric intuition which is hardwired in the human mind through the needs of our visual system, we humans lack an innate intuitive understanding of probability. This is something that has to be acquired through training and practice. An LLM like ChatGPT can serve as a dialogue partner to help you explore this gap and refine your understanding.</p>
<p>Here is a suggested use case: You can use an LLM to simulate and analyze scenarios where our intuition might mislead us. Here’s how to structure a dialogue with the model:</p>
<ol type="1">
<li><strong>Pose a Real-World Scenario</strong>:
<ul>
<li>Example: “Suppose you test positive for a rare disease with a prevalence of 1%. The test is 95% accurate, meaning it correctly identifies positives 95% of the time and negatives 95% of the time. What is the probability that you actually have the disease?”</li>
</ul></li>
<li><strong>Engage in a Dialogue</strong>:
<ul>
<li>Ask the model to explain how to approach the problem using conditional probability.</li>
<li>Explore intermediate steps such as calculating the prior probability, likelihood, and posterior probability using Bayes’ Rule.</li>
</ul></li>
<li><strong>Challenge Your Intuition</strong>:
<ul>
<li>Share your intuitive guess about the probability with the model.</li>
<li>Let the model explain where intuition might diverge from formal reasoning and why.</li>
</ul></li>
<li><strong>Experiment with Variations</strong>:
<ul>
<li>Modify the problem (e.g., change the disease prevalence or test accuracy) and ask the model to recompute probabilities. Compare how small changes in assumptions affect outcomes.</li>
</ul></li>
</ol>
<section id="example-dialogue" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="example-dialogue"><span class="header-section-number">3.5.1</span> Example Dialogue</h3>
<p>Here’s an example interaction you could try:</p>
<p><strong>You</strong>: “I think the probability of actually having the disease should be very high since the test is 95% accurate. Is this correct?”</p>
<p><strong>Model</strong>: “Let’s compute it formally using Bayes’ Rule: <span class="math display">\[\begin{equation*}
P(D|T) = \frac{P(T|D) \cdot P(D)}{P(T|D) \cdot P(D) + P(T|ND) \cdot P(ND)}
\end{equation*}\]</span> Where: - <span class="math inline">\(P(D) = 0.01\)</span> (prevalence), - <span class="math inline">\(P(ND) = 1 - P(D) = 0.99\)</span>, - <span class="math inline">\(P(T|D) = 0.95\)</span> (true positive rate), - <span class="math inline">\(P(T|ND) = 0.05\)</span> (false positive rate).</p>
<p>Substituting the values: <span class="math inline">\(P(D|T) = \frac{0.95 \cdot 0.01}{0.95 \cdot 0.01 + 0.05 \cdot 0.99} \approx 0.16\)</span></p>
<p>This means the probability you actually have the disease is about 16%, much lower than intuition might suggest because the disease is so rare.”</p>
<p>Why can exercises like this be valuable?</p>
<ul>
<li><strong>Refines Understanding</strong>: Engaging in such dialogues clarifies the application of Bayes’ Rule and highlights the importance of considering base rates.</li>
<li><strong>Reveals Pitfalls of Intuition</strong>: You’ll learn to appreciate why our gut feelings can sometimes mislead us in probabilistic reasoning.</li>
<li><strong>Encourages Exploration</strong>: By modifying scenarios and asking “what if” questions, you deepen your grasp of conditional probabilities in diverse contexts.</li>
</ul>
<p>Leverage this approach to build a stronger connection between the theory and its real-world applications.</p>
</section>
</section>
<section id="summary" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="summary"><span class="header-section-number">3.6</span> Summary</h2>
<section id="probability-concepts" class="level3" data-number="3.6.1">
<h3 data-number="3.6.1" class="anchored" data-anchor-id="probability-concepts"><span class="header-section-number">3.6.1</span> Probability Concepts</h3>
<p>In this lecture, we covered the following key probability concepts: - <strong>Conditional Probability</strong>: Understanding the probability of an event occurring given that another event has occurred, and its relevance in real-world scenarios, especially in finance. - <strong>Dependence and Independence</strong>: How events can be dependent or independent and the role of conditional probabilities in analyzing their relationships. - <strong>Bayes’ Rule</strong>: Using conditional probabilities to update beliefs based on new evidence.</p>
<p>These concepts were illustrated with practical examples, including a discussion of the financial crisis of 2007-2008 to highlight the risks of neglecting dependencies in probability modeling.</p>
</section>
<section id="r-concepts" class="level3" data-number="3.6.2">
<h3 data-number="3.6.2" class="anchored" data-anchor-id="r-concepts"><span class="header-section-number">3.6.2</span> R Concepts</h3>
<p>During the lecture, we used R to: - <strong>Simulate Conditional Probabilities</strong>: Generate random data and compute conditional probabilities to illustrate theoretical concepts. - <strong>Visualize Dependencies</strong>: Create intuitive visualizations of event overlaps and relationships between probabilities. - <strong>Practical Applications</strong>: Implement real-world examples to explore conditional probabilities and Bayes’ Rule, showcasing how to use R for data analysis in finance.</p>
<p>This lecture bridged theoretical probability concepts with practical computational tools in R, enabling a deeper understanding of the material and its applications.</p>
</section>
</section>
<section id="project-evaluating-credit-risk-using-conditional-probabilities" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="project-evaluating-credit-risk-using-conditional-probabilities"><span class="header-section-number">3.7</span> Project: Evaluating Credit Risk Using Conditional Probabilities</h2>
<section id="problem-description" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="problem-description"><span class="header-section-number">3.7.1</span> Problem Description</h3>
<p>A bank is evaluating a loan application using historical data to estimate the likelihood of default. The borrower has a low credit score, and the bank has the following data:</p>
<ol type="1">
<li><strong>Default Rates</strong>:
<ul>
<li>Probability of default for all customers: <span class="math inline">\(P(D) = 0.04\)</span>.</li>
<li>Probability of non-default for all customers: <span class="math inline">\(P(ND) = 0.96\)</span>.</li>
</ul></li>
<li><strong>Evidence</strong>:
<ul>
<li>Probability of a low credit score given default: <span class="math inline">\(P(L|D) = 0.7\)</span>.</li>
<li>Probability of a low credit score given non-default: <span class="math inline">\(P(L|ND) = 0.1\)</span>.</li>
</ul></li>
</ol>
<p>The goal is to determine the posterior probability of default given the borrower’s low credit score, <span class="math inline">\(P(D|L)\)</span>, using <strong>Bayes’ Rule</strong>. Additionally, you will verify this theoretical result by simulating customer data and analyzing outcomes.</p>
<hr>
</section>
<section id="questions" class="level3" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="questions"><span class="header-section-number">3.7.2</span> Questions</h3>
<ol type="1">
<li><strong>Compute <span class="math inline">\(P(D|L)\)</span> Theoretically</strong>:
<ul>
<li>Use Bayes’ Rule to calculate the posterior probability of default given a low credit score.</li>
</ul></li>
<li><strong>Simulate the Scenario in R</strong>:
<ul>
<li>Simulate a dataset of 10,000 customers where each customer is randomly assigned a default status based on <span class="math inline">\(P(D)\)</span>.</li>
<li>Based on the assigned default status, simulate whether each customer has a low credit score using <span class="math inline">\(P(L|D)\)</span> and <span class="math inline">\(P(L|ND)\)</span>.</li>
</ul></li>
<li><strong>Compute <span class="math inline">\(P(D|L)\)</span> from Simulated Data</strong>:
<ul>
<li>Use the simulated data to compute <span class="math inline">\(P(D|L)\)</span> and compare it to the theoretical result.</li>
</ul></li>
<li><strong>Visualize Results</strong>:
<ul>
<li>Create a simple bar plot comparing the simulated and theoretical probabilities. If you are unfamiliar with visualization tools, check out the <code>barplot()</code> function in base R.</li>
</ul></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-DiaconisSkyrms2019" class="csl-entry" role="listitem">
Diaconis, Persi, and Brian Skyrms. 2019. <em>10 Great Ideas about Chance</em>. Princeton University Press.
</div>
<div id="ref-Feller1968" class="csl-entry" role="listitem">
Feller, William. 1968. <em>An Introduction to Probability Theory and Its Applications</em>. 3rd ed. Vol. 1. Wiley.
</div>
<div id="ref-Tooze2018" class="csl-entry" role="listitem">
Tooze, Adam. 2018. <em>Crashed. How a Decade of Financial Crisis Changed the World</em>. Viking.
</div>
</div>
</section>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-lecture2.html" class="pagination-link" aria-label="Probability: Basic Definitions and Rules">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability: Basic Definitions and Rules</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>