% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={An Intuitive Introduction to Probability Theory},
  pdfauthor={Martin Summer},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{apalike}

\title{An Intuitive Introduction to Probability Theory}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{With Applications to Computational Finance using R}
\author{Martin Summer}
\date{2021-11-23}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{introduction}{%
\chapter{Introduction}\label{introduction}}

\begin{quote}
``What I hear, I forget; What I see, I remember; What I do, I understand''

\hfill --- Confucius, 551-479 BC
\end{quote}

Our lectures are going to teach you basic concepts of probability every finance
practitioner needs to know and be familiar with. Because you will need
probability as a tool for thinking about and solving finance problems with
computational methods, we will use computational finance as the context within
which we develop the concepts and ideas of probability. But we will also
make much use of the computer in this course: Our approach to teaching you
basic concepts of probability is based on understanding concepts by building
them with your own hands.

But how can we build abstract concepts such as probability, random phenomena and chance by
our own hands? How can we ``touch'' such things like an idea?
While probability is a mathematical theory, it gains practical value and an intuitive meaning in
connection with real or conceptual experiments such as, the future change in a stock price
index, the future value of a portfolio of securities, the chance that a creditor is not going
to be able to pay back your loan.

Many of these experiments we can nowadays simulate on the computer. We
can can construct, build and simulate a huge variety of random phenomena. We can - for instance -
implement models of random fluctuations of asset prices. We can model financial risks
and contemplate possible future scenarios through simulation.

We can approach our understanding of abstract concepts
by building them with our own hands on the computer. This is the approach to teaching you
probability in this course.

There are many ways to build virtual objects and to run simulations to manipulate
them. For this we will need a programming language. The language we choose for this
course is R and the integrated development environment RStudio. This is one of the main
languages used in data analysis, statistics and data science and is widely used in industry and
academia. It will be our tool to do probability in this course.

\hypertarget{downloading-and-installing-r}{%
\section{Downloading and installing R}\label{downloading-and-installing-r}}

So lets start by downloading and installing R first. R is an open source project maintained
by an international team of developers. The software is made available through a website called
the comprehensive R archive network (\url{http://cran.r-project.org}).

At the top of this website, in a box named ``Download and install R'' you will find three
links for downloading R. Choose the link that describes your operating system, Windows, Mac or
Linux. These links will lead you to the necessary information you need to install a current
version of R. The easiest install option is to install R from precompiled binaries. There is also
the option to built R from source on all operationg systems if you have the tools and the
expertise to do so. R also comes both in a 32-bit and a 64-bit version. It does not make
a substantial difference which version you use. 64-bit versions
can handle larger files and data sets with fewer memory management problems.

\hypertarget{downloading-and-installing-rstudio}{%
\section{Downloading and installing RStudio}\label{downloading-and-installing-rstudio}}

RStudio is an application that helps you write and develop R code. It makes using
R much easier for you than using it in isolation. The interface of RStudio looks the
same across all operating systems.

You can download RStudio for free from \url{https://www.rstudio.com/products/rstudio/}.
Select the box RStudio Desktop and follow the download instructions. RStudio Desktop is free.
Note that you need to have a version of R installed to use RStudio.

If you have successfully installed R and RStudio, we are ready to start.

\hypertarget{empirical-background-and-some-terminology}{%
\chapter{Empirical background and some terminology}\label{empirical-background-and-some-terminology}}

If you chose to study Finance it should be natural for you to study probability.
After all, Finance studies the allocation and pricing of money across time. You can
safe money to use it later for purchasing goods and services you can borrow money to
invest today and repay in the future from the revenues of your project. But the
future is uncertain and we do not know today how it will look like. In Finance we unavoidably
have to deal with risk and uncertainty. The most fundamental concept we have available
to deal with risk and uncertainty and to think about and analyze it is probability. Therefore
every serious student of Finance has to study probability early on.

\hypertarget{terminology}{%
\section{Terminology}\label{terminology}}

Probability is a mathematical theory. This theory gets practical value and intuitive meaning
in connection with real or conceptual experiments such as
selecting a random sample of stocks and observing their most extreme price drop over a
given period of time or observing the frequency of loan defaults. In the early days of
probability when some conceptual ideas about which we are going to learn in this course
were first developed the conceptual experiments considered by the pioneers of
probability where games of chance involving rolls of dies, or spins of a wheel as well
as reflections on placing bets on the outcomes of such games. While we will stick
mainly to our main context - computational finance - some of these chance games are
so intuitive and insightful that we will occasionally in the beginning of the course
also use some of them for illustrating concepts and playing with them.

All of the examples and
descriptions given above are, however, rather vague.
We have to be more precise what we mean by an
experiment or observation.

When we use the term (random) \emph{experiment} we mean a process leading to an uncertain
outcome. To make this notion precise and useful we need to agree what we mean by
uncertain outcomes.

Take the simple example of considering whether the price of a stock is
going to rise or fall at the next day. In a practical situations the outcome
of a move in the stock price can be that it goes up or down but it could in principle
also stay the same. Still when we think about the
experiment of observing the stock price tomorrow
in many applications in Finance we usually agree \emph{on the outset} that
\emph{up} and \emph{down} are the only possible outcomes of this experiment. By such an
agreement we have pinned down the possible outcomes.

The collection of all possible outcomes of an experiment is called the \emph{sample space}.
While the sample space of the experiment of observing tomorrow's stock price
is an idealization it is
exactly this idealization which simplifies the theory without affecting its applicability.

Idealizations of this kind are standard in probability. It
is - for example - impossible to know how high the price of a stock might become. Is there
a maximal price beyond which the price can not possibly hike? Many of us would
hesitate to claim that the price might rise without bound. Yet many models in applied
Finance are based on such an assumption. The models allow arbitrary price hikes but with arbitrary
small probability as the price gets higher and higher. Practically it does not make sense
to believe that a security price can become arbitrarily high. The use of arbitrarily small
probabilities in a financial model might seem absurd but it does no practical harm and makes
the model simple and convenient to use. Moreover, if we seriously introduced an upper bound
on a security price at \(x\) it would be also awkward to assume that it is impossible that it
could be just a cent higher, an assumption equally unappealing than assuming it can get in
principle arbitrarily high.

When we talk of a \emph{basic outcome} we mean the possible outcome of a random experiment.
An \emph{event} is
a subset of basic outcomes. Any event which consists of a single outcome in the sample space
is called a \emph{simple event}.

\emph{Probability} is a measure of how likely an event of an experiment is. Thus when we
talk about probability in a precise and meaningful sense we can only do so in relation to
a given sample space or to a certain conceptual experiment.

Thus before we can begin to seriously
talk about probability we need to develop a good understanding of experiments, sample
spaces, basic outcomes and events. In the spirit of this course we will develop this
understanding by building these concepts using R. Thus let us develop examples
of random experiments, sample spaces, basic outcomes and events in parallel with
making our first steps in R. R will be our tool which will allow us to ``touch''
probability concepts.

As we proceed through our course we will develop a broader and deeper
understanding of this language together with the probability concepts.

\hypertarget{rolling-a-die-constructing-a-random-experiment-a-sample-space-and-events-using-r}{%
\section{Rolling a die: Constructing a random experiment, a sample space and events using R}\label{rolling-a-die-constructing-a-random-experiment-a-sample-space-and-events-using-r}}

Lets start with a classic and old example of a probability model: Rolling a six sided die.
The rolling of the die is one of the non-finance examples we mentioned before. It is so
useful that we will come back to it once in a while in the beginning of the course. Here
its usefulness is enhanced because it allows us in an easy way to quickly learn
some powerful R concepts and techniques.
We want to roll this die not physically but on our computer using R and RStudio as our tool.
How can we do this?

\hypertarget{the-r-user-interface}{%
\subsection{The R User Interface}\label{the-r-user-interface}}

Before we can ask our tool to do anything for us, we need to know how to talk to
it. In our case RStudio allows us to talk to our computer. It works like any other
application. When you launch RStudio on your computer, you will see a screen looking like
this:

\begin{figure}

{\centering \includegraphics[width=0.9\linewidth]{figures/Screenshot_RStudio} 

}

\caption{The RStudio startup screen}\label{fig:unnamed-chunk-1}
\end{figure}

In this picture you see a screenshot of my RStudio screen. Interacting with the app is easy. You
type commands via your keyboard at the prompt, which is the \texttt{\textgreater{}} symbol. You can see it in
the left pane in the screenshot. You send the command to the computer
by pressing enter. After you have pressed enter, RStudio
sends the command to R and displays the result of your command with
a new prompt to enter new commands, like this:

\begin{verbatim}
> 1 + 1
[1] 2
>
\end{verbatim}

The \texttt{{[}1{]}} means that the line begins with the first value of your result. For
example, if you enter the command \texttt{20:60} which means in the R language, ``list
all the integers from 20 to 60'', and you then press return, you will get an output like this:

\begin{verbatim}
[1] 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
[34] 53 54 55 56 57 58 59 60
\end{verbatim}

meaning that 20 is the first value displayed in your result. Then there is a
line break because not
all values can be displayed on the same line and R tells you that \texttt{53} is the
34-th value of the
result.

The colon operator \texttt{:} is a very useful function in R which we will often need. It allows us
to create sequences of every integer between two given integers.

R needs a complete command to be able to execute it, when the return key is pressed.
If a command is incomplete,
like for instance
\texttt{5*},
where we enter 5, the multiplication operator but no
second factor to multiply 5 with R will show:

\begin{verbatim}
> 5*
+ 
\end{verbatim}

The \texttt{+} sign means that R needs more input to complete the expression.
So if we type the missing
factor after the \texttt{+} prompt, say 4 and then press the return key again, we
will get the result

\begin{verbatim}
> 5*
+ 4
[1] 20
\end{verbatim}

If you type a command that R does not understand, you will be returned an error message.
Don't worry
if you see an error message. It just is a way the computer tells you that he does
not understand what you
want him to do.

For instance, if you type \texttt{5\%3} you will get an error message like this

\begin{verbatim}
> 5%3
Error: unexpected input in "5%3"
>
\end{verbatim}

Sometimes it is obvious why a mistake occurred. In this case, that R just does not
know what to do with
the symbol \texttt{\%}. It has no meaning in this context. Sometimes it is
not so obvious what the error
message actually means and what you might do about it. A useful strategy in this
case is to type
the error message into a search engine and see what you can find. The chance is very
high that others
encountered the same problem before you and got helpful advice how to fix it from other users on
the internet. One site, we find particularly helpful for all kinds of questions related to R
and R programming is \url{https://stackoverflow.com/}. Try it at the next opportunity.

Now with this basic knowledge, we can already make the first step to create a
die on the computer
using R. If you think of a physical die, the essential thing that matters are
the points on its
six sides. If you throw the dice it will usually land on one of these sides
and the side which is
on the upper side of the die shows the number of points.
The colon operator \texttt{:} gives us a way to
create a group of numbers from 1 to 6. R gives us the result as a
one dimensional set of numbers.

\begin{verbatim}
> 1:6
[1] 1 2 3 4 5 6
> 
\end{verbatim}

Lets use these first steps in R to recap the probability concepts we have learned using this
example of the six sided die:
A \emph{basic outcome} of rolling a six-sided die is for example \texttt{6} if the upper side after
rolling the die happens
to be the side with 6 points. The \emph{sample space} of the experiment of rolling a six-sided die is
the set \({\cal S} = \{1,2,3,4,5,6\}\). In probability theory we often use the symbol \({\cal S}\) or
\(S\) for sample space. In many probability texts the sample space is also often denoted by
the symbol \(\Omega\) the greek letter for (big) Omega. A \emph{random experiment} in this example is
the rolling of the die. The outcome is uncertain but once the die is rolled the outcome
can be determined precisely. Finally we can also illustrate in the example the concept of an
\emph{event}: For example, the event, that the die will show less than 4 points is \(A = \{1,2,3\}\). We use here
the symbol \(A\) to denote this event and use set notation to describe the set of basic outcomes that
make up the event ``number of points smaller than 4''. The event that the outcome is that the point
shows 10 points is the empty set \(B = \emptyset\). The symbol \(\emptyset\) comes from set theory and
means the set containing no elements. This event can contain no elements because we can not get
a score of 10 by rolling a six sided die.

\hypertarget{objects}{%
\section{Objects}\label{objects}}

You can save data in R by storing them in \emph{objects}. An object is a name, you can choose yourself to
store data. For example, if you choose to store the value \texttt{6} in an object called \texttt{point\_six},
you would type:

\begin{verbatim}
> point_six <- 6
> 
\end{verbatim}

at the prompt. R will the store the value 6 in the object called \texttt{point\_six}, which
you can use to refer to the value. If you type the name of your object at the prompt, R
will distplay the value you have assigned. A usful key combination for typing the assignment
operator \texttt{\textless{}-} is to use the key combination \texttt{ALT\ \_}. At the R prompt R will automatically
print an assignment operator.

\begin{verbatim}
> point_six
[1] 6
> 
\end{verbatim}

Now you can use the name of the object to refer to its value. For instance, you could divide
\texttt{point\_six}by \texttt{2}and get a meaningful result

\begin{verbatim}
> point_six/2
[1] 3
> 
\end{verbatim}

Now to make our \texttt{die} more tangible and useful, let us store it in an R object by
typing the following command at the prompt. This command creates an object with name
\texttt{die} and assign the vector \texttt{1,2,3,4,5,\ 6} to it.

\begin{verbatim}
> die <- 1:6
> 
\end{verbatim}

\begin{figure}

{\centering \includegraphics[width=0.9\linewidth]{figures/screenwithobject} 

}

\caption{The RStudio Environment pane keeps track of the objects you have created}\label{fig:unnamed-chunk-2}
\end{figure}

You can now see in the right upper Environment pane that R shows you that there is an object with the
name \texttt{die} that it consists of integers \texttt{1,2,3,4,5}. As you create more objects they will be
stored in the Environment pane and are ready for your reference, unless you delete them. You can remove or delete an object by typing

\begin{verbatim}
> rm(object)
>
\end{verbatim}

or by assigning the value \texttt{die\ \textless{}-\ NULL} which would also remove the object from your
environment or workspace.

You can name your objects almost anything with a few exceptions. An object name must not start with
a number. There are some special symbols which can also not be used in object names, like
\texttt{\^{},\ !,\ \$,\ @,\ +,\ -,\ /,\ *}. Note that R is case sensitive and distinguishes small and big
letters. If you assign a new value for an object you have already created, R will overwrite the
object without warning.

You can see which objects are currently created and available for you in the Environment pane
of your session of by typing \texttt{ls()}.

Before we learn how we can actually roll our die and perform a random experiment with it, let us
briefly use the opportunity to explain a few things about how R does computations. We have
already explained that we can use the object name to refer to the value. So for instance
if we type

\begin{verbatim}
> die*die
[1]  1  4  9 16 25 36
> 
\end{verbatim}

This might irritate some of you because we have called the object a vector. In linear
algebra multiplication of vectors is only allowed if there is an inner product. What happens
here, if we use \texttt{*} the multiplication operator is that R does an element-wise multiplication
of the six numbers of our die. Of course R allows to take an inner product as well, but this needs
a different operator. To compute an inner product, we would type

\begin{verbatim}
> die %*% die
     [,1]
[1,]   91
\end{verbatim}

Now R displays the result as a vectors with one row and one column, which is denoted in the output by
\texttt{{[}\ ,\ 1{]}} for the column and \texttt{{[}1,\ {]}} for the row. We will learn later more about
the use and the meaning of this notation in R.

The elementwise execution R usually uses also means that when you, for example type

\begin{verbatim}
> die - 1
[1] 0 1 2 3 4 5
> 
\end{verbatim}

R would subtract \texttt{1} from every component in the vector \texttt{die}.

Another specific behavior of R, you need to know about is called ``recycling''. If you give
R two vectors of different length in an operation, R will repeat the shorter vector as long as
it is of equal length with the longer one. For example, if you have:

\begin{verbatim}
> die + 1:2
[1] 2 4 4 6 6 8
> 
\end{verbatim}

you see that R adds 1 to 1 and 2 to 2 and then starts over again by adding 1 to 3 and 2 to 4 and then
starts over once again by adding 1 to 5 and 2 to 6. If the longer vectors is not a multiple of the shorter one, R recycles but the cuts off. It will give you a warning though.

\begin{verbatim}
> die + 1:4
[1] 2 4 6 8 6 8
Warning message:
In die + 1:4 :
  longer object length is not a multiple of shorter object length
> 
\end{verbatim}

While this might seem awkward to some of you, we will see that for data manipulation
element-wise execution is often extremely useful. It allows to manipulate groups of values in
a systematic way.

\hypertarget{functions}{%
\section{Functions}\label{functions}}

R contains many functions which we can use to manipulate data and compute things. The syntax for
using a function is very simple: You type the function name and put the value of the function
argument in parentheses. Here we use for illustrations the function of the square root \texttt{sqrt()}
and the function for rounding a number \texttt{round()}.

\begin{verbatim}
> sqrt(4)
[1] 2
> round(3.1415)
[1] 3
> 
\end{verbatim}

The data you write in the parentheses are called the fuction arguments. Arguments can be all sorts of
things: raw data, R objects, results from other functions. If functions are nested, R evaluates the
innermost function first and then goes on to the outer functions. To see examples of all these instances
you can take

\begin{verbatim}
> mean(1:6)
[1] 3.5
> mean(die)
[1] 3.5
> round(mean(die))
[1] 4
> 
\end{verbatim}

for example.

For simulating random experiments, R has the function \texttt{sample()}. With this function
we can roll our die on the computer and conduct actual random experiments. The function takes
as arguments a vector names \texttt{x} and a number named \texttt{size}. \texttt{sample} will return
\texttt{size} elements randomly chosen from the vector \texttt{x}. Lets say:

\begin{verbatim}
> sample(x = 1:4, size = 2)
[1] 4 1
> 
\end{verbatim}

In this case \texttt{sample} has chosen \texttt{4,1} from the vector \texttt{x\ =\ (1,2,3,4)}. If we want
to roll the die in our computer we can thus pass the die as an argument to \texttt{sample} and
use the number \texttt{1} for the \texttt{size} argument. Lets do a few rolls with our die

\begin{verbatim}
> sample(x = die, size = 1)
[1] 3
> sample(x = die, size = 1)
[1] 2
> sample(x = die, size = 1)
[1] 3
> sample(x = die, size = 1)
[1] 5
> sample(x = die, size = 1)
[1] 1
> sample(x = die, size = 1)
[1] 5
> 
\end{verbatim}

R functions can have many arguments, but they need to be separated by a comma.

Every argument in every function has a name. We specify which data are assigned to the
arguments by setting the name equal to the data. Names help us to avaoid passing the wrong
data and thereby mixing up things or committing errors. But using names is not
necessary. If we just wrote

\begin{verbatim}
> sample(die, 1)
[1] 5
> 
\end{verbatim}

R would also know what to do. It is not always clear which names to use for a function. If you are
not sure, you can use the function \texttt{args} to look it up. Here we take the
function \texttt{round} as one example.

\begin{verbatim}
> args(round)
function (x, digits = 0) 
NULL
> 
\end{verbatim}

Note that the \texttt{digits} argument in the \texttt{round} function is already set to \texttt{0}. Frequently
R functions come with optional arguments. These arguments are optional because the come with a
default value, which is \texttt{0} in case of the round function.

We recommend that you write out argument names as a rule. It gives clearer code and avoids
errors. If you don't write argument names, R matches your values to the arguments of the
function by order.

\hypertarget{writing-your-own-functions}{%
\section{Writing your own functions}\label{writing-your-own-functions}}

Now we are ready to write our own function to roll the die in our computer. Each function in R
has the same elements: A name, a function body of code and a set of arguments. To write your
own function, you have to write up all of these parts and save them in an R object. The syntax
is:

\begin{verbatim}
my_function <- function() {}
\end{verbatim}

The name here is \texttt{my\_function}, next comes the expression \texttt{function()} which needs to be assigned.
The names of the function arguments have to be written between the parentheses. Then we
have to write the actual code within the braces \texttt{\{\}}.

To do this for the die, lets write a function names \texttt{roll\_die}.

\begin{verbatim}
> roll_die <- function(){die <- 1:6 
                         sample(die, size = 1)}
\end{verbatim}

Now we can roll our die for a few times to show how the function works

\begin{verbatim}
> roll_die()
[1] 4
> roll_die()
[1] 1
> roll_die()
[1] 5
> roll_die()
[1] 4
> roll_die()
[1] 6
> 
\end{verbatim}

A final remark in the \texttt{sample}function is in place here. If we look at the argunments of
sample using the \texttt{args} function we see

\begin{verbatim}
> args(sample)
function (x, size, replace = FALSE, prob = NULL) 
NULL
> 
\end{verbatim}

Lets do not discuss all the details of this output but concentrate for a moment on the \texttt{replace}
argument. What does this mean? As we saw previously we can use the sample function to
model the rolling of our die. If we set the \texttt{size} argument to \texttt{1} we get the roll of one
die. If we set the \texttt{size} argument to \texttt{n}, we would simulate the rolling of \texttt{n} dies.
But now the \texttt{replace} argument becomes crucial. As we can see in the output of the
\texttt{args} function \texttt{replace} has a default value \texttt{FALSE}. This is a logical argument.
It tells R, for example, that if we set \texttt{size\ =\ 2}, meaning that two dice are rolled, if the
first dice shows, say a value of 3, the second die cannot show 3 as well. This is clearly not
what we have in mind when we model the rolling of 2 dice. It should be possible that
both dies show the same value. To enable this behavior of the sample function, we have to
change the default value of the \texttt{replace} argument to \texttt{TRUE}. Then R chooses a random draw
from all of the six possible values for all dice rolled.

Congratulations. You have written your first R function for conducting a simple random
experiment. Think of the parentheses as a trigger that tells R to run the function. If
you omit the trigger R just prints the body of the function. When you run a function,
all the code in the function body is executed and R returns the result of the last
line of code. If the last line of code does not return a value neither will R.

\hypertarget{arguments}{%
\section{Arguments}\label{arguments}}

Imagine we remove the first line of code in our function body and changed the name
die in the sample function to ball.

\begin{verbatim}
roll_die2 <- function(){sample(ball, size = 1)}
\end{verbatim}

If we call the function now, we will get an error

\begin{verbatim}
> roll_die2()
Error in sample(ball, size = 1) : object 'ball' not found
\end{verbatim}

We could supply ball when we call \texttt{roll\_die2} if we make ball an argument of the
function. Lets do this:

\begin{verbatim}
> roll_die2 <- function(ball){sample(ball, size = 1)}
> 
\end{verbatim}

Now the function will work as long as we supply \texttt{ball} when we call the function.

\begin{verbatim}
> roll_die2(ball = 1:6)
[1] 2
> 
\end{verbatim}

Note that we still get an error, if we forget to supply ball argument

\begin{verbatim}
> roll_die2()
Error in sample(ball, size = 1) : 
  argument "ball" is missing, with no default
\end{verbatim}

This could be avoided if we give the function a default argument

\begin{verbatim}
> roll_die2 <- function(ball= 1:6){sample(ball, size = 1)}
> roll_die2()
[1] 4
> 
\end{verbatim}

\hypertarget{scripts}{%
\section{Scripts}\label{scripts}}

So far we have worked by interacting with the console. But what if you want to edit
your functions? It would be much easier, if you could use a draft of your code and
work form there. This can be done by using a \emph{script}.

You create a script by going to \texttt{File\ \textgreater{}\ New\ File\ \textgreater{}\ R\ script} in the menu bar of RStudio. Using
scripts is the standard way to write code in R. It not only helps you to keep track of your code,
save it and edit it later. It also makes your work reproducible. You can edit and proofread your
code and share it with others. To save your script go to \texttt{File\ \textgreater{}\ Save\ As} in the
menu bar.

\begin{figure}

{\centering \includegraphics[width=0.9\linewidth]{figures/scriptscreen} 

}

\caption{The RStudio Script}\label{fig:unnamed-chunk-3}
\end{figure}

RStudio has many useful features to help you work with scripts. You can for instance automatically
execute a line in a code by using the run button. You can also execute sections of code or the
entire script. The entire script is executed by running the Source button. For all these commands
there are key short cuts which you will learn as you work more with RStudio and R.

\hypertarget{using-packages-and-finding-help}{%
\section{Using packages and finding Help}\label{using-packages-and-finding-help}}

We have now a function which we can use to simulate the rolling of a die, \texttt{roll\_die()}. If the
die is fair it should be the case that if we roll the die often, all numbers should occur
about equally often. The die should not be weighted in favor of a particular value.

One way to learn whether our die is fair are \emph{repetition} and \emph{visualization}. These
are tools we will need all the time, when working with data and when doing probability.
While R has many useful functions, one of the great powers is that R is constantly extended
by a huge community of users by providing packages. Packages are add on functions, which will
not be available when you install R. They need to be installed and loaded before you can use them.
Since packages are such a powerful tool in R we need to introduce what they are and how to use
them in the beginning.

\hypertarget{packages}{%
\subsection{Packages}\label{packages}}

There are many visualization tools in R that come with the basic installation. Since the point
we want to make here is about packages, we will use a visualization function which is part of
the package \emph{ggplot2}, a very popular package for making all kinds of graphs. There are
many additional functions provided with this package. For the point we want to make here
we will use one of them, called \texttt{qplot}.

Since \texttt{qplot} is a function in the package \emph{ggplot2}, we first need to install this package.
To install a package you need to be connected to the internet. If you have internet connection
go to the command line and run at the command line

\begin{verbatim}
> install.packages("ggplot2")
\end{verbatim}

R will now download the package via the internet and install it. It will display various messages
in the console during this process. Don't worry if you don not know what they exactly mean and don't
panic that they are displayed in red. All packages can be installed like this. You have just to enter the
correct name in the function \texttt{install.packages()}. The lower left pane in the RStudio software
alternatively provides a tab called \textbf{Packages}. Using this tab, you can also install R packages
interactively by clicking the install button on the upper left corner of the Packages tab.

After installation the package is on our hard-drive but it can not yet be used. To use the package it has
to be laoded. This is done with the command \texttt{library}. To load the \emph{ggplot2} package we type

\begin{verbatim}
> library("ggplot2")
\end{verbatim}

and hit the return key. Many things could be said about the R package system and you will learn it
in more detail as we go along in our course. For the moment the most important thing to remember now
is that a package needs to be newly loaded whenever you want to use it in a new R session.

To check whether our dies is fair, we need to roll it many times. R provides a function, that does this
for us. This function is called \texttt{replicate} and provides an easy way to repeat a command many times.
The number of times we want to repeat something is given as an argument to the \texttt{replicate} function.

Now lets roll our die 100 times and save the result in an object we call \texttt{rolls}:

\begin{verbatim}
rolls <-replicate(100, roll_die())
\end{verbatim}

We now use the ``plot``` function from the \emph{ggplot2} library to make a quick visualization.

\begin{figure}

{\centering \includegraphics[width=0.9\linewidth]{figures/100_rolls} 

}

\caption{Frequencies of 1, 2, 3, 4, 5, 6 after rolling our virtual die 100 times}\label{fig:unnamed-chunk-4}
\end{figure}

It looks like every value occcured roughly 16 times but there is still quite some variation. For instance,
the value 3 seems to occur more than 20 times whereas the value 2 occurs less than 15 times. Maybe
we have to give it another trial with more replications. With the computer we can do this with
a fingertip. Let us roll our die 10000 times and plot the result.

\begin{verbatim}
> rolls2 <- replicate(10000, roll_die())
> qplot(rolls2m bindwidth = 1)
\end{verbatim}

Now the picture looks better.

\begin{figure}

{\centering \includegraphics[width=0.9\linewidth]{figures/10000_rolls} 

}

\caption{Frequencies of 1, 2, 3, 4, 5, 6 after rolling our virtual die 10000 times}\label{fig:unnamed-chunk-5}
\end{figure}

It seems that there is no significant visual evidence that our die is loaded.

\hypertarget{getting-help}{%
\subsection{Getting Help}\label{getting-help}}

We have now learned a tiny number of R functions and we have written one function ourselves. We have
learned how to make use of functions provided by packages. It would be overwhelming to memorize and
learn them all. In R, fortunately, every functions comes with a detailed documentation and with its own
help page. You need to learn how to use this source right from the beginning.

To access the help page of a function you type the function name preceeded by a questionmark at the
prompt, like this

\begin{verbatim}
> ?sample
\end{verbatim}

Then, after you have pressed the return key, a help page is opened in the right lower pane under the
help tab. This help page has a particular structure that you will find for every other R function
no matter whether it is provided by the base installation or by a package. In the upper left
corner you see the name of the function (\texttt{sample}) and in curly brackets next to it the term
\texttt{base}, which means that this is a function in the R base installation. Then you see a headline
about what the function does.

From the top of the page, you then first see the field \textbf{Description}. This is a short description what the function does. Here it says

\begin{verbatim}
Description
sample takes a sample of the specified size from the elements of x using either with or without replacement.
\end{verbatim}

The next field is \textbf{Usage}. It gives you the function description with the arguments. Here for example

\begin{verbatim}
Usage
sample(x, size, replace = FALSE, prob = NULL)

sample.int(n, size = n, replace = FALSE, prob = NULL,
           useHash = (!replace && is.null(prob) && size <= n/2 && n > 1e7))
           
           
\end{verbatim}

The first line in Usage should by now be familiar. Don't worry about the second line. The function can
obviously do more than we know so far.

Next comes a list of arguments the function takes and what type of information R
expects you to provide, as well as what R will do with this information. Here it says for example

\begin{verbatim}
Arguments
x   
either a vector of one or more elements from which to choose, or a positive integer. See ‘Details.’

n   
a positive number, the number of items to choose from. See ‘Details.’

size    
a non-negative integer giving the number of items to choose.

replace 
should sampling be with replacement?

prob    
a vector of probability weights for obtaining the elements of the vector being sampled.

...
\end{verbatim}

We omit some information here.

Then comes a field called \textbf{Details} which gives a more in-depth description of the function. The next
field is calles \textbf{Value}. It describes what the function returns when you run it. Then
we have a referecne to related R functions under the field \textbf{See}. Finally there is a field called
\textbf{Examples}. This field contains example code that is guaranteed to work. It shows a
couple of different cases how you can use the function in practice.

\hypertarget{some-more-examples}{%
\section{Some more examples}\label{some-more-examples}}

To close this lecture let us come back to probability and discuss some more examples of
random experiments, sample spaces, basic outcomes and events. Let us try to leverage our
R knowledge to build the objects in the different examples ourselves.

\hypertarget{the-stock-price-of-apple}{%
\subsection{The stock price of Apple}\label{the-stock-price-of-apple}}

Since the context of this course is Computational Finance, let us discuss an example from
Finance first: The
stock price of Apple is recorded daily. Let us use this example to make a first step in
loading data into R. We have already learned how we could have a first quick glance at
how they look like. We will discuss various ways to get financial data as we go along. For this
initial example we have prepared a data file for the Apple stock price from January 2021 to
the beginning of September 2021 and we have stored the data (in some format) locally. In
practice we often will not have data ready fro retrieval but will have to retrieve them from the
web, from a database or from other sources but let us not worry about these practical details
for the moment. We have stored the data in an R internal format, called RDS and we have stored the
file \texttt{apple\_stock\_prices.RDS} in a folder in our current working directory which we have
called \texttt{data}. Under this assumption we read these data and assign them to an R object
using the R function \texttt{readRDS}. Let us call
this object \texttt{apple\_stock}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{apple\_stock }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/apple\_stock\_price.RDS"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

To have a first look at the data, we use the R-function \texttt{head()}. This is a very useful function
to glance at the data because instead of shwoing us the entire, possibly very big, dataset it
shows us just the first few lines. We can even specify how many by specifying a parameter
for the number of lines we want to display, say 10:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(apple\_stock, }\AttributeTok{n =} \DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    symbol       date   open   high    low  close    volume adjusted
## 1    AAPL 2021-01-04 133.52 133.61 126.76 129.41 143301900 128.8048
## 2    AAPL 2021-01-05 128.89 131.74 128.43 131.01  97664900 130.3973
## 3    AAPL 2021-01-06 127.72 131.05 126.38 126.60 155088000 126.0080
## 4    AAPL 2021-01-07 128.36 131.63 127.86 130.92 109578200 130.3078
## 5    AAPL 2021-01-08 132.43 132.63 130.23 132.05 105158200 131.4325
## 6    AAPL 2021-01-11 129.19 130.17 128.50 128.98 100384500 128.3768
## 7    AAPL 2021-01-12 128.50 129.69 126.86 128.80  91951100 128.1977
## 8    AAPL 2021-01-13 128.76 131.45 128.49 130.89  88636800 130.2779
## 9    AAPL 2021-01-14 130.80 131.00 128.76 128.91  90221800 128.3072
## 10   AAPL 2021-01-15 128.78 130.22 127.00 127.14 111598500 126.5454
\end{verbatim}

Now we see what is contained in the data. They are organized in a table. Each column is a
variable, starting with the stock symbol of Apple, then the date, the opening price, the
highest, the lowest and the closing price, the volume and the adjusted volume. Every
row is a record of the values of these variables for a particular trading day in
the time period we consider.

Now let us make a chart of the closing price at each day over the time period of our data using
the plotting function \texttt{qplot()} we already used for visualizing the outcomes of
repeated die rolls. In order to do so, we create two new R objects which contain the date
and the column close. This means we need to select these two columns.

We
will learn more systematically how to do this in R. For the moment we just show one
way to achieve this for the particular example:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{date }\OtherTok{\textless{}{-}}\NormalTok{ apple\_stock}\SpecialCharTok{$}\NormalTok{date}
\NormalTok{price }\OtherTok{\textless{}{-}}\NormalTok{ apple\_stock}\SpecialCharTok{$}\NormalTok{close}
\end{Highlighting}
\end{Shaded}

Now we load the library \texttt{ggplot2} and use the \texttt{qplot} function. As arguments we give the
qplot function the series of dates and the series of closing prices and set a display
option, called \texttt{geom} to ``line'' to get a line graph (instead of the qplot default of a point
graph)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(}\StringTok{"ggplot2"}\NormalTok{)}

\FunctionTok{qplot}\NormalTok{(date,price, }\AttributeTok{geom =} \StringTok{"line"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Probability_Introduction_files/figure-latex/unnamed-chunk-9-1.pdf}

Now assume we are at the end of our price data series, at August 6th 2021. We want to
think about the uncertain price tomorrow. This is our random exmeriment. What would
be a suitable state space?

What are the possible prices Apple can attain? The minimum price is zero. The maximum price can
not be determined. In principle it could be infinite. The state space here would be an open
interval of real numbers, \({\cal S} = [0, \infty)]\). Quite complicated.

We could define the state space for the price change, in another way, by thinking about three
events: Up, denoted by \(u\) when the stock price increases, Even, denoted \(e\) when the stock price
does not move, and Down, denoted \(d\) when the price decreases. From this perspective
the state space would be \({\cal S} = \{u,e,d\}\). A bit simpler than before.

There are more elegant and powerful ways to read and plot data in R. We used this particular
example just to show you one particular way. More details and more general insights
how to do this we will develop as we go along.

\hypertarget{the-change-of-a-stock-price-two-days-from-now}{%
\subsection{The change of a stock price two days from now}\label{the-change-of-a-stock-price-two-days-from-now}}

Suppose we want to study the random experiment of observing a stock price move twice.
This is a random
experiment because whether the coin will go up (U) or down (D) is uncertain before we
make the observation, but once the closing price is published, the outcomes
are clear. The sample space is
\({\cal S}=\{UU, UD, DU, DD \}\). The event that the closing price at the end
of the first trading day will be higher is \(A = \{UU, UD\}\). The event that the
stock price does not decrease is \(B = \{UU\}\), which is also a
basic outcome of the random experiment.

While this example is so simple that we do not need a computer, let us take the opportunity to
introduce a new R function, which computes all possible combinations of objects.
Let us first create a virtual price move by listing the possible moves at day 1 and
day 2.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{day\_1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"U"}\NormalTok{, }\StringTok{"D"}\NormalTok{)}
\NormalTok{day\_2 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"U"}\NormalTok{, }\StringTok{"D"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

There are some new things here. Let us explain. First, while we used gray boxes to show you input
and output of code as it would appear if you interact on the console we use here a very convenient
feature in RStudio, which we will use from now on.

We compose these lecture notes in a document
format, which allows the mixing of text and code. Whenever we write a piece of R code, it is shown
in a gray box, as before but without the \texttt{\textgreater{}} prompt. When you move the cursor
on the gray box
now, you will see a copy icon in the upper right
corner of the box. This will allow you to copy this
code snippet and use it in another document or on your console to execute it.

The second new thing is that we have used a new data type, which we will
need very often: characters.
Characters can be used to form strings and R has many powerful functions to work with and operate
on strings. We will see many examples of this later.
Strings are always between \texttt{"\ "}, like this. Like
numbers, strings can be stored in objects and referred to later. But what we need here is actually
two strings in one vector. This is achieved by using the \texttt{c()} function of R.
c stands for concatenation
and here it stores both basic outcomes of a price move in two single vectors \texttt{day\_1} and \texttt{day\_2}.

We can now pass these two virtual oves to the R function \texttt{expand.grid()}.
This function will produce
the sample space of two price moves by computing all possible combinations of sequences of U and D
that can occur at the end of two trading days.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{expand.grid}\NormalTok{(day\_1, day\_2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Var1 Var2
## 1    U    U
## 2    D    U
## 3    U    D
## 4    D    D
\end{verbatim}

Don't worry at the moment if you do not understand what the output
format is and why the columns are
headed by \textbf{Var1} and \textbf{Var2} followed by the symbols \texttt{\textless{}fctr\textgreater{}}. We will come back to this.

Before we look at yet another sample, let us mention that this setup, simple as it may
seem, plays a very important role in the theory of random price
fluctuations of asset prices and in
option pricing and we will encounter it later in more detail.

\hypertarget{birthdays-and-the-blockchain}{%
\subsection{Birthdays and the Blockchain}\label{birthdays-and-the-blockchain}}

Suppose we are interested in the probability that at least two students in a class
of size \(n\) share the same birthday. This is a very famous probability problem which
is often referred to as the \emph{birthday paradox}. It is technically not really a
paradox but it is called like this because this probability behaves in a surprising
way if viewed as a function of the class size \(n\). We discuss the problem in the
context of computational finance because it has also an important application in
the design of crypto-currencies and the new field of decentralized Finance, which
make heavy use of cryptographic methods.

We will talk about actual probabilities in the next lecture. But in
this lecture we have learned that we can only talk meaningfully about probabilities if
we know the random experiment and the basic outcomes. One interesting aspect with respect to
the concepts of basic outcomes and sample space is that the birthday paradox example is
an instance where we cannot simply write down the sample space like in the example of
rolling a die.

The event we are interested in is that
\emph{at least two students in a randomly selected sample of \(n\) out of class have the same birthday}.
It turns out that it is easier to think about the complementary event, which is that
\emph{all students have different birthdays}.

In terms of possible basic outcomes there
are \(365^n\) possible outcomes if there are \(n\) students in the class. Each of
them can have a birthday at any of the 365 days in the year and in total there are
\(n\) students.

So the sample space \({\cal S}\) for the conceptual
random experiment that all \(n\) randomly selected students have different birthdays
is the set \({\cal S} =\{1,2,\ldots, 356^n\}\) of basic outcomes. For 10 students this would
be

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{365}\SpecialCharTok{\^{}}\DecValTok{10}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.1969e+25
\end{verbatim}

basic outcomes for all \(n\) students having different birthdays.

The birthday problem also plays an important role in cryptography, and its
concept of hash-functions.
Hash-functions play a key role in the implementation of Cryptocurrencies. Let us explain this
context and what it has to do with Crypto:

A \textbf{hash-function} maps a string of arbitrary but finite length to a fixed length string
of output. A
very frequently used hash-function in practice is the function SHA-256, which maps its input
to a string of 256 bits\footnote{A bit, short for binary digit, is defined as the most basic
  unit of data in telecommunications and computing. Each bit is represented
  by either a 1 or a 0}. So, you could for instance give the text of the bible as an
input to SHA-256 and it would map this into a 256-bit string, which functions like
a finger print of this text. This is a so
called \emph{one-way-function} meaning that it is easy to evaluate or compute but it is
practically impossible to learn from the value the initial argument by computing the inverse.

Hash-Functions are key pillars of modern cryptography, where they play a major role in message
authentication. This is because it is impossible to modify the input without significantly
changing the output. So in our previous example, if you only dropped one letter from the text
of the bible it would hash into a completely different value than the previous version which
still contained this letter and you would immediately see from
comparing the hash-values that something has changed.

The collision problem for hash-functions is formally equivalent to the birthday problem. The event
we are interested in is that \emph{at least two input strings hash-to the same value}. Again it
is easier to think about the complementary event that \emph{all inputs hash to a different value}.

If the range of the hash-function is \(M\) and the hash-function maps into a 256 bit string
then there are \(2^{256}\) basic outcomes. Since the hash-function maps a large string onto
a smaller string it is possible that there are two different strings \(x \neq y\) mapping
to the same value \(\text{hash}(x)=\text{hash}(y)\). This would be a problem for message
authentification because it would give the same ``fingerprint'' for two different strings. For
a cryptographically secure hash function it is therefore required that the probability of
such a collision should be small enough to exclude a collision in all practically
relevant circumstances. We will take up the eexample again in the next lecture.

\hypertarget{summary}{%
\section{Summary}\label{summary}}

These are the basic \textbf{probability concepts} we have covered in this lecture:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  A \textbf{random experiment}: A process leading to an uncertain outcome.
\item
  \textbf{State space}: The collection of all possible outcomes of a random experiment.
\item
  \textbf{Basic outcome}: A possible outcome of a random experiment.
\item
  \textbf{Event}: An event is a subset of basic outcomes. Any event which contains a single outcome is called a simple event.
\end{enumerate}

These are the \textbf{R concepts} we have covered in this lecture:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{objects} arbitrary names that can store different values and data types.
\item
  \textbf{functions} ab R object that can accept other R objects as arguments, operate on them and return a new object.
\item
  \textbf{scripts} files that store sequences of R commands and can be saved, repopened and allow the
  execution of commands.
\item
  \textbf{using packages}
\item
  \textbf{finding help}
\end{enumerate}

\hypertarget{project-1-rolling-two-dice-and-adding-the-points}{%
\section{Project 1: Rolling two dice and adding the points}\label{project-1-rolling-two-dice-and-adding-the-points}}

Here we formulate a project where you can apply the concepts we have learned in this lecture.
In this project we ask you to write an R function that virtually throws two dice and
adds up the number of points shown by the dice. Using this function do a simulation of this
random experiment. Install and load the \texttt{ggplot2} package to make a plot using the qplot function to
visualize the behavior of our dice. Are the dice fair?

\hypertarget{probability-basic-definitions-and-rules}{%
\chapter{Probability: Basic Definitions and Rules}\label{probability-basic-definitions-and-rules}}

\hypertarget{probability-in-theory-and-applications-of-probability}{%
\section{Probability in theory and applications of probability}\label{probability-in-theory-and-applications-of-probability}}

Now that we have introduced the concepts of a random experiment, sample space,
events and basic outcomes, we
can finally proceed to introduce the notion of \emph{probability}. From the preceding
lecture it should be
clear that we always speak of probability in relation to a given sample space or
a conceptual random
experiment.

In lecture 1 we said that \emph{probability} is a measure of how likely an event of an experiment is.
Probabilities are expressed as numbers. As observed in Feller (p.~19), these numbers are of the same
nature as distances in geometry. In the theory we assume they are given to us. We need not assume
anything about how they are measured. In actual applications, the determination of probabilities
or the application of the theory to observations requires often sophisticated statistical methods.
So, while the mathematical as well as the intuitive meaning of probability are clear only
as we proceed with the theory we will get a better ability to see how we can apply this concept.

\hypertarget{basic-rules-of-probability}{%
\section{Basic rules of probability}\label{basic-rules-of-probability}}

When we talk of probabilities in this lecture we mostly consider probabilities with relation
to a \emph{discrete} sample space. The simple sample spaces we considered in lecture 1 contain only a
finite number of points. Such sample spaces belong to the discrete sample spaces.

There are also more
complicated discrete sample spaces: Think of the random experiment of tossing a coin as often as
necessary to see Heads for the first time. We can begin writing down the basic outcomes as:
\(E_1=H, E_2=TH, E_3 = TTH, E_4 = TTTH, ...\). We may consider it possible that Head never appears. This
event we should perhaps call \(E_0\). In this case, when the basic events can be arranged into a simple sequence.
A sample space is called \emph{discrete} if it contains only finitely many points, or infinitely many
points which can be arranged into a simple sequence.

Not all sample spaces are discrete.
Except for the
technical tools required there is no essential difference between the two cases. In our discussion
of probability in this lecture we consider mostly discrete sample spaces.

Given a (discrete) sample space \({\cal S}\) the probabilities assigned to events in this sample
space must always fulfill three rules:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(P({\cal S}) = 1\), where \({\cal S}\) is the sample space.
\item
  For any event \(A \in {\cal S}\), \(0 \leq P(A) \leq 1\). The probability of an event can never be
  negative or larger than 1.
\item
  The probability of the union of two events \(A\) and \(B\) is always smaller or equal to the sum of the
  probability of these events looked at in isolation: \(P(A \cup B) \leq P(A) + P(B)\).
\end{enumerate}

In the theory of probability we use the language of sets and set theory to
describe relations among event.
We have used one of these relations in rule three, where we expressed the relation between two sets
as their union \(\cup\). It is useful in studying probability
to know a few of these set theoretic definitions.

Let's go through them and illustrate the concepts in the context of the
examples we have already developed
in lecture 1.

\begin{description}
\tightlist
\item[Union]
The \textbf{union of two events} \(A\) and \(B\) is the set that contains all events that are either in \(A\) or in \(B\)
or in both sets. Set union is written as \(A \cup B\).
\end{description}

Let us use the example of the experiment of rolling a die. The sample space \({\cal S}\) is
the set of all possible outcomes of rolling the dice \({\cal S}=\{1,2,3,4,5,6\}\). Assume one
event is that the outcome is 1, 2 or 3. In set notation, we would write \(A = \{1,2,3\}\). Let us
also assume that the second event is that the outcome is some even number, i.e.~2, 4, 6. Again
using set notation we would write \(B = \{2,4,6\}\). The event \(A \cup B\) is then the set of all
outcomes such that the outcome is in A or in B or in both or these sets. In such simple examples
it is sometimes helpful to depict the situation graphically.

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{figures/set_union} 

}

\caption{The meaning of set union}\label{fig:set-union}
\end{figure}

The sample space \({\cal S}\) is the gray set containing all possible outcomes of our
random experiment. Graphically the union of \(A\) and \(B\), \(A \cup B\) is a subset of
the sample space, the entire colored area.

By the way: R provides functions for
computing set operations. Let us use the occasion to show you briefly how to use these functions
in the context of this example: We define the sets \(A\) and \(B\) first using the assignment operator:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We compute the union by using the function \texttt{union()}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{union}\NormalTok{(A,B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1 2 3 4 6
\end{verbatim}

which gives us the result we have already derived graphically.

\begin{description}
\tightlist
\item[Intersection]
The \textbf{intersection of two events} is the set that contains all events that are both in \(A\) and in \(B\).
Set intersection is written as \(A \cap B\).
\end{description}

We can again illustrate this concept graphically

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{figures/set_intersection} 

}

\caption{The meaning of set intersection}\label{fig:set-intersection}
\end{figure}

The intersection of \(A\) and \(B\), \(A \cap B\) is the orange area containing the dice face with two
points. Indeed two is both in \(A\) and in \(B\), which is exactly the meaning of set intersection.

The R function for computing intersections is called \texttt{intersect()}. We call this function for
our example

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{intersect}\NormalTok{(A,B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2
\end{verbatim}

which gives us the result we have already derived graphically.

\begin{description}
\tightlist
\item[Complement]
The \textbf{complement} of an event \(A\) with respect to an event \(B\) is the set
of all elements that are in \(B\) but not in \(A\). Set difference is written as \(A \setminus B\).
\end{description}

Lets say we want to get the complement, or the set difference of \(A \cup B\) with respect to the
sample space \({\cal S}\). Let us show \({\cal S} \setminus (A \cup B)\).

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{figures/set_minus} 

}

\caption{The meaning of set intersection}\label{fig:set-minus}
\end{figure}

This complement is the dice shown in the light yellow area, i.e.~all the elements of \({\cal S}\)
which are not in \(A \cup B\).

The R function for computing set complements is called \texttt{setdiff()}. You can try it with our
example:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{S }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{6}\NormalTok{)}

\FunctionTok{setdiff}\NormalTok{(S, }\FunctionTok{union}\NormalTok{(A,B))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5
\end{verbatim}

which is 5, as expected.

\begin{description}
\tightlist
\item[Mutually Exclusive]
Two events \(A\) and \(B\) are said to be \textbf{mutually exclusive} if they have no
basic outcomes in common. The
notation is \(A \cap B = \emptyset\)
\end{description}

An example in our context is the set of even outcomes \(B=\{2,4,6\}\) and the set of
odd outcomes, let us call it \(C=\{1,3,5\}\). If we intersect these sets

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{6}\NormalTok{)}
\NormalTok{C }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{5}\NormalTok{)}

\FunctionTok{intersect}\NormalTok{(B,C)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## numeric(0)
\end{verbatim}

we get the empty set, which is expressed by R by giving the data type, in this
case numeric, because we are intersecting sets of numeric values, followed by (0). This means,
there is no numeric value in the intersection of \(B\) and \(C\).

Let us discuss probability rule 3 a bit further: Go to the picture we drew to
illustrate the meaning of set union \ref{fig:set-union}. To compute the probability \(P(A \cup B)\)
we have to add the probabilities of all sample points that are contained either in \(A\) or in \(B\)
but each point is to be counted only once. Therefore, probability rule 3, has a (weak)
inequality: \(P(A \cup B) \leq P(A) + P(B)\).

Now let \(E\) be a point contained both in \(A\) and in \(B\), in our example this would be \(E = \{2\}\),
then \(P(E)\) occurs twice on the right hand side of our inequality but only once on the left.
Therefor the right hand side exceeds the left by the amount \(P(A \cap B\)). Thus we have
\(P(A \cup B) = P(A) + P(B) - P(A \cap B)\).

This reasoning holds for arbitrary pairs of events and not only in our example. In the
case \(A\) and \(B\) are arbitrary events and \(A\) and \(B\) are mutually exclusive,
i.e.~\(A \cap B = \emptyset\) then our inequality in rule 3 becomes an equality and we have
\(P(A \cup B) = P(A) + P(B)\).

\hypertarget{interpretations-of-probability}{%
\section{Interpretations of Probability}\label{interpretations-of-probability}}

While rule 1 - 3 pins down three basic mathematical properties of probabilities, there is an
ongoing and still unsettled debate what probabilities actually mean. While in this course we
will be less concerned with this philosophical question, it is so important that you
should hear about
the basic interpretations at least once.

Probability theory took shape in the 17th century through discussions on the mathematics of
games of chance, such as poker or roulette or games where dice are rolled. In this
stage the \emph{classical} meaning of probability was the ratio of outcomes that satisfy a condition
or the description of an event divided by the total number of outcomes in the state space. Of
course this interpretation of probability makes the implicit assumption that all outcomes
have the same probability. For example, in this interpretation the probability that one role
of a dice will result in a \(6\) is \(1/6\). This interpretation is often called
\emph{classical probability}.

A more important interpretation is the interpretation of probability as \emph{relative frequency}.
In this interpretation the probability of an event \(A\) is interpreted as the number of times
the event \(A\) occurs in repeated trials divided by the total number of trials in a
random experiment.

A competing interpretation of probability is called \emph{subjective probability}. In this
interpretation probability is an opinion or a belief about how likely the occurence of
a particular event is.

\hypertarget{example-continued}{%
\section{Example continued}\label{example-continued}}

\hypertarget{the-stock-price-of-apple-1}{%
\subsection{The stock price of Apple}\label{the-stock-price-of-apple-1}}

Let us go back to our example with the stock price of Apple. In this example we had expressed
the state space as \({\cal S}=\{U, D\}\). It is however impossible to determine the probability
for each of these two elements. It is also not possible to determine the probability
for each price which is theoretically possible.

\hypertarget{tossing-a-fair-coin-twice}{%
\subsection{Tossing a fair coin twice}\label{tossing-a-fair-coin-twice}}

Assume we toss a fair coin twice and that the two possible outcomes
of this random experiment is that the coin comes up heads \(H\) or tails \(T\).
The state space of the random experiment of tossing a coin twice is
\({\cal S} = \{HH, HT, TH, TT\}\). We can now ask: What is the probability of getting H
after the first toss? Since the coin is assumed to be a fair coin each outcome of
the toss is equally likely. The probability of getting H after the first toss, must
therefore be \(1/2\). Now we could ask: What is the probability that we get H after the second
toss as well? If you think about the situation, you will see that the probability of
getting H in the second toss is completely unaffected by what happened after the first toss.
This probability is independent of the outcome of the first toss and since the coin is
a fair coin it is also equally likely to get H as it is to get T. The probability of getting
H after the first toss is therefore again \(1/2\).

Here we derived the equal probability postulate by an assumption, interpreting
the probability as a classical probability.

We could also give this postulate a frequency
interpretation using our knowledge of R.

We proceed by analogy to our approach of rolling a die. Let us
therefore create a virtual coin first.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{coin }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"H"}\NormalTok{, }\StringTok{"T"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

As in the case of the die we next write a function, so we can virtually toss the coin

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{toss\_coin }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{()\{coin }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"H"}\NormalTok{, }\StringTok{"T"}\NormalTok{)}
                        \FunctionTok{sample}\NormalTok{(coin, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) \}}
\end{Highlighting}
\end{Shaded}

Now lets toss this coin 100 times by using the \texttt{replicate} function and
save the result in an object called
tosses\_100:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tosses\_100 }\OtherTok{\textless{}{-}} \FunctionTok{replicate}\NormalTok{(}\DecValTok{100}\NormalTok{, }\FunctionTok{toss\_coin}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

Lets look at the outcome of the 100 tosses graphically

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qplot}\NormalTok{(tosses\_100)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Probability_Introduction_files/figure-latex/unnamed-chunk-21-1.pdf}
The histogram shows that the occurrence of Heads and Tails are almost 50/50 but not
exactly. Lets toss 1000 times and then look again.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tosses\_1000 }\OtherTok{\textless{}{-}} \FunctionTok{replicate}\NormalTok{(}\DecValTok{1000}\NormalTok{, }\FunctionTok{toss\_coin}\NormalTok{())}
\FunctionTok{qplot}\NormalTok{(tosses\_1000)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Probability_Introduction_files/figure-latex/unnamed-chunk-22-1.pdf}
This looks already pretty good. Lets toss even more. Why not toss a million of times?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tosses\_m }\OtherTok{\textless{}{-}} \FunctionTok{replicate}\NormalTok{(}\DecValTok{10}\SpecialCharTok{\^{}}\DecValTok{6}\NormalTok{, }\FunctionTok{toss\_coin}\NormalTok{())}
\FunctionTok{qplot}\NormalTok{(tosses\_m)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Probability_Introduction_files/figure-latex/unnamed-chunk-23-1.pdf}
Now you see the idea of the frequency interpretation. The number of occurrences of H divided
by the total number of tosses comes closer to the \(1/2\) probability as we toss many
times. We will come back to this idea again a bit later.

\hypertarget{boys-and-girls}{%
\subsection{Boys and Girls}\label{boys-and-girls}}

We have introduced the four child family before in lecture 1 and asked you to figure out the
state space of the random experiment how the sequences of boys and girls might result in this
four children outcome.

If you have correctly figured out the state space, you will surely be able to
tell which of the
following sequences is more likely i.e.~has the higher probability: \texttt{bbbb}, \texttt{bgbg} or
\texttt{gggg}?

Let's use the idea we considered first in coin tossing, and use the \texttt{expand.grid()} function
to figure out all combinations of boys and girls in a family of four kids. The outcome
of the sex of a baby at any of the four births is abstractly the same as a coin toss with
the possible outcomes: \texttt{b} or \texttt{g}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{birth\_1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"b"}\NormalTok{, }\StringTok{"g"}\NormalTok{)}
\NormalTok{birth\_2 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"b"}\NormalTok{, }\StringTok{"g"}\NormalTok{)}
\NormalTok{birth\_3 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"b"}\NormalTok{, }\StringTok{"g"}\NormalTok{)}
\NormalTok{birth\_4 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"b"}\NormalTok{, }\StringTok{"g"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now we can let R figure out all possible sequences of outcomes. We store the outcome in an
object called n and count the combinations using the R function \texttt{nrow()} which counts the
number of rows of a so called dataframe, a structure we discuss in detail in a minute.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \FunctionTok{expand.grid}\NormalTok{(birth\_1, birth\_2, birth\_3, birth\_4)}
\FunctionTok{nrow}\NormalTok{(n)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16
\end{verbatim}

There are 16 combinations in total. Applying the same reasoning as with the coin tossing
example, we see that the probability of each sequence should be equal to \(1/16\).

In reality
by the way births are slightly more likely for boys than girls. Gelman and Nolan report for
example the US numbers for the year 1981, where 1 769 000 girls were born, while there
were 1 860 000 boys: \(48.7 \%\) of births were thus girls.

Let us come to our last example,illustrating the interpretation of
probability as subjective probability.

\hypertarget{example-fintech-start-up}{%
\subsection{Example: FinTech Start Up}\label{example-fintech-start-up}}

Suppose you had a great idea for a path breaking FinTech innovation, which will disrupt
the banking landscape. To predict the success of this innovation in probabilistic terms
you could only use a subjective probability. There are no data you can rely on, since this
idea had not existed before. You can only rely on your experience and your belief in
your idea. There is no way you could use a classical or a relative frequency
interpretation of probability.

\hypertarget{independence}{%
\section{Independence}\label{independence}}

Let us go back to our fair die and ask another probability question about the
potential outcomes of rolling the die: What is the probability that a fair six sided die
will roll a 5 and then a 6?

Note that this is a question, slightly different from what
we have asked before. What we need to calculate is actually the probability of
the event that the dice shows first 5 and then 6, i.e.~we need to compute
\(P(5 \cap 6)\). We can multiply the individual probabilities because the subsequent rolls of
the die are independent:
\(P(5 \cap 6) = P(5) \cdot P(6) = \frac{1}{6} \cdot \frac{1}{6} = \frac{1}{36}\).

Indeed we have the following definition:

\begin{description}
\tightlist
\item[Independence]
Two events \(A\) and \(B\) are \textbf{independent} if an only if the probability of
both \(A\) and \(B\) occurring is the product of the probability of the two events
\(P(A \cap B) = P(A) \cdot P(B)\).
\end{description}

\hypertarget{example-the-apple-stock-price-again}{%
\subsection{Example: The Apple stock price again}\label{example-the-apple-stock-price-again}}

Let us go back to our Apple stock price data, we have used previously. We read the
data again from our data folder.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{apple\_stock }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"data/apple\_stock\_price.RDS"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Our data store price information about 150 trading days. During these dates, as you can
convince yourself, the price went up on 72 days and it went down on 77 days. It didn't
stay the same at any day. We get in total 149 counts because we need to drop one observation
to compute the changes in the price.

Now let us assume that the probability of a future up movement is \(P(U) = \frac{72}{149}\), which
is about \(0.48\) and the probability of a down movement is \(P(D) = \frac{77}{149}\), which is
about \(0.52\).

Now assume in addition that the performance of the Apple stock price on the current trading day is
independent of the performance of the Apple stock price on previous trading days. This means
that the probability of \(U\)-movements and of \(D\)-movements is unaffected by the number of
previous \(U\) and \(D\) movements. This is - of course - an assumption. You may think about
whether this assumption is reasonable.

Now let us consider a week from Monday to Friday:

\begin{itemize}
\tightlist
\item
  What is the probability that the price of
  Apple will increase on each of the consecutive days?
\end{itemize}

There are five trading days, so we need to compute
\(P(U \cap U \cap U \cap U \cap U \cap U)\). This is by our assumption of independence equal
to \(P(U) \cdot P(U) \cdot P(U) \cdot P(U) \cdot P(U)\). By our probability estimate from
relative frequency this amounts to \(0.48^5\), which amounts to \(0.025\).

\begin{itemize}
\tightlist
\item
  What is the probability that the stock price will decrease either on Monday, Tuesday, Wednesday, Thursday or Friday and will increase on the other four days?
\end{itemize}

The probability that the \(D\) movement happens, say on a Monday, is
\(P(D \cap U \cap U \cap U \cap U)\) or \(0.52*0.48^4\) which is \(0.028\).
We have in total five mutually exclusive scenarios:
\(P(D \cap U \cap U \cap U \cap U)\), \(P(U \cap D \cap U \cap U \cap U)\),
\(P(U \cap U \cap D \cap U \cap U)\), \(P(U \cap U \cap U \cap D \cap U)\),
\(P(U \cap U \cap U \cap U \cap D)\). Thus we have \(0.028 + 0.028 + 0.028 + 0.028 + 0.028\)
as the final probability of this event, which is \(0.14\).

\hypertarget{analyzing-the-stock-price-of-apple-more-r-concepts}{%
\section{Analyzing the stock price of Apple: More R concepts}\label{analyzing-the-stock-price-of-apple-more-r-concepts}}

By discussing some probability concepts within the context of stock price movements we looked
at the Apple stock price data. R gives us some powerful tools to work with such data
and they provide a very good example to teach you some more R concepts to enhance
our toolbox.

\hypertarget{loading-data}{%
\section{Loading Data}\label{loading-data}}

We loaded the apple stock price data from a file I had provided you in RDS format. This
is not the usual way you will load data into R. The most common case will be that you
get a plain text file, usually in a comma separated form or csv for short. In the data
directory we have a version of the Apple stock price file we already have already worked with
in csv format (\texttt{apple\_stock\_price.csv}). If you open this file in a text editor it
will look something like this:

\begin{verbatim}
symbol,date,open,high,low,close,volume,adjusted
AAPL,2021-01-04,133.520004,133.610001,126.760002,129.410004,143301900,128.804825
AAPL,2021-01-05,128.889999,131.740005,128.429993,131.009995,97664900,130.397324
AAPL,2021-01-06,127.720001,131.050003,126.379997,126.599998,155088000,126.007957
AAPL,2021-01-07,128.360001,131.630005,127.860001,130.919998,109578200,130.307755
AAPL,2021-01-08,132.429993,132.630005,130.229996,132.050003,105158200,131.432465
AAPL,2021-01-11,129.190002,130.169998,128.5,128.979996,100384500,128.376831
AAPL,2021-01-12,128.5,129.690002,126.860001,128.800003,91951100,128.197662 ... etc.
\end{verbatim}

Most languages used for data science applications can open plain text files and export data
as plain text files. This is why you so often find them. To load a plain text file into
R just click the \texttt{Import\ Dataset}icon in R Studios environment pane. Then select ``From
text file''. R-Studio will then ask you to select the file, you want to import. You can use the
wizard to tell RStudio what name to give to the data set (for example apple\_stock\_price).
You can also use the wizard to tell
RStudio which is the separation character used in your dataset and which character is
used to represent decimals (usually . in the US and , in Europe) and whether
the data set comes with a row of column names or a so called header. To help you, the wizard
shows you what the raw file looks like as well what your loaded data will look like based
on the input settings. I recommend to unclick the box ``Strings as factors'' in the wizard. This
will ensure that all character strings are loaded as characters (and not converted tp so called
factors). Once everything looks right, click Import. You can examine the data in
with the \texttt{head()} function.

Sometimes, for instance if you write a script, it is more convenient to use a direct command to
read a file. If the decimal sign is \texttt{.} (US convention) use \texttt{read.csv}, if it is \texttt{,} then use
\texttt{read.csv2()}. The syntax for this function, assuming that the file we want to read is in a
directory called data and is named \texttt{apple\_stock\_price.csv} is

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{apple\_stock\_price }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"data/apple\_stock\_price.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Please use the help functions to study the details of this function. It is quite powerful.
You can inspect the entire dataset using the \texttt{View()}function.
This command will open a View pane like shown in this picture, which you can use to inspect
all the data pretty much like in an excel sheet.

\begin{figure}

{\centering \includegraphics[width=0.9\linewidth]{figures/view} 

}

\caption{The result of calling the View() function}\label{fig:unnamed-chunk-28}
\end{figure}

There are many more possibilities to import data into R from many other formats, which we will
not discuss here. The principle is basically always the same and we refer you to the help menus
for further details.

\hypertarget{saving-data}{%
\section{Saving Data}\label{saving-data}}

Data can be saved by using the \texttt{write.csv()} function. It allows you to export data as a
comma separated text file. (There are many more export or saving options we do not discuss here).
If we would like to save the apple\_stock\_price object we have just assigned to a csv file we
would write

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{write.csv}\NormalTok{(apple\_stock\_price, }\AttributeTok{file =} \StringTok{"data/prices.csv"}\NormalTok{, }\AttributeTok{row.names =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Wit this command R turns the R-object \texttt{apple\_stock\_price} into a csv file with the name
\texttt{prices.csv} and stores it in a subdirectory called data. There are many possible
arguments you can set with \texttt{write.csv()} (see ?write.csv for details) but there are three
you should always use: First you should give \texttt{write.csv()} the name of the object you want to
save. Then you should give a name (if necessary with a path) to the object. Make sure to give
the full name with extension. Finally you should set the argument \texttt{row.names\ =\ FALSE}. It prevents
R from adding an extra column with a counting index for the rows. It is unlikely that another
program which reads the data will interpret the row name system correctly.

\hypertarget{atomic-vectors}{%
\section{Atomic vectors}\label{atomic-vectors}}

An atomic vector is just a simple vector of data, like the die we have already constructed

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{die }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{)}
\NormalTok{die}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1 2 3 4 5 6
\end{verbatim}

We can use R to check whether \texttt{die}is a vector

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{is.vector}\NormalTok{(die)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

An atomic vector can have only 1 value also. Each atomic vector stores values as
a one-dimensional vector and can only store one type of data. Different types
of data can be saved by different types of atomic vectors. R recognizes
altogether six basic types of atomic vectors: doubles, integers, characters,
logical, complex and raw.´

\hypertarget{doubles}{%
\subsection{Doubles}\label{doubles}}

A double vector stores regular numbers. In our data these are the columns open, high, low,
close, volume and adjusted. In general R will save any number you type as a double. Doubles can
be positive negative, large or small and can have digits or not. Ususally it is obvious
what type of object you are working with but you can check also.

Let us create a new object close by selecting the column lose`from apple\_stock\_price. In R
this is done by typing:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{close }\OtherTok{\textless{}{-}}\NormalTok{ apple\_stock\_price}\SpecialCharTok{$}\NormalTok{close}
\end{Highlighting}
\end{Shaded}

We use the symbol \texttt{\$} followed by the name of the column we want to select and assign the
selected column to an object called \texttt{close}. Now check the type by invoking the \texttt{typeof()}function:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{typeof}\NormalTok{(close)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "double"
\end{verbatim}

\hypertarget{integers}{%
\subsection{Integers}\label{integers}}

Integer vectors store numbers that can be written without commas. We will not need them
very often in probability and finance, because you can save integers also as doubles.

Integers can be specifically created in R by typing the number followed by an upper case L.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{int }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{1L, 2L, 4L)}
\NormalTok{int}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1  2  4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{typeof}\NormalTok{(int)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "integer"
\end{verbatim}

\hypertarget{characters}{%
\subsection{Characters}\label{characters}}

A character vector stores small pieces of text. For instance the stock symbol is
such a character. Lets select the symbol column and check:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{symb }\OtherTok{\textless{}{-}}\NormalTok{ apple\_stock\_price}\SpecialCharTok{$}\NormalTok{symbol}
\FunctionTok{typeof}\NormalTok{(symb)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "character"
\end{verbatim}

The individual elements of a character vector are called strings. A string can contain more than
just one letter. Character strings can be assembled from numbers and symbols as well. We
have encountered characters in some of our examples already before.

It is easy to confude R objects with character strings and you have to be careful to avoid that.
For example \texttt{symb} is the name of an R object names symb, while ``symb'' in quotations is a string
containing the characzers symb. If you forget the quotation marks R will look for an object which
probably won't exist.

\hypertarget{logicals}{%
\subsection{Logicals}\label{logicals}}

Locial vectors store TRUE and FALSE, Rs form of boolean values. Logicals are very helpful
for comparisons. Assume we are interested how many closing prices are smaller than 124.
We have already created an object \texttt{close}. So we would type

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{close }\SpecialCharTok{\textless{}} \DecValTok{124}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [37]  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [49]  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [61]  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [73] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
##  [85] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
##  [97] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE
## [109] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [133] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [145] FALSE FALSE FALSE FALSE FALSE FALSE
\end{verbatim}

\hypertarget{coercion}{%
\subsection{Coercion}\label{coercion}}

R implements a coercion system for types which always follows the same rules. Once you
are familiar with these rules you will find them very useful.

How does R coerce data types? If a character string is present in an atomic vector,
R coerces every element in this vector to character strings. If the vector contains
logicals and numbers every TRUE becomes a 1 and every FALSE becomes a 0. The same coercion
rules are used when you try to do math with logicals

This is very convenient. Say we want to count the instances when
the closing price of Apple stock was smaller than 124, i.e.~when the logical is TRUE.
We can use the \texttt{sum()}function
for that because R will treat each TRUE as a 1 and FALSE as a 0 when used with an algebraic
operation.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(close }\SpecialCharTok{\textless{}} \DecValTok{124}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 24
\end{verbatim}

We count exactly 24 days when this was true in our sample. As a consequence of this cool
feature we can compute the porportion of days in our sample when the stock price of Apple
was below 124 as

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(close }\SpecialCharTok{\textless{}} \DecValTok{124}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.16
\end{verbatim}

\hypertarget{complex-and-raw}{%
\subsection{Complex and Raw}\label{complex-and-raw}}

These data types are much less common than the ones we discussed before. They
store complex numbers and raw bytes of data. At the moment we will not say much more
about these two types.

\hypertarget{lists}{%
\section{Lists}\label{lists}}

Lists are like atomic vectors because they group data into a one-dimensional set. However
lists do not group individual values but they group R objects, such as different
atomic vectors or other lists. For example, you can make a list that contains
a numeric vector of length 31 in the first element, a character vector of length 1 in its second
and a new list with length 2 in its third. This is done by using the \texttt{list()}function:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test\_list }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}\DecValTok{100}\SpecialCharTok{:}\DecValTok{130}\NormalTok{, }\StringTok{"R"}\NormalTok{, }\FunctionTok{list}\NormalTok{(}\ConstantTok{TRUE}\NormalTok{, }\ConstantTok{FALSE}\NormalTok{))}
\NormalTok{test\_list}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [[1]]
##  [1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
## [20] 119 120 121 122 123 124 125 126 127 128 129 130
## 
## [[2]]
## [1] "R"
## 
## [[3]]
## [[3]][[1]]
## [1] TRUE
## 
## [[3]][[2]]
## [1] FALSE
\end{verbatim}

\texttt{list} creates a list in the same way as \texttt{c} creates a vector. Seperate every element in the
list by a comma.

The double-bracketed indexes tell you which element of the list is beeing displayed. The single
bracketd indexes tell you which subelement of an element is beeing displayed.

\hypertarget{data-frames}{%
\section{Data Frames}\label{data-frames}}

Data frames are the two-dimensional versions of a list. They are by far the most
frequent data structure we will use. For example the apple\_stock\_price object
we have created by reading the csv datafile is a data frame. Think of a data frame
as something like an Excel spreadsheet.

Data frames group vectors together into a two dimensional table. Each vector becomes a column
of this table. As a result each column can contain different types of data. The symbol
column contains characters, the close column contains doubles for example.

\hypertarget{project-2-analyzing-stock-price-changes}{%
\section{Project 2: Analyzing stock price changes}\label{project-2-analyzing-stock-price-changes}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Load the data for the netflix stock price.
\item
  Estimate the probability that the netflix stock
  price will rise from the share of daily up moves in the total trading days.
\item
  Estimate the
  probability that the stock price will fall in a similar way.
\item
  Assuming independence what is
  the probability that the price will rise from Monday to Wednesday and than fall on
  Thursday and Friday?
\end{enumerate}

\hypertarget{conditional-probability}{%
\chapter{Conditional Probability}\label{conditional-probability}}

\hypertarget{introdcution}{%
\section{Introdcution}\label{introdcution}}

We begin this chapter with a definition and an example. Here is the definition:

\begin{description}
\tightlist
\item[Contingency Table]
A contingency table shows counts of cases on one categorical variable contingent
on the value of another for every combination of both variables.
\end{description}

Contingency tables are useful for calculating \textbf{conditional probabilities} as they
contain all the necessary ingredients for the computation. The concept of
conditional probability will be the main contents of this lecture.

Let us start with an example of a contingency table, which will allow us to repeat at the
same time some R concepts. In our data directory I have stored
the daily prices of the Standard \& Poors 500 stock price index and the daily prices
of four stocks, Google, Amazon, Facebook and Apple beginning from January 1st 2015.
Now we would like to construct
a contingency table from these data to think about how these individual stocks
move with the overall index. Let us start with Google and you can then do the others
yourself.

First of all let us load the data for the index and write them into a variable called SP500

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SP500 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"data/sp500.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We next read the prices of the four individual stocks which are stored in
one file and write them into the variable \texttt{stock\_data}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stock\_data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"data/stock\_prices.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

For the contingency table we would like to count the number of days when the
S\&P was moving up from one day to the next and how often it was moving down. We would
like to do the same with the Google (Amazon, Facebook, Apple) stock price.

One way to see whether the price moved up or down from one day to the next is to
compute the daily price differences in the closing price. When this difference is
positive the price made an up movement, when it is negative, it made a down movement (it
could theoretically also not change at all).

There are many ways to implement such a computation in R. An efficient way to do sp one is to use
one of R's internal functions \texttt{diff()}. It implements a method for
computing differences in time series. Consider the following example: Say we have
a vector of values like

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{val }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{9}\NormalTok{,}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

and we apply the \texttt{diff()}function we will get

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{diff}\NormalTok{(val)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  2  3 -6  8  1
\end{verbatim}

Now, of course by taking differences between 4 and 2, 7 and 4, 1 and 7, 9 and 1, ans 10 and 9 we
have to drop the first observation and get a vector which is shorter than val by one component.
We can
produce a vector of equal length if we add as the first component the value NA, which is
R's symbol of ``not available'' or of a missing value. Indeed this makes sense because for the
first date if you want we have no value for the change (since we cut off there and don't know
the value from the day before).

Now let us apply this reasoning to the Standard and Poors 500: The data of the index are in a
dataframe, which is a special case of a list. We can add a column by the \$ symbol. This
symbol will append a new column with the name we write after \$. Let us call this new
column ``changes'' and compute the changes in the closing price by the \texttt{diff()}function.
Now, since we loose the first value here by taking the first difference, let us
replace it by NA and from a new column of price differecnes with the first observation
replace by NA. Thus we type:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SP500}\SpecialCharTok{$}\NormalTok{changes }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\ConstantTok{NA}\NormalTok{, }\FunctionTok{diff}\NormalTok{(SP500}\SpecialCharTok{$}\NormalTok{close))}
\end{Highlighting}
\end{Shaded}

Lets do the same for the Google stock price. If you inspect the data by using the \texttt{View()} function
you will see that the price series of our different stocks
are stacked upon each other. How can we filter just the
Google Price? Here we can make use of Rs system of selecting values from lists (since the
stock prices are a dataframe, a special list). We type:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{google }\OtherTok{\textless{}{-}}\NormalTok{ stock\_data[stock\_data}\SpecialCharTok{$}\NormalTok{symbol }\SpecialCharTok{==} \StringTok{"GOOGL"}\NormalTok{, ]}
\end{Highlighting}
\end{Shaded}

Let us explain: We can filter the rows which have the symbol ``GOOGL'' by telling R to select
the rows - rows are the first entries in stock\_data{[}rows,columns{]} after the {[} bracket.
For example, if we would type

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stock\_data[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    symbol       date   open   high    low  close
## 1   GOOGL 2015-01-02 532.60 535.80 527.88 529.55
## 2   GOOGL 2015-01-05 527.15 527.99 517.75 519.46
## 3   GOOGL 2015-01-06 520.50 521.21 505.55 506.64
## 4   GOOGL 2015-01-07 510.95 511.49 503.65 505.15
## 5   GOOGL 2015-01-08 501.51 507.50 495.02 506.91
## 6   GOOGL 2015-01-09 508.18 508.60 498.65 500.72
## 7   GOOGL 2015-01-12 499.24 500.28 490.91 497.06
## 8   GOOGL 2015-01-13 502.57 508.60 497.26 501.80
## 9   GOOGL 2015-01-14 500.42 508.26 498.16 505.93
## 10  GOOGL 2015-01-15 508.89 509.75 502.01 504.01
\end{verbatim}

we get row 1 to 10 and column 1 to 6. Now this syntax can also be used by
specifying conditions. The
condition we use is that the values of the rows we look for are all rows, where
the value of the column stock\_data\$symbol is equal to the string ``GOOGL'' and other than this
we select all columns. To express this equality we need the symbol \texttt{==} (and not \texttt{=} which
works as an assignment operator in R, similar to \texttt{\textless{}-}).

This is expressed as:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{google }\OtherTok{\textless{}{-}}\NormalTok{ stock\_data[stock\_data}\SpecialCharTok{$}\NormalTok{symbol }\SpecialCharTok{==} \StringTok{"GOOGL"}\NormalTok{, ]}
\end{Highlighting}
\end{Shaded}

Now as before with the Standard and Poors 500 Index we can add a column recording the changes
in the closing price

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{google}\SpecialCharTok{$}\NormalTok{changes }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\ConstantTok{NA}\NormalTok{, }\FunctionTok{diff}\NormalTok{(google}\SpecialCharTok{$}\NormalTok{close))}
\end{Highlighting}
\end{Shaded}

Now we add two new columns to the SP500 dataframe, by assigning a logical operation. Whenever
the price movment went up the first difference will be positive. R checks this condition for
every row and writes TRUE if the condition is fulfills and FALSE otherwise. An analogous
operation can be done for the up movements of Google's stock price.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SP500}\SpecialCharTok{$}\NormalTok{Up }\OtherTok{\textless{}{-}}\NormalTok{ SP500}\SpecialCharTok{$}\NormalTok{changes }\SpecialCharTok{\textgreater{}} \DecValTok{0}
\NormalTok{google}\SpecialCharTok{$}\NormalTok{Up }\OtherTok{\textless{}{-}}\NormalTok{ google}\SpecialCharTok{$}\NormalTok{changes }\SpecialCharTok{\textgreater{}} \DecValTok{0}
\end{Highlighting}
\end{Shaded}

We can now compute a contingency table of both movements. R has a function, called \texttt{table()}
which does this job.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(SP500}\SpecialCharTok{$}\NormalTok{Up, google}\SpecialCharTok{$}\NormalTok{Up)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        
##         FALSE TRUE
##   FALSE   556  218
##   TRUE    223  702
\end{verbatim}

The contingency table shows counts of Up and Down movements of the Stadard and Poors index closing
price and the price of Google. In all the 1699 observations, there are 556 days when
the Index moves down and the Price of Google also moves down. There are only 218 days when the
Index moves down but Google moves in the other direction Up. There are even more days when
the Index and the Google stock price move up together. Using a relative frequency interpretation
of probability we can transform these counts into probabilities by dividing the number by the
number of total observations 1699. Let's do this:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(SP500}\SpecialCharTok{$}\NormalTok{Up, google}\SpecialCharTok{$}\NormalTok{Up)}\SpecialCharTok{/}\DecValTok{1699}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        
##             FALSE      TRUE
##   FALSE 0.3272513 0.1283108
##   TRUE  0.1312537 0.4131842
\end{verbatim}

These are the probabilities of joint moves or cross moves.

\hypertarget{marginal-joint-and-conditional-probability}{%
\section{Marginal, joint and conditional probability}\label{marginal-joint-and-conditional-probability}}

Marginal probabilty
:The \textbf{marginal probability} is the unconditional probability on an event. This
probability is not conditioned on any other event. In terms of notation, we
denote the marginal probabilities of two arbitrary events \(A\) and \(B\) by
\(P(A)\) and \(P(B)\) respectively.

\begin{description}
\tightlist
\item[Joint probability]
The \textbf{joint probability} is the probability of simultaneous events. This is
the probability of the intersection of two or more events. If \(A\) and \(B\) are
arbitrary events, we write \(P(A \cap B)\).
\item[Conditional probability]
The \textbf{conditional probability} is the probability of an event \emph{given} that some other
event has occurred. The information from the event that has occured can influence
the probability of the original event. The following notation is used for
conditional probabilities: For two events \(A\) and \(B\), the conditional probability of
\(A\) given \(B\) is denoted by \(P(A\,|\,B)\) and the conditional probability of \(B\) given
\(A\) is denoted as \(P(B\, |\, A)\). In general these two conditional probabilities are
not the same.
\end{description}

The probability table of joint moves, we have computed before can help us to illustrate
these concepts and state a formula for the conditional probability.

\begin{longtable}[]{@{}lccr@{}}
\toprule
& Google-Down & Google-Up & Total \\
\midrule
\endhead
SP500-Down & 0.33 & 0.13 & 0.46 \\
SP500-Up & 0.13 & 0.41 & 0.54 \\
Total & 0.46 & 0.54 & 1.00 \\
\bottomrule
\end{longtable}

The \textbf{marginal probability} that the SP500 will make an Up move is
\(P(\text{SP500-Up} \cap \text{Google-Down}) + P(\text{SP500-Up} \cap \text{Google-up}) = P(\text{SP500-Up})\), which is 0.54, given our table. It is the sum
of the two \textbf{joint probabilities} \(P(\text{SP500-Up} \cap \text{Google-Down})\) and
\(P(\text{SP500-Up} \cap \text{Google-Up})\). To compute the conditional probability
that the stock price of Google will make an up move given that the SP500 makes an
up move we have to compute \(P(\text{Google-Up} | \text{SP500-Up})\). The probability
that the Google price went up and the SP500 went up is \(P(\text{Google-up} \cap \text{SP500-Up})\).
But given I already know that by the condition SP500 went up, I am in the second line of
my table and we know that the first line, SP500 went down - is ruled out by the
condition. We thus have now a \emph{new sample space} and we must
adjust the probabilities proportionally
to be consistent with the rules of probability. We therefore have to divide by
\(P(\text{SP500-Up})\) to get the formula
\(P(\text{Google-Up} | \text{SP500-Up}) = \frac{P(\text{Google-up} \cap \text{SP500-Up})}{P(\text{SP500-Up})}\) which is \(0.41/0.54\) or \(0.76\).
To check whether we have made the correct renormalisation you can ask yourself: Given the
rules of probability, what is \(P(\text{Google-Down} | \text{SP500-Up}))\) ? It should be
\(1 - 0.76\) or 0.24. Applying the formula for conditional probability we would compute
\(0.13/0.54\) which is indeed 0.24.

Another way to think about this formula can perhaps help to foster our intuition if we
look at this problem through the frequency interpretation of probability:

We would like to
find the conditional probability that Google makes an Up move given that
SP500 makes an up move. Suppose the daily price moves are a conceptual
random experiment with the outcomes that the
price can either move up or down and we have two prices SP500 and Google, so our
sample space has four possible outcomes:
\({\cal S} = \{ UU, UD, DU, DD \}\) where the first character if it is U means SP500-Up
and the second if it is U means Google-Up and so on for all possible combinations.
We repeat this
experiment 1699 times and keep a notebook where at every repetition we write down the
number of the experiment, the outcome and then we note whether both Google and the SP500
went up.

\begin{longtable}[]{@{}ccc@{}}
\toprule
notebook line & outcome & SP500-Up and Google-Up ? \\
\midrule
\endhead
1 & SP500-Up, Google-Down & No \\
2 & SP500-Down, Google-Up & No \\
3 & SP500-Up, Google-Up & Yes \\
. & . & . \\
. & . & . \\
. & . & . \\
1699 & SP500-Up, Google-Up & Yes \\
\bottomrule
\end{longtable}

To get the conditional probability of a Google-Up given an SP500-Up we have to count
the Google-Ups \textbf{among the notebook lines} where the SP500 has an Up move and divide by
the number of these SP500-Up lines.

Let's do this in R. To create the notebook we make a dataframe where one column is the Up column
of the SP500 data and the second columns is the Up column of the Google data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{joint\_ups }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{SP500Up =}\NormalTok{ SP500}\SpecialCharTok{$}\NormalTok{Up, }\AttributeTok{GoogleUp =}\NormalTok{ google}\SpecialCharTok{$}\NormalTok{Up)}
\end{Highlighting}
\end{Shaded}

Now we apply what we h ave already learned about referencing values in a dataframe in R to
select all the number in our fictitious notebook where the SP500 moves Up:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{joint\_ups[joint\_ups}\SpecialCharTok{$}\NormalTok{SP500Up }\SpecialCharTok{==} \ConstantTok{TRUE}\NormalTok{, ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      SP500Up GoogleUp
## NA        NA       NA
## 4       TRUE    FALSE
## 5       TRUE     TRUE
## 11      TRUE     TRUE
## 12      TRUE    FALSE
## 13      TRUE     TRUE
## 14      TRUE     TRUE
## 16      TRUE    FALSE
## 19      TRUE     TRUE
## 21      TRUE    FALSE
## 22      TRUE     TRUE
## 24      TRUE     TRUE
## 27      TRUE     TRUE
## 29      TRUE     TRUE
## 30      TRUE     TRUE
## 31      TRUE    FALSE
## 34      TRUE    FALSE
## 36      TRUE     TRUE
## 40      TRUE     TRUE
## 43      TRUE     TRUE
## 45      TRUE     TRUE
## 48      TRUE     TRUE
## 50      TRUE     TRUE
## 52      TRUE     TRUE
## 54      TRUE     TRUE
## 59      TRUE    FALSE
## 60      TRUE     TRUE
## 63      TRUE    FALSE
## 64      TRUE     TRUE
## 66      TRUE     TRUE
## 67      TRUE    FALSE
## 68      TRUE     TRUE
## 70      TRUE    FALSE
## 71      TRUE     TRUE
## 74      TRUE     TRUE
## 76      TRUE     TRUE
## 77      TRUE     TRUE
## 78      TRUE     TRUE
## 80      TRUE    FALSE
## 83      TRUE     TRUE
## 84      TRUE     TRUE
## 87      TRUE     TRUE
## 88      TRUE     TRUE
## 92      TRUE     TRUE
## 93      TRUE    FALSE
## 94      TRUE     TRUE
## 97      TRUE     TRUE
## 100     TRUE     TRUE
## 103     TRUE     TRUE
## 105     TRUE     TRUE
## 109     TRUE    FALSE
## 110     TRUE     TRUE
## 111     TRUE    FALSE
## 114     TRUE     TRUE
## 115     TRUE     TRUE
## 116     TRUE     TRUE
## 118     TRUE     TRUE
## 119     TRUE     TRUE
## 124     TRUE    FALSE
## 125     TRUE     TRUE
## 128     TRUE     TRUE
## 130     TRUE     TRUE
## 131     TRUE     TRUE
## 132     TRUE     TRUE
## 133     TRUE     TRUE
## 135     TRUE     TRUE
## 136     TRUE     TRUE
## 137     TRUE    FALSE
## 143     TRUE     TRUE
## 144     TRUE     TRUE
## 145     TRUE     TRUE
## 149     TRUE     TRUE
## 152     TRUE    FALSE
## 154     TRUE     TRUE
## 156     TRUE     TRUE
## 157     TRUE     TRUE
## 164     TRUE     TRUE
## 165     TRUE     TRUE
## 166     TRUE    FALSE
## 169     TRUE     TRUE
## 170     TRUE    FALSE
## 172     TRUE     TRUE
## 174     TRUE     TRUE
## 175     TRUE     TRUE
## 177     TRUE     TRUE
## 178     TRUE     TRUE
## 181     TRUE     TRUE
## 187     TRUE    FALSE
## 188     TRUE     TRUE
## 189     TRUE     TRUE
## 190     TRUE     TRUE
## 191     TRUE     TRUE
## 193     TRUE    FALSE
## 194     TRUE    FALSE
## 195     TRUE     TRUE
## 196     TRUE     TRUE
## 199     TRUE     TRUE
## 200     TRUE     TRUE
## 201     TRUE     TRUE
## 204     TRUE     TRUE
## 205     TRUE     TRUE
## 208     TRUE     TRUE
## 211     TRUE     TRUE
## 212     TRUE     TRUE
## 217     TRUE     TRUE
## 221     TRUE     TRUE
## 223     TRUE     TRUE
## 225     TRUE     TRUE
## 227     TRUE    FALSE
## 229     TRUE     TRUE
## 231     TRUE     TRUE
## 234     TRUE     TRUE
## 238     TRUE    FALSE
## 240     TRUE     TRUE
## 241     TRUE    FALSE
## 242     TRUE     TRUE
## 245     TRUE     TRUE
## 246     TRUE     TRUE
## 247     TRUE     TRUE
## 250     TRUE     TRUE
## 254     TRUE     TRUE
## 258     TRUE     TRUE
## 259     TRUE     TRUE
## 261     TRUE     TRUE
## 263     TRUE     TRUE
## 265     TRUE     TRUE
## 266     TRUE     TRUE
## 268     TRUE     TRUE
## 270     TRUE     TRUE
## 271     TRUE     TRUE
## 274     TRUE    FALSE
## 275     TRUE    FALSE
## 281     TRUE     TRUE
## 282     TRUE     TRUE
## 283     TRUE     TRUE
## 286     TRUE     TRUE
## 288     TRUE     TRUE
## 289     TRUE     TRUE
## 292     TRUE     TRUE
## 293     TRUE    FALSE
## 294     TRUE    FALSE
## 295     TRUE    FALSE
## 296     TRUE    FALSE
## 298     TRUE     TRUE
## 299     TRUE     TRUE
## 300     TRUE     TRUE
## 303     TRUE     TRUE
## 304     TRUE     TRUE
## 305     TRUE    FALSE
## 306     TRUE     TRUE
## 310     TRUE    FALSE
## 311     TRUE     TRUE
## 312     TRUE     TRUE
## 314     TRUE     TRUE
## 317     TRUE     TRUE
## 319     TRUE    FALSE
## 321     TRUE     TRUE
## 322     TRUE     TRUE
## 323     TRUE     TRUE
## 325     TRUE     TRUE
## 326     TRUE    FALSE
## 327     TRUE    FALSE
## 329     TRUE    FALSE
## 331     TRUE    FALSE
## 332     TRUE    FALSE
## 335     TRUE     TRUE
## 339     TRUE     TRUE
## 340     TRUE     TRUE
## 341     TRUE     TRUE
## 345     TRUE     TRUE
## 347     TRUE     TRUE
## 349     TRUE     TRUE
## 351     TRUE     TRUE
## 352     TRUE     TRUE
## 354     TRUE     TRUE
## 356     TRUE    FALSE
## 357     TRUE    FALSE
## 359     TRUE    FALSE
## 360     TRUE     TRUE
## 361     TRUE     TRUE
## 367     TRUE    FALSE
## 369     TRUE     TRUE
## 370     TRUE     TRUE
## 372     TRUE     TRUE
## 375     TRUE     TRUE
## 376     TRUE     TRUE
## 377     TRUE     TRUE
## 378     TRUE     TRUE
## 380     TRUE     TRUE
## 382     TRUE     TRUE
## 383     TRUE     TRUE
## 384     TRUE     TRUE
## 385     TRUE    FALSE
## 386     TRUE     TRUE
## 388     TRUE     TRUE
## 390     TRUE     TRUE
## 392     TRUE     TRUE
## 394     TRUE     TRUE
## 396     TRUE     TRUE
## 397     TRUE     TRUE
## 400     TRUE    FALSE
## 401     TRUE    FALSE
## 402     TRUE     TRUE
## 404     TRUE     TRUE
## 406     TRUE    FALSE
## 408     TRUE    FALSE
## 410     TRUE     TRUE
## 411     TRUE    FALSE
## 414     TRUE    FALSE
## 418     TRUE     TRUE
## 422     TRUE     TRUE
## 423     TRUE     TRUE
## 427     TRUE     TRUE
## 430     TRUE     TRUE
## 433     TRUE     TRUE
## 434     TRUE     TRUE
## 435     TRUE     TRUE
## 438     TRUE     TRUE
## 439     TRUE    FALSE
## 441     TRUE     TRUE
## 444     TRUE    FALSE
## 445     TRUE     TRUE
## 447     TRUE     TRUE
## 449     TRUE     TRUE
## 451     TRUE     TRUE
## 453     TRUE     TRUE
## 454     TRUE     TRUE
## 457     TRUE     TRUE
## 467     TRUE     TRUE
## 468     TRUE     TRUE
## 469     TRUE    FALSE
## 470     TRUE    FALSE
## 473     TRUE     TRUE
## 475     TRUE     TRUE
## 477     TRUE     TRUE
## 478     TRUE     TRUE
## 479     TRUE    FALSE
## 480     TRUE     TRUE
## 482     TRUE     TRUE
## 485     TRUE     TRUE
## 486     TRUE     TRUE
## 487     TRUE    FALSE
## 488     TRUE     TRUE
## 489     TRUE     TRUE
## 490     TRUE     TRUE
## 492     TRUE     TRUE
## 494     TRUE    FALSE
## 496     TRUE     TRUE
## 497     TRUE     TRUE
## 500     TRUE    FALSE
## 501     TRUE     TRUE
## 505     TRUE     TRUE
## 506     TRUE    FALSE
## 508     TRUE     TRUE
## 511     TRUE     TRUE
## 513     TRUE     TRUE
## 515     TRUE     TRUE
## 517     TRUE     TRUE
## 519     TRUE     TRUE
## 520     TRUE     TRUE
## 525     TRUE    FALSE
## 526     TRUE     TRUE
## 527     TRUE     TRUE
## 529     TRUE     TRUE
## 530     TRUE     TRUE
## 531     TRUE     TRUE
## 532     TRUE     TRUE
## 533     TRUE     TRUE
## 534     TRUE     TRUE
## 535     TRUE    FALSE
## 537     TRUE     TRUE
## 538     TRUE     TRUE
## 540     TRUE    FALSE
## 541     TRUE    FALSE
## 542     TRUE     TRUE
## 544     TRUE     TRUE
## 546     TRUE    FALSE
## 550     TRUE     TRUE
## 551     TRUE     TRUE
## 552     TRUE     TRUE
## 554     TRUE     TRUE
## 559     TRUE    FALSE
## 563     TRUE     TRUE
## 564     TRUE     TRUE
## 565     TRUE    FALSE
## 568     TRUE    FALSE
## 570     TRUE    FALSE
## 572     TRUE    FALSE
## 576     TRUE     TRUE
## 579     TRUE     TRUE
## 581     TRUE     TRUE
## 582     TRUE     TRUE
## 584     TRUE     TRUE
## 586     TRUE     TRUE
## 587     TRUE     TRUE
## 589     TRUE     TRUE
## 590     TRUE    FALSE
## 591     TRUE     TRUE
## 593     TRUE    FALSE
## 596     TRUE     TRUE
## 599     TRUE     TRUE
## 600     TRUE     TRUE
## 601     TRUE     TRUE
## 602     TRUE     TRUE
## 603     TRUE     TRUE
## 604     TRUE     TRUE
## 605     TRUE     TRUE
## 608     TRUE     TRUE
## 609     TRUE     TRUE
## 612     TRUE     TRUE
## 613     TRUE     TRUE
## 616     TRUE     TRUE
## 619     TRUE    FALSE
## 620     TRUE     TRUE
## 624     TRUE     TRUE
## 625     TRUE    FALSE
## 627     TRUE     TRUE
## 629     TRUE    FALSE
## 630     TRUE    FALSE
## 631     TRUE     TRUE
## 633     TRUE     TRUE
## 634     TRUE     TRUE
## 636     TRUE     TRUE
## 637     TRUE     TRUE
## 638     TRUE     TRUE
## 640     TRUE     TRUE
## 641     TRUE     TRUE
## 645     TRUE    FALSE
## 646     TRUE    FALSE
## 650     TRUE     TRUE
## 651     TRUE     TRUE
## 653     TRUE     TRUE
## 654     TRUE    FALSE
## 658     TRUE     TRUE
## 659     TRUE     TRUE
## 661     TRUE     TRUE
## 664     TRUE    FALSE
## 665     TRUE     TRUE
## 668     TRUE    FALSE
## 669     TRUE    FALSE
## 670     TRUE     TRUE
## 671     TRUE     TRUE
## 672     TRUE     TRUE
## 673     TRUE    FALSE
## 675     TRUE     TRUE
## 678     TRUE     TRUE
## 679     TRUE     TRUE
## 680     TRUE     TRUE
## 682     TRUE    FALSE
## 683     TRUE    FALSE
## 684     TRUE     TRUE
## 685     TRUE     TRUE
## 687     TRUE    FALSE
## 689     TRUE     TRUE
## 690     TRUE     TRUE
## 691     TRUE     TRUE
## 692     TRUE     TRUE
## 693     TRUE    FALSE
## 694     TRUE     TRUE
## 695     TRUE    FALSE
## 696     TRUE     TRUE
## 699     TRUE    FALSE
## 700     TRUE     TRUE
## 702     TRUE     TRUE
## 703     TRUE     TRUE
## 704     TRUE     TRUE
## 705     TRUE     TRUE
## 706     TRUE    FALSE
## 707     TRUE     TRUE
## 709     TRUE     TRUE
## 711     TRUE    FALSE
## 712     TRUE     TRUE
## 714     TRUE    FALSE
## 715     TRUE     TRUE
## 716     TRUE     TRUE
## 717     TRUE     TRUE
## 718     TRUE    FALSE
## 720     TRUE     TRUE
## 723     TRUE    FALSE
## 726     TRUE     TRUE
## 728     TRUE    FALSE
## 729     TRUE     TRUE
## 731     TRUE     TRUE
## 733     TRUE    FALSE
## 735     TRUE    FALSE
## 740     TRUE     TRUE
## 741     TRUE     TRUE
## 742     TRUE     TRUE
## 743     TRUE    FALSE
## 746     TRUE     TRUE
## 747     TRUE     TRUE
## 750     TRUE    FALSE
## 753     TRUE    FALSE
## 754     TRUE    FALSE
## 756     TRUE     TRUE
## 757     TRUE     TRUE
## 758     TRUE     TRUE
## 759     TRUE     TRUE
## 760     TRUE     TRUE
## 761     TRUE    FALSE
## 763     TRUE     TRUE
## 764     TRUE     TRUE
## 766     TRUE     TRUE
## 768     TRUE     TRUE
## 769     TRUE     TRUE
## 770     TRUE     TRUE
## 772     TRUE     TRUE
## 773     TRUE     TRUE
## 776     TRUE     TRUE
## 780     TRUE     TRUE
## 783     TRUE     TRUE
## 784     TRUE     TRUE
## 785     TRUE    FALSE
## 786     TRUE     TRUE
## 787     TRUE     TRUE
## 788     TRUE     TRUE
## 791     TRUE    FALSE
## 792     TRUE     TRUE
## 793     TRUE     TRUE
## 797     TRUE     TRUE
## 798     TRUE     TRUE
## 799     TRUE     TRUE
## 801     TRUE     TRUE
## 802     TRUE     TRUE
## 807     TRUE    FALSE
## 809     TRUE    FALSE
## 813     TRUE     TRUE
## 816     TRUE     TRUE
## 818     TRUE     TRUE
## 819     TRUE     TRUE
## 820     TRUE     TRUE
## 822     TRUE     TRUE
## 823     TRUE     TRUE
## 825     TRUE     TRUE
## 827     TRUE     TRUE
## 828     TRUE     TRUE
## 829     TRUE    FALSE
## 832     TRUE    FALSE
## 834     TRUE     TRUE
## 835     TRUE     TRUE
## 836     TRUE    FALSE
## 838     TRUE     TRUE
## 841     TRUE     TRUE
## 842     TRUE     TRUE
## 844     TRUE     TRUE
## 845     TRUE     TRUE
## 846     TRUE    FALSE
## 847     TRUE     TRUE
## 849     TRUE    FALSE
## 852     TRUE     TRUE
## 854     TRUE     TRUE
## 858     TRUE     TRUE
## 860     TRUE     TRUE
## 861     TRUE     TRUE
## 862     TRUE    FALSE
## 863     TRUE    FALSE
## 865     TRUE    FALSE
## 866     TRUE     TRUE
## 867     TRUE     TRUE
## 869     TRUE     TRUE
## 873     TRUE     TRUE
## 875     TRUE    FALSE
## 877     TRUE    FALSE
## 879     TRUE     TRUE
## 880     TRUE     TRUE
## 881     TRUE     TRUE
## 883     TRUE     TRUE
## 884     TRUE     TRUE
## 885     TRUE     TRUE
## 886     TRUE    FALSE
## 888     TRUE     TRUE
## 889     TRUE     TRUE
## 891     TRUE     TRUE
## 892     TRUE    FALSE
## 895     TRUE     TRUE
## 896     TRUE     TRUE
## 897     TRUE     TRUE
## 901     TRUE    FALSE
## 903     TRUE     TRUE
## 904     TRUE    FALSE
## 905     TRUE    FALSE
## 906     TRUE     TRUE
## 911     TRUE     TRUE
## 913     TRUE    FALSE
## 914     TRUE    FALSE
## 915     TRUE     TRUE
## 916     TRUE    FALSE
## 919     TRUE     TRUE
## 920     TRUE     TRUE
## 921     TRUE    FALSE
## 922     TRUE     TRUE
## 924     TRUE    FALSE
## 929     TRUE    FALSE
## 930     TRUE     TRUE
## 931     TRUE    FALSE
## 932     TRUE     TRUE
## 933     TRUE    FALSE
## 935     TRUE     TRUE
## 936     TRUE     TRUE
## 937     TRUE     TRUE
## 942     TRUE     TRUE
## 944     TRUE     TRUE
## 946     TRUE     TRUE
## 953     TRUE     TRUE
## 955     TRUE     TRUE
## 962     TRUE     TRUE
## 965     TRUE     TRUE
## 966     TRUE     TRUE
## 967     TRUE    FALSE
## 969     TRUE    FALSE
## 970     TRUE     TRUE
## 971     TRUE     TRUE
## 977     TRUE     TRUE
## 978     TRUE    FALSE
## 981     TRUE     TRUE
## 983     TRUE     TRUE
## 984     TRUE    FALSE
## 985     TRUE     TRUE
## 987     TRUE     TRUE
## 988     TRUE     TRUE
## 992     TRUE     TRUE
## 994     TRUE     TRUE
## 998     TRUE     TRUE
## 1003    TRUE     TRUE
## 1004    TRUE     TRUE
## 1006    TRUE    FALSE
## 1007    TRUE     TRUE
## 1009    TRUE     TRUE
## 1010    TRUE    FALSE
## 1011    TRUE     TRUE
## 1012    TRUE    FALSE
## 1013    TRUE    FALSE
## 1016    TRUE     TRUE
## 1017    TRUE     TRUE
## 1018    TRUE     TRUE
## 1019    TRUE     TRUE
## 1021    TRUE     TRUE
## 1022    TRUE    FALSE
## 1023    TRUE     TRUE
## 1026    TRUE     TRUE
## 1027    TRUE     TRUE
## 1028    TRUE    FALSE
## 1029    TRUE     TRUE
## 1030    TRUE     TRUE
## 1033    TRUE    FALSE
## 1034    TRUE    FALSE
## 1035    TRUE     TRUE
## 1036    TRUE     TRUE
## 1038    TRUE    FALSE
## 1039    TRUE     TRUE
## 1040    TRUE    FALSE
## 1042    TRUE     TRUE
## 1043    TRUE     TRUE
## 1047    TRUE     TRUE
## 1053    TRUE     TRUE
## 1054    TRUE     TRUE
## 1055    TRUE     TRUE
## 1057    TRUE    FALSE
## 1058    TRUE    FALSE
## 1061    TRUE     TRUE
## 1064    TRUE    FALSE
## 1066    TRUE    FALSE
## 1067    TRUE     TRUE
## 1068    TRUE     TRUE
## 1069    TRUE     TRUE
## 1070    TRUE     TRUE
## 1071    TRUE     TRUE
## 1072    TRUE    FALSE
## 1073    TRUE    FALSE
## 1075    TRUE     TRUE
## 1076    TRUE     TRUE
## 1077    TRUE     TRUE
## 1079    TRUE     TRUE
## 1081    TRUE     TRUE
## 1082    TRUE     TRUE
## 1083    TRUE     TRUE
## 1086    TRUE     TRUE
## 1087    TRUE     TRUE
## 1088    TRUE    FALSE
## 1091    TRUE     TRUE
## 1096    TRUE    FALSE
## 1098    TRUE    FALSE
## 1099    TRUE     TRUE
## 1100    TRUE     TRUE
## 1103    TRUE     TRUE
## 1106    TRUE    FALSE
## 1109    TRUE     TRUE
## 1112    TRUE     TRUE
## 1113    TRUE    FALSE
## 1114    TRUE     TRUE
## 1115    TRUE     TRUE
## 1116    TRUE     TRUE
## 1119    TRUE     TRUE
## 1121    TRUE     TRUE
## 1122    TRUE     TRUE
## 1123    TRUE    FALSE
## 1124    TRUE     TRUE
## 1129    TRUE    FALSE
## 1130    TRUE     TRUE
## 1131    TRUE     TRUE
## 1132    TRUE     TRUE
## 1133    TRUE     TRUE
## 1136    TRUE     TRUE
## 1137    TRUE     TRUE
## 1138    TRUE     TRUE
## 1139    TRUE     TRUE
## 1140    TRUE     TRUE
## 1143    TRUE     TRUE
## 1145    TRUE     TRUE
## 1146    TRUE     TRUE
## 1147    TRUE    FALSE
## 1149    TRUE     TRUE
## 1156    TRUE     TRUE
## 1157    TRUE     TRUE
## 1158    TRUE     TRUE
## 1161    TRUE     TRUE
## 1163    TRUE     TRUE
## 1164    TRUE     TRUE
## 1165    TRUE     TRUE
## 1167    TRUE     TRUE
## 1170    TRUE     TRUE
## 1172    TRUE     TRUE
## 1173    TRUE     TRUE
## 1174    TRUE    FALSE
## 1176    TRUE     TRUE
## 1177    TRUE     TRUE
## 1178    TRUE    FALSE
## 1180    TRUE     TRUE
## 1181    TRUE     TRUE
## 1182    TRUE     TRUE
## 1185    TRUE    FALSE
## 1186    TRUE     TRUE
## 1187    TRUE     TRUE
## 1191    TRUE     TRUE
## 1194    TRUE    FALSE
## 1197    TRUE     TRUE
## 1198    TRUE     TRUE
## 1201    TRUE     TRUE
## 1202    TRUE     TRUE
## 1203    TRUE     TRUE
## 1205    TRUE     TRUE
## 1207    TRUE     TRUE
## 1209    TRUE    FALSE
## 1211    TRUE     TRUE
## 1212    TRUE     TRUE
## 1213    TRUE     TRUE
## 1214    TRUE     TRUE
## 1216    TRUE     TRUE
## 1218    TRUE     TRUE
## 1219    TRUE     TRUE
## 1221    TRUE    FALSE
## 1222    TRUE     TRUE
## 1223    TRUE     TRUE
## 1225    TRUE    FALSE
## 1226    TRUE    FALSE
## 1227    TRUE     TRUE
## 1228    TRUE     TRUE
## 1229    TRUE    FALSE
## 1233    TRUE    FALSE
## 1234    TRUE     TRUE
## 1235    TRUE     TRUE
## 1236    TRUE    FALSE
## 1240    TRUE     TRUE
## 1241    TRUE     TRUE
## 1242    TRUE     TRUE
## 1245    TRUE     TRUE
## 1246    TRUE     TRUE
## 1247    TRUE    FALSE
## 1248    TRUE     TRUE
## 1249    TRUE    FALSE
## 1251    TRUE     TRUE
## 1252    TRUE    FALSE
## 1253    TRUE    FALSE
## 1255    TRUE     TRUE
## 1256    TRUE    FALSE
## 1258    TRUE    FALSE
## 1259    TRUE     TRUE
## 1261    TRUE     TRUE
## 1263    TRUE     TRUE
## 1264    TRUE     TRUE
## 1266    TRUE     TRUE
## 1268    TRUE     TRUE
## 1269    TRUE     TRUE
## 1270    TRUE     TRUE
## 1272    TRUE     TRUE
## 1273    TRUE     TRUE
## 1276    TRUE     TRUE
## 1278    TRUE    FALSE
## 1280    TRUE     TRUE
## 1281    TRUE    FALSE
## 1282    TRUE     TRUE
## 1283    TRUE     TRUE
## 1285    TRUE     TRUE
## 1286    TRUE     TRUE
## 1287    TRUE     TRUE
## 1289    TRUE     TRUE
## 1291    TRUE     TRUE
## 1299    TRUE     TRUE
## 1301    TRUE     TRUE
## 1305    TRUE     TRUE
## 1308    TRUE     TRUE
## 1310    TRUE     TRUE
## 1312    TRUE     TRUE
## 1315    TRUE     TRUE
## 1316    TRUE    FALSE
## 1317    TRUE     TRUE
## 1319    TRUE     TRUE
## 1322    TRUE     TRUE
## 1324    TRUE     TRUE
## 1326    TRUE     TRUE
## 1327    TRUE    FALSE
## 1329    TRUE     TRUE
## 1331    TRUE     TRUE
## 1332    TRUE     TRUE
## 1335    TRUE     TRUE
## 1337    TRUE     TRUE
## 1338    TRUE    FALSE
## 1340    TRUE     TRUE
## 1343    TRUE     TRUE
## 1344    TRUE     TRUE
## 1346    TRUE     TRUE
## 1347    TRUE     TRUE
## 1348    TRUE     TRUE
## 1351    TRUE     TRUE
## 1352    TRUE     TRUE
## 1353    TRUE     TRUE
## 1355    TRUE     TRUE
## 1357    TRUE     TRUE
## 1358    TRUE     TRUE
## 1359    TRUE    FALSE
## 1361    TRUE     TRUE
## 1362    TRUE     TRUE
## 1363    TRUE     TRUE
## 1364    TRUE    FALSE
## 1366    TRUE     TRUE
## 1367    TRUE     TRUE
## 1371    TRUE     TRUE
## 1372    TRUE     TRUE
## 1373    TRUE     TRUE
## 1375    TRUE    FALSE
## 1377    TRUE     TRUE
## 1378    TRUE     TRUE
## 1380    TRUE     TRUE
## 1382    TRUE     TRUE
## 1383    TRUE     TRUE
## 1384    TRUE     TRUE
## 1385    TRUE     TRUE
## 1386    TRUE     TRUE
## 1388    TRUE     TRUE
## 1390    TRUE     TRUE
## 1392    TRUE     TRUE
## 1393    TRUE    FALSE
## 1395    TRUE     TRUE
## 1396    TRUE     TRUE
## 1397    TRUE    FALSE
## 1398    TRUE     TRUE
## 1401    TRUE     TRUE
## 1403    TRUE     TRUE
## 1405    TRUE    FALSE
## 1406    TRUE    FALSE
## 1407    TRUE    FALSE
## 1408    TRUE     TRUE
## 1409    TRUE     TRUE
## 1410    TRUE    FALSE
## 1411    TRUE    FALSE
## 1413    TRUE     TRUE
## 1416    TRUE     TRUE
## 1417    TRUE     TRUE
## 1419    TRUE     TRUE
## 1420    TRUE    FALSE
## 1421    TRUE     TRUE
## 1422    TRUE     TRUE
## 1423    TRUE     TRUE
## 1424    TRUE    FALSE
## 1425    TRUE     TRUE
## 1427    TRUE     TRUE
## 1428    TRUE     TRUE
## 1432    TRUE     TRUE
## 1434    TRUE    FALSE
## 1435    TRUE    FALSE
## 1436    TRUE     TRUE
## 1441    TRUE     TRUE
## 1443    TRUE     TRUE
## 1444    TRUE     TRUE
## 1445    TRUE     TRUE
## 1447    TRUE    FALSE
## 1448    TRUE     TRUE
## 1450    TRUE     TRUE
## 1452    TRUE     TRUE
## 1453    TRUE     TRUE
## 1454    TRUE     TRUE
## 1455    TRUE     TRUE
## 1459    TRUE     TRUE
## 1461    TRUE     TRUE
## 1463    TRUE     TRUE
## 1464    TRUE     TRUE
## 1468    TRUE     TRUE
## 1470    TRUE     TRUE
## 1471    TRUE     TRUE
## 1472    TRUE     TRUE
## 1473    TRUE     TRUE
## 1475    TRUE     TRUE
## 1477    TRUE     TRUE
## 1479    TRUE     TRUE
## 1480    TRUE     TRUE
## 1483    TRUE     TRUE
## 1485    TRUE    FALSE
## 1486    TRUE     TRUE
## 1488    TRUE     TRUE
## 1490    TRUE     TRUE
## 1491    TRUE     TRUE
## 1493    TRUE     TRUE
## 1495    TRUE    FALSE
## 1500    TRUE     TRUE
## 1501    TRUE    FALSE
## 1502    TRUE    FALSE
## 1506    TRUE     TRUE
## 1507    TRUE     TRUE
## 1508    TRUE     TRUE
## 1510    TRUE    FALSE
## 1511    TRUE     TRUE
## 1513    TRUE     TRUE
## 1514    TRUE    FALSE
## 1515    TRUE     TRUE
## 1516    TRUE     TRUE
## 1518    TRUE    FALSE
## 1519    TRUE     TRUE
## 1522    TRUE     TRUE
## 1523    TRUE     TRUE
## 1524    TRUE     TRUE
## 1526    TRUE     TRUE
## 1529    TRUE     TRUE
## 1531    TRUE     TRUE
## 1532    TRUE     TRUE
## 1533    TRUE     TRUE
## 1534    TRUE    FALSE
## 1535    TRUE     TRUE
## 1536    TRUE    FALSE
## 1539    TRUE     TRUE
## 1540    TRUE     TRUE
## 1546    TRUE     TRUE
## 1547    TRUE     TRUE
## 1550    TRUE     TRUE
## 1554    TRUE     TRUE
## 1556    TRUE     TRUE
## 1557    TRUE    FALSE
## 1558    TRUE     TRUE
## 1559    TRUE    FALSE
## 1560    TRUE     TRUE
## 1562    TRUE    FALSE
## 1565    TRUE     TRUE
## 1568    TRUE    FALSE
## 1569    TRUE    FALSE
## 1572    TRUE     TRUE
## 1573    TRUE     TRUE
## 1574    TRUE     TRUE
## 1576    TRUE     TRUE
## 1577    TRUE     TRUE
## 1578    TRUE     TRUE
## 1580    TRUE     TRUE
## 1582    TRUE     TRUE
## 1583    TRUE    FALSE
## 1586    TRUE    FALSE
## 1588    TRUE     TRUE
## 1589    TRUE     TRUE
## 1592    TRUE     TRUE
## 1594    TRUE    FALSE
## 1596    TRUE     TRUE
## 1597    TRUE     TRUE
## 1598    TRUE     TRUE
## 1602    TRUE     TRUE
## 1603    TRUE     TRUE
## 1607    TRUE     TRUE
## 1609    TRUE     TRUE
## 1611    TRUE     TRUE
## 1612    TRUE    FALSE
## 1613    TRUE    FALSE
## 1615    TRUE    FALSE
## 1617    TRUE     TRUE
## 1619    TRUE    FALSE
## 1621    TRUE     TRUE
## 1622    TRUE    FALSE
## 1623    TRUE     TRUE
## 1628    TRUE     TRUE
## 1629    TRUE     TRUE
## 1631    TRUE     TRUE
## 1632    TRUE     TRUE
## 1633    TRUE     TRUE
## 1634    TRUE    FALSE
## 1635    TRUE    FALSE
## 1636    TRUE     TRUE
## 1637    TRUE     TRUE
## 1639    TRUE     TRUE
## 1641    TRUE     TRUE
## 1642    TRUE     TRUE
## 1644    TRUE     TRUE
## 1648    TRUE     TRUE
## 1649    TRUE     TRUE
## 1650    TRUE     TRUE
## 1651    TRUE     TRUE
## 1652    TRUE     TRUE
## 1655    TRUE    FALSE
## 1658    TRUE     TRUE
## 1660    TRUE     TRUE
## 1661    TRUE    FALSE
## 1663    TRUE    FALSE
## 1664    TRUE    FALSE
## 1665    TRUE     TRUE
## 1666    TRUE     TRUE
## 1667    TRUE     TRUE
## 1670    TRUE     TRUE
## 1671    TRUE     TRUE
## 1672    TRUE     TRUE
## 1673    TRUE     TRUE
## 1674    TRUE     TRUE
## 1676    TRUE     TRUE
## 1677    TRUE     TRUE
## 1679    TRUE     TRUE
## 1680    TRUE    FALSE
## 1686    TRUE     TRUE
## 1688    TRUE     TRUE
## 1693    TRUE     TRUE
## 1694    TRUE     TRUE
## 1695    TRUE     TRUE
## 1698    TRUE    FALSE
## 1700    TRUE     TRUE
\end{verbatim}

To count the number of rows we can use the \texttt{dim()} function.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(joint\_ups[joint\_ups}\SpecialCharTok{$}\NormalTok{SP500Up }\SpecialCharTok{==} \ConstantTok{TRUE}\NormalTok{, ])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 926   2
\end{verbatim}

It says that the number of notebook lines where the SP500 makes an Up move are 926. Since the
first line is an NA we have to subtract this line, so we have 925 lines with actual Ups in the
SP500.

Now, let us count the Ups in the Google occurring simultaneously with the SP500 ups

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{joint\_ups}\SpecialCharTok{$}\NormalTok{simultaneous }\OtherTok{=}\NormalTok{ (joint\_ups}\SpecialCharTok{$}\NormalTok{SP500Up }\SpecialCharTok{\&}\NormalTok{ joint\_ups}\SpecialCharTok{$}\NormalTok{GoogleUp)}
\end{Highlighting}
\end{Shaded}

Now we can make use of R's precedence rules to count the simultaneous up moves

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(joint\_ups}\SpecialCharTok{$}\NormalTok{simultaneous, }\AttributeTok{na.rm =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 702
\end{verbatim}

Now we compute \(702/926\) which gives us 0.76 as we have already verified before.

Note that for conditional probabilities we have for two events \(A\) and \(B\), that
\(P(A|B) \neq P(B|A)\). To see this assume that \(P(A) \neq P(B)\) and \(P(A) \neq 0\) and
\(P(B)\neq 0\). We then get:
\(P(A|B) = \frac{P(A\cap B)}{P(B)} = \frac{P(B \cap A)}{P(B}\), since \(P(A \cap B) = P(B \cap A)\).
It follows that \(\frac{P(B \cap A)}{P(B} \neq \frac{P(B \cap A)}{P(A} = P(B|A)\), since we
has assumed that \(P(A) \neq P(B)\). Therefore \(P(A|B) \neq P(B|A)\).

Try it with the stock price example above.

The notion of conditional probability also gives us a new insight into the notion of
independence, we discussed earlier. Remember that two events \(A\) and \(B\) are independent
if \(P(A \cap B) = P(B \cap A) = P(A) \cdot P(B)\). If we combine this rule with the
concept of conditional probability, we see that if two events \(A\) and \(B\) are independent, then
\(P(A|B) = \frac{P(A \cap B)}{P(B)} = \frac{P(A) \cdot P(B)}{P(B)} = P(A)\) and
\(P(B|A) = \frac{P(B \cap A)}{P(A)} = \frac{P(A) \cdot P(B)}{P(A)} = P(B)\).

This formula says that if two events are independent the probability of \(A\) is
not influenced by the event \(B\) occuring and the probability of event \(B\) is not
influenced by the event \(A\) occurring.

\hypertarget{birthdays-and-blockchains-continued}{%
\section{Birthdays and Blockchains continued}\label{birthdays-and-blockchains-continued}}

Let us go back to the problem we discussed in lecture 1 where we had \(n\) people in a class. How
much would you bet that there is nobody in the room who shares the same birthday?

We would like to compute the probability of the event that at least two people have the
same birthday, \(P(A)\). We compute this via the simpler problem that all \(n\) students have
a different birthday and by using the rules of probability.

Since the union of an event \(A\) and
its complement \(A^C\) is the whole sample space \({\cal S} = A \cup A^C\) and \(A \cap A^C = \emptyset\), we have
\(P({\cal S}) = P(A) + P(A^C)\). Now since \(P({\cal S}) = 1\), this means we can
compute the probability we are looking for as: \(1 - P(A^C)\).

In lecture 1 we have already found that for \(n\) students, assuming that every birthday is
equally likely, we have \(365^n\) possible outcomes for all students having a different birthday
and this can happen in \(365\cdot 364\cdot 363,\ldots, (365-n+1)\) ways. Therefore we get
\(1 - P(A^C) = 1 - \frac{365\cdot 364\cdot 363,\ldots, (365-n+1)}{365^n}\)

Now we can use this formula to write a function in R which gives us the probability as a
function of the number of people in a room.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{birthday\_collision }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(n)\{}
  
  \DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{prod}\NormalTok{(}\DecValTok{365}\SpecialCharTok{:}\NormalTok{(}\DecValTok{365}\SpecialCharTok{{-}}\NormalTok{n}\SpecialCharTok{+}\DecValTok{1}\NormalTok{))}\SpecialCharTok{/}\DecValTok{365}\SpecialCharTok{\^{}}\NormalTok{n}
  
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

In terms of R this should look all familiar to you: You know already how to write functions, we
use the R function \texttt{prod()} giving the product of an arbitrary finite number of factors. We did
not explicitly introduce this function but you can look up its details using the help facilities of R. The colon operator \texttt{:} you have alsoe learned already. In this example it would create
a vector of numbers from 365 to 356, which is then taken as the input to the \texttt{prod()} function. That's it.

If there are 10 people:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{birthday\_collision}\NormalTok{(}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1169482
\end{verbatim}

If there are 23 people in the room this probability is already

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{birthday\_collision}\NormalTok{(}\DecValTok{23}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5072972
\end{verbatim}

more than 50 \%. This is quite stunning because intuitively perhaps most of you
including myself would assume that this probability is much smaller. This is fun, but
what does this example have to do with computational Finance?

In lecture 1 we have explained that there is a common context with the birthday problem
and collisions of a hash function. Lets work out the collision probabilities for the
SHA-256 hash function. In the analogy of the birthday problem and hash-collsions the
number \(n\) of students in class are the inputs and their birthdays can be considered the
analogy to the hash values. When two people share the same birthday this is analogous to
a hash collision.

A hash with 256 bits can store \(2^{256}\) combinations of output values. For values
of this size we cannot make precise computations using the exact formula. This is
because the floatimg point representation of numbers will not allow us to distinguish
very large numbers. We need to work with approximations. It can be shown that the
expression:
\(\frac{M - 1}{M} \cdot \frac{M-2}{M} \cdot \frac{M-3}{M} \ldots \frac{M-(n-2)}{M} \cdot \frac{M-(n-1)}{M}\) is approximately equal to \(\exp(\frac{-n(n-1)}{2 M})\) and that this
approximation is good in the sense that the approximation error gets smaller as \(M\) gets larger
and eventually vanishes as \(M\) goes to infinity. We do not explain this calculus based argument
in detail here but those of you who are interested will find lost of references by a simple
web search.

If you take as an output range a hash function with 32 bits you can use this formula to convince
yourself that the number of hashes needed to get a collision probability of 50 \% is at
77163 hashes. This is not good enough for cryptographic security.

If we want to get the numerics for such lare ranges as 256 bit hash functions we even need
another approximation. If the exponent is very small, i.e.~M very large compared to n we can use
the further approximation \(1-\exp(-X) \approx X\). This means that \(\frac{n(n-1)}{2 M}\) is already
good enough for very large \(M\) and is \(n\) is relatively small then this can be again
simplified to \(\frac{n^2}{2 M}\). Taking this approximation we see that to make the
probability that no collision occurs \(99.8 \%\) you need with a 256 bit hash function you can
hash \(n = \sqrt{2 \cdot M \cdot 0.998}\) values before that occurs. This is a number of
the magnitude \(4.807505 \cdot 10^38\). At current hardware capacity this is several times the
age of the universe. So for practical purposes this can be considered safe.

Finally this example shows that while the computer is a powerful machine at very large numbers
brute force programming won't help because you hit the limits of numerical computation. You need
to think about how to deal with such situations.

\hypertarget{bayes-rule}{%
\section{Bayes' Rule}\label{bayes-rule}}

The definition of conditional probabilities has an important implication about the relation
between the probabilities of events, which is known as \emph{Bayes' rule}. Lets say we have two
events \(A\) and \(B\), then we know from the definition of conditional probability that
\(P(B|A) = \frac{P(B \cap A)}{P(A)}\). Since \(P(B \cap A) = P(A \cap B)\) we have
\(P(B|A) = \frac{P(B \cap A)}{P(A)} = \frac{P(A \cap B)}{P(A)}\) which is by definition
equal to \(\frac{P(A|B) \cdot P(B)}{P(A}\) provided that \(P(A) \neq 0\). The terminology
calls \(P(B)\) the \emph{prior probability} of \(B\) and \(P(B|A)\) is called the \emph{posterior probability}.

One way to think about the relation
\(P(B|A) = \frac{P(A|B) \cdot P(B)}{P(A}\) is to think about the event \(B\) as some hypothesis and
the event \(A\) as data or information.
\#\# R-Concepts

Pack the R concepts into the Apple and Stock market example.

Example strutured finance and violations of independence

\hypertarget{project}{%
\section{Project}\label{project}}

\hypertarget{random-variables}{%
\chapter{Random Variables}\label{random-variables}}

We now come to an extension of the simple probability model which is very useful. Let \({\cal S}\)
be some finite set and \(P(x)\) a probability on \({\cal S}\). A \textbf{random variable} is a
function assigning numbers to points of \({\cal S}\).
The notation \({\cal S}\) has been chosen deliberately to connect this lecture with the previous ones. A \textbf{random variable} is a function defined on the sample space.

The term random variable is slightly confusing, for what is really meant is something like a random function where the range is the sample space, i.e.~the outcome of a random experiment, and
the image is the set of real numbers.

It is a widely held convention in probability theory to denote random variables by capital letters, like \(X\) and \(Y\) and their values are denoted by \(x\) and \(y\) respectively.

Let \(X\) be a random variable and let \(x_1, x_2, \dots , x_n\) denote the values it can assume. The
aggregate of all sample points on which \(X\) assumes the fixed value \(X = x_j\) forms the event
that \(X = x_j\). Its probability is denoted by \(P(X = x_j)\).

When a random variable can only take finitely many or uncountably many values, i.e.~when the
sample space contains only finitley many or uncountably many basic outcomes, we say that the
random variable is \emph{discrete}.

The function \(P(X = x_j) = p(x_j)\) for \(j = 1, \cdots ,n\) is called
the \textbf{(probability) distribution} of the random variable \(X\). This function completely
describes the probability properties of the random variable. Note that \(p(x_j) \geq 0\)
and \(\sum_{j=1}^n p(x_j) = 1\).

The \textbf{cumulative distribution function} - abbreviated CDF - shows the probability that a
random variable \(X\) take a value less than or equal to a given value \(x\). It is usually denoted as \(F(x) = P(x \leq x)\) where \(-\infty < x < \infty\).

We have actually already encountered a random variable in our very first lecture, where we discussed
the six sided fair die. The random variable \(X\) is the rolling of the die with the numbers of
spots being \(x\). \(X\) is actually a function on the space of basic outcomes \(1, 2, 3, 4, 5, 6\).
Each of these outcomes has probability \(1/6\), since the dice is fair.

It is common to display the probabilities associated with a random variables, graphically as
a density ( a probability distribution).

insert plot use R

insert CDF for fair die use R

Now consider two random variables \(X\) and \(Y\) instead of only one. Assume both random variables
are functions on the same sample space \({\cal S}\) and denote the values which they respectively
assume by \(x_1,x_2, \cdots, x_n\) and \(y_1, y_2, \cdots, y_m\). Let us denote the corresponding
probability distributions \(f(x_i), i = 1, \cdots, n\), by \(f(x_1), f(x_2), \cdots, f(x_n)\) and
\(g(x_j), j = 1 \cdots m\) by \(g(y_1), g(y_2), \cdots, g(y_m)\).
The aggregate points which satisfy the condition \(X = x_i\) and \(Y=y_j\) are an event. Its
probability is denoted by \(P(X=x_i, Y=y_j) = p(x_i, y_j), \, i = 1 \cdots n, \, j = 1,\cdots m\)
and is called the \textbf{joint probability distribution}. Clearly we must have
\(p(x_i,y_j) \geq 0\) and \(\sum_{i,j} p(x_i,y_j) = 1\).

example 2 dice from before as tables, maybe a 3-D graph?

Here we encounter again a concept we have already heard about in the context of conditional
probability. For every fixed \(i\), we have
\(p(x_i, y_1) + p(x_i, y_2) + \cdots + p(x_i, y_m) = P(X = x_i) = f(x_i)\)
and for evey fixed \(j\) we have
\(p(x_1, y_j) + p(x_2, y_j) + \cdots p(x_n, y_j) = P(Y = y_j) = g(y_j)\)

This means that adding the probabilities of different rows and columns we obtain the probability
distribution of \(X\) and \(Y\). They may be exhibited using our tables and they are called the
\textbf{marginal distributions} which refers directly to the appearance in the table.

These notions carry over to more than two random variables. With the notation we have introduced
so far we can also define the \textbf{conditional probability} of an event \(Y = y_j\) given that
\(X = x_i\) (with \(f(x_i) > 0\)). This conditional probability is denoted as
\(P(y = y_j \, | X = x_i) = \frac{p(x_i,y_j)}{f(x_i)}\). Since this expression gives a number for
every value of \(X\) it is a function of \(X\) and
we call it the \textbf{conditional distribution of \(Y\) for given \(X\)} denoted by \(P(Y = y_j | X)\).
The conditional probability \(P(y = y_j \, | X = x_i)\) is in general different from \(g(y_j)\). In
this case the two random variables are stochastically dependent. If on the other hand
\(p(x_i,y_j)=f(x_i)g(y_j)\) for all combinations of \(x_i,y_j\) then the events \(X = x_i\) and \(Y = y_j\)
are independent and we speak of independent random variables.

Note that the joint distribution \(x\) and \(Y\) determines the distribution of \(X\) and \(Y\) but we cannot compute the distribution of \(X\) and \(Y\) from their marginal distributions. If two variables
\(X\) and \(Y\) have the same distribution they may or may not be independent.

Let us summarize the concepts we have learned in this section now in a formal definition (Feller p 217)

\begin{description}
\tightlist
\item[Random variable]
A random variable \(X\) is a function defined on a given sample space, mapping each sample point
into a real number
\item[Probability distribution]
The probability distribution of \(X\) is a function \(P(X = x_j) = p(x_j)\) for \(j = 1, \cdots ,n\).
\item[Joint Distribution]
If we have a finite set of random variables \(X, Y, \cdots, Z\) defined on the same
sample space, their joint distribution is given by the function
\(P(X=x_i, Y = y_j, \cdots, Z=z_k) = p(x_i,y_j, \cdots, z_k)\). These variables are called
\textbf{mutually independent} if
\(P(X=x_i, Y = y_j, \cdots, Z=z_k) = P(X = x_i)P(Y=y_j) \cdots P(Z=z_k)\)
\end{description}

\hypertarget{expected-value}{%
\section{Expected value}\label{expected-value}}

Sometimes the entire probability distribution is difficult to grasp at once. It is common to
describe probability distributions therefore by a summary measure. Amonng the typical summary
measure the \textbf{expectation} or the \textbf{mean} is by far the most important one.

\begin{description}
\tightlist
\item[Expected Value]
The expected value \(E[X]\) of a discrete random variable \(X\) is the probability weighted sum of
all possible values: \(E[X] = x_1p(x_1) + x_2 p(x_2) + \cdots + x_n p(x_n)\) for \(n\) possible
values of \(x\).
\end{description}

Examples: Find my simulations the following properties of expectations:

expectations of functions of a random variable )log returns.
linearity of expectation
expectation of mutually independent variables is the product of expectations.
conditional expectation is a new random variable

example: mean of a portfolio does not say anything about its risk

\hypertarget{measures-of-dispersion}{%
\section{Measures of Dispersion}\label{measures-of-dispersion}}

To capture information about the risk of the investment we need something like a deviation from
the mean or the variation of returns. If all historical returns are very close to the mean then
it will be very likely that the realized returns will not be far away from the expected value and
thus there will be not much risk. if, on the other hand, many of the historical returns are
far away from the mean one could argue that it is likely that the investment will outperform or
underperform the expected return. Measures of dispersion try to capture such variation in
one single number.

\begin{description}
\tightlist
\item[Variance]
The variance of a random variable \(X\) is the expected value of the squared deviation
from the expected value of \(X\) or
\(Var[X] = E[(X -E[X])^2]\)
\end{description}

In the case of a discrete random variable, the case we discuss in this lecture, we have
\(Var[X] = \sum_{i=1}^{n} (x_i - E[X]=^2 p(x_i))\). Note that the units of the variance are the
squared units of the random variable. This is often not very useful for interpretations. This
leads us to the concept of a standard deviation:

\begin{description}
\tightlist
\item[Standard Deviation]
The standard deviation of a random variable \(X\) is the suqare root of the variance of \(X\),
denoted \(SD[X] = \sqrt{Var[X]}\).
\end{description}

By example:

\(Var[X + a] = Vat[X]\)
\(Var[c X] = c^2 Var[X]\)
\(Var[a+ c X] = c^2Var[X]\)

Assume we have two random variables \(X\) and \(Y\) then we define their as

\begin{description}
\tightlist
\item[Covariance]
\(Cov(X,Y) = E((X - E(X))(Y-E(Y)))\)
\end{description}

Note that \(Cov(X,Y) = E(XY) - E(X)E(Y)\). If \(X\) and \(Y\) are independent, then \(E(XY) = E(X)E(Y)\),
hence if \(X\) and \(Y\) are independent, \(Cov(X,Y) = 0\). Note, however, that the converse is not true.
A covariance of 0 does \textbf{not} imply independence.

The choice of an origin and unit of measurement of a random variable is to a large
degree arbitrary. It is thus ofetn most convenient to take the mean as the origin and the
standard deviation as unit. Denote the mean of a random variable \(X\) as \(\mu\) and the variance as
\(\sigma^2\). In this case \(X-\mu\) has mean zero and variance \(\sigma^2\), and hence the variable
\(X^* = \frac{(X-\mu)}{\sigma}\) has mean 0 and variance 1. If we take the covariance
of two such normalized random variables we get the so called \textbf{correlation coefficient} \(\rho(X,Y)\).

\begin{description}
\tightlist
\item[Correlation Coefficient]
\(\rho(X,Y) = Cov(X^*,Y^*) = \frac{Cov(X,Y)}{\sigma_x \sigma_y}\)
\end{description}

The correlation coerfficient is thus just a way of writing the covariance.

Discuss examples (a) and (b) in Feller p 236 as R examples to make the point that the covariance
is not a general measure of dependence but a measure of linear dependence.

\hypertarget{example-mean-variance-portfolio-theory}{%
\section{Example: Mean-variance portfolio theory}\label{example-mean-variance-portfolio-theory}}

An important case where probability is applied in Finance is the problem that when you
make an investment with a known initial outlay of capital the amount to be returned from the
investment in the future is unknown. In the example we want to discuss now, we restrict
attention to a class of these problems where we have only a single investment period: Money
is invested at an initial time and a payoff is attained at the end of this period. Random
variables are a concept that allows us to construct models for thinking about and analyzing the
uncertainty inherent in such practical situation. While the assumption of a single
period is an idealization that does not apply to public stocks such models are applied to
this common class of investments as a simplification. For other situations the one period
model is sometimes a pretty good approximation. Think of a zero-coupon bond that will be
held to maturity. Or think about an investment in a physical project that only will yield
a payoff when completed.

Before we dive into the modelling of investment problems with uncertainty using probability and
random variables as a tool, we need to introduce some financial concepts first: An
investment instrument that can be bought and sold is called an \textbf{asset} in Finance. If \(X_0\) is
the amount invested today and \(X_1\) is the amount received ``tomorrow'', say for example in a
year from now the \textbf{total return} is defined as the ratio of the amount received to
the amount invested or formally \(R = \frac{X_1}{X_0}\). Often we simply use the term return.
The \textbf{rate of return} is defined as the difference between the amount received and the amount
invested in relation to the amount invested or \(r = \frac{X_1-X_0}{X_0}\). Often people also
speak of return when they refer to the rate of return. Both notions are related by the
equation \(R = 1+r\) and the equation for the rate of return can be rewirtten as \(X_1 = (1+r)X_0\).
This shows that the rate of return acts much like an interest rate.

When an asset is initially acquired, its rate of return is uncertain. Modelling the rate of
return as a random variable is one possibility to describe and analyze this situation of
uncertain returns. In mean-variance portfolio analysis the uncertainty is summarized by
the mean or expected value \(E(r)\) of the rate of return and its variance \(E((r-E(r)))\) and by
its covariance with other assets. Thus we reduce the description of uncertainty to two
summary measures of the distribution of the rate or return instead of working with the
entire rate of return distribution.

load a portfolio of stocks
compute returns
create a vector of weights
compute the mean return of the portfolio
compute the variance of the portfolio
discuss the magic of diversification
feasible set
feasible minimum variance set
do this with real stock data

\hypertarget{binomial-distribution}{%
\section{Binomial Distribution}\label{binomial-distribution}}

Explain Bernoulli trials
Explain repeated Bernouli trials
Show how these repeated Bernoulli trials or sums can be modeled by the binomial distribution
use R for that
Binomial

\hypertarget{example-models-of-asset-price-dynamics}{%
\section{Example: Models of asset price dynamics}\label{example-models-of-asset-price-dynamics}}

Luenberger p 296 - 299 until

\hypertarget{project-credit-risk-model-and-independence-based-on-schuxf6nbucher}{%
\section{Project: Credit risk model and independence based on Schönbucher}\label{project-credit-risk-model-and-independence-based-on-schuxf6nbucher}}

This can be constructed to apply the binomial distribution and discuss the
importance of dependence. The modelling of dependence can be taken up in
the last project

\hypertarget{continuous-random-variables}{%
\chapter{Continuous random variables}\label{continuous-random-variables}}

In this lecture we will introduce the most important probability distribution, the normal
distribution. While we have discussed discrete random variables so far, where the
number of possible outcomes for \(X\) is finite, to discuss the normal distribution we
need to deal with the case that the number of outcomes for \(X\) is uncountable infinite.
This leads us to the concept of a continuous random variable.

We will discuss here the most important concepts needed for the practical work with
continuous random variables. We just note that for a mathematically rigorous treatment
of this case we would need advanced techniques such as measure theory. We will not do that here
(reference to literature) because we want to focus on the more applied or practical aspects
of continuous random variables.

\begin{description}
\tightlist
\item[Continuous random variable]
A \textbf{continuous random variable} can take on a continuum of possible values.
\end{description}

Note that random variables that can take on a continuum of values rather than only discrete values
like the fair die, we discussed before, play an important role in practical situations. Just think
of the possible values of an asset price. Other practically important cases where a continuum
of outcomes would be a very natural model is the length of finishing a task, or the lengths and the
weight of an item.

You might object that these examples are not really continuous. Take time. We measure it in
hours, minutes or seconds. But we can measure it on a much finer grid and ultimately this
process finishes at some smallest unit only because of our limitations to measure time
at even smaller scales. Time is a continuous variable. It does not jump. In the case of stock
prices the situation is different. We have a smallest monetary unit, in the Eurozone this would
be cents. Still it turns out that in the case of prices practical modelling can be
simpler if we think of prices as continuous.

Even if we circumvent the mathematical machinery of measure theory to discuss
continuous random variable it is still important to spend some time thinking of what
a continuous random variable means.

In order to do this let us think of a continuous random variable which can take any
value in the interval \([0,1]\). We can generate such numbers very easely in R using the
function \texttt{runif()}. Let's create 10 such numbers:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{runif}\NormalTok{(}\DecValTok{10}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 0.44146137 0.80787301 0.06751658 0.07412814 0.82756398 0.99867876
##  [7] 0.24292709 0.78885807 0.33737895 0.63966723
\end{verbatim}

Now you could ask: What is the probability that this random variable takes the value of
\(0.4848450\)? Make the point that this probability is 0. The numbers always change. (explain
pseudorandom numbers), there is an infinite amount of numbers between 0 and 1 and you can not
count them. The continuum does not allow us to give positive probabilities to any one number.
No given number in the continuum can have a positive probability.

This is key: For every continuous random variable \(X\) we have \(P(X = x) = 0\) for all \(x\). Thus
in the case of a continuous random variable we can no longer talk about individual probabilities.

Now let us think about a different question. What is the probability that the random variable comes
up with a value between \(0\) and \(1/4\)? Lets simulate: R exercise.

Point: It looks uniform. 25 \%. Try other thresholds.

So as soon as we have range, we can talk about positive probabilities. But this is the big
change from discrete to continuous random variables. Whereas in the discrete cas we had points
and could talk about probabilities of points, in the continuous case we represent
probabilities as \emph{areas under a curve}. Give examples.

Areas under a curve are integrals. The representation of probabilities of a continuous random
variable corresponds to what you learned in high-school about integration under a curve.

The function that we need is called a probability density function and is defined as follows:

\begin{description}
\tightlist
\item[Probability density function]
For a continuous random variable, the probability density function, usually denoted by
\(f(x)\), has the following properties:
1. \(f(x) \leq 0\)
2. \(\int_{-\infty}^{+\infty} f(x) dx = 1\)
If \(X\) is a continuous random variable with a density function \(f\), then for any \(a < b\), the
probability that \(X\) falls in the interval \((a,b)\) is the area under the density function between
\(a\) and \(b\):
\(P(a < X < b) = \int_a^b f(x) dx\)
\end{description}

Since we can talk only about areas under the curve for continuous random variables the
really important function is the \textbf{cumulative distribution function} or CDF. Let us give
the definition here:

\begin{description}
\tightlist
\item[Cumulative Distribution Function]
The \textbf{cumulative distribution function} (abbreviated CDF) shows the probability that the
random variable \(X\) takes a value less than or equal to a deterministic value \(x\). It
shows the area under the probability density function from \(-\infty\) to \(x\). The notation is
\(F(x) = P( X \leq x)\) where \(- \infty < x < \infty\).
\end{description}

Note that the CDF can be used to compute probabilities because
\(P(a < X < b) = P(a < X \leq b) = P(a \leq X \leq b) = F(b) - F(a) = \int_a^b f(x) dx\)

Maybe graphical example here:

We now come to the most important continuous distribution, which plays a key role in
probability and all of its applications. The normal distribution.

\hypertarget{normal-distribution}{%
\section{Normal Distribution}\label{normal-distribution}}

\begin{description}
\tightlist
\item[Normal Distribution]
The normal distribution is a continuous probability distribution that is
centered around the mean, bell-shaped, symmetric and completely determined by
two parameters: The mean \(\mu\) and the variance \(\sigma^2\). The notation
is \(X \sim N(\mu, \sigma^2)\). The probability density
function of the normal distribution with mean \(\mu\) and variance \(\sigma^2\)
is given by
\(f(x,\mu, \sigma) = \frac{1}{\sigma \sqrt{2 \pi}} \exp\left(\frac{-(x - \mu)^2}{2 \sigma^2}\right)\)
\end{description}

A normally distributed random variable \(X\) can be standardized to a normally distributed
random variable with mean \(0\) and variance \(1\). This is called the

\begin{description}
\tightlist
\item[Standard Normal Distribution]
The standard normal distribution is a normal distribution with mean \(\mu = 0\) and
variance \(\sigma^2 = 1\). Any normally distributed random variable \(X\) with mean
\(\mu\) and variance \(\sigma^2\) can be rewritten as a standard normal random variable
\(Z\) in the following way:
\(Z = \frac{X - \mu}{\sigma}\). By definition \(Z \sim N(0,1)\)
\end{description}

Example with normal returns. Compute probability that return exceeds a threshold. Redo
probability computation with standardized returns. Probability is the same.

Example: An important property of the normal distribution:

\(P(\mu - \sigma \leq X \leq \mu + \sigma) = a\)
\(P(\mu - 2 \sigma \leq X \leq \mu + 2 \sigma) = b\)
\(P(\mu - 3 \sigma \leq X \leq \mu + 3 \sigma) = c\)

Sketch. Do the computation with R

\hypertarget{inverse-normal-and-quantiles}{%
\section{Inverse Normal and Quantiles}\label{inverse-normal-and-quantiles}}

In risk management we often ask the following question: For a given time horizon we would
like to know the threshold loss value, such that the probability that the portfolio loss
exceeds this value over the given time horizon is \(p\).

Note that is a different question than we asked before. Before we had a given threshold and
we were interested in the probability to get a value below the threshold. Now we have an
\textbf{inverse} problem. We have a given probability \(p\) and we want to know the threshold such
that this threshold is exceeded with this given probability. As a risk manager we want to
make this probability small.

Let us formulate these ideas in the form of a few definitions:

\begin{description}
\tightlist
\item[Inverse Normal Distribution]
With the inverse normal distribution, it is possible to calculate the value \(x\) such that
\(P(X \leq x)\) is equal to probability \(p\) for a given normally distributed random variable.
\end{description}

shwo the concept in R and how to apply it.

\begin{description}
\tightlist
\item[Quantile]
The \(pth\) quantile (or percentile) of a probability distribution is the value \(x\) such that
\(P(X \leq x) = p\). If \(X\) is normally distributed, \(X \sim N(\mu, \sigma^2)\) then the
\(x\) value such that \(P(X \leq x) = p\) is given by the inverse CDF of the normal distribution
with parameters \(\mu\) and \(\sigma\) for given \(p\).
\end{description}

Coming back to our risk management problem, we can now see that we are looking for a certain
quantile of the portfolio loss distribution. This quantile is called the \textbf{value at risk}.

\begin{description}
\tightlist
\item[Value-at-Risk]
Given a confidence level \(\alpha \in (0,1)\), Value-at-Risk (VaR) is defined as
\(VaR_\alpha = F_L(\alpha)^{-1} = \inf\{x \in \mathbb{R} | F_L(x) \geq \alpha \}\)
With a normal loss distribution \(F_L\) we can compute the value at risk
in an easy way.
\end{description}

Example: Value at risk, Portfolio with value x with average growth z over year y and stanrdard deviation k. what is the 95 VaR the 99 VaR? Compute and show.

\hypertarget{example-the-story-of-long-term-capital-and-ignoring-fat-tails}{%
\section{Example: The story of Long Term Capital and ignoring fat tails}\label{example-the-story-of-long-term-capital-and-ignoring-fat-tails}}

Student t-distribution

\hypertarget{example-models-of-asset-price-dynamics-continued}{%
\section{Example: Models of asset price dynamics continued}\label{example-models-of-asset-price-dynamics-continued}}

\hypertarget{project-portfolio-credit-risk-with-dependent-defaults}{%
\section{Project: Portfolio credit risk with dependent defaults}\label{project-portfolio-credit-risk-with-dependent-defaults}}

Schönbucher continued.

\hypertarget{appendix}{%
\chapter{Appendix}\label{appendix}}

\hypertarget{installing-r}{%
\section{Installing R}\label{installing-r}}

\hypertarget{installing-rstudio}{%
\section{Installing RStudio}\label{installing-rstudio}}

  \bibliography{book.bib,packages.bib}

\end{document}
