<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Continuous random variables and Monte Carlo Simulation – An Introduction to Probability</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-references.html" rel="next">
<link href="./04-lecture4.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-lecture5.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Continuous random variables and Monte Carlo Simulation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">An Introduction to Probability</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-lecture1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">First probability ideas and first steps in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-lecture2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability: Basic Definitions and Rules</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-lecture3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Conditional Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-lecture4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-lecture5.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Continuous random variables and Monte Carlo Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Appendix</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#continuous-random-variables-and-probability" id="toc-continuous-random-variables-and-probability" class="nav-link active" data-scroll-target="#continuous-random-variables-and-probability"><span class="header-section-number">5.1</span> Continuous Random Variables and Probability</a></li>
  <li><a href="#normal-distribution" id="toc-normal-distribution" class="nav-link" data-scroll-target="#normal-distribution"><span class="header-section-number">5.2</span> Normal Distribution</a>
  <ul class="collapse">
  <li><a href="#standardization-and-the-standard-normal-distribution" id="toc-standardization-and-the-standard-normal-distribution" class="nav-link" data-scroll-target="#standardization-and-the-standard-normal-distribution"><span class="header-section-number">5.2.1</span> Standardization and the Standard Normal Distribution</a></li>
  <li><a href="#the-68-95-99.7-rule-probability-mass-in-the-normal-distribution" id="toc-the-68-95-99.7-rule-probability-mass-in-the-normal-distribution" class="nav-link" data-scroll-target="#the-68-95-99.7-rule-probability-mass-in-the-normal-distribution"><span class="header-section-number">5.2.2</span> The 68-95-99.7 Rule: Probability Mass in the Normal Distribution</a></li>
  </ul></li>
  <li><a href="#lognormal-distribution" id="toc-lognormal-distribution" class="nav-link" data-scroll-target="#lognormal-distribution"><span class="header-section-number">5.3</span> Lognormal Distribution</a>
  <ul class="collapse">
  <li><a href="#why-the-lognormal-distribution-for-stock-prices" id="toc-why-the-lognormal-distribution-for-stock-prices" class="nav-link" data-scroll-target="#why-the-lognormal-distribution-for-stock-prices"><span class="header-section-number">5.3.1</span> Why the Lognormal Distribution for Stock Prices?</a></li>
  <li><a href="#comparing-real-stock-data-with-the-lognormal-distribution" id="toc-comparing-real-stock-data-with-the-lognormal-distribution" class="nav-link" data-scroll-target="#comparing-real-stock-data-with-the-lognormal-distribution"><span class="header-section-number">5.3.2</span> Comparing Real Stock Data with the Lognormal Distribution</a></li>
  <li><a href="#applications-and-limitations-a-balanced-perspective" id="toc-applications-and-limitations-a-balanced-perspective" class="nav-link" data-scroll-target="#applications-and-limitations-a-balanced-perspective"><span class="header-section-number">5.3.3</span> Applications and Limitations: A Balanced Perspective</a></li>
  </ul></li>
  <li><a href="#inverse-normal-and-quantiles-in-risk-management" id="toc-inverse-normal-and-quantiles-in-risk-management" class="nav-link" data-scroll-target="#inverse-normal-and-quantiles-in-risk-management"><span class="header-section-number">5.4</span> Inverse Normal and Quantiles in Risk Management</a>
  <ul class="collapse">
  <li><a href="#the-inverse-normal-function-in-r" id="toc-the-inverse-normal-function-in-r" class="nav-link" data-scroll-target="#the-inverse-normal-function-in-r"><span class="header-section-number">5.4.1</span> The Inverse Normal Function in R</a></li>
  </ul></li>
  <li><a href="#value-at-risk" id="toc-value-at-risk" class="nav-link" data-scroll-target="#value-at-risk"><span class="header-section-number">5.5</span> Value at risk</a></li>
  <li><a href="#empirical-value-at-risk-var-and-its-limitations" id="toc-empirical-value-at-risk-var-and-its-limitations" class="nav-link" data-scroll-target="#empirical-value-at-risk-var-and-its-limitations"><span class="header-section-number">5.6</span> Empirical Value at Risk (VaR) and Its Limitations</a></li>
  <li><a href="#data-and-statistics" id="toc-data-and-statistics" class="nav-link" data-scroll-target="#data-and-statistics"><span class="header-section-number">5.7</span> Data and statistics</a>
  <ul class="collapse">
  <li><a href="#peridod-length-effects" id="toc-peridod-length-effects" class="nav-link" data-scroll-target="#peridod-length-effects"><span class="header-section-number">5.7.1</span> Peridod-Length Effects</a></li>
  </ul></li>
  <li><a href="#introdcution-to-monte-carlo-simulation-in-finance" id="toc-introdcution-to-monte-carlo-simulation-in-finance" class="nav-link" data-scroll-target="#introdcution-to-monte-carlo-simulation-in-finance"><span class="header-section-number">5.8</span> Introdcution to Monte Carlo Simulation in Finance</a>
  <ul class="collapse">
  <li><a href="#simulating-portfolio-returns-for-var-calculation-step-by-step-implementation-in-r" id="toc-simulating-portfolio-returns-for-var-calculation-step-by-step-implementation-in-r" class="nav-link" data-scroll-target="#simulating-portfolio-returns-for-var-calculation-step-by-step-implementation-in-r"><span class="header-section-number">5.8.1</span> Simulating Portfolio Returns for VaR Calculation Step-by-Step Implementation in R</a></li>
  <li><a href="#step-3-optimizing-the-monte-carlo-simulation-1" id="toc-step-3-optimizing-the-monte-carlo-simulation-1" class="nav-link" data-scroll-target="#step-3-optimizing-the-monte-carlo-simulation-1"><span class="header-section-number">5.8.2</span> <strong>Step 3: Optimizing the Monte Carlo Simulation</strong></a></li>
  <li><a href="#reporting-and-documentation-of-r-code" id="toc-reporting-and-documentation-of-r-code" class="nav-link" data-scroll-target="#reporting-and-documentation-of-r-code"><span class="header-section-number">5.8.3</span> Reporting and Documentation of R Code</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Continuous random variables and Monte Carlo Simulation</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this lecture we will introduce the most important probability distribution, the <strong>normal distribution</strong>. While we have discussed discrete random variables so far, where the number of possible outcomes for <span class="math inline">\(X\)</span> is finite (or countably infinite), to discuss the normal distribution we need to deal with the case that the number of outcomes for <span class="math inline">\(X\)</span> is uncountable infinite, or a continuum. This leads us to the concept of a continuous random variable.</p>
<section id="continuous-random-variables-and-probability" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="continuous-random-variables-and-probability"><span class="header-section-number">5.1</span> Continuous Random Variables and Probability</h2>
<p>Here, we discuss the most important concepts for practical work with continuous random variables. For a mathematically rigorous treatment, advanced techniques such as measure theory are required. However, we will not delve into those here (see, for example, <span class="citation" data-cites="Billingsley1995">Billingsley (<a href="06-references.html#ref-Billingsley1995" role="doc-biblioref">1995</a>)</span>). Instead, we focus on applied and practical aspects.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Continuous Random Variable
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>continuous random variable</strong> <span class="math inline">\(X\)</span> can take on a continuum of possible values within a given range.</p>
</div>
</div>
<p>Random variables that can take on a continuum of values, rather than discrete values like the fair coin we discussed earlier, play a crucial role in practical applications. For instance, consider asset prices or returns. A stock’s price, in principle, could take any value in <span class="math inline">\([0, \infty)\)</span>. Or could it?</p>
<p>This is a modeling assumption that can be debated in terms of realism. After all, stock prices are quoted in currency, which has a smallest unit (e.g., cents or pennies). In Lecture 1, we discussed the assumption of unbounded stock prices in the context of sample spaces. Similarly, for other practical cases—such as task completion times, lengths, or weights—a continuum of outcomes often provides a natural model.</p>
<p>You might argue that these examples are not <em>truly</em> continuous. For instance, time is measured in hours, minutes, or seconds. However, we can refine our measurements to a much finer scale, with the limit imposed only by our measuring instruments. Time itself <em>is</em> continuous—it does not jump.</p>
<p>In contrast, stock prices do have a smallest monetary unit (e.g., cents in the Eurozone). Yet, for practical modeling, treating prices as continuous simplifies computations and analysis.</p>
<p>Even without delving into the mathematical machinery of measure theory, it is crucial to grasp the implications of continuous random variables. Let’s explore an example of a continuous random variable that can take any value in the interval <span class="math inline">\([0,1]\)</span>. In R, we can generate such numbers easily using the <code>runif()</code> function. Consider the following example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">runif</span>(<span class="dv">10</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.2875775 0.7883051 0.4089769 0.8830174 0.9404673 0.0455565 0.5281055
 [8] 0.8924190 0.5514350 0.4566147</code></pre>
</div>
</div>
<p>Now, consider the probability of this random variable taking on a specific value, say <span class="math inline">\(0.4566147\)</span>, one of the values in our list. To investigate, we simulate one million uniformly distributed random numbers in <span class="math inline">\([0,1]\)</span> and calculate the relative frequency of <span class="math inline">\(0.4566147\)</span> occurring:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>uniform_rv <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">6</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(uniform_rv <span class="sc">==</span> <span class="fl">0.4566147</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>The result is zero—literally zero. Even with one million draws, the random number generator in R produced unique values each time. The probability of hitting any specific value is zero.</p>
<p>This occurs because the interval <span class="math inline">\([0,1]\)</span> contains an infinite number of points. For any number in this interval, there are infinitely many numbers both larger and smaller. Assigning a positive probability to any single point would result in probabilities summing to a value greater than 1, violating the laws of probability.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>For every continuous random variable <span class="math inline">\(X\)</span>, we have <span class="math inline">\(P(X = x) = 0\)</span> for all <span class="math inline">\(x\)</span>.</p>
</div>
</div>
<p>This is a fundamental shift from discrete random variables: for continuous random variables, we cannot assign positive probabilities to individual points. Instead, probabilities are associated with <strong>intervals of real numbers</strong>.</p>
<p>For example, consider the probability that a uniformly distributed random variable <span class="math inline">\(X \sim U[0,1]\)</span> takes a value between <span class="math inline">\(0\)</span> and <span class="math inline">\(1/4\)</span>. Using the simulated numbers, we calculate:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="dv">0</span> <span class="sc">&lt;=</span> uniform_rv <span class="sc">&amp;</span> uniform_rv <span class="sc">&lt;=</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.250841</code></pre>
</div>
</div>
<p>The result is 25%, as expected. Using R’s cumulative distribution function (CDF), we confirm:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">punif</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.25</code></pre>
</div>
</div>
<p>For continuous random variables, probabilities are represented as <strong>areas under a curve</strong>. This is the major distinction from discrete random variables, where probabilities are assigned to individual points.</p>
<p>Consider this density function example:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/uniform_dist.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>With continuous random variables, probabilities are areas under the density function</figcaption>
</figure>
</div>
</div>
</div>
<p>Mathematically, these areas are calculated using integrals. The <strong>probability density function</strong> (PDF) describes the distribution as follows:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Probability Density Function of a Continuous Random Variable
</div>
</div>
<div class="callout-body-container callout-body">
<p>For a continuous random variable <span class="math inline">\(X\)</span> with density function <span class="math inline">\(f(x)\)</span>:</p>
<ol type="1">
<li><span class="math inline">\(f(x) \geq 0\)</span>, for all <span class="math inline">\(x\)</span>.</li>
<li><span class="math inline">\(\int_{-\infty}^{\infty} f(x) \, dx = 1\)</span>.</li>
<li>For any <span class="math inline">\(a &lt; b\)</span>, the probability that <span class="math inline">\(X\)</span> falls within <span class="math inline">\((a, b)\)</span> is given by the integral:<br>
<span class="math inline">\(P(a &lt; X &lt; b) = \int_a^b f(x) \, dx\)</span>.</li>
</ol>
</div>
</div>
<p>The <strong>cumulative distribution function</strong> (CDF) provides another essential tool for continuous random variables:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Cumulative Distribution Function of a Continuous Random Variable
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>cumulative distribution function</strong> (CDF) shows the probability that <span class="math inline">\(X\)</span> takes a value less than or equal to <span class="math inline">\(x\)</span>:<br>
<span class="math inline">\(F(x) = P(X \leq x)\)</span>.<br>
For any <span class="math inline">\(a &lt; b\)</span>:<br>
<span class="math inline">\(P(a &lt; X &lt; b) = F(b) - F(a) = \int_a^b f(x) \, dx\)</span>.</p>
</div>
</div>
<p>This transition from discrete points to areas under a curve marks a crucial conceptual shift in working with continuous random variables.</p>
</section>
<section id="normal-distribution" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="normal-distribution"><span class="header-section-number">5.2</span> Normal Distribution</h2>
<p>The <strong>normal distribution</strong> is perhaps the most iconic and fundamental probability distribution in all of probability theory. Its bell-shaped curve has become synonymous with ideas of natural variability and randomness. From the heights of people to measurement errors, and from stock returns to the central limit theorem, the normal distribution underpins countless phenomena in the natural and social sciences.</p>
<p>What makes the normal distribution truly remarkable is its simplicity and universality. With just two parameters—the mean (<span class="math inline">\(\mu\)</span>) and variance (<span class="math inline">\(\sigma^2\)</span>)—it captures the essence of variability in a way that is mathematically elegant and empirically ubiquitous. This distribution lies at the heart of probability theory, serving as the cornerstone for much stochastic modeling. For the application of probability to the modelling of data, the field of statistics, the normal distribution is foundational.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Normal Distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>normal distribution</strong> is a continuous probability distribution that is centered around the mean, bell-shaped, symmetric, and completely determined by two parameters: the mean <span class="math inline">\(\mu\)</span> and the variance <span class="math inline">\(\sigma^2\)</span>. The notation is <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span>. Its probability density function is given by: <span class="math display">\[
f(x, \mu, \sigma) = \frac{1}{\sigma \sqrt{2 \pi}} \exp\left(-\frac{(x - \mu)^2}{2 \sigma^2}\right)
\]</span></p>
</div>
</div>
<p>Often referred to as the <strong>Gaussian distribution</strong>, after the German mathematician Karl Friedrich Gauss (1777–1855), it is also known as the <strong>Gauss-Laplace distribution</strong>, honoring Pierre-Simon Laplace (1749–1827). The shape of its probability density function has earned it the nickname <strong>bell curve</strong>, an image deeply ingrained in the language of science, education, and beyond.</p>
<p>Let’s use R to make this image tangible.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up the sequence of x values</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the probability density function of the standard normal distribution</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the plot</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"blue"</span>, </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"The Bell Curve: Standard Normal Distribution"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Value"</span>, <span class="at">ylab =</span> <span class="st">"Density"</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-lecture5_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The code above demonstrates how to create a simple visualization of the bell curve for the standard normal distribution using base R. Here’s a breakdown of the key steps:</p>
<p>We first define a range of values: The <code>seq()</code> function generates a sequence of values for the x-axis. In this case, it creates 1,000 equally spaced values between -4 and 4, which is sufficient to capture the central shape of the bell curve.</p>
<p>In a second step we compute the density.The <code>dnorm()</code> function computes the probability density of the standard normal distribution at each value in the sequence. If the mean and standard deviation are not explicitly specified in <code>dnorm()</code>, the function assumes the standard normal distribution by default, with a mean of 0 and a standard deviation of 1This function is part of a family of functions for working with random variables in R: - <code>dnorm(x)</code> computes the density at <code>x</code>. - <code>pnorm(x)</code> computes the cumulative distribution function at <code>x</code>. - <code>qnorm(p)</code> gives the quantile for a given probability <code>p</code>. - <code>rnorm(n)</code> generates <code>n</code> random samples from the normal distribution.</p>
<p>We need not discuss the basic syntax of the plotting function once more at this stage, because by now we have often done so.</p>
<section id="standardization-and-the-standard-normal-distribution" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="standardization-and-the-standard-normal-distribution"><span class="header-section-number">5.2.1</span> Standardization and the Standard Normal Distribution</h3>
<p>One of the most powerful properties of the normal distribution is the ability to standardize it. By transforming any normally distributed random variable into a standard form, we unlock the ability to compare and analyze data across scales and contexts.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Standard Normal Distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>standard normal distribution</strong> is a normal distribution with a mean <span class="math inline">\(\mu = 0\)</span> and variance <span class="math inline">\(\sigma^2 = 1\)</span>. Any normally distributed random variable <span class="math inline">\(X\)</span> with mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span> can be rewritten as a standard normal random variable <span class="math inline">\(Z\)</span> using the transformation: <span class="math display">\[
Z = \frac{X - \mu}{\sigma}
\]</span> By definition, <span class="math inline">\(Z \sim N(0,1)\)</span>.</p>
</div>
</div>
<p>Here’s a draft for discussing the probability mass within 1, 2, and 3 standard deviations of the mean for the normal distribution, along with its significance:</p>
</section>
<section id="the-68-95-99.7-rule-probability-mass-in-the-normal-distribution" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="the-68-95-99.7-rule-probability-mass-in-the-normal-distribution"><span class="header-section-number">5.2.2</span> The 68-95-99.7 Rule: Probability Mass in the Normal Distribution</h3>
<p>One of the most useful properties of the normal distribution is that it has a predictable concentration of probability mass around the mean. This is often summarized by the <strong>68-95-99.7 rule</strong>, which states:</p>
<ul>
<li>Approximately <strong>68%</strong> of the data falls within <strong>1 standard deviation</strong> of the mean.</li>
<li>Approximately <strong>95%</strong> of the data falls within <strong>2 standard deviations</strong> of the mean.</li>
<li>Approximately <strong>99.7%</strong> of the data falls within <strong>3 standard deviations</strong> of the mean.</li>
</ul>
<p>This property is not only fundamental to understanding the normal distribution but also provides a quick and intuitive way to interpret variability in data, regardless of the units of measurement.</p>
<p>Why Is This Important?</p>
<ol type="1">
<li><p><strong>Universal Applicability:</strong><br>
The percentages remain the same no matter the scale or units of the data. For instance, whether we measure test scores, heights, or stock returns, this property holds for all normally distributed data.</p></li>
<li><p><strong>Quick Validation of Normality:</strong> The 68-95-99.7 rule provides a straightforward diagnostic tool for assessing whether a dataset is approximately normal. If the proportions of data falling within 1, 2, and 3 standard deviations deviate significantly from these benchmarks, it is a strong indicator that the data may not be normally distributed.</p></li>
<li><p><strong>Practical Insight:</strong><br>
It allows us to quickly assess how “unusual” a value is. For example:</p>
<ul>
<li>A value more than 2 standard deviations from the mean is relatively rare (occurring in only 5% of cases).</li>
<li>A value more than 3 standard deviations from the mean is exceptionally rare (occurring in only 0.3% of cases).</li>
</ul></li>
<li><p><strong>Decision-Making:</strong><br>
This rule aids in many practical applications, such as quality control, where v alues falling outside of 3 standard deviations might indicate defects or anomalies. Similarly, in finance, it helps in risk assessment by estimating the likelihood of extreme losses or gains.</p></li>
</ol>
<p>To illustrate this property, we can plot the standard normal distribution and shade the areas corresponding to 1, 2, and 3 standard deviations from the mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the x-axis range and density</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the plot</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"The 68-95-99.7 Rule"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Standard Deviations from the Mean"</span>, <span class="at">ylab =</span> <span class="st">"Density"</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Add shaded areas with distinct colors</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Shade 3 SD region first (light pink)</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="at">length.out =</span> <span class="dv">100</span>), <span class="dv">3</span>), </span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">dnorm</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="at">length.out =</span> <span class="dv">100</span>)), <span class="dv">0</span>),</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"#FBB4AE"</span>, <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Shade 2 SD region (light green)</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="at">length.out =</span> <span class="dv">100</span>), <span class="dv">2</span>), </span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">dnorm</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="at">length.out =</span> <span class="dv">100</span>)), <span class="dv">0</span>),</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"#CCEBC5"</span>, <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Shade 1 SD region (light blue)</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">100</span>), <span class="dv">1</span>), </span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">dnorm</span>(<span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">100</span>)), <span class="dv">0</span>),</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"#B3CDE3"</span>, <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Redraw the outline of the curve on top for clarity</span></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x, y, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Add legend positioned middle-left at y = 0.2</span></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="fl">0.2</span>, </span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"68% (1 SD)"</span>, <span class="st">"95% (2 SDs, includes 1 SD)"</span>, <span class="st">"99.7% (3 SDs, includes 1 &amp; 2 SDs)"</span>),</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"#B3CDE3"</span>, <span class="st">"#CCEBC5"</span>, <span class="st">"#FBB4AE"</span>), </span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>       <span class="at">border =</span> <span class="cn">NA</span>, <span class="at">box.lty =</span> <span class="dv">0</span>, <span class="at">bg =</span> <span class="st">"white"</span>, <span class="at">x.intersp =</span> <span class="fl">0.5</span>, <span class="at">y.intersp =</span> <span class="fl">1.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-lecture5_files/figure-html/visualize-probability-mass-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To confirm these proportions, we compute the probabilities using R’s cumulative distribution function (<code>pnorm</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilities for 1, 2, and 3 standard deviations</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="dv">1</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">1</span>)  <span class="co"># ~68%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="dv">2</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">2</span>)  <span class="co"># ~95%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="dv">3</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">3</span>)  <span class="co"># ~99.7%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Probability within 1 SD: "</span>, p1, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probability within 1 SD:  0.6826895 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Probability within 2 SDs: "</span>, p2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probability within 2 SDs:  0.9544997 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Probability within 3 SDs: "</span>, p3, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probability within 3 SDs:  0.9973002 </code></pre>
</div>
</div>
<p>These results reinforce the importance of the 68-95-99.7 rule as a tool for interpreting data variability and making informed decisions.</p>
</section>
</section>
<section id="lognormal-distribution" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="lognormal-distribution"><span class="header-section-number">5.3</span> Lognormal Distribution</h2>
<p>While the normal distribution models many natural and financial phenomena, it is not always suitable for modeling certain quantities—such as stock prices—that are constrained to be positive. This is where the <strong>lognormal distribution</strong> becomes essential. It serves as a natural model for variables that are strictly positive and exhibit multiplicative growth, such as asset prices in financial markets.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Lognormal Distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>lognormal random variable</strong> <span class="math inline">\(Y\)</span> is one whose natural logarithm is normally distributed. If <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span>, then <span class="math inline">\(Y = \exp(X)\)</span> follows a lognormal distribution. The probability density function of <span class="math inline">\(Y\)</span> is given by: <span class="math display">\[
f(y, \mu, \sigma) = \frac{1}{y \sigma \sqrt{2 \pi}} \exp\left(-\frac{(\ln y - \mu)^2}{2 \sigma^2}\right), \quad y &gt; 0.
\]</span></p>
</div>
</div>
<section id="why-the-lognormal-distribution-for-stock-prices" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="why-the-lognormal-distribution-for-stock-prices"><span class="header-section-number">5.3.1</span> Why the Lognormal Distribution for Stock Prices?</h3>
<p>Stock prices, by their nature, cannot fall below zero and often grow in a multiplicative manner over time. If the logarithm of a stock price follows a normal distribution, then the stock price itself is lognormally distributed. This aligns with the widely used geometric Brownian motion model This aligns with the widely used geometric Brownian motion model for stock price dynamics.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>In finance, returns are a natural way to measure changes in stock prices over time. Remember that for a discrete time interval, the return is defined as: <span class="math display">\[
R = \frac{S_t - S_0}{S_0},
\]</span> where <span class="math inline">\(S_0\)</span> is the initial price and <span class="math inline">\(S_t\)</span> is the price at time <span class="math inline">\(t\)</span>. However, this formulation has limitations for very short time intervals or when returns are compounded over time.</p>
<p>Instead, <strong>logarithmic returns</strong> (or continuously compounded returns) are defined as: <span class="math display">\[
r = \ln\left(\frac{S_t}{S_0}\right).
\]</span> This definition arises naturally because it allows for: 1. <strong>Additivity in Continuous Time:</strong><br>
Over small time intervals, the log of cumulative returns adds up, making it easy to model and sum returns over time. For instance, if a stock moves from <span class="math inline">\(S_0\)</span> to <span class="math inline">\(S_t\)</span> and then to <span class="math inline">\(S_T\)</span>, the total log return is: <span class="math display">\[
   r = \ln\left(\frac{S_t}{S_0}\right) + \ln\left(\frac{S_T}{S_t}\right) = \ln\left(\frac{S_T}{S_0}\right).
   \]</span> This property simplifies modeling in continuous time frameworks.</p>
<ol start="2" type="1">
<li><p><strong>Consistency with Compounding:</strong><br>
Financial returns often compound multiplicatively (e.g., reinvested dividends or reinvested profits). Logarithmic returns handle compounding naturally and ensure that the total return across intervals corresponds to the product of growth factors.</p></li>
<li><p><strong>Symmetry in Statistical Analysis:</strong><br>
While absolute returns can grow unboundedly in a positive direction, logarithmic returns are symmetric around the mean, simplifying statistical analysis and aligning better with the assumptions of models like geometric Brownian motion.</p></li>
</ol>
<p>When stock prices follow geometric Brownian motion, their logarithmic returns <span class="math inline">\(r\)</span> are normally distributed: <span class="math display">\[
r \sim N(\mu, \sigma^2),
\]</span> where <span class="math inline">\(\mu\)</span> is the mean log return and <span class="math inline">\(\sigma^2\)</span> is the variance. As a result, the stock price itself, given by <span class="math inline">\(S_t = S_0 \exp(r)\)</span>, follows a lognormal distribution. The lognormal distribution is particularly suitable for stock prices because:</p>
<ul>
<li><strong>Positive Skewness:</strong> It allows for rare but extreme positive returns, reflecting real-world market behavior.</li>
<li><strong>Non-Negativity:</strong> Stock prices cannot fall below zero.</li>
<li><strong>Compounding Effects:</strong> It captures the multiplicative nature of price movements over time.</li>
</ul>
</section>
<section id="comparing-real-stock-data-with-the-lognormal-distribution" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="comparing-real-stock-data-with-the-lognormal-distribution"><span class="header-section-number">5.3.2</span> Comparing Real Stock Data with the Lognormal Distribution</h3>
<p>To connect the theoretical discussion with real-world data, we’ll analyze historical stock prices from the S&amp;P 500 index. Using data from Yahoo Finance, we compute daily log returns, overlay the empirical distribution with a fitted lognormal distribution, and discuss the fit’s implications.</p>
<p>Let’s use our R-tools fro overlaying empirical data with the theoretical model of the random variable.</p>
<p>We first load tidyquant:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyquant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then we fit the model to actual stock market data for the SP500.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-lecture5_files/figure-html/lognormal-fit-sp500-tidyquant-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The R-code behind this visualization is somewhat involved and I will not go through it here because I want to focus on a more important point of potential confusion, which needs to be explained carefully. Those of you who want to look at the code just unfold the code chunk.</p>
<p>So what are we doing here? We started by assuming that <strong>stock prices follow a lognormal distribution</strong><br>
- Prices are <strong>strictly positive</strong>, which makes the <strong>lognormal</strong> distribution a natural choice. - If <span class="math inline">\(S_t\)</span> is a stock price and follows geometric Brownian motion:</p>
<p><span class="math display">\[
S_t = S_0 \exp(X_t)
\]</span> where <span class="math inline">\(X_t\)</span> is normally distributed.</p>
<p>By our assumption that stock prices are modeled by a lognormal distribution, <strong>log-returns follow a normal distribution</strong></p>
<ul>
<li>Returns are often modeled as additive over time.</li>
<li><strong>Log-returns</strong> are defined as: <span class="math display">\[
r_t = \ln\left(\frac{S_t}{S_{t-1}}\right)
\]</span></li>
<li>If stock prices follow a <strong>lognormal</strong> distribution, then <strong>log-returns</strong> must follow a <strong>normal</strong> distribution.</li>
</ul>
<p>We work with <strong>log-returns</strong> because they simplify calculations, but prices are what we observe. It would be a mistake to fitting a lognormal distribution to log-returns (instead of prices). The correct modeling framework depends on whether we are working with <strong>prices or returns</strong>.</p>
<p>Let me summarize these remarks in a side by side comparison table.</p>
<table class="table">
<colgroup>
<col style="width: 34%">
<col style="width: 44%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Distribution</th>
<th>Why?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Stock Prices <span class="math inline">\(S_t\)</span></td>
<td>Lognormal</td>
<td>Prices can’t be negative, and returns compound multiplicatively.</td>
</tr>
<tr class="even">
<td>Log-Returns <span class="math inline">\(r_t\)</span></td>
<td>Normal</td>
<td>Returns add over time and often appear symmetric.</td>
</tr>
</tbody>
</table>
<p>Now let us go back to the discussion of what we see in the graph:</p>
<ol type="1">
<li><p><strong>Fat Tails:</strong><br>
The empirical distribution may display so called <strong>fat tails</strong>, meaning extreme returns are more frequent in real data than predicted by the lognormal model. These events are crucial for risk assessment and portfolio stress testing.</p>
<p>To see more clearly whether we have fat tails in our daily log return data, let us visually zoom in to the region of more extreme negative returns.</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-lecture5_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To put this graph into perspective remember the <strong>68-95-99.7 rule</strong>. It tells us that in a normal distribution:</p>
<ul>
<li>About <strong>68%</strong> of observations fall within <strong>1 standard deviation</strong> of the mean.</li>
<li>About <strong>95%</strong> fall within <strong>2 standard deviations</strong>.</li>
<li>About <strong>99.7%</strong> fall within <strong>3 standard deviations</strong>.</li>
</ul>
<p>If <strong>daily log-returns</strong> followed a normal distribution, we would expect <strong>only 0.15% of observations</strong> to be more extreme than <strong>-3σ</strong>. However, in our empirical data, <strong>0.99% of returns</strong> fall below this threshold—<strong>more than six times the expected frequency</strong>.</p>
<p>This gives us a <strong>critical insight for risk management</strong>:</p>
<ul>
<li><p><strong>Normal models underestimate extreme downside risk</strong>—leading to potential miscalculations in risk measures like <strong>Value-at-Risk (VaR)</strong>, a concept we will discuss later in more detail.</p></li>
<li><p>Market downturns often exhibit far worse losses than a normal distribution would predict.</p></li>
<li><p>Alternative distributions, such as the <strong>t-distribution</strong> or <strong>generalized extreme value (GEV) models</strong>, may be better suited to capturing these extreme tail risks.</p></li>
</ul>
<ol start="2" type="1">
<li><strong>Asymmetry (Skewness):</strong><br>
Real stock returns often show <strong>negative skewness</strong>, where extreme negative returns (e.g., during crashes) are more pronounced than extreme positive returns.</li>
</ol>
<p>This is another critical property of financial returns which is <strong>asymmetry</strong>, or <strong>skewness</strong>.</p>
<p>What Does Skewness Mean? A normal distribution is <strong>symmetric</strong>, meaning that extreme positive and negative values are equally likely. However, real-world stock returns often show negative skewness, meaning that large negative returns occur more frequently than large positive returns. This asymmetry is particularly visible during market crashes, when prices tend to decline much faster than they rise during bull markets.</p>
<p>In our <strong>fat-tail visualization</strong>, we focused on the <strong>left tail</strong> of the distribution (extreme losses). If stock returns were truly <strong>symmetric</strong>, we would expect to see a similar excess probability mass on the <strong>right tail</strong> (large gains). However: The left tail extends much further and is more pronounced than the right. Large losses tend to be larger in magnitude than large gains.</p>
<p>This is why risk management focuses more on downside risk —investors care more about avoiding catastrophic losses than capturing rare, extreme gains.</p>
<p>To quantify this asymmetry, we can compute the <strong>skewness statistic</strong> of our dataset. A normal distribution has a skewness of 0, while: Negative skewness (&lt; 0) indicates that the left tail is heavier than the right. Positive skewness (&gt; 0) indicates the opposite. In our data the skewness is</p>
<p>-1.05. For reference: A normal distribution has a skewness of 0 (perfect symmetry). A skewness of -1.05 indicates a strongly asymmetric distribution with heavier left tails.</p>
</section>
<section id="applications-and-limitations-a-balanced-perspective" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="applications-and-limitations-a-balanced-perspective"><span class="header-section-number">5.3.3</span> Applications and Limitations: A Balanced Perspective</h3>
<p>Looking at our empirical data, we see that the normal approximation to log-returns fits quite well in the center of the distribution. You can check for yourself that as you go to considering weekly or monthly returns instead of daily ones this fit in the center becomes actually quite good. The lognormal model remains a widely used and valuable framework for understanding stock price dynamics.</p>
<p>However, while the center of the distribution aligns well with theory, the tails remain problematic. As we saw in the fat-tail visualization, extreme negative returns occur far more often than a normal model would suggest. This is a critical issue in risk management, where tail events—such as financial crises or sudden market drops—can have disproportionate consequences.</p>
<p>That said, in many other applications, where the focus is on general trends, valuation models, or portfolio optimization, a good fit in the center may be sufficient. The profession does not work with a “wrong” model—rather, different models are used depending on the question being asked. For example:</p>
<ul>
<li>In option pricing (Black-Scholes), the lognormal assumption is a reasonable starting point, though corrections (e.g., stochastic volatility models) are often needed.</li>
<li>In long-term investment strategies, where extreme short-term fluctuations average out, the normal/lognormal framework remains quite effective.</li>
</ul>
<p>Thus, while tail risks must be explicitly accounted for in risk management, the lognormal assumption remains a useful and practical tool in many areas of finance.</p>
</section>
</section>
<section id="inverse-normal-and-quantiles-in-risk-management" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="inverse-normal-and-quantiles-in-risk-management"><span class="header-section-number">5.4</span> Inverse Normal and Quantiles in Risk Management</h2>
<p>In risk management, a fundamental question is:</p>
<p>What is the worst-case loss I should expect, given a certain probability threshold?</p>
<p>This is different from what we studied earlier. Previously, we were given a threshold and asked for the probability of falling below it. Now, we flip the question:</p>
<ul>
<li>We are given a probability (e.g., 1%)</li>
<li>We want to find the threshold such that losses exceed it only with that probability.</li>
</ul>
<p>This is known as the inverse problem in probability, and it plays a central role in Value at Risk (VaR) calculations.</p>
<p>Suppose you manage a portfolio with uncertain (random) returns. A key risk management question is:</p>
<p>How large can losses be over a given time horizon, with a probability of only 1% (or another predefined risk threshold)?</p>
<p>For example, a bank may want to ensure that the probability of losing more than a certain percentage of its capital remains below 1%. In this case, the 1% quantile of portfolio returns (often called the 1% Value at Risk, or VaR) is the key statistic.</p>
<section id="the-inverse-normal-function-in-r" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="the-inverse-normal-function-in-r"><span class="header-section-number">5.4.1</span> The Inverse Normal Function in R</h3>
<p>The quantile function (or inverse cumulative distribution function) helps solve this problem. For a normally distributed random variable <span class="math inline">\(X\)</span>, we want to find the threshold <span class="math inline">\(x\)</span> such that: <span class="math inline">\(P(X≤x)=p\)</span> where <span class="math inline">\(p\)</span> is a given probability.</p>
<p>In R, we compute this using the <code>qnorm()</code> function. Let’s demonstrate how it works using our data from before:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.01</span>, <span class="at">mean =</span> <span class="fu">mean</span>(log_returns), <span class="at">sd =</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(log_returns)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.02709901</code></pre>
</div>
</div>
<p>This function finds the 1% quantile of a normal distribution with a given mean and a given standard deviation derived from the logarithmic returns of the SP500. It answers the question:</p>
<p>What is the worst-case daily return we should expect, such that losses exceed this level only 1% of the time?</p>
<p>This is often referred to as the inverse normal problem, since it inverts the cumulative distribution function (CDF). Definition: Quantile</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
p-quantile
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <span class="math inline">\(p\)</span>-th quantile (or percentile) of a probability distribution is the value <span class="math inline">\(x\)</span> such that: <span class="math display">\[
P(X≤x)=p
\]</span> If <span class="math inline">\(X\)</span> is normally distributed, i.e., <span class="math inline">\(X\sim N(\mu,\sigma^2)\)</span>, then: <span class="math display">\[
x=F^{−1}(p),
\]</span></p>
<p>where <span class="math inline">\(F^{−1}\)</span> is the inverse CDF (quantile function) of the normal distribution with parameters <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>.</p>
</div>
</div>
<p>The <strong>median</strong> is the 50% quantile (<span class="math inline">\(P(X≤x)=0.5\)</span>), dividing the distribution in half. The <strong>1%-quantile</strong> (or 99% left-tail quantile) gives us a worst-case threshold, which is critical for risk management models, like value at risk. You can consider any other percentile you might be interested in in this way.</p>
<p>The inverse CDF is essential in many areas of finance, including risk management, stress testing, and capital adequacy planning.</p>
<p>Now that we understand quantiles and the inverse normal, we can directly apply this concept to Value at Risk (VaR).</p>
</section>
</section>
<section id="value-at-risk" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="value-at-risk"><span class="header-section-number">5.5</span> Value at risk</h2>
<p>Designing portfolios in a way that enable an acceptable trade off between risk of loss and the potential for profit is a key consideration in portfolio management. Quantitative risk measures are one way to achieve goals like this.</p>
<p>Quantitative measures of risk a broad topic that we can not fully cover here. But one particular popular risk measure <strong>value at risk</strong> is directly based on the concept of quantiles of a normally distributed random variable and thus is the perfect application case for appreciating the significance of quantiles as an analytical tool in finance.</p>
<p>Let us imagine a financial position modeled by a continuous random variable <span class="math inline">\(X\)</span> denoting the change in value of a position at a given future time <span class="math inline">\(T\)</span>. In general the variable may take on either positive or negative values depending on its realization. We refer to the random variable <span class="math inline">\(X\)</span> for convenience as <strong>position</strong>. From the risk perspective, we may focus on the associated loss, which is <span class="math inline">\(-X\)</span>.</p>
<p>The concept of <strong>value at risk</strong> (abbreviated VaR) is motivated by the concern about loss. We start by specifying a <strong>loss tolerance</strong> <span class="math inline">\(h\)</span> between 0 and 1 and a companion <strong>confidence level</strong> equal to <span class="math inline">\(1-h\)</span>. For example, we could choose a loss tolerance <span class="math inline">\(h=0.05\)</span> and a corresponding confidence level of <span class="math inline">\(1-h = 0.95\)</span></p>
<p>For a particular position <span class="math inline">\(X\)</span> and a given loss tolerance <span class="math inline">\(h\)</span>, VaR is then the smallest number <span class="math inline">\(V\)</span> such that the probability of a loss greater than <span class="math inline">\(V\)</span> is no more than <span class="math inline">\(h\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Value at risk
</div>
</div>
<div class="callout-body-container callout-body">
<p>For a given position <span class="math inline">\(X\)</span> and a given loss toleracne <span class="math inline">\(h\)</span>, VaR is the smallest number <span class="math inline">\(V\)</span> such that the probability of a loss greater tan <span class="math inline">\(V\)</span> is no more than <span class="math inline">\(h\)</span>:</p>
<p><span class="math display">\[
VaR_h(X) = \min_{h} \{ V: P\left[ - X &gt; V \right] \leq h \}
\]</span> Equivalently, VaR is the smallest number <span class="math inline">\(V\)</span> such that the probability of the loss beeing no more than <span class="math inline">\(V\)</span> is gretaer than <span class="math inline">\(1-h\)</span> or:</p>
<p><span class="math display">\[
VaR_h(X) = \min_{h} \{ V: P\left[ - X \leq V \right] &gt; 1 - h \}
\]</span></p>
</div>
</div>
<p>Here is a visualization:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-lecture5_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>95% Value at Risk (VaR) Visualization</figcaption>
</figure>
</div>
</div>
</div>
<p>The graph illustrates the 95% Value at Risk (VaR) concept using a normal distribution of daily portfolio log returns. The blue curve represents the probability density function of log-returns. The red-shaded area on the left highlights the 5% tail probability, indicating extreme negative returns that occur with only a 5% likelihood. The green-shaded area represents the complementary 95% probability mass, where returns are expected to fall under normal conditions.</p>
<p>Two vertical dashed lines mark key reference points:</p>
<ul>
<li>The black dashed line represents the mean return (expected value).</li>
<li>The red dashed line represents the VaR threshold, the level of loss that is only exceeded 5% of the time.</li>
</ul>
<p>This visualization helps quantify downside risk: A risk manager using VaR at 95% confidence would focus on the red-shaded region to assess the worst-case loss threshold. However, as we have seen with empirical stock return data, real-world distributions often exhibit fat tails, meaning extreme losses occur more frequently than the normal model predicts. This suggests that while VaR is a useful benchmark, adjustments may be needed for more accurate risk assessments.</p>
<p>The value at risk as defined here and in the literture comes with an implicit definition of a given time horizon <span class="math inline">\(T\)</span> at which <span class="math inline">\(X\)</span> is realized. If the position is liquid this horizon may be one or a few days. Often there are also regulatry requirements setting the rules how this horizon can or must be chosen.</p>
<p>Now you can see how the concepts of the inverse normal can be directly brough to bear in the case of normally distributed log returns of stock prices.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Proposition: VaR for the normal distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose <span class="math inline">\(X\)</span> follows a normal distribution with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>. Then</p>
<p><span class="math display">\[
VaR_h(X) = - \sigma \, F^{-1}_N(h) - \mu
\]</span> where <span class="math inline">\(F_N\)</span> is the cumulative probability distribution function of the standardized normal variable (with mean 0 and standard deviation 1).</p>
</div>
</div>
<p>Here’s a structured <strong>draft</strong> covering the <strong>three Value at Risk (VaR) examples</strong> along with <strong>R code</strong> to illustrate each case.</p>
<p>Let’s consider three examples:</p>
<p><strong>Example 1: Highly Liquid Portfolio with Small Mean Return</strong></p>
<p>A <strong>highly liquid portfolio</strong> consists of assets that can be easily bought or sold with minimal impact on price. Examples include:</p>
<ul>
<li>Short-term U.S. Treasury bills</li>
<li>Large-cap ETFs (e.g., SPY, QQQ)</li>
<li>Highly traded currency pairs (EUR/USD, USD/JPY)</li>
</ul>
<p>For such portfolios: Expected returns are very small over short time horizons. VaR is then mainly driven by portfolio variance (volatility) rather than the mean return. In this case the VaR can be approximated as: <span class="math display">\[
  VaR_{95\%} \approx 1.65 \times \sigma
\]</span> since the mean return is negligible over short periods and <span class="math inline">\(-F^{-1}_N(0.05) = 1.65\)</span>. Check using the quantile function of the normal distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.05</span>)<span class="sc">*</span>(<span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.644854</code></pre>
</div>
</div>
<p>Here is a numerical R-example for typical values of such a portfolio</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define parameters</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>sigma_liquid <span class="ot">&lt;-</span> <span class="fl">0.015</span>  <span class="co"># 1.5% daily volatility (assumption)</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>mu_liquid <span class="ot">&lt;-</span> <span class="dv">0</span>         <span class="co"># Negligible mean return</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span>          <span class="co"># 95% confidence level</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute 1-day VaR</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>VaR_liquid <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alpha, <span class="at">mean =</span> mu_liquid, <span class="at">sd =</span> sigma_liquid)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Output result</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"1-day 95%% VaR for a highly liquid portfolio: %.4f (or %.2f%%)"</span>, VaR_liquid, VaR_liquid <span class="sc">*</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "1-day 95% VaR for a highly liquid portfolio: -0.0247 (or -2.47%)"</code></pre>
</div>
</div>
<p>For a <strong>highly liquid</strong> asset with daily volatility of <strong>1.5%</strong>, the <strong>1-day 95% VaR</strong> is approximately <strong>-2.47%</strong>, meaning that on 5% of days, the portfolio could lose at least 2.47%** under normal conditions.</p>
<p><strong>Example 2: A pension fund</strong>:</p>
<p>Let’s consider next the example of a <strong>10-Day VaR for a Pension Fund</strong>. A pension fund typically invests in a <strong>diversified mix of stocks, bonds, and alternative assets</strong>. Suppose a fund manager wants to compute <strong>10-day VaR</strong> for a <strong>$500 million endowment</strong>.</p>
<p>To scale VaR from <strong>1-day to N-days</strong>, we assume returns follow a <strong>normal distribution</strong> and use the square-root rule:</p>
<p><span class="math display">\[
VaR_{N-\text{day}} = VaR_{1-\text{day}} \times \sqrt{N}
\]</span> Here is a numerical R-example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define parameters</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>sigma_fund <span class="ot">&lt;-</span> <span class="fl">0.02</span>    <span class="co"># 2% daily volatility</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>mu_fund <span class="ot">&lt;-</span> <span class="fl">0.0002</span>     <span class="co"># 0.02% daily return (assumed)</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10</span>               <span class="co"># 10-day horizon</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>portfolio_value <span class="ot">&lt;-</span> <span class="dv">500</span> <span class="co"># $500 million</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute 1-day VaR</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>VaR_fund_1d <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alpha, <span class="at">mean =</span> mu_fund, <span class="at">sd =</span> sigma_fund)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute 10-day VaR using square-root scaling</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>VaR_fund_10d <span class="ot">&lt;-</span> VaR_fund_1d <span class="sc">*</span> <span class="fu">sqrt</span>(N) <span class="sc">*</span> portfolio_value</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Output result</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"10-day 95%% VaR for a $500M pension fund: $%.2f million"</span>, VaR_fund_10d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "10-day 95% VaR for a $500M pension fund: $-51.70 million"</code></pre>
</div>
</div>
<p>For a pension fund with 2% daily volatility, a $ 500 million portfolio, and a 10-day horizon, the 10-day 95% VaR is around $ X million. This means the fund can expect to lose at least this amount over a 10-day period with 5% probability.</p>
<p><strong>Example 3: Portfolio diversification</strong>: Finally, let’s look at the example of a diversified portfolio. Now, suppose the pension fund invests 50% in equities and 50% in bonds, with:</p>
<ul>
<li>Stock volatility = 2.5%</li>
<li>Bond volatility = 1.0%</li>
<li>Negative correlation (-0.3) between stocks and bonds</li>
</ul>
<p>Under normal conditions, VaR satisfies subadditivity:</p>
<p><span class="math display">\[
VaR(A + B) \leq VaR(A) + VaR(B)
\]</span></p>
<p>which means <strong>diversification reduces overall risk</strong>.</p>
<p>Here is a numerical R-example_</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define portfolio components</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>sigma_stocks <span class="ot">&lt;-</span> <span class="fl">0.025</span>  <span class="co"># 2.5% daily volatility</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>sigma_bonds <span class="ot">&lt;-</span> <span class="fl">0.01</span>    <span class="co"># 1.0% daily volatility</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>w_stocks <span class="ot">&lt;-</span> <span class="fl">0.5</span>        <span class="co"># 50% allocation to stocks</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>w_bonds <span class="ot">&lt;-</span> <span class="fl">0.5</span>         <span class="co"># 50% allocation to bonds</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.3</span>    <span class="co"># Negative correlation</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute portfolio volatility</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>portfolio_volatility <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  (w_stocks <span class="sc">*</span> sigma_stocks)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  (w_bonds <span class="sc">*</span> sigma_bonds)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2</span> <span class="sc">*</span> w_stocks <span class="sc">*</span> w_bonds <span class="sc">*</span> sigma_stocks <span class="sc">*</span> sigma_bonds <span class="sc">*</span> correlation</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute portfolio VaR</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>VaR_portfolio <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alpha, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> portfolio_volatility) <span class="sc">*</span> portfolio_value</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute individual VaRs</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>VaR_stocks <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alpha, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> sigma_stocks) <span class="sc">*</span> (w_stocks <span class="sc">*</span> portfolio_value)</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>VaR_bonds <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(alpha, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> sigma_bonds) <span class="sc">*</span> (w_bonds <span class="sc">*</span> portfolio_value)</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Output results</span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"VaR without diversification: $%.2f million"</span>, VaR_stocks <span class="sc">+</span> VaR_bonds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "VaR without diversification: $-14.39 million"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"VaR with diversification: $%.2f million"</span>, VaR_portfolio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "VaR with diversification: $-9.86 million"</code></pre>
</div>
</div>
<p>Without diversification, the combined VaR of individual assets would be higher than the VaR of the diversified portfolio. This illustrates the subadditivity property of VaR, which states that risk should not increase when assets are combined. However, this property holds only when log-returns follow a normal distribution. If the normality assumption does not hold—such as in cases with fat tails, skewness, or extreme market events—VaR may no longer be subadditive, and diversification benefits could be overestimated. If you are interested in details of risk management the go to referecne is still <span class="citation" data-cites="McNeilEmbrechtsFrey2015">McNeil, Embrechts, and Frey (<a href="06-references.html#ref-McNeilEmbrechtsFrey2015" role="doc-biblioref">2015</a>)</span>.</p>
</section>
<section id="empirical-value-at-risk-var-and-its-limitations" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="empirical-value-at-risk-var-and-its-limitations"><span class="header-section-number">5.6</span> Empirical Value at Risk (VaR) and Its Limitations</h2>
<p>So far, we have used parametric VaR based on the normal distribution. However, we can also estimate VaR empirically, directly from historical data, without assuming a particular distribution.</p>
<p>To compute the empirical 95% VaR, we:</p>
<ol type="1">
<li>Sort the historical log returns in ascending order.</li>
<li>Find the return at the 5th percentile of the empirical distribution.</li>
</ol>
<p>For a <strong>10-day VaR</strong>, we use <strong>weekly returns</strong> rather than daily data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert daily log returns to 5-day log returns by summing </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co">#over non-overlapping 5-day periods</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>log_returns_10d <span class="ot">&lt;-</span> </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colSums</span>(<span class="fu">matrix</span>(log_returns, <span class="at">nrow =</span> <span class="dv">5</span>, </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">byrow =</span> <span class="cn">TRUE</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in matrix(log_returns, nrow = 5, byrow = TRUE): data length [1509] is
not a sub-multiple or multiple of the number of rows [5]</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort 10-day log returns in ascending order</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>sorted_returns <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">na.omit</span>(log_returns_10d))</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute empirical cumulative distribution function (ECDF)</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(sorted_returns)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>ecdf_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, n) <span class="sc">/</span> n  <span class="co"># Explicitly named for clarity</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify empirical quantiles for 95% and 99% VaR</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>VaR_95_empirical <span class="ot">&lt;-</span> sorted_returns[<span class="fu">min</span>(<span class="fu">which</span>(ecdf_values <span class="sc">&gt;=</span> <span class="fl">0.05</span>))]</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>VaR_99_empirical <span class="ot">&lt;-</span> sorted_returns[<span class="fu">min</span>(<span class="fu">which</span>(ecdf_values <span class="sc">&gt;=</span> <span class="fl">0.01</span>))]</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Output results</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"Empirical 95%% VaR: %.4f (10-day horizon)"</span>, VaR_95_empirical)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Empirical 95% VaR: -0.0386 (10-day horizon)"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"Empirical 99%% VaR: %.4f (10-day horizon)"</span>, VaR_99_empirical)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Empirical 99% VaR: -0.0866 (10-day horizon)"</code></pre>
</div>
</div>
<p>The 95% empirical VaR** suggests that, based purely on historical data, the worst 5% of observed weeks had returns of at least -4% or lower. The 99% empirical VaR tells us that in the worst 1% of historical weeks, losses exceeded -0.09.</p>
<p>Let’s look at a visualization:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-lecture5_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Empirical CDF of 5-Day Log Returns with 95% and 99% VaR Thresholds</figcaption>
</figure>
</div>
</div>
</div>
<p>Empirical VaRs are straightforward but they also have <strong>important limitations</strong>, particularly with small samples:</p>
<ul>
<li>If we only have a few years of weekly returns, the 5th percentile may be based on very few observations.</li>
<li>VaR then depends heavily on the worst few weeks, making it unreliable.</li>
<li>The 99% quantile requires even fewer observations, making it very sensitive to individual extreme weeks.</li>
<li>More advanced techniques (such as Extreme Value Theory (EVT)) can help estimate tail risks beyond observed data.</li>
<li>If we haven’t observed an extreme event, empirical VaR ignores it.</li>
<li>This happened in the case of <strong>Long-Term Capital Management (LTCM)</strong>.</li>
</ul>
<p><strong>Example: The LTCM Case: A Real-World Lesson</strong> In the late 1990s, the hedge fund <strong>Long-Term Capital Management (LTCM)</strong> collapsed due to ignoring large, low-probability tail risks. The fund’s risk models were based on historical market behavior, assuming that extreme losses were too unlikely to be of concern.</p>
<p>However, during the 1998 Russian financial crisis, markets experienced far greater volatility than LTCM had anticipated. The fund suffered catastrophic losses, requiring a $3.6 billion bailout coordinated by the Federal Reserve to prevent wider market contagion.</p>
<p>For those of you who are interested in <strong>advanced risk modeling</strong>, a deeper discussion can be found in <span class="citation" data-cites="McNeilEmbrechtsFrey2015">McNeil, Embrechts, and Frey (<a href="06-references.html#ref-McNeilEmbrechtsFrey2015" role="doc-biblioref">2015</a>)</span>.</p>
</section>
<section id="data-and-statistics" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="data-and-statistics"><span class="header-section-number">5.7</span> Data and statistics</h2>
<p>Over the course we have now so many times estimated moments for log-returns and then plugged theses estimates into our software provided functions. It seems necessary at this stage to clarify a few things about the statistics of return data.</p>
<p>Unlike in probability, where we start from the assumption of a random model, typically one or many random variables and think about the consequences for the outcomes, like the properties shape and moments of the distribution and so on, in statistics we take the reverse perspective. We observe data and then try to find out what could be the random variables that might have generated these data, if there is a random process in the background of our observations.</p>
<p>I would therefore like to discuss some key issues in the empirical analysis of return data. The key data source for estimation is historical returns data, which are today available on the internet at daily frequency. This approach is reasonably reliable fro some parameters such as variances and covariances. It is, however, decidedly <strong>unreliable</strong> for other parameters such as expected return. The reason why I want to discuss this problem is that the root cause is a fundamental limitation of the estimation process not the quality of the data or measurement.</p>
<section id="peridod-length-effects" class="level3" data-number="5.7.1">
<h3 data-number="5.7.1" class="anchored" data-anchor-id="peridod-length-effects"><span class="header-section-number">5.7.1</span> Peridod-Length Effects</h3>
<p>Suppose that the annual return of a stock is <span class="math inline">\(1+r_y\)</span>. It can be thought of as the result of 12 monthly returns and can be written as a product <span class="math display">\[
1+r_y = (1+r_1)(1+r_2)(1+r_3)\dots (1+r_{12})
\]</span> Note that in this equation tge monthly returns are not measured per annum. They are the actual returns over a month. If the returns are small, we can expand the product and keep only the first order terms as a good approximation: <span class="math display">\[
1+r_y \approx 1 + r_1 + r_2 + r_3 + \dots + r_{12}
\]</span> In this approximation the compounding effects are ignored, which is for the purpose of a rough estimates of orders of magnitude of parameters good enough.</p>
<p>Now let’s think about these returns from the perspective of probability theory and imagine that there is an underlying random variable model generating them. Let these random variables be mutually uncorrelated and each monthly return <span class="math inline">\(r_i\)</span> has the same expected value <span class="math inline">\(\bar{r}\)</span> and the same variance <span class="math inline">\(\sigma^2\)</span>. using our approximation we find that <span class="math display">\[
\bar{r_y} = 12\, \bar{r}
\]</span> Likewise <span class="math display">\[
\sigma_y^2 = \mathbb{E}\left[ \sum_{i=1}^{12}(r_i-\bar{r}) \right] = \mathbb{E}\left[ \sum_{i=1}^{12}(r_i - \bar{r})^2 \right] = 12 \sigma^2
\]</span> where the pull of the exponent into the squared brackets is a consequence of the assumption that the returns are uncorrelated. Now turn these equations around and taking the suqare root of the variance, we obtain an expression for the monthly values in terms of annual values <span class="math display">\[\begin{eqnarray*}
\bar{r} &amp;=&amp; \frac{1}{12} \bar{r}_y \\
\bar{\sigma} &amp;=&amp; \frac{1}{\sqrt{12}} \sigma_y
\end{eqnarray*}\]</span> This can be generalized to any length of period. If the period is <span class="math inline">\(p\)</span> part of a year (expressed as a fraction of a year) then the expected return and the standard error of the 1-period rate of return can be found by generalizing from monthly periods <span class="math inline">\(p = 1/12\)</span>. This gives us</p>
<p><span class="math display">\[\begin{eqnarray*}
\bar{r_p}&amp;=&amp; p \, \bar{r}_y \\
\bar{\sigma_p}&amp;=&amp; \sqrt{p} \, \sigma_y
\end{eqnarray*}\]</span></p>
<p>Because the expected return decreases linearly with the period, the standard deviation is proportional to the square root of the length of the period. Therefore the ratio if the two <strong>increases dramatically</strong> as the length is reduced. In the limit, as the length goes to zero, this ratio diverges. Thus rates of return for small perios have high standard deviations compared to their expected values.</p>
<p>Let#s put this into perspective. The mean annual return for stocks ranges from around <span class="math inline">\(6%\)</span> to <span class="math inline">\(30%\)</span> with a typical value at around <span class="math inline">\(12%\)</span>. These mean values change over time so any particual value is meaningful roughly for about 2 or three years. The standard deviation of yearly stock returns ranges from 10% to 60% with typically 15%.</p>
<p>Let#s translate these numbers into monthly values, thus <span class="math inline">\(p=1/12\)</span>. With <span class="math inline">\(\bar{r}_y = 12 %\)</span> and and <span class="math inline">\(\sigma_y = 15%\)</span> this leds to $r_{1/12} = 1% and $_{1/12} = 4.33%. So while for the yearly figure the ratio is 1.25 it is 4.3 for the monthly.</p>
<p>If we assume the returns are generated through independent daily returns and assume 25o trading days then <span class="math inline">\(\r_{1/250} = 0.048\)</span> % and <span class="math inline">\(\sigma_{1/250} = 0.95\)</span> %. The ratio is now 19.8.</p>
<p>Now we can show how this amplification effect makes the estimation of expected mean rates nearly impossible. Let’s select a basic period length <span class="math inline">\(p\)</span> and try to estimate the mean for this period. We assume that the returns of each period are independent random variables with mean <span class="math inline">\(\bar{r}\)</span> and standard error <span class="math inline">\(\sigma\)</span>. We also assume that individual returns are mtually uncorrelated.</p>
<p>Suppose we have <span class="math inline">\(n\)</span> samples of period returns The best estimate for the mean is <span class="math display">\[
\hat{\bar{r}} = \frac{1}{n} \sum_{i=1}^n r_i
\]</span></p>
<p>The estimate is itself a random variables. If we used different samples, we got different v alues for this estimate. However the expected value of the estimate is the true value <span class="math display">\[
\mathbb{E}(\hat{\bar{r}}) = \hat{\mathbb{E}} \left( \frac{1}{n} \sum_{i = 1}^n r_i \right) = \bar{r}
\]</span> We compute the standard deviation of the estimate to asess the accuracy of the estimator for the mean returns. <span class="math display">\[
\sigma_{\hat{\bar{r}}}^2 = \mathbb{E} \left[ (\hat{\bar{r}} - \bar{r})^2 \right] = \mathbb{E}\left[\frac{1}{n} \sum_{i=1}^n (r_i - \bar{r}) \right]^2 = \frac{1}{n} \sigma^2
\]</span> Hence <span class="math display">\[
\sigma_{\hat{\bar{r}}} = \frac{\sigma}{\sqrt{n}}
\]</span></p>
<p>This is a standard formula for the error in the estimate of a mean value.</p>
<p>If the period is 1 month, the monthly values used earlier ar <span class="math inline">\(\bar{r} = 1\)</span> % and <span class="math inline">\(\sigma = 4.33\)</span> %. If we use 12 month of data we get <span class="math display">\[
\sigma_{\hat{\bar{r}}} = \frac{4.33}{\sqrt{12}}
\]</span> which is 1,25 %. The standard error of the mean return estimate is then larger than the mean return itself. If we use 4 years of data we can cut this standard deviation by a factor 2, which still must count as a very poor estimate. For an estimate to be considered good we need to be able to cut down the standard deviation to about 1/10th of the mean. This would require about <span class="math inline">\(n = 43.3^2 = 1875\)</span> or about 156 years of data.</p>
<p>This is a well known problem in empirical finance which has even a name. It is called the <strong>historical blur</strong> problem for the measurement of <span class="math inline">\(\bar{r}\)</span>. It is basically impossible to measure <span class="math inline">\(\bar{r}\)</span> to within workable accuracy using historical data. The problem can not be improved much by changing the period length. If longer periods are used, each sample is more reliable but fewer independent samples are obtained in any year. If the period is smaller, more samples are available but each is worse in terms of the ratio of standard deviation to mean value.</p>
</section>
</section>
<section id="introdcution-to-monte-carlo-simulation-in-finance" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="introdcution-to-monte-carlo-simulation-in-finance"><span class="header-section-number">5.8</span> Introdcution to Monte Carlo Simulation in Finance</h2>
<p>Monte Carlo simulation is a computational technique that uses repeated random sampling to estimate uncertain outcomes. It is particularly useful when dealing with <strong>probabilistic models</strong> and <strong>complex systems</strong> where analytical solutions are difficult or impossible to derive. It is also an excellent application context where we can discuss how to optimize speed and efficiency in R code.</p>
<p>The term Monte Carlo Simulation originates from the Manhattan Project during World War II, where scientists, including Stanislaw Ulam and John von Neumann, used random sampling techniques to model complex physical processes, such as neutron diffusion in nuclear reactions. The name “Monte Carlo” was inspired by the famous Monte Carlo Casino in Monaco, reflecting the method’s reliance on randomness and probability—just like games of chance in a casino.</p>
<p>Monte Carlo methods are used extensively in computational Finance. Financial markets are inherently uncertain, and Monte Carlo methods allow us to model this uncertainty by simulating a large number of possible outcomes. Some key applications in finance include:</p>
<ul>
<li><strong>Risk estimation</strong> (e.g., computing Value at Risk).<br>
</li>
<li><strong>Pricing derivatives</strong> (e.g., options pricing using risk-neutral Monte Carlo methods).<br>
</li>
<li><strong>Portfolio optimization</strong> (e.g., estimating expected returns and volatility distributions).</li>
</ul>
<p>In this lecture, we focus on <strong>estimating Value at Risk (VaR)</strong> which we have discussed from a conceptual viewpoint in this lecture and where we have focussed on cases of normally distributed log returns of stocks. We also briefly touched on the approach of historical simulation, where past return data are used to estimated the risk</p>
<p>In contrast to these methods Monte Carlo Simulation simulates future returns using random draws based on estimated statistical properties like mean and standard deviation. This is an apporach where the computer can shine.</p>
<section id="simulating-portfolio-returns-for-var-calculation-step-by-step-implementation-in-r" class="level3" data-number="5.8.1">
<h3 data-number="5.8.1" class="anchored" data-anchor-id="simulating-portfolio-returns-for-var-calculation-step-by-step-implementation-in-r"><span class="header-section-number">5.8.1</span> Simulating Portfolio Returns for VaR Calculation Step-by-Step Implementation in R</h3>
<p>We will now implement a <strong>basic Monte Carlo simulation</strong> in R to estimate VaR.</p>
<p>The approach consists of:</p>
<ol type="1">
<li><strong>Estimating the portfolio’s mean return and standard deviation</strong> based on historical data.<br>
</li>
<li><strong>Generating thousands of random return scenarios</strong> assuming a normal distribution.<br>
</li>
<li><strong>Calculating the simulated portfolio losses</strong> and extracting the VaR from the loss distribution.</li>
</ol>
<section id="step-1-simulating-portfolio-returns" class="level4" data-number="5.8.1.1">
<h4 data-number="5.8.1.1" class="anchored" data-anchor-id="step-1-simulating-portfolio-returns"><span class="header-section-number">5.8.1.1</span> Step 1: Simulating Portfolio Returns</h4>
<p>We begin by assuming that <strong>log-returns</strong> of a portfolio follow a normal distribution, which is a common assumption in risk modeling.</p>
<p>Given <strong>historical return data</strong>, we estimate the <strong>mean</strong> and <strong>standard deviation</strong>, then simulate thousands of potential returns. I do not do an explicit estimation in the follwoing code chunk because we have done so explicitly at many parts in this lecture. This could be done with historical data (keeping the blur problem in mind) and then - since the normal distribution is fully characterized by mean and standard deviation - we can use the normality assumption to pin down a simulation distribution. For the sake of demonstration I do 10000 simulations here fro somewhat typical returns parameter values. You can play with this. This can be in principle scaled up a lot. Note also that we set a random seed for reproduceability here. For the visualization I take the <code>ggplot2</code> package, which I think, produced the visualy most appealing results in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary packages</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)  <span class="co"># For visualization</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulated historical daily log-returns (e.g., from a stock index)</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>historical_returns <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">250</span>, <span class="at">mean =</span> <span class="fl">0.0005</span>, <span class="at">sd =</span> <span class="fl">0.01</span>)  <span class="co"># 250 trading days</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate parameters (mean and standard deviation)</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">mean</span>(historical_returns)</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fu">sd</span>(historical_returns)</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 10,000 future return scenarios using Monte Carlo</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>n_sim <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>simulated_returns <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n_sim, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma)</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick visualization of simulated returns</span></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">returns =</span> simulated_returns), <span class="fu">aes</span>(<span class="at">x =</span> returns)) <span class="sc">+</span></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>, <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Simulated Portfolio Returns"</span>,</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Simulated Return"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-lecture5_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-2-estimating-value-at-risk-var" class="level4" data-number="5.8.1.2">
<h4 data-number="5.8.1.2" class="anchored" data-anchor-id="step-2-estimating-value-at-risk-var"><span class="header-section-number">5.8.1.2</span> Step 2: Estimating Value at Risk (VaR)</h4>
<p>Once we have simulated thousands of possible portfolio returns, we extract <strong>Value at Risk (VaR)</strong> from the distribution. Since <strong>VaR is the quantile of the loss distribution</strong>, we take the <strong>left-tail quantile</strong> (e.g., 5% or 1% quantile).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute portfolio losses (negative returns)</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>simulated_losses <span class="ot">&lt;-</span> <span class="sc">-</span>simulated_returns  <span class="co"># Losses are negative returns</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute VaR at 95% and 99% confidence levels</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>VaR_95 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(simulated_losses, <span class="at">probs =</span> <span class="fl">0.95</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>VaR_99 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(simulated_losses, <span class="at">probs =</span> <span class="fl">0.99</span>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Monte Carlo Estimated VaR:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Monte Carlo Estimated VaR:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"95% VaR:"</span>, <span class="fu">round</span>(VaR_95, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>95% VaR: 0.0151 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"99% VaR:"</span>, <span class="fu">round</span>(VaR_99, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>99% VaR: 0.0214 </code></pre>
</div>
</div>
<p>The raw VaR numbers reported in our Monte Carlo simulation— e.g., <strong>95% VaR = 0.0151</strong>—represent the potential <strong>daily loss</strong> as a fraction of the portfolio value. However, to make this result more intuitive, let’s express it in <strong>real monetary terms</strong>.</p>
<p>Suppose we are managing a $10 billion USD portfolio. The 95% VaR of 0.0151 means:</p>
<ul>
<li><strong>Daily Loss Interpretation</strong>:</li>
</ul>
<p>Under normal market conditions, there is a 95% probability that the portfolio will lose no more than $ 151 million USD in a single trading day (1.51% of $ 10 billion).<br>
Conversely, there is a 5% chance that losses will exceed this amount.</p>
<ul>
<li><strong>Yearly Exceedance Frequency</strong>:</li>
</ul>
<p>Since 5% of trading days (approximately 12–13 days per year in a 250-day trading year) fall in the worst-case loss category,<br>
we expect to lose more than $151 million USD on about 12–13 days per year.</p>
<p>You can do this kind of translation for the 99% VaR for yourself. You can even support your intuition by leveraging the power of R to write a function yourself to make such interpretations dynamic for arbitrary portfolio sizes and let R do the interpretation for you. Let us call this function <code>interpret_VaR</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to interpret Monte Carlo VaR results</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>interpret_var <span class="ot">&lt;-</span> <span class="cf">function</span>(VaR_95, VaR_99, portfolio_value, <span class="at">trading_days =</span> <span class="dv">250</span>) {</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Compute monetary losses</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  VaR_95_dollars <span class="ot">&lt;-</span> VaR_95 <span class="sc">*</span> portfolio_value</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  VaR_99_dollars <span class="ot">&lt;-</span> VaR_99 <span class="sc">*</span> portfolio_value</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Compute expected exceedance frequency</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ~5% exceedance</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  days_exceeding_95 <span class="ot">&lt;-</span> trading_days <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.95</span>)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ~1% exceedance</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>  days_exceeding_99 <span class="ot">&lt;-</span> trading_days <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.99</span>)  </span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Print interpretation</span></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Monte Carlo Value at Risk (VaR) Interpretation:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"-------------------------------------------------</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Portfolio Value: $"</span>, <span class="fu">format</span>(portfolio_value, <span class="at">big.mark =</span> <span class="st">","</span>), <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"95% VaR Interpretation:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"- Expected daily loss will not exceed"</span>, </span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">round</span>(VaR_95 <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>), <span class="st">"% in 95% of cases.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"- This corresponds to a daily loss limit of approximately $"</span>, </span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>      <span class="fu">format</span>(<span class="fu">round</span>(VaR_95_dollars, <span class="dv">2</span>), <span class="at">big.mark =</span> <span class="st">","</span>), <span class="st">".</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"- However, about"</span>, </span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>      <span class="fu">round</span>(days_exceeding_95, <span class="dv">1</span>), <span class="st">"days per year, losses may exceed this level.</span><span class="sc">\n\n</span><span class="st">"</span>)</span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb43-26"><a href="#cb43-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"99% VaR Interpretation:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb43-27"><a href="#cb43-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"- Expected daily loss will not exceed"</span>, </span>
<span id="cb43-28"><a href="#cb43-28" aria-hidden="true" tabindex="-1"></a>      <span class="fu">round</span>(VaR_99 <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>), <span class="st">"% in 99% of cases.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb43-29"><a href="#cb43-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"- This corresponds to a daily loss limit of approximately $"</span>, </span>
<span id="cb43-30"><a href="#cb43-30" aria-hidden="true" tabindex="-1"></a>      <span class="fu">format</span>(<span class="fu">round</span>(VaR_99_dollars, <span class="dv">2</span>), <span class="at">big.mark =</span> <span class="st">","</span>), <span class="st">".</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb43-31"><a href="#cb43-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"- However, about"</span>, </span>
<span id="cb43-32"><a href="#cb43-32" aria-hidden="true" tabindex="-1"></a>      <span class="fu">round</span>(days_exceeding_99, <span class="dv">1</span>), <span class="st">"days per year, losses may exceed this level.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb43-33"><a href="#cb43-33" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb43-34"><a href="#cb43-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-35"><a href="#cb43-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Example usage: Assume a portfolio of $10 billion</span></span>
<span id="cb43-36"><a href="#cb43-36" aria-hidden="true" tabindex="-1"></a>portfolio_value <span class="ot">&lt;-</span> <span class="fl">10e9</span>  <span class="co"># $10 billion</span></span>
<span id="cb43-37"><a href="#cb43-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-38"><a href="#cb43-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Call the function with Monte Carlo estimated VaR</span></span>
<span id="cb43-39"><a href="#cb43-39" aria-hidden="true" tabindex="-1"></a><span class="fu">interpret_var</span>(<span class="fl">0.0151</span> , <span class="fl">0.0214</span> , portfolio_value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Monte Carlo Value at Risk (VaR) Interpretation:
-------------------------------------------------
Portfolio Value: $ 1e+10 

95% VaR Interpretation:
- Expected daily loss will not exceed 1.51 % in 95% of cases.
- This corresponds to a daily loss limit of approximately $ 1.51e+08 .
- However, about 12.5 days per year, losses may exceed this level.

99% VaR Interpretation:
- Expected daily loss will not exceed 2.14 % in 99% of cases.
- This corresponds to a daily loss limit of approximately $ 2.14e+08 .
- However, about 2.5 days per year, losses may exceed this level.</code></pre>
</div>
</div>
</section>
<section id="step-3-optimizing-the-monte-carlo-simulation" class="level4" data-number="5.8.1.3">
<h4 data-number="5.8.1.3" class="anchored" data-anchor-id="step-3-optimizing-the-monte-carlo-simulation"><span class="header-section-number">5.8.1.3</span> Step 3: Optimizing the Monte Carlo Simulation</h4>
<p>A naive Monte Carlo approach can be slow for large-scale simulations. To <strong>optimize performance</strong>, we introduce:</p>
<ul>
<li><strong>Vectorization</strong>: Using matrix operations instead of loops.</li>
<li><strong>Parallel computing</strong>: Running simulations in parallel using the <code>future.apply</code> package.</li>
<li><strong>Efficient data handling</strong>: Using <code>data.table</code> instead of standard data frames.</li>
</ul>
<p>These are excellent points! To <strong>expand and refine</strong> this section, I’ll structure it as follows:</p>
<hr>
</section>
</section>
<section id="step-3-optimizing-the-monte-carlo-simulation-1" class="level3" data-number="5.8.2">
<h3 data-number="5.8.2" class="anchored" data-anchor-id="step-3-optimizing-the-monte-carlo-simulation-1"><span class="header-section-number">5.8.2</span> <strong>Step 3: Optimizing the Monte Carlo Simulation</strong></h3>
<p>Monte Carlo simulations can become computationally expensive when scaled up, making <strong>performance optimization</strong> an important consideration.</p>
<p>We introduce three key techniques:<br>
1. <strong>Vectorization</strong> – Using efficient matrix operations instead of loops.<br>
2. <strong>Parallel Computing (<code>future.apply</code>)</strong> – Distributing tasks across multiple CPU cores.<br>
3. <strong>Efficient Data Handling (<code>data.table</code>)</strong> – Reducing memory overhead and improving speed.</p>
<p>R has built in functionality for parallel computing. Here we will discuss parallel computing with <code>future.apply</code>.</p>
<p>So what us <code>future.apply</code> and how does t help? The <code>future.apply</code> package allows us to run <strong>apply-type functions in parallel</strong> across multiple CPU cores, improving computational speed when processing large datasets. Normally, R executes code <strong>sequentially</strong> (one operation at a time).<br>
What <code>future.apply</code> does is that it enables <strong>parallel execution</strong>, meaning tasks run simultaneously across multiple CPU cores, reducing computation time.</p>
<p>Parallelization <strong>is essential</strong> when:</p>
<ul>
<li>You need to <strong>simulate millions of scenarios</strong> (e.g., high-frequency Monte Carlo simulations).<br>
</li>
<li>Your computations involve <strong>nested loops</strong> (e.g., pricing derivatives across many strike prices).<br>
</li>
<li>You work with <strong>large financial datasets</strong> that slow down single-threaded processing.</li>
</ul>
<p>However, parallelization is not always beneficial for small-scale problems due to <strong>overhead costs</strong> of setting up parallel workers.</p>
<p>Let us compare sequential vs.&nbsp;parallel Monte Carlo Simulation to demonstrate these points. We first run a <strong>single-core Monte Carlo simulation</strong> and then compare it to a <strong>parallelized version</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary package</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(future.apply)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: future</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up parallel processing using all available CPU cores</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plan</span>(multisession)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define Monte Carlo function for Value at Risk (VaR)</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>monte_carlo_var <span class="ot">&lt;-</span> <span class="cf">function</span>(n_sim, mu, sigma, <span class="at">confidence =</span> <span class="fl">0.95</span>) {</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  simulated_losses <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">rnorm</span>(n_sim, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">quantile</span>(simulated_losses, <span class="at">probs =</span> confidence))</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Define number of simulations</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>n_sim <span class="ot">&lt;-</span> <span class="dv">100000</span>  <span class="co"># Large-scale simulation</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Measure time for sequential computation (single core)</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>start_time_seq <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>VaR_95_seq <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="cf">function</span>(x) <span class="fu">monte_carlo_var</span>(n_sim, mu, sigma, <span class="fl">0.95</span>))</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>end_time_seq <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>time_seq <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(end_time_seq, start_time_seq, <span class="at">units =</span> <span class="st">"secs"</span>))  <span class="co"># Convert to numeric seconds</span></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Measure time for parallel computation (multiple cores)</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>start_time_par <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>VaR_95_par <span class="ot">&lt;-</span> <span class="fu">future_sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="cf">function</span>(x) <span class="fu">monte_carlo_var</span>(n_sim, mu, sigma, <span class="fl">0.95</span>), <span class="at">future.seed =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>end_time_par <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>time_par <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(end_time_par, start_time_par, <span class="at">units =</span> <span class="st">"secs"</span>))  <span class="co"># Convert to numeric seconds</span></span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Print timing results</span></span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Execution Time Comparison:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Execution Time Comparison:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Sequential Execution Time: "</span>, <span class="fu">round</span>(time_seq, <span class="dv">2</span>), <span class="st">" seconds</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sequential Execution Time:  0.07  seconds</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Parallel Execution Time: "</span>, <span class="fu">round</span>(time_par, <span class="dv">2</span>), <span class="st">" seconds</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parallel Execution Time:  1.26  seconds</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Speedup Factor: "</span>, <span class="fu">round</span>(time_seq <span class="sc">/</span> time_par, <span class="dv">2</span>), <span class="st">"x faster with parallel computing</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Speedup Factor:  0.06 x faster with parallel computing</code></pre>
</div>
</div>
<p>Let’s break down the key steps in our parallel Monte Carlo simulation for VaR and explain why each part matters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(future.apply)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plan</span>(multisession)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>future.apply</code> is an enhanced version of <code>apply()</code> functions** that supports parallel execution. <code>plan(multisession)</code> tells R to use multiple CPU cores instead of executing code sequentially. Normally, R runs tasks one at a time (single-threaded). With <code>multisession</code>, R splits tasks across CPU cores, reducing execution time for large simulations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>monte_carlo_var <span class="ot">&lt;-</span> <span class="cf">function</span>(n_sim, mu, sigma, <span class="at">confidence =</span> <span class="fl">0.95</span>) {</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  simulated_losses <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">rnorm</span>(n_sim, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">quantile</span>(simulated_losses, <span class="at">probs =</span> confidence))</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We generate <code>n_sim</code> random portfolio losses from a normal distribution (negating returns to represent losses).<br>
We extract the VaR quantile from the simulated loss distribution. This function encapsulates our Monte Carlo simulation into a modular, reusable block of code. Later, we parallelize multiple independent simulations using this function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>start_time_seq <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>VaR_95_seq <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="cf">function</span>(x) <span class="fu">monte_carlo_var</span>(n_sim, mu, sigma, <span class="fl">0.95</span>))</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>end_time_seq <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>time_seq <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(end_time_seq, start_time_seq, <span class="at">units =</span> <span class="st">"secs"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We measure execution time for the sequential (single-core) simulation.<br>
<code>sapply(1:10, function(x) ...)</code> runs 10 independent Monte Carlo simulations.<br>
This serves as our baseline for performance comparison. We need to measure the cost of computing independent Monte Carlo simulations one by one.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>start_time_par <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>VaR_95_par <span class="ot">&lt;-</span> <span class="fu">future_sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="cf">function</span>(x) <span class="fu">monte_carlo_var</span>(n_sim, mu, sigma, <span class="fl">0.95</span>), <span class="at">future.seed =</span> <span class="cn">TRUE</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>end_time_par <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>time_par <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(end_time_par, start_time_par, <span class="at">units =</span> <span class="st">"secs"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We now run 10 Monte Carlo simulations in parallel, distributing them across CPU cores. <code>future.seed = TRUE</code> ensures statistically valid random number generation across parallel workers. Unlike sequential execution, multiple CPU cores now share the workload. This should reduce execution time, but the actual gain depends on the computational task and system configuration.</p>
<p>The last step just compares performance</p>
<p>At first glance, the results of our output seems counterintuitive—why is parallel execution <strong>slower</strong> than sequential execution here?<br>
It is key to understand that parallelization does not always improve speed. Small tasks don’t benefit from parallel execution.</p>
<ul>
<li>The <strong>overhead cost</strong> of setting up parallel workers (process spawning, memory sharing, inter-process communication) can <strong>exceed the time saved</strong> for small problems.<br>
</li>
<li><strong>Parallelization shines for large-scale computations</strong>.</li>
</ul>
<p>Let’s increase the number of simulations to <strong>10 million (<code>1e7</code>) per iteration</strong> to demonstrate when parallel computing becomes a necessity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define larger-scale simulation</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>n_sim <span class="ot">&lt;-</span> <span class="fl">1e7</span>  <span class="co"># 10 million simulations per iteration</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the comparison again</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>start_time_seq <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>VaR_95_seq <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="cf">function</span>(x) <span class="fu">monte_carlo_var</span>(n_sim, mu, sigma, <span class="fl">0.95</span>))</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>end_time_seq <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>time_seq <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(end_time_seq, start_time_seq, <span class="at">units =</span> <span class="st">"secs"</span>))</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>start_time_par <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>VaR_95_par <span class="ot">&lt;-</span> <span class="fu">future_sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="cf">function</span>(x) <span class="fu">monte_carlo_var</span>(n_sim, mu, sigma, <span class="fl">0.95</span>), <span class="at">future.seed =</span> <span class="cn">TRUE</span>)</span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>end_time_par <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a>time_par <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(end_time_par, start_time_par, <span class="at">units =</span> <span class="st">"secs"</span>))</span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Execution Time Comparison (Larger Simulations):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Execution Time Comparison (Larger Simulations):</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Sequential Execution Time: "</span>, <span class="fu">round</span>(time_seq, <span class="dv">2</span>), <span class="st">" seconds</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sequential Execution Time:  6.21  seconds</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Parallel Execution Time: "</span>, <span class="fu">round</span>(time_par, <span class="dv">2</span>), <span class="st">" seconds</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Parallel Execution Time:  3.34  seconds</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Speedup Factor: "</span>, <span class="fu">round</span>(time_seq <span class="sc">/</span> time_par, <span class="dv">2</span>), <span class="st">"x faster with parallel computing</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Speedup Factor:  1.86 x faster with parallel computing</code></pre>
</div>
</div>
<p>Now we see a doubling of speed achieved by our prallelisation. You can play around yourself to get a feeling for the performance enhancements you may gain for computationally large problems. Maybe you can go back to the very first probelm we dealt with in this coures financial-transaction-identifyer collision probability ofr large transaction volume and large output space <span class="math inline">\(M\)</span>.</p>
<p>Let’s visualize the execution time comparison of our example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary package</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulated execution times (adjust these with actual results if needed)</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>execution_times <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Simulation_Size =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"100,000 Sims"</span>, <span class="st">"10,000,000 Sims"</span>), </span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>                           <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"100,000 Sims"</span>, <span class="st">"10,000,000 Sims"</span>)),</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Execution_Time =</span> <span class="fu">c</span>(<span class="fl">0.07</span> , <span class="fl">1.22</span>, <span class="fl">6.17</span>, <span class="fl">2.85</span>),  <span class="co"># Replace with actual results</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Method =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Sequential"</span>, <span class="st">"Parallel"</span>), <span class="at">each =</span> <span class="dv">2</span>)</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Create bar plot</span></span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(execution_times, <span class="fu">aes</span>(<span class="at">x =</span> Simulation_Size, <span class="at">y =</span> Execution_Time, <span class="at">fill =</span> Method)) <span class="sc">+</span></span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Execution Time Comparison: Sequential vs. Parallel Monte Carlo Simulation"</span>,</span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Simulation Size"</span>,</span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Execution Time (seconds)"</span>) <span class="sc">+</span></span>
<span id="cb67-18"><a href="#cb67-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>)) <span class="sc">+</span></span>
<span id="cb67-19"><a href="#cb67-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-lecture5_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here are the key Takeaways from the visualization:</p>
<p>For small-scale simulations (100,000 draws), parallelization adds overhead and is actually slower. For large-scale simulations (10 million draws), parallel computing significantly reduces execution time. The break-even point depends on system resources, but the lesson is clear: parallel computing is most useful for large problems.</p>
<p>If we need even more computational power, tools such as GPU-based parallelization can help:</p>
<ul>
<li><code>gpuR</code>: Allows running matrix operations on GPUs in R.</li>
<li><code>torch (for R)</code>: Enables deep learning-like parallel computations on GPUs.</li>
<li><code>cuda.ml</code>: Uses NVIDIA’s CUDA for ultra-fast numerical processing.</li>
</ul>
<p>These methods are beyond the scope of our discussion but become crucial for high-frequency trading, derivative pricing, and deep learning applications in finance.</p>
<section id="efficient-data-handling-with-data.table" class="level4" data-number="5.8.2.1">
<h4 data-number="5.8.2.1" class="anchored" data-anchor-id="efficient-data-handling-with-data.table"><span class="header-section-number">5.8.2.1</span> Efficient Data Handling with <code>data.table</code></h4>
<p><code>data.table</code>is an R package that increases the efficiency of data handling and becomes useful if you are dealing with big datasets. Monte Carlo Simulation is a typical context where such issues can arise quickly. In this case the use of <code>data.table</code>brings enhanced memory efficiency: Standard <code>data.frame</code> operations create copies of data, increasing memory usage. <code>data.table</code> avoids this by modifying objects in place.<br>
<code>data.table</code> is optimized for speed. It can process millions of rows significantly faster than <code>data.frame</code>.</p>
<p>Let’s discuss an example where we compare data frames and the <code>data.table</code>package. Let’s compare performance for <strong>storing and manipulating simulated losses</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data.table package</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'data.table'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:xts':

    first, last</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:zoo':

    yearmon, yearqtr</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate a large dataset of simulated losses</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>n_sim <span class="ot">&lt;-</span> <span class="fl">1e6</span>  <span class="co"># 1 million simulations</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>simulated_losses <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">rnorm</span>(n_sim, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Store as a standard data frame</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>df_losses <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">losses =</span> simulated_losses)</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Store as a data.table</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>dt_losses <span class="ot">&lt;-</span> <span class="fu">data.table</span>(<span class="at">losses =</span> simulated_losses)</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Measure time to compute quantiles using data.frame</span></span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>start_df <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>VaR_95_df <span class="ot">&lt;-</span> <span class="fu">quantile</span>(df_losses<span class="sc">$</span>losses, <span class="at">probs =</span> <span class="fl">0.95</span>)</span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>end_df <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a>time_df <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(end_df, start_df, <span class="at">units =</span> <span class="st">"secs"</span>))  <span class="co"># Convert to numeric</span></span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Measure time to compute quantiles using data.table</span></span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a>start_dt <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a>VaR_95_dt <span class="ot">&lt;-</span> dt_losses[, <span class="fu">quantile</span>(losses, <span class="at">probs =</span> <span class="fl">0.95</span>)]</span>
<span id="cb72-20"><a href="#cb72-20" aria-hidden="true" tabindex="-1"></a>end_dt <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb72-21"><a href="#cb72-21" aria-hidden="true" tabindex="-1"></a>time_dt <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(end_dt, start_dt, <span class="at">units =</span> <span class="st">"secs"</span>))  <span class="co"># Convert to numeric</span></span>
<span id="cb72-22"><a href="#cb72-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-23"><a href="#cb72-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Print timing results</span></span>
<span id="cb72-24"><a href="#cb72-24" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Execution Time Comparison for VaR Calculation:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Execution Time Comparison for VaR Calculation:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Data Frame Execution Time: "</span>, <span class="fu">round</span>(time_df, <span class="dv">4</span>), <span class="st">" seconds</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data Frame Execution Time:  0.0112  seconds</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Data Table Execution Time: "</span>, <span class="fu">round</span>(time_dt, <span class="dv">4</span>), <span class="st">" seconds</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data Table Execution Time:  0.0172  seconds</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Speedup Factor: "</span>, <span class="fu">round</span>(time_df <span class="sc">/</span> time_dt, <span class="dv">2</span>), <span class="st">"x faster with data.table</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Speedup Factor:  0.65 x faster with data.table</code></pre>
</div>
</div>
</section>
</section>
<section id="reporting-and-documentation-of-r-code" class="level3" data-number="5.8.3">
<h3 data-number="5.8.3" class="anchored" data-anchor-id="reporting-and-documentation-of-r-code"><span class="header-section-number">5.8.3</span> Reporting and Documentation of R Code</h3>
<p>Monte Carlo simulations often generate large volumes of data, and proper documentation and reporting are essential for:</p>
<ul>
<li><strong>Reproducibility</strong>: Ensuring others (or future you) can understand and replicate your work.<br>
</li>
<li><strong>Clarity</strong>: Providing a clear summary of simulation results, assumptions, and methodology.<br>
</li>
<li><strong>Communication</strong>: Making results accessible to different stakeholders (e.g., researchers, risk managers).</li>
</ul>
<hr>
<section id="writing-readable-and-reproducible-r-code" class="level4" data-number="5.8.3.1">
<h4 data-number="5.8.3.1" class="anchored" data-anchor-id="writing-readable-and-reproducible-r-code"><span class="header-section-number">5.8.3.1</span> Writing Readable and Reproducible R Code</h4>
<p>Here are three best practice tips:</p>
<ol type="1">
<li><strong>Use clear function names and comments</strong>
<ul>
<li>Avoid cryptic variable names.<br>
</li>
<li>Add comments to explain key steps.</li>
</ul></li>
<li><strong>Include metadata in scripts</strong>
<ul>
<li>Define <strong>input parameters</strong> at the beginning.<br>
</li>
<li>Set a <strong>random seed</strong> for reproducibility.</li>
</ul></li>
<li><strong>Use docstrings with <code>roxygen2</code></strong> (for functions in packages).</li>
</ol>
<p>The <code>roxygen2</code> package is a widely used tool for automatically generating documentation for R functions, especially in package development. Instead of manually writing separate documentation files, roxygen2 allows you to write structured docstrings directly above function definitions using specially formatted comments (#’).</p>
<p>Why use <code>roxygen2</code>? Here are three reasons:</p>
<ol type="1">
<li>Consistency – Ensures documentation is always in sync with the function code.</li>
<li>Efficiency – Eliminates the need for manually maintaining help files.</li>
<li>Integration – Works seamlessly with RStudio, devtools, and pkgdown for package development.</li>
</ol>
<p><code>roxygen</code> works by extracting special comments (#’) and converting them into R help files. You can specify parameters, return values, usage examples, and references. The devtools::document() function compiles the documentation.</p>
<p>For example, this is how a well documented Monte Carlo function could look like.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co">#' Monte Carlo Simulation for Value at Risk (VaR)</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="co">#'</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="co">#' This function estimates Value at Risk using Monte Carlo simulations.</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="co">#'</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param n_sim Number of simulations</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param mu Mean return of asset</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param sigma Standard deviation of returns</span></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param confidence Confidence level for VaR (default = 0.95)</span></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return Estimated VaR</span></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a><span class="co">#' @examples</span></span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a><span class="co">#' monte_carlo_var(10000, 0.0005, 0.01, 0.95)</span></span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a>monte_carlo_var <span class="ot">&lt;-</span> <span class="cf">function</span>(n_sim, mu, sigma, <span class="at">confidence =</span> <span class="fl">0.95</span>) {</span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>  simulated_losses <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">rnorm</span>(n_sim, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma)</span>
<span id="cb80-14"><a href="#cb80-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">quantile</span>(simulated_losses, <span class="at">probs =</span> confidence))</span>
<span id="cb80-15"><a href="#cb80-15" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>This uses <strong><code>roxygen2</code></strong> syntax for automatic documentation generation.<br>
</li>
<li>Calling <code>devtools::document()</code> in a package project generates documentation from comments.</li>
</ul>
<p>Once we run a Monte Carlo simulation, we need to <strong>summarize and present</strong> the results effectively.</p>
<p>A structured summary table is often clearer than raw printouts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example results from Monte Carlo VaR estimation</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>Confidence_Level <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"95%"</span>, <span class="st">"99%"</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>VaR_Percentage <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.0151</span>, <span class="fl">0.0214</span>)  <span class="co"># Example VaR values</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>Portfolio_Value <span class="ot">&lt;-</span> <span class="fl">10e9</span>  <span class="co"># Assume $10 billion portfolio</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute VaR amount in monetary terms</span></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>VaR_Amount <span class="ot">&lt;-</span> VaR_Percentage <span class="sc">*</span> Portfolio_Value</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame</span></span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Confidence_Level =</span> Confidence_Level,</span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">VaR_Percentage =</span> VaR_Percentage,</span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Portfolio_Value =</span> Portfolio_Value,</span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">VaR_Amount =</span> VaR_Amount</span>
<span id="cb81-15"><a href="#cb81-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb81-16"><a href="#cb81-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-17"><a href="#cb81-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Print formatted table</span></span>
<span id="cb81-18"><a href="#cb81-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Confidence_Level VaR_Percentage Portfolio_Value VaR_Amount
1              95%         0.0151           1e+10   1.51e+08
2              99%         0.0214           1e+10   2.14e+08</code></pre>
</div>
</div>
<p>Instead of manually copying outputs, <strong>Quarto/RMarkdown</strong> can generate reports dynamically.</p>
<p>Here’s the <strong>Base R</strong> version of the <strong>Quarto (qmd) report snippet</strong>, avoiding <code>ggplot2</code> and <code>dplyr</code>:</p>
<p>This is how a rewritten example report snippet in Quarto (<code>.qmd</code>) would - for instance - look like:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="sc">---</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>title<span class="sc">:</span> <span class="st">"Monte Carlo Simulation Report"</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>author<span class="sc">:</span> <span class="st">"Your Name"</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>date<span class="sc">:</span> <span class="st">"`r Sys.Date()`"</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>format<span class="sc">:</span> html</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a><span class="sc">---</span></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary base R functions</span></span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results as an HTML table using knitr::kable</span></span>
<span id="cb83-11"><a href="#cb83-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb83-12"><a href="#cb83-12" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(results, <span class="at">format =</span> <span class="st">"html"</span>, <span class="at">caption =</span> <span class="st">"Monte Carlo Estimated VaR"</span>)</span>
<span id="cb83-13"><a href="#cb83-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-14"><a href="#cb83-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Define execution times (example data)</span></span>
<span id="cb83-15"><a href="#cb83-15" aria-hidden="true" tabindex="-1"></a>Simulation_Size <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"100,000 Sims"</span>, <span class="st">"10,000,000 Sims"</span>)</span>
<span id="cb83-16"><a href="#cb83-16" aria-hidden="true" tabindex="-1"></a>Execution_Time_Sequential <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.07</span>, <span class="fl">25.3</span>)  <span class="co"># Hypothetical values</span></span>
<span id="cb83-17"><a href="#cb83-17" aria-hidden="true" tabindex="-1"></a>Execution_Time_Parallel <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.22</span>, <span class="fl">5.8</span>)</span>
<span id="cb83-18"><a href="#cb83-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-19"><a href="#cb83-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Create bar plot using base R</span></span>
<span id="cb83-20"><a href="#cb83-20" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(</span>
<span id="cb83-21"><a href="#cb83-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">height =</span> <span class="fu">rbind</span>(Execution_Time_Sequential, Execution_Time_Parallel),</span>
<span id="cb83-22"><a href="#cb83-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">beside =</span> <span class="cn">TRUE</span>,</span>
<span id="cb83-23"><a href="#cb83-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>),</span>
<span id="cb83-24"><a href="#cb83-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">names.arg =</span> Simulation_Size,</span>
<span id="cb83-25"><a href="#cb83-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.text =</span> <span class="fu">c</span>(<span class="st">"Sequential"</span>, <span class="st">"Parallel"</span>),</span>
<span id="cb83-26"><a href="#cb83-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Execution Time Comparison"</span>,</span>
<span id="cb83-27"><a href="#cb83-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Simulation Size"</span>,</span>
<span id="cb83-28"><a href="#cb83-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Execution Time (seconds)"</span></span>
<span id="cb83-29"><a href="#cb83-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb83-30"><a href="#cb83-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-31"><a href="#cb83-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Save summary table as CSV</span></span>
<span id="cb83-32"><a href="#cb83-32" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(results, <span class="st">"monte_carlo_var_results.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb83-33"><a href="#cb83-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-34"><a href="#cb83-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Save entire workspace (useful for large simulations)</span></span>
<span id="cb83-35"><a href="#cb83-35" aria-hidden="true" tabindex="-1"></a><span class="fu">save.image</span>(<span class="st">"monte_carlo_workspace.RData"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In a report you would of course interweave text and code, but the example chunk gives you an idea. Quarto is very versatily and visually appealing. For instance the lecture notes for this code as well as the slides and all other materials are entirely written in Quarto.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Billingsley1995" class="csl-entry" role="listitem">
Billingsley, Patrick. 1995. <em>Probability and Measure</em>. Wiley.
</div>
<div id="ref-Luenberger2009" class="csl-entry" role="listitem">
Luenberger, David. 2009. <em>Investment Science</em>. Oxford University Press.
</div>
<div id="ref-McNeilEmbrechtsFrey2015" class="csl-entry" role="listitem">
McNeil, Alexander, Paul Embrechts, and Rudiger Frey. 2015. <em>Quantitative Risk Management</em>. Princeton University Press.
</div>
</div>
</section>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Geometric Brownian Motion (GBM) is a stochastic process widely used to model stock prices. It follows the equation: <span class="math display">\[
dS_t=μ\,S_t \,dt+σ\,S_t\,dW_t
\]</span> where <span class="math inline">\(\mu\)</span> is the drift (expected return), <span class="math inline">\(\sigma\)</span> is the volatility, and <span class="math inline">\(W_t\)</span> is a Wiener process (also called a Brownian motion). A Wiener process is a continuous-time stochastic process with independent, normally distributed increments and is fundamental in modeling randomness in finance. GBM ensures that stock prices remain strictly positive. For a more extensive discussion see for example <span class="citation" data-cites="Luenberger2009">Luenberger (<a href="06-references.html#ref-Luenberger2009" role="doc-biblioref">2009</a>)</span><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/martin-summer-1090\.github\.io\/Probability_Introduction\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-lecture4.html" class="pagination-link" aria-label="Random Variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Random Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">References</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>