<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Appendix | An Introduction to Probability</title>
  <meta name="description" content="Lecture Notes. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Appendix | An Introduction to Probability" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Lecture Notes. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Appendix | An Introduction to Probability" />
  
  <meta name="twitter:description" content="Lecture Notes. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Martin Summer" />


<meta name="date" content="2022-02-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="references-1.html"/>

<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
<link rel="stylesheet" href="css/box.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">An Introduction to Probability Theory</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-are-these-lecture-notes-about"><i class="fa fa-check"></i>What are these lecture notes about</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#downloading-and-installing-r"><i class="fa fa-check"></i>Downloading and installing R</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#downloading-and-installing-rstudio"><i class="fa fa-check"></i>Downloading and installing RStudio</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure-of-the-notes"><i class="fa fa-check"></i>Structure of the Notes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="first-steps.html"><a href="first-steps.html"><i class="fa fa-check"></i><b>1</b> First probability ideas and first steps in R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="first-steps.html"><a href="first-steps.html#rolling-a-die"><i class="fa fa-check"></i><b>1.1</b> Rolling a die: First Probability ideas.</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="first-steps.html"><a href="first-steps.html#random-experiments-sample-space-events"><i class="fa fa-check"></i><b>1.1.1</b> Random experiments, sample space, events</a></li>
<li class="chapter" data-level="1.1.2" data-path="first-steps.html"><a href="first-steps.html#the-role-and-nature-of-idealizations-in-applications"><i class="fa fa-check"></i><b>1.1.2</b> The role and nature of idealizations in applications</a></li>
<li class="chapter" data-level="1.1.3" data-path="first-steps.html"><a href="first-steps.html#classical-probability"><i class="fa fa-check"></i><b>1.1.3</b> Classical Probability: Measuring uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="first-steps.html"><a href="first-steps.html#rolling-die-on-computer"><i class="fa fa-check"></i><b>1.2</b> Rolling a die on the computer: First steps in R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="first-steps.html"><a href="first-steps.html#r-interface"><i class="fa fa-check"></i><b>1.2.1</b> The R User Interface</a></li>
<li class="chapter" data-level="1.2.2" data-path="first-steps.html"><a href="first-steps.html#objects"><i class="fa fa-check"></i><b>1.2.2</b> Objects</a></li>
<li class="chapter" data-level="1.2.3" data-path="first-steps.html"><a href="first-steps.html#functions"><i class="fa fa-check"></i><b>1.2.3</b> Functions</a></li>
<li class="chapter" data-level="1.2.4" data-path="first-steps.html"><a href="first-steps.html#writing_your_own_functions"><i class="fa fa-check"></i><b>1.2.4</b> Writing your own functions</a></li>
<li class="chapter" data-level="1.2.5" data-path="first-steps.html"><a href="first-steps.html#arguments"><i class="fa fa-check"></i><b>1.2.5</b> Arguments</a></li>
<li class="chapter" data-level="1.2.6" data-path="first-steps.html"><a href="first-steps.html#scripts"><i class="fa fa-check"></i><b>1.2.6</b> Scripts</a></li>
<li class="chapter" data-level="1.2.7" data-path="first-steps.html"><a href="first-steps.html#packages_help"><i class="fa fa-check"></i><b>1.2.7</b> Using packages and finding Help</a></li>
<li class="chapter" data-level="1.2.8" data-path="first-steps.html"><a href="first-steps.html#packages"><i class="fa fa-check"></i><b>1.2.8</b> Packages</a></li>
<li class="chapter" data-level="1.2.9" data-path="first-steps.html"><a href="first-steps.html#getting_help"><i class="fa fa-check"></i><b>1.2.9</b> Getting Help</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="first-steps.html"><a href="first-steps.html#coincidences"><i class="fa fa-check"></i><b>1.3</b> Application: Coincidences and the Blockchain</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="first-steps.html"><a href="first-steps.html#birthday_problem"><i class="fa fa-check"></i><b>1.3.1</b> The birthday problem</a></li>
<li class="chapter" data-level="1.3.2" data-path="first-steps.html"><a href="first-steps.html#an-r-function-to-compute-birthday-probabilities"><i class="fa fa-check"></i><b>1.3.2</b> An R function to compute birthday probabilities</a></li>
<li class="chapter" data-level="1.3.3" data-path="first-steps.html"><a href="first-steps.html#determining-birthday-collisions-by-simulation"><i class="fa fa-check"></i><b>1.3.3</b> Determining birthday collisions by simulation</a></li>
<li class="chapter" data-level="1.3.4" data-path="first-steps.html"><a href="first-steps.html#hashfunctions"><i class="fa fa-check"></i><b>1.3.4</b> Hash-functions and the blockchain</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="first-steps.html"><a href="first-steps.html#summary"><i class="fa fa-check"></i><b>1.4</b> Summary</a></li>
<li class="chapter" data-level="1.5" data-path="first-steps.html"><a href="first-steps.html#project-1-craps-a-casion-dice-game."><i class="fa fa-check"></i><b>1.5</b> Project 1: Craps: A casion dice game.</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basic-rules.html"><a href="basic-rules.html"><i class="fa fa-check"></i><b>2</b> Probability: Basic Definitions and Rules</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basic-rules.html"><a href="basic-rules.html#terminology"><i class="fa fa-check"></i><b>2.1</b> Terminology</a></li>
<li class="chapter" data-level="2.2" data-path="basic-rules.html"><a href="basic-rules.html#probability-theory-and-applications"><i class="fa fa-check"></i><b>2.2</b> Probability in theory and applications of probability</a></li>
<li class="chapter" data-level="2.3" data-path="basic-rules.html"><a href="basic-rules.html#basic-rules-of-probability"><i class="fa fa-check"></i><b>2.3</b> Basic rules of probability</a></li>
<li class="chapter" data-level="2.4" data-path="basic-rules.html"><a href="basic-rules.html#frequency"><i class="fa fa-check"></i><b>2.4</b> Probability and Frequency</a></li>
<li class="chapter" data-level="2.5" data-path="basic-rules.html"><a href="basic-rules.html#independence"><i class="fa fa-check"></i><b>2.5</b> Independence</a></li>
<li class="chapter" data-level="2.6" data-path="basic-rules.html"><a href="basic-rules.html#moreR"><i class="fa fa-check"></i><b>2.6</b> Some more concepts from R: Reading Data, R Objects, Subsetting and Modifying Values</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="basic-rules.html"><a href="basic-rules.html#readingdata"><i class="fa fa-check"></i><b>2.6.1</b> Reading data in R</a></li>
<li class="chapter" data-level="2.6.2" data-path="basic-rules.html"><a href="basic-rules.html#robjects"><i class="fa fa-check"></i><b>2.6.2</b> R objects</a></li>
<li class="chapter" data-level="2.6.3" data-path="basic-rules.html"><a href="basic-rules.html#apple-up-down"><i class="fa fa-check"></i><b>2.6.3</b> Example: Will the stock price of Apple move up or down?</a></li>
<li class="chapter" data-level="2.6.4" data-path="basic-rules.html"><a href="basic-rules.html#benford"><i class="fa fa-check"></i><b>2.6.4</b> Example: Benfords law: The empirical probabilities of leading digits</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="basic-rules.html"><a href="basic-rules.html#summary-lecture-2"><i class="fa fa-check"></i><b>2.7</b> Summary</a></li>
<li class="chapter" data-level="2.8" data-path="basic-rules.html"><a href="basic-rules.html#project2"><i class="fa fa-check"></i><b>2.8</b> Project 2: Should we trust European supervisory bank data?</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="conditional-probability.html"><a href="conditional-probability.html"><i class="fa fa-check"></i><b>3</b> Conditional Probability</a>
<ul>
<li class="chapter" data-level="3.1" data-path="conditional-probability.html"><a href="conditional-probability.html#contingency-tables"><i class="fa fa-check"></i><b>3.1</b> Contingency tables</a></li>
<li class="chapter" data-level="3.2" data-path="conditional-probability.html"><a href="conditional-probability.html#marginal-joint-and-conditional-probability"><i class="fa fa-check"></i><b>3.2</b> Marginal, joint and conditional probability</a></li>
<li class="chapter" data-level="3.3" data-path="conditional-probability.html"><a href="conditional-probability.html#the-multiplication-rule"><i class="fa fa-check"></i><b>3.3</b> The multiplication rule</a></li>
<li class="chapter" data-level="3.4" data-path="conditional-probability.html"><a href="conditional-probability.html#law-of-total-probability"><i class="fa fa-check"></i><b>3.4</b> Law of total probability</a></li>
<li class="chapter" data-level="3.5" data-path="conditional-probability.html"><a href="conditional-probability.html#example-independence-and-the-financial-crisis-of-2007-2008"><i class="fa fa-check"></i><b>3.5</b> Example: Independence and the Financial Crisis of 2007-2008</a></li>
<li class="chapter" data-level="3.6" data-path="conditional-probability.html"><a href="conditional-probability.html#bayes-rule"><i class="fa fa-check"></i><b>3.6</b> Bayes’ Rule</a></li>
<li class="chapter" data-level="3.7" data-path="conditional-probability.html"><a href="conditional-probability.html#example-the-importance-of-updating-in-investing"><i class="fa fa-check"></i><b>3.7</b> Example The Importance of Updating in Investing</a></li>
<li class="chapter" data-level="3.8" data-path="conditional-probability.html"><a href="conditional-probability.html#project-studying-the-investment-game-a-bit-further"><i class="fa fa-check"></i><b>3.8</b> Project: Studying the investment game a bit further</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="random-variables.html"><a href="random-variables.html"><i class="fa fa-check"></i><b>4</b> Random Variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="random-variables.html"><a href="random-variables.html#discrete-distributions"><i class="fa fa-check"></i><b>4.1</b> Discrete Distributions</a></li>
<li class="chapter" data-level="4.2" data-path="random-variables.html"><a href="random-variables.html#expected-value"><i class="fa fa-check"></i><b>4.2</b> Expected value</a></li>
<li class="chapter" data-level="4.3" data-path="random-variables.html"><a href="random-variables.html#variation"><i class="fa fa-check"></i><b>4.3</b> Variation</a></li>
<li class="chapter" data-level="4.4" data-path="random-variables.html"><a href="random-variables.html#random-variables-the-cornerstone-for-modeling-investments-under-uncertainty"><i class="fa fa-check"></i><b>4.4</b> Random variables: The cornerstone for modeling investments under uncertainty</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="random-variables.html"><a href="random-variables.html#asset-return"><i class="fa fa-check"></i><b>4.4.1</b> Asset return</a></li>
<li class="chapter" data-level="4.4.2" data-path="random-variables.html"><a href="random-variables.html#random-asset-returns"><i class="fa fa-check"></i><b>4.4.2</b> Random asset returns</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="random-variables.html"><a href="random-variables.html#modelling-random-asset-returns-first-steps-in-r-programing"><i class="fa fa-check"></i><b>4.5</b> Modelling random asset returns: First steps in R programing</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="random-variables.html"><a href="random-variables.html#a-strategy-for-writing-a-program"><i class="fa fa-check"></i><b>4.5.1</b> A strategy for writing a program</a></li>
<li class="chapter" data-level="4.5.2" data-path="random-variables.html"><a href="random-variables.html#if-statements-and-if-else-statements"><i class="fa fa-check"></i><b>4.5.2</b> if Statements and if-else Statements</a></li>
<li class="chapter" data-level="4.5.3" data-path="random-variables.html"><a href="random-variables.html#portfolios-and-linear-algebra"><i class="fa fa-check"></i><b>4.5.3</b> Portfolios and linear algebra</a></li>
<li class="chapter" data-level="4.5.4" data-path="random-variables.html"><a href="random-variables.html#lookup-tables"><i class="fa fa-check"></i><b>4.5.4</b> Lookup Tables</a></li>
<li class="chapter" data-level="4.5.5" data-path="random-variables.html"><a href="random-variables.html#writing-the-outcome-program"><i class="fa fa-check"></i><b>4.5.5</b> Writing the outcome program</a></li>
<li class="chapter" data-level="4.5.6" data-path="random-variables.html"><a href="random-variables.html#for-loops"><i class="fa fa-check"></i><b>4.5.6</b> for Loops</a></li>
<li class="chapter" data-level="4.5.7" data-path="random-variables.html"><a href="random-variables.html#portfolio-expected-return-and-variance"><i class="fa fa-check"></i><b>4.5.7</b> Portfolio expected Return and Variance</a></li>
<li class="chapter" data-level="4.5.8" data-path="random-variables.html"><a href="random-variables.html#properties-of-expected-returns-and-portfolio-expected-return"><i class="fa fa-check"></i><b>4.5.8</b> Properties of expected returns and portfolio expected return</a></li>
<li class="chapter" data-level="4.5.9" data-path="random-variables.html"><a href="random-variables.html#properties-of-variance-and-portfolio-variance"><i class="fa fa-check"></i><b>4.5.9</b> Properties of variance and portfolio variance</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="random-variables.html"><a href="random-variables.html#the-binomial-distribution-and-models-of-asset-price-dynamics"><i class="fa fa-check"></i><b>4.6</b> The Binomial Distribution and models of asset price dynamics</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="random-variables.html"><a href="random-variables.html#the-binomial-distribution-in-applied-computational-finance"><i class="fa fa-check"></i><b>4.6.1</b> The binomial distribution in applied computational Finance</a></li>
<li class="chapter" data-level="4.6.2" data-path="random-variables.html"><a href="random-variables.html#bernoulli-random-variables-as-a-building-block-of-the-binomial-distribution"><i class="fa fa-check"></i><b>4.6.2</b> Bernoulli random variables as a building block of the binomial distribution</a></li>
<li class="chapter" data-level="4.6.3" data-path="random-variables.html"><a href="random-variables.html#modeling-asset-price-dynamics-with-binomial-trees"><i class="fa fa-check"></i><b>4.6.3</b> Modeling asset price dynamics with binomial trees</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="random-variables.html"><a href="random-variables.html#project-credit-risk-model-and-independence"><i class="fa fa-check"></i><b>4.7</b> Project: Credit risk model and independence</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="continuous-random-variables.html"><a href="continuous-random-variables.html"><i class="fa fa-check"></i><b>5</b> Continuous random variables</a>
<ul>
<li class="chapter" data-level="5.1" data-path="continuous-random-variables.html"><a href="continuous-random-variables.html#continuous-random-variables-and-probability"><i class="fa fa-check"></i><b>5.1</b> Continuous random variables and probability</a></li>
<li class="chapter" data-level="5.2" data-path="continuous-random-variables.html"><a href="continuous-random-variables.html#normal-distribution"><i class="fa fa-check"></i><b>5.2</b> Normal Distribution</a></li>
<li class="chapter" data-level="5.3" data-path="continuous-random-variables.html"><a href="continuous-random-variables.html#inverse-normal-and-quantiles"><i class="fa fa-check"></i><b>5.3</b> Inverse Normal and Quantiles</a></li>
<li class="chapter" data-level="5.4" data-path="continuous-random-variables.html"><a href="continuous-random-variables.html#example-value-at-risk-and-the-problem-of-fat-tails"><i class="fa fa-check"></i><b>5.4</b> Example Value at Risk and the problem of fat tails</a></li>
<li class="chapter" data-level="5.5" data-path="continuous-random-variables.html"><a href="continuous-random-variables.html#more-than-one-normal-random-variable"><i class="fa fa-check"></i><b>5.5</b> More than one normal random variable</a></li>
<li class="chapter" data-level="5.6" data-path="continuous-random-variables.html"><a href="continuous-random-variables.html#project-portfolio-credit-risk-with-dependent-defaults"><i class="fa fa-check"></i><b>5.6</b> Project: Portfolio credit risk with dependent defaults</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="6" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>6</b> Appendix</a>
<ul>
<li class="chapter" data-level="6.1" data-path="appendix.html"><a href="appendix.html#further-reading"><i class="fa fa-check"></i><b>6.1</b> Further Reading</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="appendix.html"><a href="appendix.html#probability-theory-and-mathematics"><i class="fa fa-check"></i><b>6.1.1</b> Probability theory and mathematics</a></li>
<li class="chapter" data-level="6.1.2" data-path="appendix.html"><a href="appendix.html#further-studies-of-r"><i class="fa fa-check"></i><b>6.1.2</b> Further studies of R</a></li>
<li class="chapter" data-level="6.1.3" data-path="appendix.html"><a href="appendix.html#probability-philosophy-and-concepts"><i class="fa fa-check"></i><b>6.1.3</b> Probability, Philosophy and Concepts</a></li>
<li class="chapter" data-level="6.1.4" data-path="appendix.html"><a href="appendix.html#monte-carlo-simulation-and-computing"><i class="fa fa-check"></i><b>6.1.4</b> Monte Carlo Simulation and Computing</a></li>
<li class="chapter" data-level="6.1.5" data-path="appendix.html"><a href="appendix.html#finance-and-risk-management"><i class="fa fa-check"></i><b>6.1.5</b> Finance and Risk Management</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="appendix.html"><a href="appendix.html#worked-solutions-for-projects"><i class="fa fa-check"></i><b>6.2</b> Worked Solutions for Projects</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="appendix.html"><a href="appendix.html#project-1-proposal-for-worked-solution"><i class="fa fa-check"></i><b>6.2.1</b> Project 1: Proposal for worked solution</a></li>
<li class="chapter" data-level="6.2.2" data-path="appendix.html"><a href="appendix.html#project-2-proposal-for-worked-solution"><i class="fa fa-check"></i><b>6.2.2</b> Project 2: Proposal for worked solution:</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to Probability</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="appendix" class="section level1" number="6">
<h1><span class="header-section-number">Chapter 6</span> Appendix</h1>
<div id="further-reading" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Further Reading</h2>
<p>This is the end of this lecture and these lecture notes which have made an attempt to
teach you introductory probability by building probability concepts with R in a
finance application context. The field of probability and its applications is
huge an rich and only a tiny part of it could be covered in this course. The hope is, of course,
that the lecture has been able to teach you some tools and concepts which will enable those
of you who found this subject interesting to explore it on your own, using your own
interests and the literature on probability as a guide. For those of you who want to do
so, let me give you a few pointers to the literature, which might cover for some of
you the next steps.</p>
<div id="probability-theory-and-mathematics" class="section level3" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Probability theory and mathematics</h3>
<p>I have confessed already in the beginning of this lecture that I think that among the many
probability books on the market the book by <span class="citation"><a href="#ref-Feller1968" role="doc-biblioref">Feller</a> (<a href="#ref-Feller1968" role="doc-biblioref">1968</a>)</span> is still an outstanding master piece
in exposition. It is full of passion and enthusiasm for the subject and interesting throughout.
Its orientation is clearly mathematical but the confinement to discrete sample spaces allows him
to cover much ground with minimal machinery. Reading or studying this books is perhaps even more
fun today since you can complement by using the computer to study and think about the many
interesting examples contained in it, something you could not do when the book first appeared.</p>
<p>Among the big ideas in probability was the attempt to build a general, axiomatic framework for the
field that would establish probability theory firmly as a field of mathematics. The modern
mathematical formulation of probability is perhaps nowhere better presented than in
<span class="citation"><a href="#ref-Billingsley1995" role="doc-biblioref">Billingsley</a> (<a href="#ref-Billingsley1995" role="doc-biblioref">1995</a>)</span>. It is a very good source for those of you who have or had
some more advanced training in mathematics.</p>
</div>
<div id="further-studies-of-r" class="section level3" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Further studies of R</h3>
<p>If you are a beginner of R and if you found the language and what it can do useful and
interesting I recommend to study the book by <span class="citation"><a href="#ref-Grolemund2014" role="doc-biblioref">Grolemund</a> (<a href="#ref-Grolemund2014" role="doc-biblioref">2014</a>)</span>. It is a great read and I have relied
very much on it for this course. From this book I tried to emulate the idea that R is best
taught withing a concrete context instead of teaching the language as such perhaps with a few
toy examples and then apply the machinery afterwards. The book is also available online and
I recommend the beginners among you very warmly to study it. You can get the book on the internet
at <a href="https://rstudio-education.github.io/hopr/" class="uri">https://rstudio-education.github.io/hopr/</a></p>
<p>More advanced students in the group who want to learn and understand R seriously as a programming
language, should at some stage study <span class="citation"><a href="#ref-Wickham2019" role="doc-biblioref">Wickham</a> (<a href="#ref-Wickham2019" role="doc-biblioref">2019</a>)</span>. This book is also freely available in an
online edition at <a href="https://adv-r.hadley.nz/" class="uri">https://adv-r.hadley.nz/</a>.</p>
<p>Finally let me point out to you an excellent guide to the huge number of useful books many of them
freely available at the site <a href="https://www.bigbookofr.com/" class="uri">https://www.bigbookofr.com/</a> which is a regularly updated list
of books about R and applications of R.</p>
</div>
<div id="probability-philosophy-and-concepts" class="section level3" number="6.1.3">
<h3><span class="header-section-number">6.1.3</span> Probability, Philosophy and Concepts</h3>
<p>For those of you who have an interest in conceptual and foundational discussions and
reflections, I would like to point you to four sources in particular. First of all,
I think you should at some stage study the outstanding discussion by <span class="citation"><a href="#ref-DiaconisSkyrms2019" role="doc-biblioref">Diaconis and Skyrms</a> (<a href="#ref-DiaconisSkyrms2019" role="doc-biblioref">2019</a>)</span>.
I made several references to it in these lecture notes. It is a truly good read.</p>
<p>For those of you who have the training and the interest in more formal discussions, I would
like to recommend the monographs of <span class="citation"><a href="#ref-Gilboa2009" role="doc-biblioref">Gilboa</a> (<a href="#ref-Gilboa2009" role="doc-biblioref">2009</a>)</span> and <span class="citation"><a href="#ref-Halpern2017" role="doc-biblioref">Halpern</a> (<a href="#ref-Halpern2017" role="doc-biblioref">2017</a>)</span></p>
<p>An outstanding and very famous book, which is more of a meditation about randomness
also with respect to financial markets is <span class="citation"><a href="#ref-Taleb2007" role="doc-biblioref">Taleb</a> (<a href="#ref-Taleb2007" role="doc-biblioref">2007</a>)</span>. If you had to choose one and only one
book in this section, it is perhaps this one.</p>
</div>
<div id="monte-carlo-simulation-and-computing" class="section level3" number="6.1.4">
<h3><span class="header-section-number">6.1.4</span> Monte Carlo Simulation and Computing</h3>
<p>We discussed a lot about simulation in this lecture. If you want to learn about Monte Carlo
simulation seriously, you should at some stage study <span class="citation"><a href="#ref-Liu2001" role="doc-biblioref">Liu</a> (<a href="#ref-Liu2001" role="doc-biblioref">2001</a>)</span>. A standard reference for
Monte Carlo Simulation in Finance and Financial Engineering is <span class="citation"><a href="#ref-Glasserman2003" role="doc-biblioref">Glasserman</a> (<a href="#ref-Glasserman2003" role="doc-biblioref">2003</a>)</span></p>
</div>
<div id="finance-and-risk-management" class="section level3" number="6.1.5">
<h3><span class="header-section-number">6.1.5</span> Finance and Risk Management</h3>
<p>There are many books on Finance, some very technical other verbose and business like. I believe
that among the Finance books I know the book by <span class="citation"><a href="#ref-Luenberger2009" role="doc-biblioref">Luenberger</a> (<a href="#ref-Luenberger2009" role="doc-biblioref">2009</a>)</span> is truly outstanding. A
comprehensive overview on the methods and mathematics of risk management in a financial
context is <span class="citation"><a href="#ref-McNeilEmbrechtsFrey2015" role="doc-biblioref">McNeil, Embrechts, and Frey</a> (<a href="#ref-McNeilEmbrechtsFrey2015" role="doc-biblioref">2015</a>)</span></p>
</div>
</div>
<div id="worked-solutions-for-projects" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Worked Solutions for Projects</h2>
<div id="project-1-proposal-for-worked-solution" class="section level3" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> Project 1: Proposal for worked solution</h3>
<pre><code>1. Your first task in this project will be to write a function which allows you 
to virtually throw a pair of dice and sum up the points shown after the throw.
</code></pre>
<p>Here is one possible implementation. Note that there are - of course - other
ways providing the same output. The lines starting with
<code>#</code> are comments. You can read them when editing the function script
but R will ignore them when interpreting the function.</p>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="appendix.html#cb444-1" aria-hidden="true" tabindex="-1"></a>roll <span class="ot">&lt;-</span> <span class="cf">function</span>(){</span>
<span id="cb444-2"><a href="appendix.html#cb444-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb444-3"><a href="appendix.html#cb444-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># create a die</span></span>
<span id="cb444-4"><a href="appendix.html#cb444-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb444-5"><a href="appendix.html#cb444-5" aria-hidden="true" tabindex="-1"></a>  die <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span></span>
<span id="cb444-6"><a href="appendix.html#cb444-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb444-7"><a href="appendix.html#cb444-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># roll the dice by making use of sample. We roll two dice, therefore size has to be equal to 2</span></span>
<span id="cb444-8"><a href="appendix.html#cb444-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># note that we need to set replace to TRUE because both dice should be able to show all possible</span></span>
<span id="cb444-9"><a href="appendix.html#cb444-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># points</span></span>
<span id="cb444-10"><a href="appendix.html#cb444-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb444-11"><a href="appendix.html#cb444-11" aria-hidden="true" tabindex="-1"></a>  dice <span class="ot">&lt;-</span> <span class="fu">sample</span>(die, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb444-12"><a href="appendix.html#cb444-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb444-13"><a href="appendix.html#cb444-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># sum up the points of the two dice</span></span>
<span id="cb444-14"><a href="appendix.html#cb444-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb444-15"><a href="appendix.html#cb444-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(dice)</span>
<span id="cb444-16"><a href="appendix.html#cb444-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb444-17"><a href="appendix.html#cb444-17" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Comment: Note that when you choose to sample twice from the points 1 - 6 using the <code>sample()</code>
function, you need to set the replace argument to <code>TRUE</code>. Check the notes or the help for
sample if you need to look up what this means. If replace is set to <code>FALSE</code> - as is the default with sample - then you have a situation where it is impossible that when the first die shows
a particular number, the second dice shows it as well. This is clearly not what we have in mind
if we think of dice throws. Of course we want to allow, for example, that both dice ,may show 6.</p>
<pre><code>2. Simulate and plot the result of your simulation using `qplot()` with the `binwidth`
argument set to 1. Use 10000 runs of your function for the simulation.
</code></pre>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="appendix.html#cb446-1" aria-hidden="true" tabindex="-1"></a>rolls <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, <span class="fu">roll</span>())</span>
<span id="cb446-2"><a href="appendix.html#cb446-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb446-3"><a href="appendix.html#cb446-3" aria-hidden="true" tabindex="-1"></a><span class="co"># load library ggplot2. Note: you can load ggplot2 only if you have installed the package first:</span></span>
<span id="cb446-4"><a href="appendix.html#cb446-4" aria-hidden="true" tabindex="-1"></a><span class="co"># This can be done by typing install.packages(ggplot2) at the prompt of the R console or</span></span>
<span id="cb446-5"><a href="appendix.html#cb446-5" aria-hidden="true" tabindex="-1"></a><span class="co"># use the RStudio menues in the lower right panel.</span></span>
<span id="cb446-6"><a href="appendix.html#cb446-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb446-7"><a href="appendix.html#cb446-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb446-8"><a href="appendix.html#cb446-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb446-9"><a href="appendix.html#cb446-9" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(rolls, <span class="at">binwidth =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="Probability_Introduction_files/figure-html/simulate%20and%20plot-1.png" width="672" /></p>
<p>Comment: Note that <code>qplot()</code> is a function contained in an R library in this case ggplot2. This
library is not part of base-R and therefore has to be installed and then
loaded with the <code>library()</code> function. While the package needs to be installed only once, it needs
to be loaded in every new R-session to make it available. There are many other functions, also
functions included in base R, that allow you to make plots. Here we ask for <code>qplot()</code> specifically
to familiarize you with the concept of add-pn packages and their use.</p>
<pre><code>3. Are these dice fair? Why?
</code></pre>
<p>We answer this question by considering the sample space of this random experiment first.
There are in total <span class="math inline">\(6 \times 6\)</span> pairs, in total 36 ways to sum up points. Each pair
has probability <span class="math inline">\(1/36\)</span> and since the multiple pairs do not occur in the same
event the pair probabilities that lead to a particular sum can be added. The sample space
<span class="math inline">\({\cal S}\)</span> could be visualized like this:</p>
<table>
<thead>
<tr class="header">
<th align="center">Probability</th>
<th align="center">Outcome</th>
<th align="left">Possibilities</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">P(sum = 2) = 1/36</td>
<td align="center">2</td>
<td align="left">(1,1)</td>
</tr>
<tr class="even">
<td align="center">P(sum = 3) = 2/36</td>
<td align="center">3</td>
<td align="left">(1,2),(2,1)</td>
</tr>
<tr class="odd">
<td align="center">P(sum = 4) = 3/36</td>
<td align="center">4</td>
<td align="left">(1,3),(2,2),(3,1)</td>
</tr>
<tr class="even">
<td align="center">P(sum = 5) = 4/36</td>
<td align="center">5</td>
<td align="left">(1,4),(2,3),(3,2),(4,1)</td>
</tr>
<tr class="odd">
<td align="center">P(sum = 6) = 5/36</td>
<td align="center">6</td>
<td align="left">(1,5),(2,4),(3,3),(4,2),(5,1)</td>
</tr>
<tr class="even">
<td align="center">P(sum = 7) = 6/36</td>
<td align="center">7</td>
<td align="left">(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)</td>
</tr>
<tr class="odd">
<td align="center">P(sum = 9) = 4/36</td>
<td align="center">9</td>
<td align="left">(3,6),(4,5),(5,4),(6,3)</td>
</tr>
<tr class="even">
<td align="center">P(sum = 10) = 3/36</td>
<td align="center">10</td>
<td align="left">(4,6),(5,5),(6,4)</td>
</tr>
<tr class="odd">
<td align="center">P(sum = 11) = 2/36</td>
<td align="center">11</td>
<td align="left">(5,6),(6,5)</td>
</tr>
<tr class="even">
<td align="center">P(sum = 12) = 1/36</td>
<td align="center">12</td>
<td align="left">(6,6)</td>
</tr>
</tbody>
</table>
<p>The frequencies with which the sums occur look very much like the theoretical probabilities
for equally probable pairs. Our dice thus look as if they are fair. Fair here means that
none of the two dice has a bias to land on any face more likely than on another. Of course this
does not mean that all sums occur equally often, because there are for example more combinations
that can result in a sum of 7 than there are combinations that can result in a sum of 12, say.
If the dice are fair the frequencies will be proportional to the theoretical probabilities and
for many independent throws of the dice they should get close to the theoretical probabilities.</p>
<pre><code>4. Assume the dice were unfair in the following sense: Numbers 1,2,3,4 and 5 have a 
probability of $1/8$ while the 6 has a probability of $3/8$. Study the help page of
the `sample`function and find out how you could give these new probability weights
to the function. If you redo your simulation analysis with the loaded dice, how does the
picture change?
</code></pre>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="appendix.html#cb449-1" aria-hidden="true" tabindex="-1"></a>roll_biased <span class="ot">&lt;-</span> <span class="cf">function</span>(){</span>
<span id="cb449-2"><a href="appendix.html#cb449-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb449-3"><a href="appendix.html#cb449-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Construct die</span></span>
<span id="cb449-4"><a href="appendix.html#cb449-4" aria-hidden="true" tabindex="-1"></a>  die <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span></span>
<span id="cb449-5"><a href="appendix.html#cb449-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb449-6"><a href="appendix.html#cb449-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Roll biased or laded die by specifying the probabilities such that there is relatively</span></span>
<span id="cb449-7"><a href="appendix.html#cb449-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># more mass on outcome 6.</span></span>
<span id="cb449-8"><a href="appendix.html#cb449-8" aria-hidden="true" tabindex="-1"></a>  dice <span class="ot">&lt;-</span> <span class="fu">sample</span>(die, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">8</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">8</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">8</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">8</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">8</span>, <span class="dv">3</span><span class="sc">/</span><span class="dv">8</span>))</span>
<span id="cb449-9"><a href="appendix.html#cb449-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb449-10"><a href="appendix.html#cb449-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(dice)</span>
<span id="cb449-11"><a href="appendix.html#cb449-11" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="appendix.html#cb450-1" aria-hidden="true" tabindex="-1"></a>rolls <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, <span class="fu">roll_biased</span>())</span>
<span id="cb450-2"><a href="appendix.html#cb450-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb450-3"><a href="appendix.html#cb450-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(rolls, <span class="at">binwidth =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="Probability_Introduction_files/figure-html/simulate-biased-die-1.png" width="672" /></p>
<p>Comment: This example shows that you can determine the probabilities with which the sample
function draws basic outcomes. If you would not know these probabilities but only the plot
you would immediately realize that the dice must be biased because also with many rolls the
relative frequencies are nowhere near where you would expect them if the dice were fair</p>
<pre><code>5. Write a script for this random experiment.
</code></pre>
<p>We create a script with <code>File &gt; new File &gt; R script</code>and write the code for <code>roll_biased</code> into the script. That’s it.</p>
<pre><code>6. Now look at the random experiment of throwing two dice with the concepts from
probability theory: What is the sample space of this experiment. What are the 
probabilities of the basic outcomes? What is the probability of getting sum 7, what is
the probability of getting sum 2?
</code></pre>
<p>The sample space is:
<span class="math inline">\({\cal S} = \{ (1,1), (1,2), (1,3), (1,4), (1,5), (1,6), \\ (2,6), (3,6), (4,6), (5,6), (6,6), (2,1), (2,2), (2,3), \\ (2,4), (2,5), (3,5), (4,5), (5,5), (6,5), (3,1), (3,2), \\ (3,3), (3,4), (4,4), (5,4), (6,4), (4,1), (4,2), (4,3), \\ (5,3), (6,3), (5,1), (5,2), (6,2), (6,1) \}\)</span></p>
<p>The probabilities of the basic outcomes are <span class="math inline">\(1/36\)</span>.</p>
<p>The probability of getting the sum 7 is
<span class="math inline">\(6/36\)</span> or <span class="math inline">\(1/6\)</span>,
the probability of getting a 2 is <span class="math inline">\(1/36\)</span>.</p>
<p>Comment: I have not specified in the question whether the probabilities
should be computed for the fair or the
unfair die. I should have perhaps formulated more precisely.
Here I showed the probabilities of the fair dice. The sample space would be the
same for both cases.</p>
<pre><code>7. Imagine now that you are at the casino which uses fair dice and you can spend 150 Euro
for chips. Since you have figured out that 7 is the most
likely outcome you would like to buy bets on 7. The casino
offers you a bet for 15 cent. When you win you get 1 Euro for the
bet, when you loose the Casino gets the 15 cents. 
So you could make 1000 bets in total 
on 7. Is this a good or a bad deal for you? Try to think about
this problem in terms of a simulation.
</code></pre>
<p>Comment: I realized that my formulation of the payoffs is misleading and this created confusion.
This is my fault. What I should have written is: if you win you get 1 and if you loose you get
nothing. Every bet costs 15 cents. This is the situation I had in mind but failed to formulate
clearly.</p>
<p>With 15 cent per bet and a budget of 150 we can bet on 1000 rolls
of the dice. Theoretically the proportion of outcomes where the sum is
7 should be 6/36 or 1/6 so you would gain 1 in about 166 cases and 0 otherwise.
You would pay 150 for 1000 rolls since your chip costs 0.15 per bet. This would
result in a net gain. So theoretically this should be a good deal for you.</p>
<p>If we take a simulation approach we have to keen the following in mind:</p>
<p>Now if you roll the dice 1000 times the proportion of getting will vary from run to run and
sometimes it will show more and at other times less outcomes where the sum is 7, so you do not see
from a simulation of 1 run of 1000 rolls clearly if you make a loss or a gain. If you simulate
many such runs you will get a clearer picture.</p>
<p>Function for 1 run:</p>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="appendix.html#cb454-1" aria-hidden="true" tabindex="-1"></a>craps <span class="ot">&lt;-</span> <span class="cf">function</span>(n, cost){</span>
<span id="cb454-2"><a href="appendix.html#cb454-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb454-3"><a href="appendix.html#cb454-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># roll the dice n times. For our particular example this would be n = 1000 and store the</span></span>
<span id="cb454-4"><a href="appendix.html#cb454-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># results, the sums in a vector outcomes.</span></span>
<span id="cb454-5"><a href="appendix.html#cb454-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb454-6"><a href="appendix.html#cb454-6" aria-hidden="true" tabindex="-1"></a>  outcomes <span class="ot">&lt;-</span> <span class="fu">replicate</span>(n, <span class="fu">roll</span>())</span>
<span id="cb454-7"><a href="appendix.html#cb454-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb454-8"><a href="appendix.html#cb454-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># select the outcomes where the sum is 7</span></span>
<span id="cb454-9"><a href="appendix.html#cb454-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb454-10"><a href="appendix.html#cb454-10" aria-hidden="true" tabindex="-1"></a>  wins <span class="ot">&lt;-</span> (outcomes <span class="sc">==</span> <span class="dv">7</span>)</span>
<span id="cb454-11"><a href="appendix.html#cb454-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb454-12"><a href="appendix.html#cb454-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Since for each win you get 1 you can sum the total wins to get your revenue. Deduct the</span></span>
<span id="cb454-13"><a href="appendix.html#cb454-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># total costs to get your profit</span></span>
<span id="cb454-14"><a href="appendix.html#cb454-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb454-15"><a href="appendix.html#cb454-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(wins) <span class="sc">-</span> (cost<span class="sc">*</span>n)</span>
<span id="cb454-16"><a href="appendix.html#cb454-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb454-17"><a href="appendix.html#cb454-17" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>One round:</p>
<div class="sourceCode" id="cb455"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb455-1"><a href="appendix.html#cb455-1" aria-hidden="true" tabindex="-1"></a><span class="fu">craps</span>(<span class="dv">1000</span>,<span class="fl">0.15</span>)</span></code></pre></div>
<pre><code>## [1] 13</code></pre>
<p>Here you have a gain. But this could be due to randomness. To see clearer you might want
to do many repetitions for this, say 1000.</p>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="appendix.html#cb457-1" aria-hidden="true" tabindex="-1"></a>sim <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">craps</span>(<span class="dv">1000</span>,<span class="fl">0.15</span>))</span></code></pre></div>
<p>Lets plot the profits for you</p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="appendix.html#cb458-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(sim, <span class="at">bins =</span> <span class="dv">10</span>)</span></code></pre></div>
<p><img src="Probability_Introduction_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>On average you would make a profit under these terms. Can this be true? One way to think about
it is that in one run of 1000 rolls you should make revenues of about 6/36*1000, because this
is the proportion of cases where you make 1 Euro. Overall this would be 166.6667. Even if
you pay 150 for this you will make a gain. It seems to be a good deal for you. No Casino in the
world will ever offer such terms!</p>
</div>
<div id="project-2-proposal-for-worked-solution" class="section level3" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> Project 2: Proposal for worked solution:</h3>
<pre><code>1. Go to the EBA website https://www.eba.europa.eu/risk-analysis-and-data/eu-wide-stress-testing
and download the 
file Credit Risk IRB (https://www.eba.europa.eu/assets/st21/full_database/TRA_CRE_IRB.csv).
You can do so by downloading the file, storing it locally and then read it into R or you can
read it directly from the web.
</code></pre>
<p>We download the file directly and store it in an R-object, which we call <code>eba_data</code></p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="appendix.html#cb460-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://www.eba.europa.eu/assets/st21/full_database/TRA_CRE_IRB.csv&quot;</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>This should result in an R-object <code>eba_data</code> (or whatever name you chose to give to the data) with
528550 records of 15 variables. One way to check this would be the <code>dim()</code> function we also
used in the lecture:</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="appendix.html#cb461-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(eba_data)</span></code></pre></div>
<pre><code>## [1] 528550     15</code></pre>
<pre><code>2-(a) Extract all variables names, using the `names()`function.
</code></pre>
<p>We refer to our data object by name <code>eba_data</code>. You must choose the name you have selected, of course.</p>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="appendix.html#cb464-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(eba_data)</span></code></pre></div>
<pre><code>##  [1] &quot;Country_code&quot;     &quot;LEI_Code&quot;         &quot;Bank_name&quot;        &quot;Period&quot;          
##  [5] &quot;Item&quot;             &quot;Scenario&quot;         &quot;Portfolio&quot;        &quot;Country&quot;         
##  [9] &quot;Country_rank&quot;     &quot;Exposure&quot;         &quot;IFRS9_Stages&quot;     &quot;Status&quot;          
## [13] &quot;CR_exp_moratoria&quot; &quot;CR_guarantees&quot;    &quot;Amount&quot;</code></pre>
<pre><code>
2-(b) Select all rows where the Scenario variable has value 1. Note
       that the symbol you need in the R syntax for equal is `==`, the syntax is therefore 
       `Scenario == 1`. You might check out the R-help entry `Comparison` for further details.
       </code></pre>
<p>We overwrite our object name <code>eba_data</code>at each step.</p>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="appendix.html#cb467-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> eba_data[eba_data<span class="sc">$</span>Scenario <span class="sc">==</span> <span class="dv">1</span>, ]</span></code></pre></div>
<p>Explanation: Since our object name is <code>eba_data</code> we subset it by <code>eba_data[, ]$</code>. The
first slot addresses rows the second slot addresses columns. We want to say: Take those rows
where the column Scenario takes value 1. The column scenario is <code>eba_data$Scenario</code>. The
filter condition is thus written in the row slot. The column slot is left blank because we
want to have records for each variable. Note that without warning R has created here a new
object, with the same name than the old one. But the new <code>eba_data</code> has only those rows left,
where the Scenario-Variable is equal to 1.</p>
<pre><code>2 -(c) From the resulting data-frame select all rows where the Country variable is not equal to 0.        (hint: The not equal operator in the R syntax is `!=`). If you look into the Metadata-File
       you will see that 0 are all the aggregate exposures not broken down by country. Excluding 
       these will give us country exposures.</code></pre>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="appendix.html#cb469-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> eba_data[eba_data<span class="sc">$</span>Country <span class="sc">!=</span> <span class="dv">0</span>, ]</span></code></pre></div>
<pre><code>2 -(d) From the resulting data frame select all rows where the Portfolio variable has value 1 or         2.These codes describe the accounting rules under which the exposure values are reported, 
       internal rating based (IRB) or standard approach (SA). As a hint you can use R&#39;s subset
       operator `%in%` here so `Portfolio %in% c(1,2)` written with the approprate subsetting rule
       will select all rows where the Porfolio variable has value 1 or 2.</code></pre>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="appendix.html#cb471-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> eba_data[eba_data<span class="sc">$</span>Portfolio <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), ]</span></code></pre></div>
<pre><code>2-(e) From the resulting data frame choose all the rows where the Exposure variable is not 0.This
       gives again disaggregated numbers.</code></pre>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="appendix.html#cb473-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> eba_data[eba_data<span class="sc">$</span>Exposure <span class="sc">!=</span> <span class="dv">0</span>, ]</span></code></pre></div>
<pre><code>2-(f) From the resulting data frame choose all the rows where the Status variable has value 0.
</code></pre>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="appendix.html#cb475-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> eba_data[eba_data<span class="sc">$</span>Status <span class="sc">==</span> <span class="dv">0</span>, ]</span></code></pre></div>
<pre><code>2-(g) From the resulting data frame choose all the rows where the IFRS9_Stages variable has value        1,2, or 3.</code></pre>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="appendix.html#cb477-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> eba_data[eba_data<span class="sc">$</span>IFRS9_Stages <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>), ]</span></code></pre></div>
<pre><code>2-(h) From the resulting data frame choose all the rows where the CR_guarantees variable is 0
</code></pre>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="appendix.html#cb479-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> eba_data[eba_data<span class="sc">$</span>CR_guarantees <span class="sc">==</span> <span class="dv">0</span>, ]</span></code></pre></div>
<pre><code>2- (i) From the resulting data frame choose all the rows where the CR_exp_moratoria variable is 0.
</code></pre>
<div class="sourceCode" id="cb481"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb481-1"><a href="appendix.html#cb481-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> eba_data[eba_data<span class="sc">$</span>CR_exp_moratoria <span class="sc">==</span> <span class="dv">0</span>, ]</span></code></pre></div>
<pre><code> 2- (j) From the resulting data frame, drop all rows where the Amount variable is 0.
   </code></pre>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="appendix.html#cb483-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> eba_data[eba_data<span class="sc">$</span>Amount<span class="sc">!=</span> <span class="dv">0</span>, ]</span></code></pre></div>
<p>This results in a new data frame with dimension:</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="appendix.html#cb484-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(eba_data)</span></code></pre></div>
<pre><code>## [1] 23512    15</code></pre>
<pre><code>3. Check the type of the Amount variable.
</code></pre>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="appendix.html#cb487-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(eba_data<span class="sc">$</span>Amount)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>Explanation: <code>typeof(eba_data$Amount)</code> checks the type of the variable and returns the actual
type. We have reported amounts as strings of characters not as numerics in the data so far.</p>
<pre><code>4. Transform the Amount variable to type `numeric()`</code></pre>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="appendix.html#cb490-1" aria-hidden="true" tabindex="-1"></a>eba_data<span class="sc">$</span>Amount <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(eba_data<span class="sc">$</span>Amount)</span></code></pre></div>
<pre><code>## Warning: NAs introduced by coercion</code></pre>
<pre><code>5. Check for NA in the Amount variable in the resulting data frame and if you find any, remove them. </code></pre>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb493-1"><a href="appendix.html#cb493-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(eba_data<span class="sc">$</span>Amount))</span></code></pre></div>
<pre><code>## [1] 5763</code></pre>
<p>Explanation: <code>is.na(eba_data$Amount)</code> returns a logical vector which is <code>TRUE</code> at the components
where the Amount variable has value <code>NA</code>and <code>FALSE</code>otherwise. Applying <code>sum()</code> to this vector
coerces <code>TRUE</code>to 1 and <code>FALSE</code>to 0. If 0 there is no <code>NA</code> otherwise we have some, in particular we
have 5763 instances of <code>NA</code>. This comes from the fact that some components in Amount contained
the character <code>.</code> which returns <code>NA</code>if <code>as.numeric()</code>is applied to it. This seems clear, since
after all <code>.</code> is a string which corresponds to no number.</p>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="appendix.html#cb495-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(eba_data)</span></code></pre></div>
<pre><code>6. Change the Amount variable from the actual unit of Million Euros to the unit of 1 Euro and throw
away data smaller than 1 after this transformation.
</code></pre>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="appendix.html#cb497-1" aria-hidden="true" tabindex="-1"></a>eba_data<span class="sc">$</span>Amount <span class="ot">&lt;-</span> eba_data<span class="sc">$</span>Amount<span class="sc">*</span><span class="dv">10</span><span class="sc">^</span><span class="dv">6</span></span></code></pre></div>
<p>Explanation: If an amount is expressed in units of one million, one million Euro appears as 1. If
we multiply by 10^6 this is expressed as 1 000 000. We transform the Amount variable in this way
and overwrite the old variable by the values with the new units.</p>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="appendix.html#cb498-1" aria-hidden="true" tabindex="-1"></a>eba_data <span class="ot">&lt;-</span> eba_data[eba_data<span class="sc">$</span>Amount <span class="sc">&gt;=</span> <span class="dv">1</span>, ]</span></code></pre></div>
<p>Explanation: We identify the values larger than 1 by logical subsetting of the Amount variable and
select all these values from the data frame by selecting all rows where the Amount variable is
larger than 1.</p>
<pre><code>7. Select the leading digits from the Amount variable, using R&#39;s string functions and add a
variable with name LD to your data frame. 
</code></pre>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="appendix.html#cb500-1" aria-hidden="true" tabindex="-1"></a>eba_data<span class="sc">$</span>LD <span class="ot">&lt;-</span> <span class="fu">as.character</span>(eba_data<span class="sc">$</span>Amount) <span class="sc">|</span><span class="er">&gt;</span></span>
<span id="cb500-2"><a href="appendix.html#cb500-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">substr</span>(<span class="dv">1</span>,<span class="dv">1</span>)</span></code></pre></div>
<p>Explanation: We can extract the leading digit from a string of characters <code>x</code> by applying
the <code>substr()</code> function, with arguments <code>1,1</code> to <code>x</code>. To operate with this logic on Amount, we have
to transform the type of Amount back to character first. We then use the R-pipe to apply
substr to this new variables. The syntax is
equivalent to <code>substr(as.character(eba_data$Amount),1,1)</code></p>
<pre><code>8. Compare the empirical frequencies in the data with the theoretical frequencies
from Benford&#39;s law. Do the data look ok or suspicious?</code></pre>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="appendix.html#cb502-1" aria-hidden="true" tabindex="-1"></a>comptable <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">table</span>(eba_data<span class="sc">$</span>LD)<span class="sc">/</span><span class="fu">length</span>(eba_data<span class="sc">$</span>LD))</span>
<span id="cb502-2"><a href="appendix.html#cb502-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(comptable) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Digit&quot;</span>, <span class="st">&quot;Freq&quot;</span>)</span></code></pre></div>
<p>Explanation: We tabulate the LD data using the R function <code>table()</code>. We divide each count by
the number of observations using the <code>length()</code>function to get proportions. The output of this
operation is then forced into a data frame and saved in the variable <code>comptable</code> we assign the
names <code>Digit</code>and <code>Freq</code> to the variables.</p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="appendix.html#cb503-1" aria-hidden="true" tabindex="-1"></a>comptable<span class="sc">$</span>Freq_Benf <span class="ot">&lt;-</span> <span class="fu">log10</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="fu">as.numeric</span>(comptable<span class="sc">$</span>Digit))</span></code></pre></div>
<p>Explanation: We add a new variable to our data frame using the formula for Benfords law for
the distribution of digits <span class="math inline">\(\{1,2,3,4,5,6,7,8,9\}\)</span>. Since we do a computation
with logs and division we have to be careful to change the type of our character numbers which are
expressed as strings to numerical types first.</p>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb504-1"><a href="appendix.html#cb504-1" aria-hidden="true" tabindex="-1"></a>comptable</span></code></pre></div>
<pre><code>##   Digit       Freq  Freq_Benf
## 1     1 0.28810398 0.30103000
## 2     2 0.17129133 0.17609126
## 3     3 0.12811529 0.12493874
## 4     4 0.09878497 0.09691001
## 5     5 0.08245267 0.07918125
## 6     6 0.07188471 0.06694679
## 7     7 0.06148630 0.05799195
## 8     8 0.05238768 0.05115252
## 9     9 0.04549308 0.04575749</code></pre>
<p>The digit distribution matches up very well. So from the perspective of Benford’s law about
the distribution of leading digits the EBA exposure data from the one data file we inspected
here look perfectly ok and seem not to be cooked up in any way. Note that this does not mean
that there are no problems in these data. This analysis jsut provides some first order
evidence that the data seem not to be obviously manipulated or forged.</p>

<div id="refs" class="references csl-bib-body hanging-indent">
<div class="csl-entry">
Berger, Arno, and Theodore Hill. 2015. <em>An Introduction to Benford’s Law</em>. Princeton University Press.
</div>
<div class="csl-entry">
Billingsley, Patrick. 1995. <em>Probability and Measure</em>. Wiley.
</div>
<div class="csl-entry">
Coval, Joshua, Jakub Jurek, and Erik Stafford. 2009. <span>“The Economics of Structured Finance.”</span> <em>Journal of Economic Perspectives</em> 3 (1). <a href="http://pubs.aeaweb.org/doi/pdfplus/10.1257/jep.23.1.3">http://pubs.aeaweb.org/doi/pdfplus/10.1257/jep.23.1.3</a>.
</div>
<div class="csl-entry">
Diaconis, Persi, and Brian Skyrms. 2019. <em>10 Great Ideas about Chance</em>. Princeton University Press.
</div>
<div class="csl-entry">
Dunbar, Nicolas. 2000. <em>Inventing Money: The Story of Long-Term Capital Management and the Legends Behind It</em>. Wiley.
</div>
<div class="csl-entry">
Feller, William. 1968. <em>An Introduction to Probability Theory and Its Applications</em>. 3rd ed. Vol. 1. Wiley.
</div>
<div class="csl-entry">
Gilboa, Ithak. 2009. <em>Theory of Decision Under Uncertainty</em>. Cambridge University Press.
</div>
<div class="csl-entry">
Glasserman, Paul. 2003. <em>Monte Carlo Methods in Financial Engineering</em>. Springer.
</div>
<div class="csl-entry">
Grolemund, Garrett. 2014. <em>Hands on Programming with <span>R</span></em>. O’Reilly. <a href="https://rstudio-education.github.io/hopr/">https://rstudio-education.github.io/hopr/</a>.
</div>
<div class="csl-entry">
Halpern, Joseph. 2017. <em>Reasoning about Uncertainty</em>. 2nd ed. MIT Press.
</div>
<div class="csl-entry">
Healy, Kirean. 2019. <em>Data Visualization: A Practical Introduction</em>. Princeton University Press.
</div>
<div class="csl-entry">
Kahnemann, Daniel. 2013. <em>Thinking Fast and Slow</em>. Farrar, Strauss Giroux.
</div>
<div class="csl-entry">
Lewis, Michael. 2011. <em>The Big Short. Inside the Doomsday Machine</em>. Norton.
</div>
<div class="csl-entry">
Liu, Jun S. 2001. <em>Monte Carlo Strategies in Scientific Computing</em>. Springer.
</div>
<div class="csl-entry">
Lo, Andrew, and Craig MacKinlay. 2019. <em>A Non-Random Walk down Wallstreet</em>. Princeton University Press.
</div>
<div class="csl-entry">
Luenberger, David. 2009. <em>Investment Science</em>. Oxford University Press.
</div>
<div class="csl-entry">
McNeil, Alexander, Paul Embrechts, and Rudiger Frey. 2015. <em>Quantitative Risk Management</em>. Princeton University Press.
</div>
<div class="csl-entry">
Narayanan, Arvind, Joseph Bonneau, Edward Felten, Andrew Miller, and Steven Goldfeder. 2016. <em>Bitcoin and Cryptocurrency Technologies: A Comprehensive Introduction</em>. Princeton University Press.
</div>
<div class="csl-entry">
Samuelson, Paul. 1965. <span>“Proof That Properly Anticipated Prices Fluctuate Randomly.”</span> <em>Industrial Management Review</em> 6.
</div>
<div class="csl-entry">
Taleb, Nassim Nicolas. 2007. <em>Fooled by Randomenss</em>. Penguin.
</div>
<div class="csl-entry">
Tooze, Adam. 2018. <em>Crashed. How a Decade of Financial Crisis Changed the World</em>. Viking.
</div>
<div class="csl-entry">
Wickham, Hadley. 2019. <em>Advanced r</em>. 2nd ed. Taylor; Francis.
</div>
<div class="csl-entry">
Wickham, Hadley, and Garrett Grolemund. 2017. <em>R for Data Science</em>. O’Reilly. <a href="https://r4ds.had.co.nz/">https://r4ds.had.co.nz/</a>.
</div>
</div>
</div>
</div>
</div>

































<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Billingsley1995" class="csl-entry">
Billingsley, Patrick. 1995. <em>Probability and Measure</em>. Wiley.
</div>
<div id="ref-DiaconisSkyrms2019" class="csl-entry">
Diaconis, Persi, and Brian Skyrms. 2019. <em>10 Great Ideas about Chance</em>. Princeton University Press.
</div>
<div id="ref-Feller1968" class="csl-entry">
Feller, William. 1968. <em>An Introduction to Probability Theory and Its Applications</em>. 3rd ed. Vol. 1. Wiley.
</div>
<div id="ref-Gilboa2009" class="csl-entry">
Gilboa, Ithak. 2009. <em>Theory of Decision Under Uncertainty</em>. Cambridge University Press.
</div>
<div id="ref-Glasserman2003" class="csl-entry">
Glasserman, Paul. 2003. <em>Monte Carlo Methods in Financial Engineering</em>. Springer.
</div>
<div id="ref-Grolemund2014" class="csl-entry">
Grolemund, Garrett. 2014. <em>Hands on Programming with <span>R</span></em>. O’Reilly. <a href="https://rstudio-education.github.io/hopr/">https://rstudio-education.github.io/hopr/</a>.
</div>
<div id="ref-Halpern2017" class="csl-entry">
Halpern, Joseph. 2017. <em>Reasoning about Uncertainty</em>. 2nd ed. MIT Press.
</div>
<div id="ref-Liu2001" class="csl-entry">
Liu, Jun S. 2001. <em>Monte Carlo Strategies in Scientific Computing</em>. Springer.
</div>
<div id="ref-Luenberger2009" class="csl-entry">
Luenberger, David. 2009. <em>Investment Science</em>. Oxford University Press.
</div>
<div id="ref-McNeilEmbrechtsFrey2015" class="csl-entry">
McNeil, Alexander, Paul Embrechts, and Rudiger Frey. 2015. <em>Quantitative Risk Management</em>. Princeton University Press.
</div>
<div id="ref-Taleb2007" class="csl-entry">
Taleb, Nassim Nicolas. 2007. <em>Fooled by Randomenss</em>. Penguin.
</div>
<div id="ref-Wickham2019" class="csl-entry">
Wickham, Hadley. 2019. <em>Advanced r</em>. 2nd ed. Taylor; Francis.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="references-1.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
